ethereum-optimism/optimism

packages/rollup-full-node/src/app/utils.ts
Add DeployContract, CreateMockProvider, GetWallets
=> Add Utils for Full Node Provider

packages/docs/src/core/src/what-is-the-ovm.rst
-Fixed two typos: "chain can" <- "chain can"
-"we provide ``@eth-..." <- "we ``@eth-..."
- 
-
-
- #
- #
- #
- [x ] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.
=> Small text corrections

packages/docs/src/core/src/limitations.rst
Small PR reflecting that tx.origin is allowed now that we have it!
=> Update tx.origin Documentation

lerna.json, packages/core-db/package.json, packages/core-utils/package.json, packages/docs/package.json, packages/integration-test-utils/package.json, packages/optimistic-game-semantics/package.json, packages/ovm-truffle-provider-wrapper/package.json, packages/ovm/package.json, packages/rollup-contracts/package.json, packages/rollup-core/package.json, packages/rollup-dev-tools/package.json, packages/rollup-full-node/package.json, packages/solc-transpiler/package.json, packages/test-ERC20-Truffle/package.json, packages/test-ERC20-Waffle/package.json, packages/test-ovm-full-node/package.json, packages/test-synthetix-synth/package.json
=> Publish alpha24

.github/workflows/dev-ecr-deploy.yml, docker-compose.yml, docker/geth/Dockerfile, packages/rollup-full-node/exec/wait-for-nodes.sh
Adds CD task for automatic deployment to shared dev (with geth L2) on merge to `master`.
- Fixes # [YAS-272](https://optimists.atlassian.net/browse/YAS-272)
=> CD For Shared Dev with Geth

docker-compose.yml, docker/geth/entrypoint.sh, packages/rollup-core/test/app/l1-to-l2-transaction-processor.spec.ts, packages/rollup-full-node/package.json, packages/rollup-full-node/src/app/utils/environment.ts, packages/rollup-full-node/src/app/utils/l1-node.ts, packages/rollup-full-node/src/exec/fullnode.ts
Adds ability to purge data by changing an ENV var.
Also fixes an error connecting to an existing L1ToL2TransactionPasser.
=> Adding ability to purge data by changing an ENV var

packages/ovm/src/app/utils.ts, packages/rollup-full-node/src/app/test-web3-rpc-handler.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/test-ovm-full-node/src/simple-storage-stress-test.ts
Removes locks from Web3 RPC Server, making all transactions be sent from a new wallet.
- Fixes # [278](https://optimists.atlassian.net/browse/YAS-278)
=> Removes locks from Web3 RPC Server

docker-compose.yml, docker/geth/entrypoint.sh
=> Remove unused KEYSTORE_PATH

docker-compose.yml, packages/rollup-full-node/src/app/utils/environment.ts
=> adding missing env vars to docker-compose

docker/geth/README.md
Update Docker deployment README
=> Update Docker deployment README

packages/rollup-contracts/.gitattributes
Will enables solidity syntax highlight on github.com so contracts are more pleasant to read
=> Enables solidity syntax highlight on github.com

.github/workflows/dev-ecr-deploy.yml, .github/workflows/synthetix-uat-ecr-deploy.yml, .gitignore, aws/synthetix/dev/full-node/docker-compose.yml, aws/synthetix/dev/full-node/ecs-params.yml, aws/synthetix/uat/geth/README.md, aws/synthetix/uat/geth/docker-compose.yml, aws/synthetix/uat/geth/ecs-params.yml, aws/synthetix/uat/web/README.md, aws/synthetix/uat/web/docker-compose.yml, aws/synthetix/uat/web/ecs-params.yml, docker/geth/entrypoint.sh, docker/publish-geth-container.sh, docker/publish-rollup-fullnode-container.sh
Updates necessary for Synthetix UAT env.
- Adds synthetix UAT deployment config and info on how to deploy
- Fixes issue with geth entrypoint.sh that disallowed service discovery DNS name to be used
- AddsCD for synthetix-uat branch
- Fixes # [YAS-307](https://optimists.atlassian.net/browse/YAS-307)
=> Synthetix UAT Env

packages/rollup-full-node/src/app/web3-rpc-handler.ts
Adding more logging around transaction hash mapping, waiting for conf…irmation, and handling errors
=> Error Handling and Logging around OVM -> EVM Tx hash map

lerna.json, package.json, packages/core-db/package.json, packages/core-utils/package.json, packages/optimistic-game-semantics/package.json, packages/ovm-truffle-provider-wrapper/package.json, packages/ovm/package.json, packages/rollup-contracts/package.json, packages/rollup-core/package.json, packages/rollup-dev-tools/package.json, packages/rollup-full-node/package.json, packages/solc-transpiler/package.json
=> Release version 25

docker-compose.yml, docker/geth/README.md, docker/geth/entrypoint.sh
Fixes the geth entrypoint to error on missing file and removing unused vars.
=> Updating geth entrypoint to account for 1492 block fix

docker/geth/entrypoint.sh
=> Making L2 geth node an archive node

.github/workflows/dev-ecr-deploy.yml
Automatically deploys builds from master to `synthetix-dev`.
=> automatically deploys builds from master to `synthetix-dev`

package.json, packages/rollup-full-node/README.md, packages/rollup-full-node/src/app/routing-handler.ts, packages/rollup-full-node/src/app/util/environment.ts, packages/rollup-full-node/src/exec/fullnode.ts, packages/rollup-full-node/test/app/routing-handler.spec.ts, tslint.json, yarn.lock
Allowing configuration of IP addresses that do not get rate limited
Fixes [YAS-338](https://optimists.atlassian.net/browse/YAS-338)
=> Allowing configuration of IP addresses that do not get rate limited

Dockerfile, packages/rollup-full-node/config/env_var_updates.config, packages/rollup-full-node/src/app/account-rate-limiter.ts, packages/rollup-full-node/src/app/routing-handler.ts, packages/rollup-full-node/src/exec/fullnode.ts, packages/rollup-full-node/test/app/account-rate-limiter.spec.ts, packages/rollup-full-node/test/app/routing-handler.spec.ts
Adds file from which router will periodically read for updates and proceed to update environment variables. This is read from a file because docker will not allow processes to pick up changes to environment variables.
- Fixes # [YAS-363](https://optimists.atlassian.net/browse/YAS-363)
=> Adding ability for router to update environment variables after startup

packages/test-ovm-full-node/contracts/Precompiles.sol, packages/test-ovm-full-node/package.json, packages/test-ovm-full-node/test/precompiles-support.spec.ts
Adds precompile integration tests.
- Fixes #YAS-420
=> Precompile integration tests

lerna.json, packages/contracts/package.json, packages/core-db/package.json, packages/core-utils/package.json, packages/ovm-truffle-provider-wrapper/package.json, packages/rollup-core/package.json, packages/rollup-dev-tools/package.json, packages/rollup-full-node/package.json, packages/solc-transpiler/package.json
I recently published new versions of most of our packages to npm - this PR updates our package versions + dependencies to reflect the published versions
Was getting an issue with Lerna not recognizing that the packages had changed since they were last updated...Couldn't figure out a quick fix so instead just published the packages manually. 
- Fixes # YAS-471, YAS-472
=> Update package versions to reflect npm 

packages/contracts/contracts/optimistic-ethereum/chain/CanonicalTransactionChain.sol, packages/contracts/contracts/optimistic-ethereum/chain/StateCommitmentChain.sol, packages/contracts/contracts/optimistic-ethereum/queue/L1ToL2TransactionQueue.sol, packages/contracts/contracts/optimistic-ethereum/queue/RollupQueue.sol, packages/contracts/package.json, packages/contracts/test/contracts/chain/CanonicalTransactionChain.spec.ts, packages/contracts/test/contracts/chain/StateCommitmentChain.spec.ts, packages/contracts/test/contracts/queue/RollupQueue.spec.ts, packages/contracts/test/test-helpers/rl-helpers.ts, packages/core-utils/src/app/misc.ts
Adds event emission on enqueue and appending of tx batches and state batches.
- Fixes # [YAS-490](https://optimists.atlassian.net/browse/YAS-490)
=> Adding event emission and tests to rollup chain contracts

packages/rollup-full-node/src/app/test-web3-rpc-handler.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/src/types/web3-rpc-handler.ts, packages/rollup-full-node/test/app/test-web-rpc-handler.spec.ts, packages/rollup-full-node/test/app/web-rpc-handler.spec.ts, yarn.lock
Adds minimal capabilities to enable EVM-tracing of OVM transactions.
- Fixes YAS 501
=> Adding eth_traceTransaction endpoint

packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/src/types/web3-rpc-handler.ts
Adds the `web3_clientVersion` endpoint to the full node
- Fixes #YAS-544
=> Add web3_clientVersion endpoint

packages/contracts/.gitattributes
Solidity code on GitHub under Languages section
- n/a
=> Solidity code on GitHub under Languages section

packages/contracts/README.md, packages/contracts/buidler.config.ts, packages/contracts/src/deployment/config.ts, packages/contracts/src/deployment/contract-deploy.ts, packages/contracts/src/deployment/default-config.ts, packages/contracts/src/deployment/deploy-l1-rollup-contracts.ts, packages/contracts/src/deployment/environment.ts, packages/contracts/src/deployment/types.ts, packages/contracts/test/deployment/deployment.spec.ts, packages/contracts/test/deployment/geth-input-dump.spec.ts
* Adds optimization to buidler compilation
* Adds manual gas limit setting to contract deployment (otherwise `estimateGas` fails on ExecutionManager & FraudVerifier
* Adds deployment ability to configure an AddressResolver address and only deploy contracts if they are not already registered with it (if deployment fails don't redeploy the ones that succeeded)
- Fixes N/A
=> Making deployments to testnet work

.github/workflows/dev-ecr-deploy.yml
Fixing github action to publish correct docker image
=> Fixing github action to publish correct docker image

packages/rollup-services/src/exec/services.ts
Fixing contract creation in Services exec script.
=> Fixing contract creation in Services exec script

packages/rollup-core/test/db/helpers.ts, packages/rollup-core/test/db/l2-data-service.dbspec.ts, packages/rollup-core/test/db/verifier-data-service.dbspec.ts
Fixes broken DB tests
- Fixes # [None]
=> Fixing DB tests

packages/core-db/src/app/ethereum/ethereum-block-processor.ts
Dev keeps on hanging while syncing blocks because we get rate limited wtihin a fetch, which throws an exception, but since it's in an event handler, the error never gets caught and it just silently makes block syncing stop. This change makes it so that we exit on these sort of issues, which will trigger a process restart. 
Note: This can probably be improved, but that can happen after dev is self-stabilizing.
- Fixes # [YAS-638](https://optimists.atlassian.net/browse/YAS-638) (partially)
=> Fixing block processing hang

packages/docs/developer-documentation/erc20-tutorial/README.md
Fix formatting issues in erc20-tutorial
=> Fix formatting issues in erc20-tutorial

.github/scripts/replace-aws-account-id.sh, .github/workflows/integration-test.yml, docker-compose.ci.env, docker-compose.ci.yml
Adds integration tests to CI on PR to master or merge to master.
- Fixes # [YAS-645](https://optimists.atlassian.net/browse/YAS-645)
=> Adding integration test docker-compose.ci.yml and github task

packages/provider/src/app/network.ts, packages/provider/src/app/provider.ts, packages/provider/src/app/signer.ts
=> provider: fix imports

packages/provider/package.json
Update provider package.json to reflect latest npm publish.
=> update provider package.json

packages/provider/src/app/signer.ts, packages/provider/test/sendtransaction.spec.ts
=> bugfix: signer constructor

packages/docs/protocol-specifications/optimistic-rollup/README.md
Fix a small typo I came across while reading the docs. 
N/A
N/A
N/A
=> Docs: fix small typo

packages/provider/src/app/provider.ts, packages/provider/src/app/signer.ts
=> types: add this._ethersType for v4 support

packages/contracts/package.json, packages/contracts/test/deployment/geth-input-dump.spec.ts
Ports https://github.com/ethereum-optimism/optimism-monorepo/pull/270 to `master`
=> state dump: add contract code hashes

.github/workflows/dockerhub-build-push.yml
Builds and pushes postgres image and rollup services image to dockerhub on push to `testnet` branch.
=> Adding push to dockerhub on merge to testnet branch

packages/contracts/contracts/optimistic-ethereum/ovm/PartialStateManager.sol, packages/contracts/contracts/optimistic-ethereum/ovm/precompiles/DeployerWhitelist.sol
Add toggle for arbitrary contract deployment!
None
=> Add arbitrary contract deployment toggle

packages/provider/package.json
=> publish new provider

packages/rollup-core/src/app/data/consumers/canonical-chain-batch-submitter.ts
Padding signature V value to submit in rollup tx batch
=> Padding signature V value to submit in rollup tx batch

packages/provider/package.json, yarn.lock
Update the ovm tools used as deps for the provider
=> provider: update deps

packages/provider/package.json
Publish commit for latest provider package
=> package: provider alpha.6

Dockerfile.dev, packages/rollup-services/exec/build_and_run.sh
This updates the files to work with https://github.com/ethereum-optimism/optimism-integration
- Did any workflows depend on these files not being changed?
=> testing: update to work with monorepo

.github/workflows/push-to-integration-repo.yml
=> gh actions: fix bumpage

.github/workflows/push-to-integration-repo.yml
=> bumpage: fix

.github/workflows/push-to-integration-repo.yml
=> gh actions: auto bump

.github/workflows/push-to-integration-repo.yml
=> bumpage: again

.github/workflows/push-to-integration-repo.yml
Need to also commit the `.gitmodules` repo on an integration commit + push
=> be sure to commit gitmodules

packages/contracts/contracts/optimistic-ethereum/bridge/BaseCrossDomainMessenger.sol, packages/contracts/contracts/optimistic-ethereum/bridge/L1CrossDomainMessenger.sol
Authenticate the contract method. Beware of frontrunning tho
=> xdomain messenger: authenticate target address

Dockerfile.dev
=> docker: temp fix for deps

packages/batch-submitter/exec/run-batch-submitter.js
Make `run-batch-submitter.js` executable
=> Make Batch Submitter executable

packages/batch-submitter/src/batch-submitter.ts, packages/batch-submitter/test/batch-submitter/mockchain-provider.ts
Add better genesis block handling in tests
=> Add better genesis block handling in tests

packages/provider/package.json
=> Bump version

.github/workflows/dockerhub-build-push.yml
=> github actions: fix docker push

.github/workflows/integration.yml
Fixes tests running on merge to master
=> fix for merge to master

packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/coders/ecdsa-coder.ts, packages/batch-submitter/src/types.ts, packages/batch-submitter/test/batch-submitter/mockchain-provider.ts, packages/batch-submitter/test/batch-submitter/transaction-batch-submitter.spec.ts, packages/provider/src/app/provider.ts
Fixes the provider to return needed metadata & add support for some small api inconsistencies.
=> Update ethers block formatter & fix inconsistency

packages/provider/package.json
=> provider: 0.0.1-alpha.8

package.json, packages/batch-submitter/package.json, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/provider/src/app/provider.ts, yarn.lock
Update deps explicitly, return `l1BlockNumber` as a JS number instead of hex string
=> fixes: integrations

packages/provider/package.json
Bumps the version of the provider
=> provider: 0.0.1-alpha.9

packages/provider/package.json, yarn.lock
=> provider: 0.0.1-alpha.12

packages/docs/protocol-specifications/ovm/ovm-components.md
Fix broken link from main to doctest branch, link fetched from ovmmono-monorepo README
=> Fix: Broken link, update ovm-components.md

.github/workflows/dockerhub-build-push.yml, .github/workflows/integration.yml, .github/workflows/push-to-integration-repo.yml
Updates the version of `webfactory/ssh-agent`
=> workflows: update ssh-agent

packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts
=> Fix bug where we weren't submitting last state root

packages/ovm-toolchain/package.json, yarn.lock
=> v2 Upgrade and publish

packages/provider/README.md
Updates the readme with a recommendation to use a regular provider until we have more test coverage around this provider.
=> provider: update readme

packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts
=> Only commit fraud once

packages/core-utils/package.json
Bumps core-utils to v0.0.1-alpha31
=> core-utils: v0.0.1-alpha.31

packages/provider/package.json
Bumps the node engine version in the `package.json`
=> provider: v0.0.1-alpha.13

packages/core-utils/package.json, packages/ovm-toolchain/package.json, packages/provider/package.json, packages/watcher/package.json, yarn.lock
Types were not being exported even though they were generated. 
I added the `types` field to the `package.json` and linked it to the `build/index.d.ts` file. (As advised here: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)
=> Add types to package.json

README.md
=> readme: fix

README.md
Fixes non-existing (404) tutorial link to the new repository
- Fixes #386
=> Fix tutorial link (#386)

package.json
Adds the node engines >= 10 to package.json
=> package: add engines >= 10

packages/core-utils/package.json
=> core-utils: v0.1.1

packages/core-utils/package.json
=> core-utils: v0.1.5

packages/provider/test/sendtransaction.spec.ts
=> cleanup: remove dead variable

packages/watcher/package.json
Should fix #410. We'll need to publish a new version to make this work.
- Fixes #410 
-
=> Export types in watcher package.json

packages/watcher/package.json, packages/watcher/src/watcher.ts, yarn.lock
=> chore(watcher): use AbstractProvider instead of any

packages/smock/README.md
Fixes a small typo in the smock README. Whoops!
=> [smock] Fix typo in README

yarn.lock
This PR commits the `yarn.lock` after running `yarn` locally
=> deps: commit yarn.lock

integration-tests/package.json, packages/batch-submitter/package.json, packages/contracts/package.json, packages/data-transport-layer/package.json, packages/message-relayer/package.json
Porting over one more [versioning change from the old repo](https://github.com/ethereum-optimism/contracts/commits/master/package.json)
=> chore: bump contracts version

.github/workflows/release.yml
as title, just to speed up the release time a bit
=> ci: cache yarn deps in release

.changeset/five-dots-marry.md
=> chore: add changeset for publishing a new git tag for private pkgs

packages/hardhat-ovm/README.md
=> chore:  fix name of plugin that is being installed

README.md
=> add: socials to README

.github/CODEOWNERS, CODEOWNERS.md
fixes https://github.com/ethereum-optimism/optimism/issues/420
=> feat: add CODEOWNERS

.gitignore
Quick PR which adds `*.swp` to the gitignore.
`.swp` files are often created when editing with vim!
=> style: add *.swp to gitignore

.changeset/green-squids-thank.md, l2geth/core/rollup_fee.go, l2geth/core/rollup_fee_test.go
This is purely a style change to appease the go linter. It updates things to match two rules:
- https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps
- https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences
=> l2geth: change `ROLLUP_BASE_TX_SIZE` to camelcase

.changeset/slimy-berries-listen.md, l2geth/go.sum
The `go.sum` file was altered after running a `make test`, so this commits the altered file. It is a very small change, just a single line for `httpmock`
=> l2geth: commit updated go.sum

.changeset/slow-rats-jog.md, integration-tests/test/ovmcontext.spec.ts, integration-tests/test/rpc.spec.ts, packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts, packages/data-transport-layer/src/services/l1-ingestion/handlers/state-batch-appended.ts, packages/data-transport-layer/src/services/l1-ingestion/handlers/transaction-enqueued.ts, packages/data-transport-layer/src/services/l1-ingestion/service.ts
Running `yarn lint:fix` in base and committing all the changes on master it surfaced.
Seems like CI didn't catch those as errors, should our linters be consistent?
=> fix: run yarn lint:fix

.changeset/many-wombats-hear.md, packages/batch-submitter/exec/run-batch-submitter.js
fixes bug introduced in https://github.com/ethereum-optimism/optimism/pull/538/commits/933880d443538d413f8bac6488e34b3339078ad5
=> fix: start the batch submitter properly

integration-tests/package.json, integration-tests/test/shared/utils.ts, yarn.lock
Fixes https://github.com/ethereum-optimism/optimism/issues/655
=> test: allow configuring integration tests with env vars

ops/docker-compose.yml
Fixes https://github.com/ethereum-optimism/optimism/issues/690
=> scale is not docker v3 valid

ops/docker-compose.yml
Removes trailing whitespace from `docker-compose.yml`
=> fix: remove trailing whitespace

.changeset/nice-walls-relate.md, l2geth/scripts/start.sh
Updates `scripts/start.sh` to be more flexible so that it can be used to sync kovan
=> l2geth: more flexible start script

.changeset/afraid-wasps-wonder.md, packages/data-transport-layer/src/utils/validation.ts
Updates the config parsing for the DTL so that it will now error out on a random message and instead return a better error message
=> fix: dtl config parsing

.changeset/moody-pigs-attend.md, packages/batch-submitter/package.json, packages/batch-submitter/src/batch-submitter/batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/test/batch-submitter/batch-submitter.spec.ts, yarn.lock
Adds key metrics to the batch submitter so we can monitor them on a dashboard.
See issue for metric list
**Metadata**
- https://github.com/ethereum-optimism/optimism/issues/637
=> feat[batch-submitter]: add metrics

examples/waffle/test/erc20.spec.js
This fix comes after the discovery made in https://github.com/ethereum-optimism/optimism/issues/664#issuecomment-832293814
=> fix: remove hardcoded gasLimit

examples/hardhat/deploy/ERC20.deploy.js, examples/hardhat/test/erc20.test.js
This fix comes after the discovery made in https://github.com/ethereum-optimism/optimism/issues/664#issuecomment-832293814
=> fix: remove hardcoded gasPrice and gasLimit

.github/workflows/ts-packages.yml, packages/contracts/codechecks.yml, packages/contracts/package.json, yarn.lock
Enables comparison reports on gas cost delta against base. Will plug in thresholds checking in near future once we get an idea of a good tolerance level for that.
=> Run codechecks in CI for gas cost benchmarking

.changeset/thick-rings-serve.md, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/hardhat-ovm/src/index.ts, yarn.lock
Allows the batch submitter to recover when a deposit is skipped.
=> feat: add skipped deposit auto heal

packages/smock/README.md
This function will not return an array of strings, it will return a string.
=> Fix bad comment in Smock Docs

packages/contracts/README.md
=> docs(contracts): Add codecov badge

.changeset/soft-bikes-sing.md, packages/message-relayer/src/service.ts
This PR removes the logging of the `options` at runtime. This is not safe because it contains secrets
=> relayer: logging cleanup

.github/workflows/geth.yml, .github/workflows/integration.yml, .github/workflows/ts-packages.yml
Fixes workflows so they'll execute correctly on `develop`.
=> fix: have workflows run on develop

packages/batch-submitter/README.md, packages/data-transport-layer/README.md
Document new env vars in typescript services from previous changes.
**Metadata**
- Adds context for new variables and when Sentry is initialized
=> chore: update READMEs with new env vars

.changeset/plenty-chicken-report.md, packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol
This comment is:
1. Out of date. See incorrect comment: https://github.com/ethereum-optimism/optimism/blob/cb2e9ad2548788613f2c135258ae8a7e5ba917be/packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol#L103 and implementation: https://github.com/ethereum-optimism/optimism/blob/cb2e9ad2548788613f2c135258ae8a7e5ba917be/packages/contracts/contracts/optimistic-ethereum/libraries/codec/Lib_EIP155Tx.sol#L97-L98
2. Is not required. Doesn't actually improve code readability.
So I just deleted it.
=> fix: remove incorrect comment

packages/contracts/test/helpers/test-runner/test-runner.ts
A small change to the test-runner setup code making it possible to specify `contractStorage` values in the prestate using the special `setPlaceholderStrings()`. 
ie. Imagine you want to store an address which is deployed in the [`beforeEach`](https://github.com/ethereum-optimism/optimism/blob/c70d32ea26e5976639e9d17120f61e903a657fe7/packages/contracts/test/helpers/test-runner/test-runner.ts#L121) hook. You'd have to run the tests, console.log the address which results in an `INVALID_STATE_ACCESS`, then paste it here:
```
contractStorage: {
[predeploys.OVM_SafetyCache]: {
'0x0000000000000000000000000000000000000000000000000000000000000000': getStorageXOR(
0x.......someAddress
),
},
```      
After: 
```
contractStorage: {
[predeploys.OVM_SafetyCache]: …
```
=> test(contracts): easily set storageXOR values in prestate

ops/docker-compose-metrics.yml, ops/docker/prometheus/prometheus.yml
Add the collection of batch-submitter metrics when running the docker-compose project.
=> Batch submitter metrics collection for docker-compose.

.changeset/clever-numbers-end.md
Adding changeset corresponding to https://github.com/ethereum-optimism/optimism/pull/890
=> fix: add changeset for BS change

README.md
=> docs: add docker-compose up step to README

packages/contracts/test/contracts/OVM/bridge/base/OVM_L1CrossDomainMessenger.spec.ts
Fixes a test that was accidentally broken because of the way we combined `regenesis/0.4.0` and `0.4.0-rc`.
=> fix[contracts]: fix broken test from regenesis/0.4.0 <> 0.4.0-rc merge

packages/contracts/bin/take-dump.ts, packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_CongestionPriceOracle.sol, packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_GasPriceOracle.sol, packages/contracts/src/contract-deployment/config.ts, packages/contracts/src/contract-dumps.ts, packages/contracts/test/contracts/OVM/precompiles/OVM_GasPriceOracle.spec.ts
Refactors the existing PR so that the required variables are stored and renames it to the `GasPriceOracle`
The variables and algorithm can be found here: https://github.com/ethereum-optimism/optimism/issues/823#issuecomment-843453169
=> contracts: gas price oracle

.changeset/poor-crabs-count.md, integration-tests/test/rpc.spec.ts, l2geth/internal/ethapi/api.go
=> fix(l2geth): do not throw an error when estimating gas for txs with nil data

integration-tests/test/rpc.spec.ts
Adding another sanity check for gas estimation.
=> test: adds test that gas estimation is deterministic

packages/core-utils/README.md
Adds some basic docs for L2 fee encoding/decoding
=> docs: core-utils

.changeset/late-countries-guess.md, packages/contracts/README.md
Add hardhat deploy instructions to the `contracts` package `README`.
=> feat: add hardhat deploy instructions to readme

packages/data-transport-layer/package.json, packages/data-transport-layer/src/services/l2-ingestion/service.ts
Fixes some lint errors in the DTL. Note there is an error that was caught that could be significant but I am not sure it is covered in our testing...
=> fix: lint errors in dtl

.github/workflows/publish-canary.yml
Prior, the output was not being shared between jobs correctly
=> Fix canary publishing

.github/workflows/sync-tests.yml
Uploading logs for failures in the sync test
**Metadata**
- Fixes https://github.com/ethereum-optimism/optimism/issues/1095
=> feat[ci]: upload logs for sync tests if failure

README.md
Doing some relatively minor updates to the README just to clean things up a bit.
=> maintenance[monorepo]: first pass update to README

README.md
Various minor tweaks to the README.
=> Misc. small improvements to README

.changeset/short-badgers-itch.md, packages/batch-submitter/src/batch-submitter/batch-submitter.ts
Improves logging to include more information about the batch being submitted or not. Useful for debugging.
=> refactor: improve logging for batch submission timeout scenarios

.changeset/rude-eels-count.md, packages/data-transport-layer/package.json, packages/data-transport-layer/src/services/l1-ingestion/service.ts, packages/data-transport-layer/src/services/l2-ingestion/service.ts, packages/data-transport-layer/src/services/main/service.ts, packages/data-transport-layer/src/services/run.ts, packages/data-transport-layer/src/services/server/service.ts
Helps with debugging and evaluating sync progress.
=> Add highest L1 and L2 block number Gauge metrics to DTL

packages/contracts/scripts/deploy-scripts/mainnet.sh
Add a deploy script for mainnet regenesis.
=> feat[contracts]: add mainnet deploy script

.changeset/spotty-garlics-kick.md, packages/data-transport-layer/src/services/l1-ingestion/service.ts
- fix: bind correct object to method handler
- build: add changeset
=> Bind correct object to method handler in DTL

README.md
Adds a short "Contributing" section to the primary README with a link to the contributing guide and instructions on where to find good first issues.
=> Add short contribution section to primary README

.changeset/gorgeous-starfishes-laugh.md, packages/batch-submitter/src/batch-submitter/batch-submitter.ts
- fix: prevent batch submitter from submitting batches if low on ETH
- build: add changeset
=> Prevent batch submitter from submitting batches if low on ETH

.husky/pre-commit, packages/batch-submitter/.lintstagedrc.yml, packages/batch-submitter/package.json, packages/common-ts/.lintstagedrc.yml, packages/common-ts/package.json, packages/contracts/.lintstagedrc.yml, packages/contracts/package.json, packages/core-utils/.lintstagedrc.yml, packages/core-utils/package.json, packages/data-transport-layer/.lintstagedrc.yml, packages/data-transport-layer/package.json, packages/hardhat-ovm/.lintstagedrc.yml, packages/hardhat-ovm/package.json, packages/message-relayer/.lintstagedrc.yml, packages/message-relayer/package.json, packages/smock/.lintstagedrc.yml, packages/smock/package.json, specs/package.json, yarn.lock
Makes committing less of hassle.
=> Only lint files which are staged on precommit

.changeset/loud-hounds-double.md, packages/message-relayer/package.json, packages/message-relayer/src/exec/withdraw.ts, packages/message-relayer/tsconfig.build.json, packages/message-relayer/tsconfig.json
Nice little tool for doing withdrawals programmatically. Just create an `.env` file inside `message-relayer` with the appropriate values.
=> feat[message-relayer]: L2 => L1 transaction relaying tool

.changeset/ninety-cheetahs-love.md, integration-tests/test/native-eth.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/shared/utils.ts
Some basic clean up of #1172. 
* Added a changeset (`yarn changeset`)
* Fixed conflict with develop using rebase, and squashed into a single commit (`git rebase -i develop`)
Closes OP-914
=> refactor(integration): Add clarity to the expectApprox function signature

packages/contracts/deploy-l2/000-OVM_L2StandardTokenFactory.deploy.ts
Just a minor lint that keeps popping up in CI.
=> fix: lint deploy-l2 folder in contracts

README.md
Adds a small section to the README about rebasing. Also did some minor linting.
**Metadata**
- Fixes OP-913
=> feat: update README to include info about rebasing

.changeset/plenty-walls-compare.md, packages/contracts/CHANGELOG.md, packages/contracts/package.json, packages/contracts/tasks/l2-gasprice.ts
=> Merge develop into master

.changeset/kind-hotels-turn.md, go/gas-oracle/gasprices/l2_gas_pricer.go
This PR improves the logging in the `gas-oracle`
=> gas-oracle: improve logging

packages/contracts/deployments/README.md, packages/contracts/scripts/generate-markdown.js
Dynamically generate predeploys contract in the contracts README.
**Metadata**
- Fixes https://github.com/ethereum-optimism/optimism/issues/1177
=> Dynamically generate predeploy contracts markdown

.changeset/kind-hotels-turn.md, .changeset/six-cobras-fold.md, .changeset/tidy-swans-mate.md, .changeset/wise-mails-laugh.md, go/gas-oracle/CHANGELOG.md, go/gas-oracle/package.json, l2geth/CHANGELOG.md, l2geth/cmd/utils/flags.go, l2geth/package.json, packages/smock/CHANGELOG.md, packages/smock/package.json
=> Develop -> Master Release PR

.changeset/stupid-socks-build.md, package.json, yarn.lock
Updates the typescript dependency to latest
=> deps: update typescript to 4.3.5

.changeset/olive-chicken-heal.md, packages/contracts/contracts/optimistic-ethereum/libraries/standards/L2StandardERC20.sol
Duplicate of #1181 .
That PR has the gas usage action hanging, gonna see if making a PR from a non-external branch fixes.
=> Make it possible to override mint & burn methods in L2StandardERC20

.github/workflows/ts-packages.yml, package.json, yarn.lock
Upgrades codechecks package to fix issues with running on external contributions.
Undo PRs #1203 and #1197
=> Upgrade codechecks fix

.changeset/rare-experts-cheat.md, packages/contracts/README.md, packages/contracts/hardhat.config.ts, packages/contracts/tasks/set-owner.ts, packages/contracts/tasks/withdraw-fees.ts
Adds a hardhat task to withdraw our ETH fees to L1
=> Add hardhat task for withdrawing ETH fees

.changeset/cuddly-sloths-fly.md, l2geth/miner/worker.go
These are minor changes to the miner codepath.
=> l2geth: small changes to miner codepath

ops/docker-compose-nobuild.yml
=> Faster development node (download instead of build)

.changeset/selfish-chairs-thank.md, l2geth/rollup/client.go
Small style fix in the rollup client
Co-authored-by: r1cs
=> l2geth: rollup client style

.changeset/fast-seas-train.md, l2geth/accounts/abi/abi.go, l2geth/accounts/abi/bind/backends/simulated.go, l2geth/accounts/keystore/keystore.go, l2geth/cmd/geth/main.go, l2geth/cmd/geth/usage.go, l2geth/cmd/utils/flags.go, l2geth/consensus/clique/clique.go, l2geth/consensus/ethash/consensus.go, l2geth/core/blockchain_test.go, l2geth/core/chain_makers_test.go, l2geth/core/genesis.go, l2geth/core/rawdb/accessors_chain.go, l2geth/core/rawdb/accessors_indexes.go, l2geth/core/state/statedb.go, l2geth/core/state_processor.go, l2geth/core/state_transition.go, l2geth/core/types/transaction.go, l2geth/internal/ethapi/api.go, l2geth/les/api_backend.go, l2geth/light/txpool.go, l2geth/miner/worker_test.go, l2geth/trie/trie.go
This PR reduces the diff and adds comments to existing diff. This starts the process of having a more self documenting diff
=> l2geth: various fixes to reduce the diff and add docs

.github/workflows/release.yml
Fixes broken indentation that caused release.yml to bork itself.
=> fix: broken indentation in release.yml

.changeset/hot-turkeys-pretend.md, l2geth/core/vm/instructions.go, l2geth/core/vm/interpreter.go
This PR updates the memory usage
=> l2geth: update memory usage in geth

.changeset/plenty-numbers-breathe.md, integration-tests/test/whitelist.spec.ts, l2geth/core/vm/evm.go, l2geth/rollup/dump/constants.go, l2geth/rollup/util/vm_errors.go, ops/docker-compose.yml, packages/contracts/bin/take-dump.ts, packages/contracts/contracts/L2/predeploys/OVM_DeployerWhitelist.sol, packages/contracts/src/make-dump.ts, packages/contracts/tasks/whitelist.ts
Adds the whitelist back in to the system. Also simplifies the whitelist code quite a bit.
**Metadata**
- Fixes ENG-1363
=> feat: reintroduce whitelist

.changeset/few-students-pretend.md, packages/contracts/bin/deploy.ts, packages/contracts/contracts/L1/rollup/CanonicalTransactionChain.sol, packages/contracts/contracts/L1/rollup/ICanonicalTransactionChain.sol, packages/contracts/deploy/004-OVM_CanonicalTransactionChain.deploy.ts, packages/contracts/tasks/deploy.ts, packages/contracts/test/contracts/L1/messaging/L1CrossDomainMessenger.spec.ts, packages/contracts/test/contracts/L1/messaging/deposit.gas.spec.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.gas.spec.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.spec.ts
Removes variables and functions which are no longer in use. 
Also changes `public` to `external` where possible, which may save some gas.
=> Remove unused vars and appendQueueBatch from CTC

packages/regenesis-surgery/.gitignore, packages/regenesis-surgery/package.json, packages/regenesis-surgery/scripts/contract-recompiler.ts, packages/regenesis-surgery/src/constants.ts, packages/regenesis-surgery/src/download-solc.ts, packages/regenesis-surgery/src/helpers.ts, yarn.lock
Add functionality for auto downloading of the emscripten builds of
solc for the auto recompilation process.
=> state-surgery: begin to modularize

packages/regenesis-surgery/scripts/contract-recompiler.ts
Grab the immutables from the old code and insert
them into the new code.
=> state-surgery: insert immutables

.changeset/orange-mayflies-repair.md, integration-tests/test/predeploys.spec.ts, packages/contracts/src/make-genesis.ts
Fixes an issue where some constants were not being correctly set during the deploy process. Also adds unit tests to make sure we won't run into a similar issue again in the future.
=> fix: correctly set all deploy constants

.changeset/real-tips-own.md
Release the contracts as `patch` not `major`
=> fix: update contracts release to patch

.changeset/cool-roses-appear.md, .changeset/tasty-frogs-smash.md, packages/contracts/src/make-genesis.ts, packages/core-utils/src/alias.ts
The precompiles need to be in the genesis file with 1
wei. Also add the script for generating the goerli genesis
file.
=> contracts: add precompiles to make genesis

.changeset/dull-shirts-develop.md, packages/contracts/deploy/000-Lib_AddressManager.deploy.ts, packages/contracts/deploy/006-OVM_BondManager.deploy.ts, packages/contracts/deploy/007-OVM_L1CrossDomainMessenger.deploy.ts, packages/contracts/deploy/008-Proxy__OVM_L1CrossDomainMessenger.deploy.ts, packages/contracts/deploy/009-Proxy__OVM_L1StandardBridge.deploy.ts, packages/contracts/deploy/010-finalize.ts, packages/contracts/src/hardhat-deploy-ethers.ts, packages/core-utils/src/common/hex-strings.ts
Various minor fixes to the deployment process. Generally cleans up the whole process, makes it easier to follow, and makes it more robust.
=> feat: cleanup deployment process

packages/regenesis-surgery/package.json, packages/regenesis-surgery/test/config/hardhat.config.ts, packages/regenesis-surgery/test/setup.ts, packages/regenesis-surgery/test/unit-tests/handlers.spec.ts, yarn.lock
Adding boilerplate for testing handlers to https://github.com/ethereum-optimism/optimism/pull/1507
**Metadata**
- Fixes
=> test: add test setup for surgery handlers

packages/regenesis-surgery/scripts/surgery.ts
Minor cleanup to the main surgery script entrypoint.
=> feat: clean up main surgery script

packages/regenesis-surgery/scripts/constants.ts
Add Hop and Synthetix mainnet addresses for contracts that need ETH as WETH
**Metadata**
- Fixes
=> feat: add mainnet WETH addresses

.changeset/tame-chicken-work.md
Trigger releases by adding a changeset
=> ci: trigger releases

packages/contracts/deployments/README.md, packages/contracts/scripts/generate-markdown.js
Updates the deployments README with info about the latest deployments. We really should automate this.
=> maintenance: update deployments readme

.eslintrc.js, integration-tests/test/fee-payment.spec.ts, integration-tests/test/native-eth-ovm-calls.spec.ts, integration-tests/test/native-eth.spec.ts, integration-tests/test/whitelist.spec.ts, packages/contracts/deploy/008-Proxy__OVM_L1CrossDomainMessenger.deploy.ts, packages/contracts/deploy/011-set-addresses.ts, packages/contracts/src/hardhat-deploy-ethers.ts, packages/contracts/tasks/l2-gasprice.ts, packages/contracts/tasks/set-owner.ts, packages/contracts/tasks/whitelist.ts, packages/contracts/tasks/withdraw-fees.ts, packages/contracts/test/contracts/L1/messaging/L1CrossDomainMessenger.spec.ts, packages/contracts/test/contracts/L1/messaging/L1StandardBridge.spec.ts, packages/contracts/test/contracts/L1/messaging/deposit.gas.spec.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.gas.spec.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.spec.ts, packages/contracts/test/contracts/L2/messaging/L2StandardBridge.spec.ts, packages/contracts/test/contracts/L2/predeploys/OVM_GasPriceOracle.spec.ts, packages/core-utils/src/common/misc.ts, packages/core-utils/src/watcher.ts, packages/core-utils/test/fees.spec.ts, packages/regenesis-surgery/scripts/solc.ts, packages/regenesis-surgery/test/integration/verified.spec.ts, packages/regenesis-surgery/test/provider.ts
Adds eslint rule to error on unused vars. This PR also fixes violations of that rule not only in the integration tests but in the whole project
**Metadata**
- Fixes #1682
=> [Issue-1682] Cleanup unused imports

.github/workflows/ts-packages.yml, integration-tests/sync-tests/1-sync-verifier.spec.ts, integration-tests/sync-tests/2-sync-replica.spec.ts, integration-tests/test/basic-l1-l2-communication.spec.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/utils/tx-submission.ts, packages/batch-submitter/test/batch-submitter/batch-submitter.spec.ts, packages/batch-submitter/test/batch-submitter/mockchain-provider.ts, packages/batch-submitter/test/helpers/constants.ts, packages/batch-submitter/test/utils/tx-submission.spec.ts, packages/data-transport-layer/src/db/simple-db.ts, packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts, packages/data-transport-layer/src/services/l1-ingestion/service.ts, packages/data-transport-layer/src/services/l2-ingestion/handlers/transaction.ts, packages/data-transport-layer/src/services/l2-ingestion/service.ts, packages/data-transport-layer/src/services/main/service.ts, packages/data-transport-layer/src/services/server/service.ts, packages/regenesis-surgery/scripts/utils.ts
Fixes a regression in CI that would not properly lint the entire monorepo.
=> fix: use correct lint check in CI

integration-tests/test/bridged-tokens.ts
Adds a test for token transfers, and withdrawing tokens transferred from someone else.
=> integration-tests: Test a bridged token transfer too

packages/contracts/deploy/014-OVM_L1StandardBridge.deploy.ts, packages/contracts/src/hardhat-deploy-ethers.ts
=> fix: await hardhatnode

.changeset/slimy-planes-lick.md
=> release: v0.5.0 regenesis changesets

yarn.lock
helping debug https://github.com/ethereum-optimism/optimism/pull/1748
**Metadata**
- Fixes
=> fix: run yarn on develop

.github/workflows/release.yml
Fixed proxyd release github workflow
=> Fixed proxyd release github workflow

packages/regenesis-surgery/package.json, packages/regenesis-surgery/test/predeploy.spec.ts, packages/regenesis-surgery/test/setup.ts, packages/regenesis-surgery/test/uniswap.spec.ts, yarn.lock
tests for predeploys before and after surgery
currently based on genesis and state dump files, to expand to live providers
**Metadata**
- Fixes
=> wip: surgery predeploy tests

README.md
Various minor updates to the primary README.
=> maintenance: minor updates to primary README

.changeset/metal-monkeys-repeat.md, integration-tests/package.json, packages/batch-submitter/package.json, packages/common-ts/package.json, packages/contracts/package.json, packages/core-utils/package.json, packages/data-transport-layer/package.json, packages/message-relayer/package.json, packages/regenesis-surgery/package.json, packages/replica-healthcheck/package.json
Standardizes the package json structure for all of our packages
=> fix: standardize package json structure

packages/regenesis-surgery/package.json, packages/regenesis-surgery/test/predeploy.spec.ts, packages/regenesis-surgery/test/setup.ts, packages/regenesis-surgery/test/uniswap.spec.ts, yarn.lock
Adds test coverage of the predeploys in the regenesis-surgery package
=> regenesis-surgery: predeploy tests

packages/regenesis-surgery/package.json, packages/regenesis-surgery/scripts/classifiers.ts, packages/regenesis-surgery/scripts/handlers.ts, packages/regenesis-surgery/scripts/types.ts, packages/regenesis-surgery/scripts/utils.ts, packages/regenesis-surgery/test/erc20.spec.ts, packages/regenesis-surgery/test/provider.spec.ts, packages/regenesis-surgery/test/setup.ts, packages/regenesis-surgery/test/utils.ts, yarn.lock
Adds tests for erc20 state diffs. Additional special cases need to be added to handle certain contracts that should have a diff. These contracts are:
```
0x6fd9d7ad17242c41f7131d257212c54a0e816691
0x7fb688ccf682d58f86d7e38e03f9d22e7705448b
0xb27e3eab7526bf721ea8029bfcd3fdc94c4f8b5b
0x8f69ee043d52161fd29137aedf63f5e70cd504d5
0x7c17611ed67d562d1f00ce82eebd39cb7b595472
0x4200000000000000000000000000000000000006
0xe3c332a5dce0e1d9bc2cc72a68437790570c28a4
0x94b008aa00579c1307b0ef2c499ad98a8ce58e58
0x68f180fcce6836688e9084f035309e29bf0a2095
0xda10009cbd5d07dd0cecc66161fc93d7c9000da1
0xab7badef82e9fe11f6f33f87bc9bc2aa27f2fcb5
0x350a791bfc2c21f9ed5d10980dad2e2638ffa7f6
0xe0bb0d3de8c10976511e5030ca403dbf4c25165b
0x96db852d93c2fea0f447d6ec22e146e4e09caee6 …
```
=> test: add erc20 test coverage

packages/contracts/package.json, packages/contracts/scripts/generate-deployed-artifacts.ts
Rewrites `generate-deployed-artifacts.js` in TypeScript.
=> feat: rewrite generate-deployed-artifacts in ts

.changeset/tiny-houses-smoke.md, packages/batch-submitter/package.json, packages/core-utils/package.json, packages/message-relayer/package.json, packages/regenesis-surgery/package.json, packages/replica-healthcheck/package.json
I made a mistake when constructing these package JSON files. All versions released from these package JSONs are broken. We need to publish a new version ASAP or people will continue to have issues.
=> fix: package json errors

README.md
Fixes typos in the directory structure diagram in the primary README. Whoops!
=> fix: minor update to primary README

.changeset/metal-cherries-march.md
Trigger a release of `proxyd` after a bug in CI prevented a release
=> proxyd: trigger release

.github/workflows/static-analysis.yml, package.json, packages/contracts/contracts/L1/deployment/AddressDictator.sol, packages/contracts/contracts/L1/deployment/ChugSplashDictator.sol, packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol, packages/contracts/contracts/L1/messaging/L1StandardBridge.sol, packages/contracts/contracts/L1/rollup/CanonicalTransactionChain.sol, packages/contracts/contracts/L1/rollup/ChainStorageContainer.sol, packages/contracts/contracts/L1/rollup/StateCommitmentChain.sol, packages/contracts/contracts/L1/verification/BondManager.sol, packages/contracts/contracts/L2/messaging/L2CrossDomainMessenger.sol, packages/contracts/contracts/L2/messaging/L2StandardBridge.sol, packages/contracts/contracts/L2/predeploys/OVM_DeployerWhitelist.sol, packages/contracts/contracts/L2/predeploys/OVM_GasPriceOracle.sol, packages/contracts/contracts/L2/predeploys/OVM_L2ToL1MessagePasser.sol, packages/contracts/contracts/L2/predeploys/OVM_SequencerFeeVault.sol, packages/contracts/contracts/chugsplash/L1ChugSplashProxy.sol, packages/contracts/contracts/libraries/bridge/CrossDomainEnabled.sol, packages/contracts/contracts/libraries/resolver/Lib_ResolvedDelegateProxy.sol, packages/contracts/contracts/libraries/rlp/Lib_RLPReader.sol, packages/contracts/contracts/libraries/trie/Lib_MerkleTrie.sol, packages/contracts/contracts/standards/L2StandardERC20.sol, packages/contracts/slither.config.json, yarn.lock
- slither github action crash fixed by adding dependency
- slither results have been reviewed, noisy checkers muted 
- false positives added to a slither ignore list
- slither github action changed so it fails on new errors by diffing against the ignore database
**Metadata**
- Fixes #1658
=> Slither github action fix and ignore database

go/op_exporter/main.go
Added a polling cycle var to op-exporter
=> Added a polling cycle var to op-exporter

.changeset/four-islands-hear.md, packages/data-transport-layer/src/services/run.ts
Cleanly catch stop signals and exit gracefully
=> dtl: cleanly catch sigterm and sigint

.changeset/odd-crews-approve.md, go/proxyd/backend.go, go/proxyd/rpc.go, go/proxyd/server.go
=> go/proxyd: Allow string RPC IDs

packages/sdk/src/interfaces/types.ts, packages/sdk/test/cross-chain-provider.spec.ts
Adds a test scaffold for the `CrossChainProvider`. Looking for review on the contents of the proposed tests and making sure that the proposed behavior is what you would expect from each function.
**Metadata**
- Fixes ENG-1751
=> feat: add test scaffold for CrossChainProvider

.changeset/clever-bananas-look.md, ops/docker/Dockerfile.monorepo, packages/contracts/contracts/test-libraries/bridge/TestLib_CrossDomainUtils.sol, packages/sdk/hardhat.config.ts, packages/sdk/package.json, packages/sdk/src/index.ts, packages/sdk/src/interfaces/types.ts, packages/sdk/src/utils.ts, packages/sdk/test/contracts/AbsolutelyNothing.sol, packages/sdk/test/contracts/MessageEncodingHelper.sol, packages/sdk/test/utils.spec.ts
Implements the utilities described in the SDK project charter and adds tests for each.
**Metadata**
- Fixes ENG-1746
- Fixes ENG-1747
=> feat: add sdk utils and corresponding tests

packages/sdk/test/cross-chain-erc20-pair.spec.ts
Adding the test scaffold for the CrossChainERC20Pair
=> feat: CrossChainERC20Pair test scaffold

.changeset/popular-dogs-push.md, .github/workflows/release.yml
Fixed github release workflow tag on op-exporter
📋 🍝 💥
=> Fixed github release workflow tag on op-exporter

packages/sdk/src/interfaces/cross-chain-provider.ts, packages/sdk/test/cross-chain-erc20-pair.spec.ts, packages/sdk/test/cross-chain-messenger.spec.ts, packages/sdk/test/cross-chain-provider.spec.ts
Some minor tweaks to the expected behavior of the SDK based on conversation with @SmitV.
=> feat: tweaks from final SDK behavior review

go/proxyd/cmd/proxyd/main.go
Proxyd should use json logging
=> Proxyd should use json logging

.changeset/gold-ants-breathe.md
=> Force proxyd build

packages/sdk/src/interfaces/cross-chain-provider.ts, packages/sdk/src/interfaces/types.ts, packages/sdk/src/utils/coercion.ts, packages/sdk/src/utils/contracts.ts, packages/sdk/src/utils/index.ts, packages/sdk/src/utils/message-encoding.ts, packages/sdk/src/utils/type-utils.ts, packages/sdk/test/cross-chain-provider.spec.ts, packages/sdk/test/utils/coercion.spec.ts, packages/sdk/test/utils/contracts.spec.ts, packages/sdk/test/utils/message-encoding.spec.ts
This PR is a bit beefy but the contents are relatively straightforward:
1. Break the `utils.ts` file into several different files depending on the utility type.
2. Similarly, break out the tests for each utility file into its own spec file.
3. Create a new `type-utils.ts` file for useful types.
4. Create a new utility for connecting to the OE contracts intelligently.
5. Add tests for the new utility.
**Metadata**
- Fixes ENG-1789
=> feat: add SDK contract utils and corresponding tests

packages/sdk/src/cross-chain-provider.ts, packages/sdk/src/index.ts, packages/sdk/src/utils/contracts.ts, packages/sdk/test/contracts/ICrossDomainMessenger.sol, packages/sdk/test/contracts/MockMessenger.sol, packages/sdk/test/cross-chain-provider.spec.ts
This PR creates the `CrossChainProvider` class which implements the `ICrossChainProvider` interface. It also implements function `getMessagesByTransaction` and the appropriate tests.
**Metadata**
- Fixes ENG-1796
- Fixes ENG-1795
=> feat: tests for CrossChainProvider constructor and getMessagesByTransaction

packages/sdk/src/cross-chain-provider.ts, packages/sdk/src/interfaces/cross-chain-provider.ts, packages/sdk/src/interfaces/types.ts, packages/sdk/src/utils/contracts.ts, packages/sdk/src/utils/message-encoding.ts, packages/sdk/test/contracts/MockBridge.sol, packages/sdk/test/contracts/MockMessenger.sol, packages/sdk/test/cross-chain-provider.spec.ts, packages/sdk/test/utils/message-encoding.spec.ts
Implementation and tests for `getTokenBridgeMessagesByAddress`. Also introduces new alias functions for deposits and withdrawals.
**Metadata**
- Fixes ENG-1798
=> feat(sdk): add tests for getTokenBridgeMessagesByAddress

.circleci/config.yml
=> ci: Add proxyd to nightly build

integration-tests/package.json, package.json, packages/batch-submitter/package.json, packages/common-ts/package.json, packages/contracts/package.json, packages/core-utils/package.json, packages/data-transport-layer/package.json, packages/message-relayer/package.json, packages/sdk/package.json, yarn.lock
=> maintenance: remove eslint-plugin-ban dependency

.github/workflows/ts-packages.yml
In #1931 branch coverage was increased to levels we should improve over time. Therefore here we will fail coverage checks if tests for new logic isn't added.
**Metadata**
- Related to #1555
=> Fail CI if coverage threshold checks fail

.changeset/fluffy-ghosts-heal.md, go/op-exporter/Makefile, go/op-exporter/collector.go, go/op-exporter/main.go, go/op-exporter/version/version.go
Add a metric to op-exporter for the build information.
=> feature - added op-exporter version metric

.changeset/shaggy-brooms-shave.md, packages/contracts/tasks/l2-gasprice.ts
Updates the gas oracle hardhat task to also let it
manage the scalar and overhead.
=> feat(contracts): add in better gas oracle management

.changeset/kind-poems-happen.md, integration-tests/.prettierrc.js, integration-tests/.prettierrc.json, integration-tests/contracts/ValueCalls.sol, integration-tests/test/rpc.spec.ts, l2geth/internal/ethapi/api.go
Solving - [Issue 1998](https://github.com/ethereum-optimism/optimism/issues/1998)
=> Makes sure that the Default sender is address(0)

packages/sdk/test/l2-provider.spec.ts
Basic test scaffold for the L2Provider class.
**Metadata**
- Fixes ENG-1784
=> feat: L2Provider test scaffold

.changeset/dirty-emus-guess.md, packages/core-utils/src/bcfg.ts
Improves the docstrings for the BCFG typings that we maintain as part of `core-utils`.
=> maintenance: improved docstrings for BCFG

.changeset/six-actors-attend.md, l2geth/core/state_transition.go
=> l2geth: fix nonce issue

packages/sdk/src/cross-chain-provider.ts, packages/sdk/src/interfaces/cross-chain-provider.ts, packages/sdk/src/interfaces/types.ts, packages/sdk/test/contracts/MockSCC.sol, packages/sdk/test/cross-chain-provider.spec.ts, packages/sdk/test/helpers/constants.ts, packages/sdk/test/helpers/index.ts
Implements the `getMessageStatus` function for the SDK.
**Metadata**
- Fixes ENG-1799
=> feat: implement getMessageStatus

packages/sdk/src/cross-chain-messenger.ts, packages/sdk/test/contracts/MockBridge.sol, packages/sdk/test/cross-chain-messenger.spec.ts
Implements the `depositETH` function for the SDK.
**Metadata**
- Fixes ENG-1828
=> feat(sdk): implement depositETH

packages/sdk/src/cross-chain-messenger.ts, packages/sdk/test/contracts/MockBridge.sol, packages/sdk/test/cross-chain-messenger.spec.ts
Implements the SDK's `withdrawETH` function.
**Metadata**
- Fixes ENG-1829
=> feat(sdk): implement withdrawETH

go/batch-submitter/cmd/batch-submitter/main.go
Change "crtiical" to "critical" in line 23.
=> Fix Typo In Comment

.changeset/friendly-bikes-exist.md, packages/sdk/src/cross-chain-messenger.ts
This PR will trigger a minor release of the SDK and cut a beta release of the package.
=> feat: SDK beta release

packages/sdk/test/cross-chain-messenger.spec.ts
Fixes a flaky test in the SDK first spotted in this PR: https://github.com/ethereum-optimism/optimism/pull/2133
=> fix(sdk): updated flaky test

.changeset/ninety-rings-promise.md, packages/sdk/package.json
Fixes a release bug which published the SDK but did not include any source files.
=> fix: correctly export SDK

.changeset/rich-lemons-wave.md, .changeset/warm-pears-hope.md, integration-tests/contracts/FakeL2StandardERC20.sol, integration-tests/test/basic-l1-l2-communication.spec.ts, integration-tests/test/bridged-tokens.spec.ts, packages/sdk/src/utils/contracts.ts
This PR updates the integration tests to use the SDK for the token bridging tests.
=> feat: use SDK for bridge integration tests

.changeset/young-keys-travel.md, .github/workflows/bss-core.yml, .github/workflows/golangci-lint.yml, go/bss-core/crypto.go, go/bss-core/drivers/clear_pending_tx.go, go/bss-core/drivers/clear_pending_tx_test.go, go/bss-core/drivers/interface.go, go/bss-core/mock/l1client.go
Fixes a bug where clearing txs are rejected on startup if the gas limit is not set.
**Metadata**
- Fixes ENG-1951
=> bss: properly set gas limit on clearing txs

.changeset/kind-zoos-tell.md, ops/scripts/relayer.sh, packages/message-relayer/src/exec/run.ts
Fixes a bug where the relayer package was not correctly running the
start script since the start script updated recently.
**Metadata**
- Fixes #2179
=> fix: make relayer work again

.changeset/spicy-camels-fly.md, packages/contracts/src/deploy-utils.ts
***This has not yet been tested.***
Sourcify verification of contracts during deployment. 
This was surfaced as something that needed to be handled manually during the latest regeneses.
**Metadata**
- Fixes #1983
=> feat: verify contracts on sourcify during deploy

integration-tests/test/bridged-tokens.spec.ts, integration-tests/test/contracts.spec.ts, integration-tests/test/hardfork.spec.ts, integration-tests/test/native-eth-ovm-calls.spec.ts, integration-tests/test/predeploys.spec.ts, integration-tests/test/rpc.spec.ts
Added internal/external import seperation on integration tests
**Metadata**
- Fixes #2017
=> added internal/external import seperation on integration tests

.changeset/chilled-bats-warn.md, packages/sdk/.depcheckrc, packages/sdk/.gitignore, packages/sdk/package.json, packages/sdk/src/cross-chain-messenger.ts, yarn.lock
Adds a new command for automatically generating SDK docs.
=> feat(sdk): support autogenerated docs

.changeset/odd-grapes-wonder.md, packages/sdk/README.md
Updates the SDK README and includes a changeset that will trigger the
1.0.0 release of the SDK.
=> feat(sdk): update README and release 1.0.0

.changeset/slimy-taxis-study.md, packages/sdk/package.json
Updates the package.json file for the SDK to include the correct
repository link.
=> fix(sdk): update package json with correct repo

packages/contracts/README.md
Updates various parts of the contracts README, primarily making sure
that the process for deploying the contracts is up to date.
=> main(ct): finish updating contracts readme

.changeset/mighty-sloths-float.md, .changeset/small-deers-shout.md, .changeset/tame-schools-switch.md, .changeset/three-roses-remember.md, go/teleportr/Makefile, go/teleportr/api/metrics.go, go/teleportr/api/server.go, go/teleportr/cmd/teleportr-api/main.go, go/teleportr/db/db.go, go/teleportr/db/db_test.go, go/teleportr/drivers/disburser/driver.go, go/teleportr/flags/api_flags.go, go/teleportr/go.mod, go/teleportr/go.sum
This PR adds the teleport API server that will be used to facilitate requests for the Gateway and track deposits/disbursements. Posting this sketch to get early feedback on the desired API.
**Metadata**
- Fixes ENG-1933
=> feat: add teleportr API server

CONTRIBUTING.md
Error message isn't immediately helpful.  Might be a common issue for others.
=> docs: update contributing.md for exit code 137

.changeset/good-knives-add.md, .changeset/selfish-paws-reply.md, packages/common-ts/src/base-service/base-service-v2.ts
- Adds proper snake_case for metric names
- Updates log lines for when the service is shutting down
=> various small BaseServiceV2 improvements

.github/workflows/publish-canary.yml, .github/workflows/release.yml
CI infra to publish the indexer service
=> ci: publish indexer docker image

.changeset/great-llamas-watch.md, .github/workflows/indexer.yml
Added a CI job for indexer unit tests, added changeset patch for initial release.
=> indexer changeset

.changeset/chilly-stingrays-decide.md, .changeset/eighty-squids-impress.md, .changeset/gorgeous-eggs-brake.md, .changeset/orange-oranges-bow.md, .changeset/plenty-dancers-eat.md, .changeset/thirty-hairs-remain.md, .changeset/thirty-stingrays-reply.md, go/gas-oracle/CHANGELOG.md, go/gas-oracle/package.json, go/l2geth-exporter/CHANGELOG.md, go/l2geth-exporter/package.json, go/teleportr/CHANGELOG.md, go/teleportr/package.json, integration-tests/CHANGELOG.md, integration-tests/package.json, packages/common-ts/CHANGELOG.md, packages/common-ts/package.json, packages/data-transport-layer/CHANGELOG.md, packages/data-transport-layer/package.json, packages/message-relayer/CHANGELOG.md, packages/message-relayer/package.json, packages/replica-healthcheck/CHANGELOG.md, packages/replica-healthcheck/package.json, yarn.lock
- feat(ct): overhaul deployment process
- go/teleportr contracts: Updates to support deploying Teleportr to Kovan
- Internal and public replicas for mainnet and kovan 0.5.14
- deps: update l2geth-exporter to use go-ethereum v1.10.16
- deps: update bss-core to go-ethereum v1.10.16
- go/teleportr: Add balance metrics
- fix(rhc): fix bug in healthcheck dockerfile
- feat(rhc): cleanly catch connection failures
- feat(itests): add basic healthcheck tests
- fix(ops): collect all logs on failure
- build(deps): bump minimist from 1.2.5 to 1.2.6
- gas-oracle: allow configurable base fee poll interval
- ci: Add CircleCI config
- Version Packages
=> Develop -> Master

packages/contracts/package.json
Adds parallel test execution to contracts to speed things up a bit.
=> feat(ct): run tests in parallel

.github/mergify.yml
Not sure why Mergify didn't pick this up in CI.
=> ci: Fix bad condition

.changeset/lemon-coins-tan.md, go/proxyd/Dockerfile, ops/docker/Dockerfile.batch-submitter-service, ops/docker/Dockerfile.gas-oracle, ops/docker/Dockerfile.geth, ops/docker/Dockerfile.indexer, ops/docker/Dockerfile.l2geth-exporter, ops/docker/Dockerfile.op-exporter, ops/docker/Dockerfile.teleportr
This should speed up builds as more common
base images are built and also opens
up the possibility of using generics in the code.
=> deps: use docker golang:1.18.0-alpine3.15

.changeset/twelve-buses-greet.md
Fixes an issue that breaks releases
=> changesets: delete old batch submitter

.changeset/lazy-mangos-relax.md, .github/workflows/release.yml
Fixes an error in CI for publishing the builder images
=> fix: trigger builder image releases

.github/workflows/changesets.yml, .github/workflows/release.yml
=> Develop -> Master PR

.github/mergify.yml
The config was invalid, and we reached the maximum number of nested rules.
=> ci: Fix mergify config

packages/contracts/test/contracts/L1/verification/BondManager.spec.ts
Cleans up BondManager tests using same techniques as previous test
cleanup PRs.
=> maint(ct): clean up BondManager tests

.circleci/config.yml
Nightly builds added to ci. Images are built for the `nightly` tag.
=> ci: Nightly release builds

package.json
This removes an outdated section of the primary `package.json`.
**Metadata**
- Fixes #2280
=> cleanup: removed outdated section of primary package.json #2280

README.md
This is the most up-to-date logo.
https://github.com/ethereum-optimism/brand-kit/blob/main/assets/svg/Profile-Logo.svg
=> doc: fix OP logo on README.md

.changeset/curvy-bottles-join.md
Bump the go and js builder docker images
=> docker: bump go/js builder images

.changeset/gentle-mugs-know.md
Add changesets for each of the dependabot PRs that were merged recently
=> deps: bump go-ethereum to 1.10.17

.changeset/few-comics-fly.md, .changeset/green-phones-shop.md, .changeset/shy-panthers-hear.md, .changeset/wise-rabbits-drive.md, integration-tests/package.json, l2geth/CHANGELOG.md, l2geth/package.json, packages/common-ts/CHANGELOG.md, packages/common-ts/package.json, packages/contracts-bedrock/CHANGELOG.md, packages/contracts-bedrock/package.json, packages/contracts-periphery/CHANGELOG.md, packages/contracts-periphery/package.json, packages/contracts/CHANGELOG.md, packages/contracts/package.json, packages/core-utils/CHANGELOG.md, packages/core-utils/package.json, packages/core-utils/src/external/geth/geth-types.ts, packages/data-transport-layer/CHANGELOG.md, packages/data-transport-layer/package.json, packages/integration-tests-bedrock/package.json, packages/message-relayer/CHANGELOG.md, packages/message-relayer/package.json, packages/replica-healthcheck/CHANGELOG.md, packages/replica-healthcheck/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
=> Trigger releases

yarn.lock
=> fix: regenerate yarn.lock

Makefile, packages/integration-tests-bedrock/.gitignore, packages/integration-tests-bedrock/foundry.toml, packages/integration-tests-bedrock/package.json, packages/integration-tests-bedrock/test/deposit.spec.ts
Fixes a CI build issue for the forge bedrock integration tests
=> fix: bedrock itests

.changeset/short-nails-burn.md, teleportr/drivers/disburser/driver.go
This is already on mainnet, but as a launch fix release.
=> teleportr: Increase max disbursements to 15

.github/mergify.yml
According to Mergify support this should prevent the looping we've seen.
=> ci: Update mergify to not loop

.changeset/twelve-insects-marry.md, teleportr/api/chain_data.go, teleportr/api/chain_data_test.go, teleportr/api/server.go, teleportr/drivers/disburser/driver.go, teleportr/drivers/disburser/metrics.go, teleportr/drivers/disburser/retry.go, teleportr/drivers/disburser/retry_test.go, teleportr/flags/api_flags.go, teleportr/go.mod, teleportr/go.sum
- Sets Teleportr's status to unavailable if there is a lag between deposits and disbursements.
- Automatically retries disbursements that failed due to networking errors.
=> teleportr: Better availability endpoint + retries

op-e2e/system_test.go
=> e2e tests: Fix leaky timer

.changeset/eight-coats-fix.md, packages/common-ts/src/base-service/base-service-v2.ts
Have BSV2 collect default node metrics
=> feat(cmn): BSV2 collects default metrics

.changeset/chilly-balloons-trade.md, packages/contracts-bedrock/package.json, yarn.lock
Updates the version of the hardhat forge plugin so that the artifacts that are generated are correct
=> deps: update hh forge plugin

packages/contracts/contracts/L1/messaging/L1StandardBridge.sol
=> chore(contracts): Fix comment about safeTransferFrom

packages/contracts-bedrock/deploy-config/devnetL1.ts, packages/contracts-bedrock/tasks/genesis-l2.ts
Updates to foundry/hardhat broke the genesis builder, this fixes them
Fix problems with the genesis builder
=> contracts-bedrock: fix genesis builder

op-e2e/system_test.go
Also updates the test to use a fixed block number to calculate balances, and fixes a subtraction to not mutate the `header.Number` value.
=> op-e2e: Use correct base fee in fees test

.changeset/twelve-days-perform.md, .github/workflows/release.yml, ops/docker/ci-builder/Dockerfile, package.json
Adds `ci-builder` to the changesets setup so that automated releases can happen
=> ci-builder: update foundry + add release changeset

op-node/rollup/driver/step.go
@mslipper hit a bug where the sequencer is producing a block with bad data. To ensure we catch it when it happens again, so we can investigate the issue, we should defensively check the L1 origin changes.
=> bedrock: check L1 origin changes when sequencing new blocks

packages/contracts-periphery/contracts/L1/messaging/L1ERC721Bridge.sol, packages/contracts-periphery/contracts/L2/messaging/L2ERC721Bridge.sol, packages/contracts-periphery/contracts/universal/Semver.sol, packages/contracts-periphery/contracts/universal/op-erc721/OptimismMintableERC721Factory.sol
Removes reinitialization from the ERC721 factory.
=> fix(ctp): remove reinitialization from ERC721 fact

yarn.lock
=> fix: Run yarn dedupe

.changeset/great-grapes-explain.md, packages/contracts-bedrock/package.json, yarn.lock
Bumps typechain, must come before https://github.com/ethereum-optimism/optimism/pull/2937
=> deps: update typechain to 8.1.0

.changeset/empty-pigs-argue.md, ops/docker/Dockerfile.packages, ops/docker/ci-builder/Dockerfile
=> ops: build with ethereumoptimism/foundry:latest

.changeset/rude-ads-try.md, ops/docker/Dockerfile.packages, ops/docker/foundry/Dockerfile, packages/contracts/hardhat.config.ts
Use the same version of alpine across images
=> ops: use alpine:3.14 with foundry image

.circleci/config.yml
Makes it easier to debug when problems go wrong
=> ci: print slither version before running

.changeset/heavy-shoes-know.md, .github/workflows/release.yml
Give the correct path to the dockerfile
The build didn't work again, see https://github.com/ethereum-optimism/optimism/runs/7323865184?check_suite_focus=true
=> ci: ci-builder fix

packages/contracts-bedrock/contracts/L1/L1CrossDomainMessenger.sol, packages/contracts-bedrock/contracts/L1/L1StandardBridge.sol, packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol, packages/contracts-bedrock/contracts/L1/OptimismPortal.sol, packages/contracts-bedrock/contracts/L1/ResourceMetering.sol, packages/contracts-bedrock/contracts/L2/GasPriceOracle.sol, packages/contracts-bedrock/contracts/L2/L2CrossDomainMessenger.sol, packages/contracts-bedrock/contracts/L2/L2StandardBridge.sol, packages/contracts-bedrock/contracts/L2/L2ToL1MessagePasser.sol, packages/contracts-bedrock/contracts/legacy/AddressManager.sol, packages/contracts-bedrock/contracts/legacy/DeployerWhitelist.sol, packages/contracts-bedrock/contracts/legacy/L1ChugSplashProxy.sol, packages/contracts-bedrock/contracts/libraries/Burn.sol, packages/contracts-bedrock/contracts/libraries/rlp/RLPReader.sol, packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol, packages/contracts-bedrock/contracts/universal/OptimismMintableERC20.sol, packages/contracts-bedrock/contracts/universal/OptimismMintableERC20Factory.sol, packages/contracts-bedrock/contracts/universal/Proxy.sol, packages/contracts-bedrock/contracts/universal/ProxyAdmin.sol, packages/contracts-bedrock/contracts/universal/StandardBridge.sol
Just pushing the same commit as in #3058, since CI won't run properly on PRs from forked repos.
=> contracts-bedrock: fix solhint ordering warnings

packages/contracts-bedrock/tasks/genesis-l1.ts, packages/contracts-bedrock/tasks/genesis-l2.ts, packages/contracts-bedrock/tasks/rollup-config.ts
Removes linter errors by importing things that extend types
=> contracts-bedrock: fix imports

.changeset/pretty-olives-wink.md
Includes new version of foundry
Trigger a release of `ci-builder`
=> ops: new ci-builder

.changeset/spotty-cameras-guess.md, packages/contracts-bedrock/scripts/differential-testing.ts
Fixes a bug in the differential tests
=> contracts-bedrock: fix test

.changeset/many-crabs-visit.md, packages/sdk/src/utils/contracts.ts
I put in the token address instead of bridge address.  Tested this one with gateway.
=> feat: Update wsteth address

op-node/rollup/driver/state.go
Suggestion on top of the work of #3130: This implements the derivation step backoff without blocking the other event handling.
=> op-node: event backoff (extends #3130)

.changeset/polite-flies-shop.md, packages/sdk/src/cross-chain-messenger.ts, packages/sdk/src/interfaces/bridge-adapter.ts, packages/sdk/tasks/deposit.ts
Withdrawals don't seem to update balances correctly
for some reason, still need to debug why that is.
=> fix: eth deposits through bridge

yarn.lock
It got out of date, this updates it. The changes
are very minimal.
=> deps: fix yarn.lock

.changeset/thick-books-fail.md, packages/contracts-bedrock/package.json, yarn.lock
=> contracts-bedrock: update @foundry-rs/hardhat-forge

op-bindings/predeploys/addresses.go, op-bindings/predeploys/addresses_test.go, op-e2e/setup.go, op-e2e/system_test.go
Updates the address names and also create a
mapping of addresses so that they can be iterated
over.
=> predeploys: fix address names

state-surgery/state/encoding.go, state-surgery/state/state_test.go
Adds the ability to serialize strings in state.
It only supports strings less than 32 bytes long
which would require major refactoring and we do
not currently need that functionality.
Main test cases come from mainnet WETH contract
=> state-surgery: add string serialization support

state-surgery/immutables/immutables.go, state-surgery/immutables/immutables_test.go
Fix some naming so that it reads better
=> state-surgery: fix naming

.circleci/config.yml
This helps improve performance.
=> ci: Use a docker machine instead of remote docker

.circleci/config.yml, packages/contracts-bedrock/deployments/goerli/ProxyAdmin.json, packages/contracts-bedrock/hardhat.config.ts, state-surgery/genesis/config.go, state-surgery/genesis/genesis.go, state-surgery/genesis/helpers.go, state-surgery/genesis/layer_one.go, state-surgery/genesis/layer_two.go, state-surgery/genesis/layer_two_test.go, state-surgery/state/encoding.go, state-surgery/state/state.go
Generate the L2 genesis block given a hardhat and a deploy config.
=> state-surgery: genesis block generation

.circleci/config.yml
This suite tests deposits and withdrawals.
=> ci: Add hive l1ops suite

.changeset/fast-ligers-fry.md, packages/contracts-bedrock/deploy/001-InitImplementations.deploy.ts, packages/contracts-bedrock/deploy/002-ConfigureProxyAdmin.ts
Uses local nonce management for sending configuration
transactions. This will make the parallel deployments
more reliable.
=> contracts-bedrock: parallel deployment fix

op-bindings/Makefile, op-bindings/bindings/optimismmintableerc20factory.go
Was forgotten because it lives in the `universal`
directory and not the `L2` directory
=> op-bindings: add OptimismMintableERC20Factory

packages/contracts-bedrock/deploy/001-InitImplementations.deploy.ts
Removes a left over console.log in the deploy script
=> contracts-bedrock: remove extra console.log

op-bindings/Makefile, op-bindings/bindings/erc20.go, op-bindings/bindings/optimismmintableerc20.go, op-bindings/bindings/weth9.go
Adds more bindings that will be useful for the indexer and the L2 genesis creation
=> op-bindings: add more bindings

op-node/p2p/gossip.go
- OPB-05: Puts the signature verification before further unmarshaling to guard against mal-formed payloads.
- Adds a minimum size check to the payload decoding to ensure we always have at least a signature and a payload available.
=> op-node: Fix OPB-05, fix additional security issue

indexer/db/db.go, proxyd/errors.go
These where missed in local lints but when a full lint was run these popped up.
=> Last unwrapped errors

CONTRIBUTING.md
=> Fix: expired Discord link

op-chain-ops/genesis/setters.go
Improve the error message during genesis generation
=> op-chain-ops: better error message

packages/contracts-bedrock/.storage-layout
Commits the new storage layout
=> contracts-bedrock: regenerate storage layout

ops/docker/ci-builder/check-changed.sh
check-changed was breaking when develop -> master PRs were open.
=> ci: Fix check-changed

op-node/rollup/derive/engine_queue.go
=> op-node: emit l2_finalized block

packages/contracts-bedrock/README.md
Lints the readme in `contracts-bedrock`
=> contracts-bedrock: lint readme

packages/contracts-bedrock/contracts/L1/L1StandardBridge.sol, packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol, packages/contracts-bedrock/contracts/L2/L2StandardBridge.sol, packages/contracts-bedrock/contracts/libraries/Encoding.sol, packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol, packages/contracts-bedrock/contracts/universal/ProxyAdmin.sol, packages/contracts-bedrock/contracts/universal/StandardBridge.sol, specs/deposits.md
These changes address comments made by the OpenZeppelin auditors.
**Tests**
Comments and documentation only, no tests have been added.
=> Various improvements to documentation in the smart contracts and deposit spec

.changeset/empty-emus-own.md, .circleci/config.yml, ops/docker/ci-builder/Dockerfile
Fixes an issues with the codecov download in the `ci-builder` image.
=> ci: Fix download/verify codecov in builder image

.changeset/spicy-points-invent.md, packages/contracts-periphery/contracts/universal/drippie/dripchecks/CheckBalanceHigh.sol, packages/contracts-periphery/contracts/universal/drippie/dripchecks/CheckBalanceLow.sol, packages/contracts-periphery/contracts/universal/drippie/dripchecks/CheckGelatoLow.sol, packages/contracts-periphery/contracts/universal/drippie/dripchecks/CheckTrue.sol
Bumps the version on drip checks to match Drippie.sol
=> ctp: Bump version in drip checks

.circleci/config.yml
I'm still seeing sporadic errors with the l1ops tests. This PR fixes the artifacts upload so that I can debug further.
=> ci: Fix Hive artifacts

.circleci/config.yml
Need to include these artifacts for the contracts tests to work.
=> ci: Fix contracts tests

packages/contracts-periphery/deploy/nft-bridge/L2ERC721BridgeImplementation.ts, packages/contracts-periphery/hardhat.config.ts
Use the companion network config to ensure that the correct artifact is being used.
=> cpt: nft bridge deploy script bugfix

op-node/rollup/derive/engine_update.go
This splits the payload building process into two steps. The payload building is common between verifier and sequencer, but a sequencer may want to give the Engine more time before sealing the block that is built, so it can fill the block, and optimize tx choice. Similarly, in action testing, as L2 sequencer actor, we want to enact the building of the payload as Engine actor to reach different edge-cases, and thus also need to breathe before sealing the payload.
This PR does not change any functionality, it merely refactors a function into two parts, and adds docs.
=> op-node: split start of payload building and confirmation of payload

.github/mergify.yml
This allows us to use stacked diffs more effectively.
=> ci: Have Mergify use a merge commit

.changeset/shy-trainers-sneeze.md, proxyd/server.go
Adds support for pattern matchin in exempt origins. This should help with some of the issues Synthetix and others are seeing.
=> proxyd: Support pattern matching in origin and user agent

packages/contracts-bedrock/deploy/001-InitImplementations.deploy.ts
=> ctb: Fix deploy script

ops/docker/scripts/dashboard-sync.py
This solves Issue #3709
Updated the grafana dashboard
=> Update grafana dashboard

packages/contracts-bedrock/contracts/test/CrossDomainMessenger.t.sol
Resolves a small compiler warning. Nothing significant.
=> fix(ctb): resolve compiler warning

README.md
I made the monorepo prettier and added some more detail. A good readme makes the monorepo gods happy.
=> feat(docs): update readme

.changeset/fluffy-ducks-compare.md, indexer/flags/flags.go
Flags don't appear to be used anywhere
=> chore: Delete some unused flags

packages/migration-data/.gitignore, packages/migration-data/bin/cli.ts
Adds a command for parsing state dump files from l2geth into two json files to be inputted to the migration script.
=> feat(md): state dump file parsing

.changeset/real-deers-heal.md, l2geth/statedumper/dumper_test.go, op-chain-ops/genesis/config.go
=> l2geth: Fix state dumper

package.json
Removes an outdated no-hoist entry from the root package.json file.
=> Remove outdated no-hoist entry

packages/contracts/docs/CanonicalTransactionChain.md, packages/contracts/docs/IBondManager.md, packages/contracts/docs/IL2ERC20Bridge.md, packages/contracts/docs/IStateCommitmentChain.md, packages/contracts/docs/L2StandardBridge.md, packages/contracts/docs/StateCommitmentChain.md, packages/contracts/docs/iOVM_L1BlockNumber.md, packages/contracts/docs/iOVM_L2ToL1MessagePasser.md
New docstrings were added, now the auto generated docs are updated as well.
=> contracts: update docs

op-batcher/driver.go, op-batcher/txmgr.go
This is a wrapper on top of the transaction manger. It does simple nonce management
and provides a nice interface to the underlying transaction manager.
=> op-batcher: New Transaction Manager

packages/contracts-bedrock/deploy/008-L1StandardBridgeImpl.ts, packages/contracts-bedrock/deploy/011-OptimismMintableERC20FactoryImpl.ts, packages/contracts-bedrock/deploy/012-L1ERC721BridgeImpl.ts
=> fix(ctb): broken devnet tests

.changeset/large-actors-leave.md, op-bindings/bindings/l2erc721bridge_more.go, op-bindings/bindings/optimismmintableerc721factory_more.go, packages/contracts-bedrock/.solhint.json, packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol, packages/contracts-bedrock/contracts/L1/OptimismPortal.sol, packages/contracts-bedrock/contracts/deployment/BaseSystemDictator.sol, packages/contracts-bedrock/contracts/deployment/MigrationSystemDictator.sol, packages/contracts-bedrock/contracts/deployment/PortalSender.sol, packages/contracts-bedrock/contracts/universal/ERC721Bridge.sol, packages/contracts-bedrock/contracts/universal/IOptimismMintableERC721.sol, packages/contracts-bedrock/contracts/universal/OptimismMintableERC721.sol, packages/contracts-bedrock/contracts/universal/OptimismMintableERC721Factory.sol, packages/contracts-bedrock/contracts/universal/Semver.sol
Clears remaining contracts-bedrock lint warnings.
=> fix(ctb): clear remaining lint warnings

op-node/rollup/driver/origin_selector_test.go
=> op-node: Add unit tests to origin selector

codecov.yml
Fixes some issues in the current codecov config.
=> ci: Fixes to codecov configuration

specs/deposits.md, specs/derivation.md, specs/glossary.md, specs/system_config.md
Define the system configuration updates, reading, derivation and corresponding L1 block info changes in the specification.
This specifies the system configuration changes in #3787, #3788, #3789, #3790.
=> specs: system configuration contract and derivation [bedrock]

ops/docker/ci-builder/Dockerfile, packages/contracts-bedrock/README.md
Updates the version of foundry used in CI
Fixes ENG-2982
=> ci: update foundry

.changeset/modern-pens-wave.md
Adds a changeset so that `ci-builder` gets a release
=> ci-builder: add changeset

ops-bedrock/Dockerfile.l2, ops-bedrock/docker-compose.yml, ops-bedrock/entrypoint.sh, packages/contracts-bedrock/deploy-config/devnetL1.json
Various fixes to make the devnet run again.
=> ci: Fix devnet

packages/contracts-bedrock/deploy/015-FreshSystemDictator.ts, packages/contracts-bedrock/deploy/017-MigrationSystemDictator.ts, packages/contracts-bedrock/src/deploy-utils.ts
Asserts `Dictator` configuration after deployment.
=> feat(ctb): assert dictator config

.changeset/quick-mangos-thank.md, indexer/Dockerfile, indexer/docker.go.work
I build this locally with the following command:
```bash
docker build --file ./indexer/Dockerfile --tag indexer:test .
```
Can confirm that it works, the build command is very similar to the one used in CI
=> indexer: fix docker build

op-chain-ops/genesis/db_migration.go
Should fix the failing build on develop.
=> chain-ops: fix double import of log

yarn.lock
Yarn lock file seems to have gotten out of date.
=> fix(ci): update yarn lock

packages/migration-data/bin/cli.ts, specs/overview.md
That last contributor PR added a too long line. My bad.
=> specs: Fix long line

packages/contracts-bedrock/contracts/deployment/MigrationSystemDictator.sol
Introduces the first exit point for the MigrationSystemDictator.
=> feat(ctb): MSD exit point 1

packages/sdk/tasks/deposit-erc20.ts
=> fix(sdk): test flakes

.circleci/config.yml, bedrock-devnet/devnet/__init__.py, packages/contracts-bedrock/deploy/018-MigrationSystemDictatorSteps.ts
Re-enables the devnet deployment in CI, forgot to re-enable it before making changes to the deploy script
=> ci: enable devnet deploy

packages/contracts-bedrock/contracts/deployment/MigrationSystemDictator.sol, packages/contracts-bedrock/deploy/018-MigrationSystemDictatorSteps.ts
Fixes a deploy bug that slipped through CI because the devnet test was not a required check.
=> fix(ctb): deploy bug

.changeset/purple-waves-poke.md
Missed a changeset for adding echidna to ci-builder.
=> Add missing changeset

op-node/chaincfg/chains.go
Updates the Beta-1 config to match the config post-regenesis.
=> op-node: Update Beta-1 config

op-chain-ops/crossdomain/migrate.go, op-chain-ops/genesis/db_migration.go
The `op-migrate` script had some leftover stuff
in it from early iterations on its development.
The leftover stuff was cleaned up to improve the
overall UX of the script. Now code should not need to be commented out + rebuild the binary, it will
automatically detect when the script has already
ran on a datadir.
Also pass through the no check arg so that we can
re-enable the checking and dynamically change if
we want to run the data validation as part of the
migration.
=> op-chain-ops: more cleanup in migrate script

op-chain-ops/ether/migrate.go
Check for `nil` when getting the chain params.
Also log info about the chain params
=> op-chain-ops: safety with params

op-chain-ops/genesis/db_migration.go
Adds cleanup to the migration script, ensures that config is sane.
We cannot allow for non monotonic block time. We also try to make eip 1159 stable at start and use a hardcoded initial base fee.
Add additional logging
=> op-migrate: various sanity checks + cleanup

op-node/flags/flags.go
**Tests**
**Invariants**
**Metadata**
=> op-node: Update heartbeat DNS

packages/contracts-bedrock/contracts/deployment/MigrationSystemDictator.sol, packages/contracts-bedrock/deploy-config/devnetL1.json, packages/contracts-bedrock/deploy-config/goerli-forked.json, packages/contracts-bedrock/deploy/007-L1ERC721BridgeProxy.ts, packages/contracts-bedrock/deploy/018-MigrationSystemDictatorSteps.ts, packages/contracts-bedrock/hardhat.config.ts, packages/contracts-bedrock/src/deploy-utils.ts
Various fixes to the migration script as discovered during migration practice.
=> fix(ctb): various migration fixes

packages/contracts-bedrock/deploy-config/goerli.json
Creates a Goerli deploy config. Would like review from @trianglesphere, @tynes, and @smartcontracts on this. I'll respond in PR comments with specific values that give me pause.
=> ctb: Create Goerli deploy config

op-chain-ops/cmd/op-migrate/main.go
Removes the starting-l1-block-number field from the migration command. The field is replaced with the `l1StartingBlockTag` field to keep things consistent.
=> op-chain-ops: Remove starting-l1-block-number field

packages/contracts-bedrock/contracts/L1/L1StandardBridge.sol, packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol, packages/contracts-bedrock/contracts/L1/SystemConfig.sol, packages/contracts-bedrock/contracts/L2/BaseFeeVault.sol, packages/contracts-bedrock/contracts/L2/CrossDomainOwnable.sol, packages/contracts-bedrock/contracts/L2/CrossDomainOwnable2.sol, packages/contracts-bedrock/contracts/L2/L2StandardBridge.sol, packages/contracts-bedrock/contracts/universal/StandardBridge.sol
Cleans up a few minor issues with comments.
**Tests**
Please describe any tests you've add
=> maint(ctb): minor comment cleanup

.changeset/stale-experts-roll.md, packages/data-transport-layer/src/services/l1-ingestion/service.ts
Fixes a bug with the DTL's shutoff block logic.
=> fix(dtl): bug with shutoff logic

.changeset/cold-mangos-explain.md, packages/sdk/src/cross-chain-messenger.ts
Removes an unused variable and function from the SDK.
=> maint(sdk): remove unused variable

packages/contracts-bedrock/deploy/000-ProxyAdmin.ts, packages/contracts-bedrock/deploy/001-AddressManager.ts, packages/contracts-bedrock/deploy/002-L1StandardBridgeProxy.ts, packages/contracts-bedrock/deploy/003-L2OutputOracleProxy.ts, packages/contracts-bedrock/deploy/004-L1CrossDomainMessengerProxy.ts, packages/contracts-bedrock/deploy/005-OptimismPortalProxy.ts, packages/contracts-bedrock/deploy/006-OptimismMintableERC20FactoryProxy.ts, packages/contracts-bedrock/deploy/007-L1ERC721BridgeProxy.ts, packages/contracts-bedrock/deploy/008-SystemConfigProxy.ts, packages/contracts-bedrock/deploy/009-SystemDictatorProxy.ts, packages/contracts-bedrock/deploy/010-L1CrossDomainMessengerImpl.ts, packages/contracts-bedrock/deploy/011-L1StandardBridgeImpl.ts, packages/contracts-bedrock/deploy/012-L2OutputOracleImpl.ts, packages/contracts-bedrock/deploy/013-OptimismPortalImpl.ts, packages/contracts-bedrock/deploy/014-OptimismMintableERC20FactoryImpl.ts, packages/contracts-bedrock/deploy/015-L1ERC721BridgeImpl.ts, packages/contracts-bedrock/deploy/016-PortalSenderImpl.ts, packages/contracts-bedrock/deploy/017-SystemConfigImpl.ts, packages/contracts-bedrock/deploy/018-SystemDictatorImpl.ts, packages/contracts-bedrock/src/deploy-utils.ts
Cleans up the custom deployment function that we wrap around hardhat-deploy and adds new function comments. The function no longer does source verification, so I changed the name.
=> maint(ctb): clean up deploy function

op-service/httputil/server.go
Updates `ListenAndServeContext` to prevent a goroutine leak and return `nil` if the context is canceled.
=> op-service: Exit HTTP server more cleanly

packages/contracts-bedrock/scripts/forge-test-names.ts
Cleans up the test names script and fixes a few errors.
=> fix(ctb): clean and fix test names script

.changeset/hot-beds-cough.md, packages/data-transport-layer/src/services/l1-ingestion/service.ts
=> feat(dtl): fast goerli sync

.changeset/cold-eyes-rescue.md, .changeset/plenty-sheep-scream.md, integration-tests/package.json, package.json, packages/actor-tests/package.json, packages/contracts-bedrock/package.json, packages/contracts-governance/package.json, packages/contracts-periphery/package.json, packages/contracts/package.json, packages/data-transport-layer/package.json, packages/drippie-mon/package.json, packages/fault-detector/package.json, packages/hardhat-deploy-config/package.json, packages/message-relayer/package.json, packages/migration-data/package.json, packages/replica-healthcheck/package.json, yarn.lock
Updates TypeScript to the latest version so we get access to the satisfies keyword.
=> maint: update TypeScript version

.changeset/healthy-teachers-stare.md, .changeset/neat-terms-buy.md, .circleci/config.yml, .gitignore, codecov.yml, ops/docker/ci-builder/Dockerfile, packages/contracts-bedrock/contracts/echidna/FuzzAddressAliasing.sol, packages/contracts-bedrock/echidna.yaml, packages/contracts-bedrock/foundry.toml, packages/contracts-bedrock/package.json
This PR adds a simple echidna test which tests an address aliasing round trip.
It also does some basic scaffolding to lay the groundwork for forthcoming echidna tests.
=>  CI: Echidna tests for Aliasing

.changeset/perfect-guests-relax.md, op-chain-ops/crossdomain/migrate.go, packages/sdk/src/cross-chain-messenger.ts
Set the withdrawal migration gas limit to
a non zero number.
=> fix: migration gaslimit

.changeset/late-cameras-jam.md, .circleci/config.yml, packages/contracts-bedrock/contracts/echidna/FuzzResourceMetering.sol, packages/contracts-bedrock/echidna.yaml
Adds ResourceMetering fuzz tests with Echidna.
=> ctb: Add echidna tests for metering

.changeset/light-buckets-flash.md, .circleci/config.yml, packages/contracts-bedrock/contracts/echidna/FuzzHashing.sol
=> ctb: Add echidna tests for Hashing

packages/contracts-periphery/contracts/foundry-tests/AttestationStation.t.sol
Small followup to attestation contract saw unused imports
=> feat(contracts-periphery): Remove unused import from attestation contract

.changeset/stale-crews-kiss.md, packages/contracts-periphery/package.json
- add a yarn script for forge test coverage
=> feat(contracts-periphery): Add package.json script for forge test coverage

packages/contracts-bedrock/.solhint.json, packages/contracts-bedrock/contracts/echidna/FuzzAddressAliasing.sol, packages/contracts-bedrock/contracts/echidna/FuzzBurn.sol, packages/contracts-bedrock/contracts/echidna/FuzzEncoding.sol, packages/contracts-bedrock/contracts/echidna/FuzzHashing.sol, packages/contracts-bedrock/contracts/echidna/FuzzResourceMetering.sol
=> ctb: Fix linter warnings in echidna contracts

.changeset/famous-insects-try.md, .circleci/config.yml, packages/contracts-bedrock/contracts/echidna/FuzzOptimismPortal.sol
Another echidna test, this one meant to verify the important property that, given valid inputs, the `depositTransaction()` function does not revert.
=> ctb: Add echidna test ensuring depositTransaction completes

packages/contracts-bedrock/contracts/L2/BaseFeeVault.sol, packages/contracts-bedrock/contracts/L2/L1FeeVault.sol
=> contracts-bedrock: delete unused imports

.changeset/nervous-wasps-check.md, packages/contracts-periphery/config/deploy/ethereum.ts, packages/contracts-periphery/config/deploy/hardhat.ts, packages/contracts-periphery/config/deploy/kovan.ts, packages/contracts-periphery/config/deploy/optimism-goerli.ts, packages/contracts-periphery/config/deploy/optimism-kovan.ts, packages/contracts-periphery/config/deploy/optimism.ts, packages/contracts-periphery/deploy/op-nft/AttestationStationImpl.ts, packages/contracts-periphery/deploy/op-nft/AttestationStationProxy.ts, packages/contracts-periphery/src/config/deploy.ts
- Add deploy script
- Add proxy script
=> feat(contracts-periphery): Add deploy script for AttestationStation

.changeset/thick-ligers-smell.md, packages/contracts-periphery/config/deploy/ethereum.ts, packages/contracts-periphery/config/deploy/hardhat.ts, packages/contracts-periphery/config/deploy/kovan.ts, packages/contracts-periphery/config/deploy/optimism-goerli.ts, packages/contracts-periphery/config/deploy/optimism-kovan.ts, packages/contracts-periphery/config/deploy/optimism.ts, packages/contracts-periphery/deploy/op-nft/OptimistImpl.ts, packages/contracts-periphery/deploy/op-nft/OptimistProxy.ts, packages/contracts-periphery/src/config/deploy.ts
- Add deploy script for optimist sbt
=> feat(contracts-periphery): Add Optimist SBT deploy script

.changeset/orange-needles-suffer.md, packages/contracts-periphery/src/config/deploy.ts
- add as default options to config
=> feat(contracts-periphery): Add optimistName and optimistSymbol

packages/contracts-periphery/config/deploy/hardhat.ts, packages/contracts-periphery/deploy/op-nft/AttestationStationProxy.ts
Deploys the proxy in a deterministic manner for
the attestationstation
=> ctp: AttestationStation deterministic proxy

packages/contracts-periphery/config/deploy/hardhat.ts, packages/contracts-periphery/deploy/op-nft/OptimistProxy.ts
Deterministic deployment of the `OptimistProxy` contract
=> ctp: deterministic deployment optimist proxy

packages/contracts-periphery/contracts/foundry-tests/Optimist.t.sol
- remove some repetition in optimist tests
=> feat(contracts-periphery): Clean up optimist tests

packages/contracts-periphery/contracts/universal/op-nft/Optimist.sol
Cleans up comments inside the Optimist NFT.
=> maint(ctp): clean up Optimist comments

op-node/node/node.go
I only set `OpNode.server` to the created server if it starts up successfully. This alleviates an error where if creation succeeds, but startup does not, we attempt to stop the server which panics.
This also adds logging to indicate that initialization failed. This logging primarily benefits users who call `node.New` directly rather than end users because there is already logging in the main function.
**Tests**
I tested this manually with op-e2e & was able to reproduce the error & confirm that it is fixed.
**Metadata**
- Fixes ENG-2863
=> op-node: Fix panic when p2p server fails to start

packages/contracts-bedrock/contracts/test/L2ERC721Bridge.t.sol, packages/contracts-bedrock/contracts/test/MerkleTrie.t.sol
Fixes a few small linting errors.
=> fix(ctb): linting errors

.changeset/great-cherries-bake.md, .changeset/weak-crabs-reflect.md, .github/workflows/release.yml, packages/balance-monitor/package.json
Fixes inconsistent package naming for the `balance-monitor` package.
=> bmon(chore): Fix package name

ops-bedrock/devnet-up.sh, ops-bedrock/docker-compose.yml
Reverts ethereum-optimism/optimism#4641
=> Revert "feat(ops-bedrock): Add gateway ui to make devnet-up"

indexer/flags/flags.go
Flag type is a Bool for a couple of flags.  I think it's just copy paste pasta.
=> fix(indexer): Fix flag type

op-node/client/rpc.go
This is done in BaseClient because all RPC calls in the op-node flow through the base client. I have set it to 10s for the CallContext and 20s for the BatchCallContext. These values are large enough to handle complex computation, but will prevent a slow loris or throttling attack. Smaller timeouts can stil be set further up the chain.
**Tests**
None.
=> op-node: Set RPC timeouts

.changeset/cyan-cougars-push.md, packages/balance-monitor/package.json
Tweaks the Balance Monitor package json to correctly export dist and src folders.
=> fix(bm): tweak package json

package.json, yarn.lock
- update changesets to latest version
- this version has better error handling
=> feat(ci): Update changesets to latest version

ops/check-changed/main.py
Adds a bunch of patterns that should trigger a rebuild of all dependencies. Mostly related to build stuff.
=> check-changed: Add additional patterns to force total rebuild

.changeset/many-toys-sleep.md, ops/docker/Dockerfile.packages
Fix a copy paste typo in Dockerfile.packages.
=> fix(bmon): Fix balance monitor name

.circleci/config.yml
Creates docker build jobs in circleci for indexer
=> creates indexer docker build cci configs

op-chain-ops/cmd/op-migrate/main.go, op-chain-ops/genesis/check.go, packages/contracts-bedrock/deploy-config/goerli.json
**Tests**
**Invariants**
**Metadata**
=> finalize goerli config

.changeset/new-actors-yawn.md, packages/sdk/src/utils/chain-constants.ts
These addresses correspond to the proxies
=> sdk: add in bedrock addresses

packages/sdk/tasks/deposit-eth.ts
Improves the logs in the deposit task, makes
it easier to run on production networks.
=> sdk: better logs in deposit task

op-node/p2p/cli/load_config.go
See https://github.com/ethereum-optimism/optimism/pull/4669#discussion_r1067413614
Depends on #4669
=> op-node: P2P key path check

op-batcher/batcher/driver.go
=> op-batcher: Fix typo

.circleci/config.yml, ops/docker/Dockerfile.packages
Adds the new package to Dockerfile.packages and releases.yml
=> Add two step monitor package to dockerfile and releases

op-node/heartbeat/service.go, op-node/metrics/metrics.go, op-node/p2p/gossip.go, op-node/p2p/node.go, op-node/sources/batching.go, op-node/sources/eth_client.go, op-node/sources/l1_client.go, op-node/sources/l2_client.go
In-line documentation for the `op-node` split out of #4743
=> feat: op-node docs

specs/assets/batch-deriv-chain.svg
In the right bottom of the digram, the sequence number under block 11 should be 4 instead of 2.
=> fix batch-deriv-chain.svg

op-batcher/batcher/txmgr.go
Be extra pendantic around expected data being not `nil` to prevent unexpected panics.
=> op-batcher: better error handling logic

.changeset/tasty-adults-design.md, packages/common-ts/src/base-service/base-service-v2.ts
Add body parser options so we can configure larger max size
=> allow body parser options to be passed in

CONTRIBUTING.md
I saw this in the foundry docs and thought it would be good to add to ours
=> docs: Add note about small contributions

CITATION.cff
Adds a CITATION file as per user request.
Closes #4827
=> maint: add CITATION file

op-node/p2p/gossip.go
Since #4864 nodes on any chain that still had a sequencer using the legacy block gossip hash (all of them currently) would print a `unexpected block author` warning for each gossip message because the signature check using the new block hash algorithm failed.
This updates the logic to check the legacy hash first without logging any warnings, then if that isn't accepted, check with the new hash and log warnings on failure.
**Metadata**
- Part of https://linear.app/optimism/issue/CLI-3341/sherlock-067-125-chain-id-is-clobbered-in-p2p-signing-hash
=> Don't log warnings when legacy block gossip validation fails

op-signer/client/client.go
Make tls config optional for the op-signer client
**Tests**
Haven't added tests, but did run op-batcher with this config and got it to use the default http client.
**Metadata**
=> Make tlsconfig optional for op-signer client

.changeset/moody-planes-greet.md, packages/contracts-bedrock/contracts/universal/IOptimismMintableERC20.sol
Inherits `IERC165` to `IOptimismMintableERC20`.
=> fix(ctb): add is IERC165 to IOptimismMintableERC20

.circleci/config.yml
Was on the other devnet task, not this one though.
=> Add logs to devnet-up test

op-chain-ops/genesis/db_migration.go
=> op-chain-ops: Fix misleading comment

.editorconfig, op-bindings/Makefile
Prints the version of abigen running in CI to debug the unexpected diff in erc20.go
=> feat(bindings): Print abigen version in CI

packages/atst/src/constants/defaultDataType.ts, packages/atst/src/constants/defaultRpcUrl.ts, packages/atst/src/index.ts, packages/atst/src/lib/__snapshots__/logger.spec.ts.snap, packages/atst/src/lib/parseAttestationBytes.spec.ts, packages/atst/src/lib/parseAttestationBytes.ts, packages/atst/src/lib/prepareWriteAttestation.spec.ts, packages/atst/src/lib/prepareWriteAttestation.ts, packages/atst/src/lib/prepareWriteAttestations.spec.ts, packages/atst/src/lib/prepareWriteAttestations.ts, packages/atst/src/lib/readAttestation.spec.ts, packages/atst/src/lib/readAttestation.ts, packages/atst/src/lib/readAttestations.spec.ts, packages/atst/src/lib/readAttestations.ts, packages/atst/src/lib/stringifyAttestationBytes.ts, packages/atst/src/lib/writeAttestation.spec.ts, packages/atst/src/lib/writeAttestation.ts, packages/atst/src/types/AttestationReadParams.ts, packages/atst/src/types/DataTypeOption.ts, packages/atst/src/types/WagmiBytes.ts
Add the sdk to @eth-optimism/sdk
=> :sparkles: Add atst SDK

packages/atst/README.md
**[Check it out!](https://github.com/ethereum-optimism/optimism/blob/06dce6882e3649e3fff7482f408afbdb15a60af5/packages/atst/README.md)**
Preview:
=> Minor cleanup on README

.changeset/tall-insects-buy.md
To trigger the release process for chain-mon on the next release.
=> chore(cmon): Add a changeset

packages/atst/docs/sdk.md, packages/atst/src/index.ts, packages/atst/src/lib/encodeRawKey.spec.ts, packages/atst/src/lib/encodeRawKey.ts, packages/atst/src/lib/prepareWriteAttestation.ts, packages/atst/src/lib/prepareWriteAttestations.ts
- adds an encodeRawKey function
- will kekkak256 keys longer than 32 bytes
=> feat(atst): Add encodeRawKey

op-service/txmgr/txmgr.go, op-service/txmgr/txmgr_test.go
Return the same transaction if we don't update any fields. We do this because Ethereum signatures are not deterministic and therefore the transaction hash will change wwhen we re-sign the tx. We don't want to do that because we want to see ErrAlreadyKnown instead of ErrReplacementUnderpriced.
**Metadata**
- Fixes CLI-3546
=> op-service/txmgr: Return previous tx if no updates

op-node/rollup/derive/frame.go, op-node/rollup/derive/params.go
=> op-node/derivation: JSON Encoding for Frames

packages/contracts/docs/TeleportrDisburser.md
=> contracts: fix typo in TeleportrDisburser.md

packages/contracts-bedrock/src/deploy-utils.ts
It is possible for the backend to prune the chain db which will cause `waitForTransaction` to hang forever if the contract was not recently deployed. Only check for the transaction if it was recently deployed and instead add a safety check that looks at the on chain code. It is unlikely to deploy a contract that leaves no code in the state, so this is safe. The state cannot be pruned so this will be a more reliable check to ensure that the deployment is sane and exists. We do not use selfdestruct so this is safe.
=> contracts-bedrock: fix deploy utils

.circleci/config.yml
=> CI: Cache yarn

.circleci/config.yml
Properly checks that files are changed when running contracts-bedrock tests.
=> fix(ci): check changed for contracts tests

docs/op-stack/src/.vuepress/config.js
Updates the Algolia search key for the OP Stack docs.
=> fix(docs): update algolia search key

op-batcher/batcher/txmgr.go, op-proposer/proposer/l2_output_submitter.go
This will hopefully help with some of the send issues we've been seeing.
I'd like to wait a release cycle or two to include this so I can track down
other issues, but long term I think this is the right thing to do.
=> op-batcher/proposer: Increase sendTx timeout

op-e2e/actions/l1_miner.go, op-e2e/actions/l2_batcher.go, op-e2e/actions/l2_batcher_test.go
Test to ensure the channel functionality works as expected in case of high-demand for lots of L2 calldata. This ensures we can handle batch-derivation when L2 blocks grow larger than L1 blocks and batcher data-tx target size.
This also includes some minor changes to the action test actors, to modify tx-options of the batcher, catch the full-channel error, and be more explicit about tx-inclusion (to not rely on pending-block for nonce values and such).
=> op-e2e: test high-demand large L2 blocks case

op-node/flags/flags.go, op-node/rollup/derive/batch_queue.go, op-node/rollup/derive/channel_bank.go
Log more in the channel bank & batch queue to aid debugging.
=> op-node: More logging

op-e2e/bridge_test.go
Adds a test for bridging an ERC20 token through the L1StandardBridge
=> op-e2e: bridge erc20 test

docs/op-stack/src/docs/contribute.md
Contribute to OP Stack should say Contribute to the OP Stack.
=> fix(docs): minor typo in contributing title

.changeset/clever-jokes-notice.md, packages/contracts-bedrock/deploy/020-SystemDictatorSteps-1.ts, packages/contracts-bedrock/deploy/021-SystemDictatorSteps-2.ts
30 seconds is too long, it feels like the script is broken.
=> feat(ctb): reduce the timeout on awaitCondition

docs/op-stack/src/docs/build/getting-started.md, packages/contracts-bedrock/deploy-config/getting-started.json
=> feat(deploy-config/getting-started): `Clarify TIMESTAMP` is int

.github/workflows/release.yml
Fixes a small bug in the release workflow file.
=> fix(ci): error in release workflow file

docs/op-stack/src/.vuepress/config.js, docs/op-stack/src/docs/build/conf.md, docs/op-stack/src/docs/build/getting-started.md, docs/op-stack/src/docs/build/operations.md
This also adds a number of tidbits, such as "how to reduce your ETH costs" and "what is the maximum block time".
Closing: DEVRL-782, DEVRL-808
=> feat(docs/op-stack): Add an operations page

op-node/rollup/derive/system_config.go
Updated the error message for ConfigUpdateEventABIHash check
=> fix: sys config error message correction

specs/dispute-game-interface.md
Expands on the dispute game interface started in #5264 by @tynes.
**Metadata**
- Closes CLI-3478
**TODOs**
=> 🤼 DisputeGame interfaces

op-node/p2p/sync_test.go
Remove timeouts on sync tests, since CI resources or scheduling seems too limited to meet them. cc @trianglesphere
=> op-node: remove sync test timeouts for CI

packages/contracts-bedrock/scripts/slither.sh, packages/contracts-bedrock/slither.config.json
Fixes an incorrect boolean branch statement that was causing slither to run in triage mode in CI.
=> fix(ctb): Do not run slither triage in CI

specs/introduction.md
Closing: DEVRL-848
As per https://github.com/sherlock-audit/2023-01-optimism-judging/blob/b7921698c1c537714c5f2021aa46ce0a1935ba39/1-specs-findings/1-processed/1-true/names/214.md#L1
=> feat(specs/introduction.md): Sherlock correction

specs/dispute-game-interface.md, specs/dispute-game.md
WIP dispute game interface specs based on work by @clabby 
Closes CLI-3479
Closes CLI-3478
=> specs: DisputeGame interface + behavior

specs/bridges.md
Closing: DEVRL-846
As per https://github.com/sherlock-audit/2023-01-optimism-judging/blob/b7921698c1c537714c5f2021aa46ce0a1935ba39/1-specs-findings/1-processed/1-true/bridge-interface/208.md#L1
=> feat(specs/bridges.md): Sherlock correction

specs/challenger.md
Fixes the lint error introduced in #5360
=> fix: specs lint

specs/guaranteed-gas-market.md
Closing: DEVRL-849
Sherlock finding https://github.com/sherlock-audit/2023-01-optimism-judging/blob/b7921698c1c537714c5f2021aa46ce0a1935ba39/1-specs-findings/1-processed/1-true/basefee-math/266.md
=> fix(spects/guaranteed-gas-market): Sherlock correction

op-e2e/actions/blocktime_test.go
Fix TestBatchInLastPossibleBlocks flake: the `PendingNonceAt` was not stable.
=> op-e2e: fix TestBatchInLastPossibleBlocks flake

op-e2e/system_test.go
Previously the logs looked like this:
```
node.go:349:                INFO [04-17|15:37:04.297] Publishing signed execution payload on p2p role=sequencer id=9e8876..ff5492:1
node.go:349:                INFO [04-17|15:37:04.305] Publishing signed execution payload on p2p role=sequencer id=8c249f..20419f:2
node.go:364:                INFO [04-17|15:37:04.305] Received signed execution payload from p2p role=verifier  id=8c249f..20419f:2   peer=QmS56i9RQdZtcVPHDBfznMvSdamc3CV5b7stp2JxUqYP82
node.go:349:                INFO [04-17|15:37:04.309] Publishing signed execution payload on p2p role=sequencer id=25a64e..8c458e:3
node.go:364:                INFO [04-17|15:37:04.311] Received signed execution payload from p2p role=verifier  id=25a64e..8c458e:3 …
```
=> op-e2e: fix TestSystemMockP2P - wait for peers to mesh

specs/withdrawals.md
=> fix(specs/withdrawals): Sherlock updates

.circleci/config.yml
=> test(ci): Add circleci for atst

.circleci/config.yml, packages/contracts-dispute/.gas-snapshot, packages/contracts-dispute/.storage-layout, packages/contracts-dispute/package.json, packages/contracts-dispute/scripts/storage-snapshot.sh, packages/contracts-dispute/src/AttestationDisputeGame.sol, packages/contracts-dispute/src/BondManager.sol, packages/contracts-dispute/src/interfaces/IBondManager.sol, packages/contracts-dispute/src/lib/LibSafeCall.sol, packages/contracts-dispute/test/BondManager.t.sol
Implements the naive bond manager ahead of the spec as a proof of concept.
> **Note**
>
> This does not need a pr review from anyone besides @clabby since it upstreams directly into `pops/dispute-game-contracts`
=> feat(contracts-dispute): Naive Bond Manager [PoPs]

packages/contracts-bedrock/.env.example, packages/contracts-bedrock/hardhat.config.ts, packages/contracts-bedrock/src/deploy-utils.ts
Some changes which make it easier to run through the deployment process locally, and disable the live signer mode.
=> Improvements to enable deployment practice

packages/contracts-bedrock/contracts/deployment/SystemDictator.sol, packages/contracts-bedrock/deploy/021-SystemDictatorSteps-2.ts, packages/contracts-bedrock/src/deploy-utils.ts
Combines steps 3 through 5 into `phase2()`.
A subsequent PR will also include `updateDynamicConfig()` in `phase2`.
Fixes CLI-3790
=> Add phase2 function to MSD

packages/contracts-bedrock/deploy-config/mainnet.ts
Deduplicates repeated strings.
=> feat(ctb): Use named vars for reused config addresses

op-node/chaincfg/chains.go
=> feat: Update op-node mainnet chain config

specs/dispute-game-interface.md
Fixes the outdated `IAttestationDisputeGame` specification.
=> fix(spec): Update `IAttestationDisputeGame` spec

packages/contracts-bedrock/hardhat.config.ts, packages/contracts-bedrock/tasks/check-l2.ts
Small fixes that make the script work in practice
=> contracts-bedrock: fixes to check-l2 script

op-chain-ops/cmd/withdrawals/main.go
Adds the ability to wait for the finalization period in the withdrawal script. Previously there was an assumption that the finalization period was very short so there were never any issues not waiting for it.
=> op-chain-ops: wait for finalization period in withdraw script

packages/contracts-bedrock/tasks/check-l2.ts
Adds a few inline doc comments and corrects the loop bound in `check-l2.ts` for the mainnet migration.
=> chore(ctb): :broom: & document check-l2.ts task

packages/contracts-bedrock/deploy-config/mainnet.json, packages/contracts-bedrock/deploy-config/mainnet.ts
=> contracts-bedrock: fixup deployconf

op-node/chaincfg/chains.go
=> feat: mainnet update chains

proxyd/consensus_poller.go
Avoid spamming info and warn log levels.
**Tests**
Manual.
**Invariants**
n/a
**Metadata**
- Fixes INF-198
**TODOs**
=> proxyd/nit: adjust log level

op-challenger/challenger/challenger.go, op-challenger/challenger/utils.go, op-challenger/cmd/main.go
Adds main logic required to run an op-challenger binary stub.
**Metadata**
Fixes CLI-3944
=> feat(pops): Main Challenger Binary Logic

packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol, packages/contracts-bedrock/contracts/L1/SystemConfig.sol, packages/contracts-bedrock/contracts/test/CommonTest.t.sol, packages/contracts-bedrock/contracts/test/L2OutputOracle.t.sol, packages/contracts-bedrock/deploy/013-BondManager.ts, packages/contracts-bedrock/deploy/021-SystemDictatorInit.ts, packages/contracts-dispute/.solhint.json, packages/contracts-dispute/.solhintignore, packages/contracts-dispute/package.json, packages/contracts-dispute/src/AttestationDisputeGame.sol, packages/contracts-dispute/src/BondManager.sol, packages/contracts-dispute/src/DisputeGameFactory.sol, packages/contracts-dispute/src/FaultDisputeGame.sol, packages/contracts-dispute/src/interfaces/IAttestationDisputeGame.sol, packages/contracts-dispute/src/interfaces/IBondManager.sol, packages/contracts-dispute/src/interfaces/IDisputeGameFactory.sol, packages/contracts-dispute/src/lib/LibHashing.sol, packages/contracts-dispute/src/lib/LibPosition.sol, packages/contracts-dispute/src/lib/LibSafeCall.sol, packages/contracts-dispute/test/AttestationDisputeGame.t.sol, packages/contracts-dispute/test/BondManager.t.sol, packages/contracts-dispute/test/CommonTest.t.sol, packages/contracts-dispute/test/DisputeGameFactory.t.sol, packages/contracts-dispute/test/L2OutputOracle.t.sol, packages/contracts-dispute/test/lib/LibPosition.t.sol
> **Note**
> WIP - Only needs to be reviewed by @tynes or @refcell, going into `pops/dispute-game-contracts`
=> feat(pops): Enhance test suite / :broom:

op-node/chaincfg/chains.go
Updates `Mainnet` chain config.
=> feat: Update mainnet chain config.

op-node/chaincfg/chains.go
Updates the mainnet chain config.
**Checklist**
=> feat(chains.go): Step 26 of the Migration Rehearsal

op-chain-ops/cmd/withdrawals/main.go
=> withdrawals: make parallel

op-node/chaincfg/chains.go
Updates `chains.go` mainnet chain config using the rollup artifact.
**Checklist**
=> feat(op-node): mainnet chain config

op-challenger/flags/flags_test.go, op-program/host/flags/flags_test.go
Use a built in function rather than manually slicing strings.
=> Use strings package to check for a prefix

op-chain-ops/cmd/op-migrate/main.go, op-chain-ops/crossdomain/legacy_withdrawal.go
Add comments to ensure that a known bug is commented. See https://github.com/ethereum-optimism/optimism/pull/5682 for a longer description.
Adds a minimal check to make sure this bug is never encountered in practice.
=> op-chain-ops: better comments

docs/op-stack/src/docs/understand/explainer.md
=> docs: update

packages/contracts-bedrock/contracts/dispute/BondManager.sol
Ensure that a constant amount of gas is passed to each account when splitting up the seized bond. We can assume that the recipients will be able to receive ether with 30,000 gas. It is the end user's fault if they do funny business in a fallback function and cannot receive the ether. We also cannot revert if the transfer fails because a malicious entity could prevent all other entities from receiving their funds. Previously, the amount of gas sent to each recipient was different and also based on the amount of gasleft in the execution. The problem with using gasleft here is that gas estimation will result in enough gas being used for the most gas guzzling call to be used for each of the calls.
=> contracts-bedrock: seize and split gas management

packages/contracts-bedrock/deploy-config/mainnet.json
=> deploy-config: update

op-node/chaincfg/chains.go
op-node mainnet `chains.go` values
=> feat(op-node): Chains go mainnet

.circleci/config.yml, .github/workflows/tag-service.yml, ops/scripts/ci-docker-tag-op-stack-release.sh
* adds cci -> GCR docker build jobs for fault detector
* updates Tag Service action and docker release script to support fault-detector
=> INF-247 adds fault detector cci docker build and tag support

.circleci/config.yml
=> adds fault-detector to hold job

indexer/.gitignore, indexer/README.md, indexer/docker-compose.yml, indexer/example.env
- adds a docker-compose file for running indexer with docker-compose up
- adds example.env file
=> feat: Add docker-compose to indexer

packages/contracts-bedrock/deploy-config/mainnet.json
=> contracts-bedrock: deploy config final

packages/contracts-bedrock/tasks/check-l2.ts
Makes the script run much faster in parts that are covered by the go post check during the migration.
Ported from `feat/mainnet` branch
=> contracts-bedrock: make check-l2 script faster

op-node/chaincfg/chains.go
=> op-node: update mainnet chain config

op-bindings/Makefile, op-bindings/bindings/disputegamefactory.go
Adds the `DisputeGameFactory` as a target in `op-bindings` makefile for downstream use in the op-challenger.
**Metadata**
Fixes CLI-3953
=> feat(op-bindings): Dispute Game Factory Bindings

op-challenger/challenger/challenger.go
Following #5827, this pr initializes the `DisputeGameFactory` contract and abi using `op-bindings`.
=> feat(op-challenger): DisputeGameFactory initialization.

indexer/cmd/indexer-refresh/README.md, indexer/cmd/indexer-refresh/main.go, indexer/indexer.go, indexer/integration_tests/bedrock_test.go, indexer/legacy/config.go, indexer/legacy/config_test.go, indexer/legacy/indexer.go
- Move old indexer to indexer/legacy
- add some boilerplate for a new entrypoint
=> chore(indexer): Add entrypoint for indexer

op-node/chaincfg/chains.go
=> chainconfig: comment in mainnet config

op-node/chaincfg/chains.go
Adds deploy config mainnet values as part of step 22.3
=> feat(op-node): Mainnet config

docs/op-stack/package.json, docs/op-stack/yarn.lock
- Add preview mode
- runs docs site in `production` mode
- allows folks to debug issues that happen in production
- also allows folks to preview the produciton build when working on app
=> feat(op-stack docs): Add preview mode

docs/op-stack/src/.vuepress/enhanceApp.js
Unfortunately, this error doesn't happen in development, so the only way I have to test a fix is push it to production.
=> fix(docs/op-stack): Try to fix the reload code

packages/contracts-bedrock/scripts/eoa-migration.sh
Adds the `eoa-migration.sh` script. Will be deleted after the June 6 migration.
=> Add `eoa-migration.sh`

packages/sdk/src/utils/chain-constants.ts
This reverts commit b5079b5c6b381065f5921f399e49719060e4824d.
=> Revert "TEMP: delete this commit"

op-node/chaincfg/chains.go
Adds the mainnet rollup configuration to the `op-node`.
=> feat(op-node): Mainnet rollup configuration

indexer/docker-compose.yml, indexer/ui/Dockerfile, indexer/ui/README.md, indexer/ui/prisma.sh, indexer/ui/schema.prisma
- script to update prisma config
- --check flag into script will validate prisma config
=> feat(indexer): Add script to update prisma ui

op-node/chaincfg/chains.go
Adds the mainnet rollup config to the op-node chain config.
=> feat(op-node): Mainnet rollup config

op-chain-ops/ether/migrate.go
=> op-chain-ops: Fix logging in ether migration

op-node/chaincfg/chains.go
Finalize the mainnet rollup config in the `op-node` chain config.
**Checklist**
=> feat(op-node): Finalize Mainnet Rollup Config

indexer/cmd/indexer-refresh/main.go, indexer/config/config.go, indexer/config/config_test.go, indexer/go.mod, indexer/go.sum, indexer/indexer.toml
- adds toml file for configuring indexer
=> feat: Add indexer.toml file

indexer/cli/cli.go, indexer/cmd/indexer-refresh/main.go, indexer/example.env
- Add a new cli app
- indexer api runs api
- indexer indexer runs indexer
- open to a better name
- Both load config toml file
- hook up to actual services in followup prs
=> feat(indexer): Add cli app

op-node/sources/receipts.go, op-node/sources/receipts_test.go
Erigon supports `eth_` but does not accept block-hashes as arguments. Instead, we need to use an alternative receipt fetching RPC method that does.
Fix https://github.com/ethereum-optimism/optimism/issues/5924
**Tests**
Updated tests to cover the new method, but can't run an erigon node as part of CI.
**Metadata**
Fix CLI-4076
**TODOs**
=> op-node: support erigon_getBlockReceiptsByBlockHash

go.mod, go.sum
Pull in latest op-geth changes to ensure they're being used in e2e tests.
=> op-geth: Pull in latest op-geth changes (v1.101106.0-rc.2)

ops/docker/Dockerfile.packages
Cleans up the typescript dockerfile. This should eventually be refactored more but works for now.
=> cleanup: typescript dockerfile

indexer/.gitignore
=> chore(indexer): Update git ignroe to ignore binaries

.changeset/fair-poems-give.md, packages/fault-detector/src/service.ts, packages/sdk/src/cross-chain-messenger.ts, packages/sdk/test/cross-chain-messenger.spec.ts
- Make bedrock default
- We didn't want to make this breaking change prebedrock
- Don't delete any code yet do that in a future pr
=> feat(sdk): Make bedrock the default

.changeset/fair-poems-give.md
- remove message relayer from a changeset
=> fix(monorepo): Delete message relayer changeset

.changeset/chilly-carrots-impress.md, .changeset/fair-poems-give.md, .changeset/few-shoes-deny.md, .changeset/moody-foxes-enjoy.md, .changeset/rotten-cheetahs-guess.md, .changeset/smooth-bulldogs-hear.md, .changeset/tasty-seahorses-add.md, packages/chain-mon/CHANGELOG.md, packages/chain-mon/package.json, packages/common-ts/CHANGELOG.md, packages/common-ts/package.json, packages/contracts-bedrock/CHANGELOG.md, packages/contracts-bedrock/contracts/test/invariants/OptimismPortal.t.sol, packages/contracts-bedrock/invariant-docs/OptimismPortal.md, packages/contracts-bedrock/package.json, packages/contracts-periphery/package.json, packages/core-utils/CHANGELOG.md, packages/core-utils/package.json, packages/fault-detector/CHANGELOG.md, packages/fault-detector/package.json, packages/replica-healthcheck/CHANGELOG.md, packages/replica-healthcheck/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
=> Developer -> Master

op-challenger/fault/main.go
This adds some very basic data structures around the fault proof game.
Also implements a basic position type.
=> op-challenger: Fault Proof Game Interfaces

packages/contracts-bedrock/contracts/dispute/DisputeGameFactory.sol, packages/contracts-bedrock/contracts/dispute/FaultDisputeGame.sol, packages/contracts-bedrock/contracts/dispute/interfaces/IBondManager.sol, packages/contracts-bedrock/contracts/dispute/interfaces/IDisputeGame.sol, packages/contracts-bedrock/contracts/dispute/interfaces/IDisputeGameFactory.sol, packages/contracts-bedrock/contracts/dispute/interfaces/IFaultDisputeGame.sol, packages/contracts-bedrock/contracts/dispute/interfaces/IInitializable.sol, packages/contracts-bedrock/contracts/dispute/interfaces/IVersioned.sol, packages/contracts-bedrock/contracts/dispute/lib/LibClock.sol, packages/contracts-bedrock/contracts/dispute/lib/LibHashing.sol, packages/contracts-bedrock/contracts/dispute/lib/LibPosition.sol, packages/contracts-bedrock/contracts/libraries/DisputeErrors.sol, packages/contracts-bedrock/contracts/libraries/DisputeTypes.sol, packages/contracts-bedrock/contracts/test/DisputeGameFactory.t.sol, packages/contracts-bedrock/contracts/test/FaultDisputeGame.t.sol, packages/contracts-bedrock/contracts/test/LibClock.t.sol, packages/contracts-bedrock/contracts/test/LibPosition.t.sol
Updates the doc comment style of all `dispute` related contracts to adhere to the style guide.
=> chore(ctb): Update `dispute` contracts' comment style

cannon/docs/README.md, cannon/mipsevm/evm_test.go, cannon/mipsevm/memory.go, cannon/mipsevm/mips.go
=> cannon: Remove unicorn references

op-challenger/fault/types.go
This adds the responder interface
=> op-challenger: Add Responder interface

op-challenger/fault/alphabet_provider_test.go, op-challenger/fault/cmd/examples/position.go, op-challenger/fault/cmd/examples/solver.go, op-challenger/fault/cmd/main.go, op-challenger/fault/solver.go, op-challenger/fault/solver_test.go
- Refactors fault examples into `cmd/examples/`
- Added a new `Solver` example in `cmd/examples/`
- New game `Solver` instance
- Bunch of new alphabet and solver tests
**Metadata**
Fixes CLI-4122
=> feat(op-challenger): AlphabetProvider + Naive Solver

op-challenger/fault/game.go
Creates a `Game` state interface that will be used by an `op-challenger` `Agent` to interact with the game state.
=> feat(op-challenger): Game State Interface

packages/fault-detector/src/helpers.ts, packages/fault-detector/src/service.ts, packages/fault-detector/test/helpers.spec.ts
Lints the `fault-detector`.
Not sure how this made it through CI.
=> fix: Linter for fault detector

package.json
- add node.js version to engines
- delete unused yarn config
=> feat: Clean up package.json post pnpm

.github/workflows/publish-canary.yml
- noticed a typo in publish-canary workflow
=> fix: typo in publish-canary workflow

op-challenger/fault/game.go
This updates how the game state is stored. It is still a tree like structure from parent to children, but stores each list of children (+ additional information) inside the primary map.
**Tests**
No extra unit tests. Current unit tests pass.
=> op-challenger: Update game state internal

indexer/config/config_test.go, indexer/indexer.toml
- forgot to include name in the toml config
=> fix(indexer): Add name to toml config
