- .changeset/moody-beds-guess.md
- .github/workflows/publish-canary.yml
- .github/workflows/release.yml
- ops/docker/Dockerfile.packages
- packages/contracts-bedrock/package.json
Published as `ethereumoptimism/deployer-bedrock`.
This will be published along with new releases of the `npm` package.
It wraps `hardhat deploy`. The config file will want to be mounted
in at runtime if deploying to a non default network.
> contracts-bedrock: add deployer docker image

- op-node/l2/util.go
- op-node/rollup/derive/batch.go
- op-node/rollup/derive/batch_queue.go
- op-node/rollup/derive/batch_test.go
- op-node/rollup/derive/batches.go
- op-node/rollup/derive/batches_test.go
- op-node/rollup/derive/channel_out.go
This commits a batch to a specific L1 origin block by hash rather
than just by number. This help in the case of L1 reorgs by stopping
batches from being applied in weird ways.
This does not add a block number to the batch. The plan for eager batch derivation
is to continue to use timestamps, but slightly modify derivation rules (similar to how
they would be modified even if it was switched over to using block numbers).
**Metadata**
> op-node: Add Epoch Hash to batch

- .changeset/stupid-ties-reply.md
- l2geth/eth/api_tracer.go
The `debug_standardTraceBlockToFile` RPC was panicing here:
```go
// Line 572 in eth/api_tracer.go
if config != nil && config.Overrides != nil {
```
`config` is an instance of `StdTraceConfig`, which embeds a pointer to `vm.LogConfig`. This pointer is `nil` when the user doesn't pass in any overrides. Since `vm.LogConfig` exposes the `Overrides` parameter, this caused a panic.
`debug_standardTraceBlockToFile` is required for users like Dune, who need access to transaction traces that are too complex to serve over RPC.
> l2geth: Fix NPE in API tracer

- packages/contracts-bedrock/foundry.toml
Explicitly set `build_info` to true in the `foundry.toml`. Ideally this should take in the config from the `hardhat.config.js` but for some reason isnt right now
> contracts-bedrock: buildinfo set to true

- op-node/eth/l1info.go
- op-node/eth/status.go
- op-node/eth/types.go
- op-node/l1/source.go
- op-node/l1/types.go
- op-node/l2/source.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/step.go
- op-node/testutils/fake_chain.go
- op-node/testutils/mock_engine.go
- op-node/testutils/mock_l1.go
- op-node/testutils/random.go
This PR modifies moves types into the `eth` package from the `derive` package,
updates some handling of the execution engine API error results, and adds some
testutils.
These changes are pulled from the full batch derivation PR.
> op-node: Refactor types and L1/L2 Source

- ops-bedrock/devnet-up.sh
- ops-bedrock/test-integration.sh
- packages/contracts-bedrock/.gitignore
Increases the timeout on waiting for a URL to respond in `devnet-up`. 
Also a couple minor changes related to running `devnet-up`.
> ops-bedrock: Increase timeout on wait_up

- .changeset/strange-pets-draw.md
- integration-tests/test/nft-bridge.spec.ts
- packages/contracts-periphery/contracts/universal/op-erc721/IOptimismMintableERC721.sol
- packages/contracts-periphery/contracts/universal/op-erc721/OptimismMintableERC721.sol
- packages/contracts-periphery/contracts/universal/op-erc721/OptimismMintableERC721Factory.sol
- packages/contracts-periphery/deploy/nft-bridge/OptimismMintableERC721FactoryImplementation.ts
- packages/contracts-periphery/test/contracts/L2/messaging/L2ERC721Bridge.spec.ts
- packages/contracts-periphery/test/contracts/universal/OptimismMintableERC721.spec.ts
- packages/contracts-periphery/test/contracts/universal/OptimismMintableERC721Factory.spec.ts
Fixes two minor bugs in the Optimism Mintable ERC721 implementation.
Includes a new required input (remoteChainId) and fixes two issues with
the generated baseURI.
Will require an upgrade.
> fix(ctp): bugs in Mintable ERC721

- packages/contracts-bedrock/tasks/genesis-l2.ts
We were creating 65k predeploys, which made a huge genesis file. This PR reduces that to 2048.
> genesis: Reduce number of predeploys

- Makefile
Adds a handy dandy command (`make devnet-logs`) for accessing the logs of a running devnet instance.
> make: add devnet-logs

- .circleci/config.yml
The previous version of the pattern would match any change in a directory containing the word `contracts`.
> ci: Only run legacy itests when legacy contracts change

- packages/common-ts/package.json
CI breaks since it runs coverage against all
packages and there is no coverage command for
`common-ts`. This adds a simple no-op so that
coverage can be ran for all tests
> fix(common-ts): fix coverage command

- op-batcher/batch_submitter.go
- op-batcher/config.go
- op-batcher/flags/flags.go
- op-batcher/sequencer/driver.go
- op-e2e/setup.go
- op-node/node/api.go
- op-node/node/node.go
- op-node/node/server.go
- op-node/node/server_test.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/state.go
- op-node/testutils/random.go
- op-proposer/rollupclient/rollupclient.go
- ops-bedrock/docker-compose.yml
Previously the batcher would continue batch submitting from the L2 head.
However, if the sequencer runs  while the batch submitter is offline, the L2 chain continues, and the batch-submitter will be skipping a part. This causes a reorg, after which the batch submitter can't recover without restart (since it didn't detect reorgs).
This PR fixes the above, to make restarting of sequencer and batcher work without so much disruption of the L2 chain.
> Bedrock: fix new batcher, use sync status api, start from safe head

- packages/contracts-bedrock/deploy-config/devnetL1.ts
Update it from 10 to 1000. It seems to reduce the
reorg issues but not completely. The bug should be
fixed, this is just a temporary bandaid to allow the
system to run in a more stable fashion.
Co-authored-by: Joshua Gutow <jgutow@optimism.io>
> contracts-bedrock: update max sequencer drift config

- packages/contracts-periphery/contracts/L1/messaging/L1ERC721Bridge.sol
- packages/contracts-periphery/contracts/L2/messaging/L2ERC721Bridge.sol
- packages/contracts-periphery/contracts/universal/op-erc721/IOptimismMintableERC721.sol
- packages/contracts-periphery/contracts/universal/op-erc721/OptimismMintableERC721.sol
- packages/contracts-periphery/test/contracts/L2/messaging/L2ERC721Bridge.spec.ts
Replaces ERC721 with ERC721Enumerable for the standard version of the
OptimismMintableERC721 token. Enumerable is generally less useful on L1
because it consumes more gas but it makes indexing significantly easier
and gas is cheap on L2. Also removes reinitializer functions because we
don't want to be initializing contracts every time we re-deploy.
> feat(ctb): use ERC721Enumerable for standard token

- .changeset/many-walls-shave.md
- packages/contracts-bedrock/.gas-snapshot
- packages/contracts-bedrock/contracts/libraries/Lib_CrossDomainHashing.sol
- packages/contracts-bedrock/contracts/test/CrossDomainHashing.t.sol
- packages/contracts-bedrock/src/utils.ts
- packages/contracts-bedrock/tasks/deposits.ts
- packages/contracts-bedrock/test/helpers.spec.ts
There is a solidity contract for computing the L2 tx hash
so that its easy for devs to compute it with an `eth_call`.
This makes it easy for users that do not have a custom library
written in their language to compute the L2 tx hash.
Also fix the typescript implementation of the deposit tx type
so that the correct tx hash is computed.
> contracts-bedrock: fix deposit helpers

- packages/contracts-bedrock/package.json
- packages/contracts-bedrock/scripts/slither.sh
Fixes slither to work in CI, this is a temp fix until we can configure the outdir for `build-info` using foundry, see https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/3883/workflows/d23c46f9-501a-4853-9305-d12ff1a12d0b/jobs/52916/steps
> contracts-bedrock: fix slither

- op-node/rollup/derive/batch_queue.go
Fixes a likely bug in #2882. The max L2 time should only be increased based on the min L2 time to ensure there's at least 1 block in the epoch. If the safe head already has this epoch, then the minimum is reached, and we should not touch the max L2 time then.
> [bedrock] Eager batch derivation - min l2 time fix

- .github/labeler.yml
Has PR labeler correctly label PRs to the contracts-bedrock package.
> fix(ci): add bedrock contracts to PR labeler

- .changeset/yellow-readers-vanish.md
- packages/contracts-bedrock/hardhat.config.ts
- packages/contracts-bedrock/package.json
- yarn.lock
Update to the latest version of typechain and no longer
use the hh plugin. Directly call typechain as the hardhat
plugin is unreliable when using foundry.
> contracts-bedrock: fix typechain

- .changeset/big-scissors-remain.md
- .github/workflows/release.yml
- ops/docker/foundry/Dockerfile
- ops/docker/foundry/package.json
- package.json
Based on the following commit:
https://github.com/foundry-rs/foundry/commit/b7b1ec471bdd38221773e1a569dc4f20297bd7db
Allows us to control the version of foundry being used in our toolchain. This dockerfile is exactly the same as upstream's but pins to a specific commit hash.
> docker: add ethereumoptimism/foundry docker image

- packages/contracts-bedrock/hardhat.config.ts
- packages/contracts-bedrock/package.json
- yarn.lock
This commit greatly speeds up the compilation
time for `hardhat compile` by updating to the
latest version of the plugin.
This is known to work with the following forge version:
```
forge 0.2.0 (4ad4bb6 2022-07-06T17:55:43.107018225Z)
```
To use this version:
```
$ foundryup -C 4ad4bb660ad0b429e76e980fd6c1d50aee7c112b
```
> contracts-bedrock: speed up compilation time

- .changeset/fresh-pugs-remain.md
- packages/contracts-bedrock/contracts/test/ProxyAdmin.t.sol
- packages/contracts-bedrock/contracts/universal/ProxyAdmin.sol
Addresses solc warnings in ProxyAdmin.sol. Also changes the input type
from Proxy to address payable because it is *not* guaranteed that the
input will actually be of Proxy type.
> fix(ctb): solc warnings in ProxyAdmin.sol

- op-node/rollup/driver/state.go
- packages/contracts-bedrock/deploy-config/devnetL1.ts
The `unsafeHead` or `l2Head` is state managed between two separate
processes: the driver state loop and the derivation pipeline. It
is updated during a reorg, during block creation, or during p2p
payload insertion. What happened is that during block creation
the state loop would inform the derivation pipeline of the new
unsafe L2 head; however it was using an old value. This would
cause the communication back from the pipeline to use an old
unsafe head during the setting inside the state loop. Then
the state loop would create a new L2 block with the same L2 parent
thus causing an inadvertent chain reorganization.
This commit also reverts the very significant increase in sequencer
drift to a more reasonable value.
Tested locally with the devnet. Up to …
> Op Node: Fix one reorg bug

- ops-bedrock/devnet-up.sh
The value is pulled in from the rollup.json config; however it
was still using the old config that was checked in (& deleted
a while ago) instead of using the generated config.
Tested locally.
> ops: Use correct sequencer inbox value for the batch

- op-node/rollup/derive/batch_queue.go
- op-node/rollup/derive/channel_bank.go
The derivation pipeline was being reset past genesis to buffer data. The previous behavior shouldn't be breaking anything, but also inefficient / unnecessary.
> op-node: clip derivation reset to not go past L1 genesis

- op-node/rollup/derive/attributes_queue.go
- op-node/rollup/derive/engine_queue.go
Debugging the testnet with Josh/BenW. This catches a misconfiguration issue in the verifier, just in case it happens again.
> op-node: testnet fixes - sanity check L2 block after block derivation reset

- op-batcher/Dockerfile
- op-batcher/docker.go.work
- op-node/Dockerfile
- op-node/docker.go.work
- op-proposer/Dockerfile
- op-proposer/docker.go.work
- ops-bedrock/docker-compose.yml
In preparation of the go module versioning work: move the dockerfiles to the dir of their module, and use a temporary `go.work` for the docker build so the modules build with the local monorepo contents.
We still have the `replace github.com/ethereum-optimism/optimism/op-something v0.0.0 => ../op-something` directives in the mod files, but the `use` directives in the new `docker.go.work` files make those unnecessary during the docker build now.
So we can remove them in the next PR that introduces versioning for them.
With a separate toy go workspace project I tested that:
- the go.work file thing in docker works: it's not building with the module version referenced in the `require` of the  `go.mod`, but rather with the local copy referenced by the `docker.go.work`.
- we don't need to copy …
> ops-bedrock: move docker files into their module dirs

- specs/meta/versioning.md
Accidentally broke develop CI with markdown formatting during versioning process. This PR fixes that. Just removing tabs and adding a missing language identifier in code-blocks.
> specs: fix markdown lint in meta spec doc

- .changeset/itchy-carpets-fail.md
- .github/workflows/release.yml
Fixes the broken publish step of `ci-builder`. This is required to update our tooling versions
See https://github.com/ethereum-optimism/optimism/runs/7310233030?check_suite_focus=true
> ci: fix publishing of ci-builder

- .changeset/slow-peaches-sit.md
- ops/docker/ci-builder/Dockerfile
Also deletes leftover copies of solc in the
root of the image. They are copied to the places
where they are expected.
Updates bash in the `ci-builder` image, this seems to fix problems with `vm.ffi` in https://github.com/ethereum-optimism/optimism/pull/2980. That PR works on my machine locally and I rebuilt this docker image locally and ran the tests in it and they all passed. In the existing `ci-builder`, the differential tests fail for some reason.
Will need to trigger a release of `ci-builder`
> ci: updates version of bash in ci-builder

- .changeset/chatty-moles-grow.md
- .changeset/itchy-carpets-fail.md
- .changeset/slow-peaches-sit.md
- .circleci/config.yml
- .github/workflows/release.yml
- ops/docker/ci-builder/Dockerfile
- packages/contracts-bedrock/README.md
- packages/sdk/src/utils/contracts.ts
> Develop -> Master PR

- .changeset/few-mails-cough.md
- packages/contracts-bedrock/contracts/libraries/trie/MerkleTrie.sol
- packages/contracts-bedrock/contracts/libraries/trie/SecureMerkleTrie.sol
Cleans up natspec in the MerkleTrie and SecureMerkleTrie contracts.
> style(ctb): clean MerkleTrie and SecureMerkleTrie

- op-e2e/setup.go
This was previously waiting for 2 blocks to deploy the portal contract.
Some new contract changes are now hitting a timeout so this increases
the timeout to 6 L1 blocks.
> op-e2e: Wait longer for Optimism Portal Deploy

- op-e2e/setup.go
- op-e2e/system_test.go
This PR:
- deploys output oracle with correct config
- de-duplicates block time and genesis setup info.
Previously the contract was being deployed with a block time of 2 instead of 1, and thus failing to confirm the latest outputs, and increasingly lagging behind the L2 chain.
> op-e2e: deploy output oracle with correct config (bedrock)

- op-proposer/drivers/l2output/driver.go
**Description:**
Currently the proposer does not use a safe head for creating output proposal which causes a failure in proposing with: `L2OutputOracle: cannot propose L2 output in the future`, as the output oracle does not know the unsafe head.
To fix this, we limit the block range the output proposer works with to the safe head instead.
Edit: does not include a test atm.
Fixes: ENG-2348
> fix (op-proposer): use safe head in block range

- packages/contracts-bedrock/contracts/L1/L1CrossDomainMessenger.sol
- packages/contracts-bedrock/contracts/L1/L1StandardBridge.sol
- packages/contracts-bedrock/contracts/L1/L2OutputOracle.sol
- packages/contracts-bedrock/contracts/L1/OptimismPortal.sol
- packages/contracts-bedrock/contracts/L1/ResourceMetering.sol
- packages/contracts-bedrock/contracts/L2/GasPriceOracle.sol
- packages/contracts-bedrock/contracts/L2/L2CrossDomainMessenger.sol
- packages/contracts-bedrock/contracts/L2/L2StandardBridge.sol
- packages/contracts-bedrock/contracts/L2/L2ToL1MessagePasser.sol
- packages/contracts-bedrock/contracts/legacy/AddressManager.sol
- packages/contracts-bedrock/contracts/legacy/DeployerWhitelist.sol
- packages/contracts-bedrock/contracts/legacy/L1ChugSplashProxy.sol
- packages/contracts-bedrock/contracts/libraries/Burn.sol
- packages/contracts-bedrock/contracts/libraries/rlp/RLPReader.sol
- packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol
- packages/contracts-bedrock/contracts/universal/OptimismMintableERC20.sol
- packages/contracts-bedrock/contracts/universal/OptimismMintableERC20Factory.sol
- packages/contracts-bedrock/contracts/universal/Proxy.sol
- packages/contracts-bedrock/contracts/universal/ProxyAdmin.sol
- packages/contracts-bedrock/contracts/universal/StandardBridge.sol
Fixed the ordering warnings across all contracts
**Metadata**
- Partially #2883
> contracts-bedrock: fix solhint ordering warnings

- .changeset/fresh-peaches-remain.md
- packages/contracts-periphery/contracts/L1/L1ERC721Bridge.sol
- packages/contracts-periphery/contracts/L1/TeleportrDeposit.sol
- packages/contracts-periphery/contracts/L1/TeleportrWithdrawer.sol
- packages/contracts-periphery/contracts/L2/L2ERC721Bridge.sol
- packages/contracts-periphery/contracts/L2/TeleportrDisburser.sol
- packages/contracts-periphery/contracts/foundry-tests/AssetReceiver.t.sol
- packages/contracts-periphery/contracts/foundry-tests/TeleportrWithdrawer.t.sol
- packages/contracts-periphery/contracts/foundry-tests/Transactor.t.sol
- packages/contracts-periphery/contracts/testing/helpers/CallRecorder.sol
- packages/contracts-periphery/contracts/testing/helpers/ExternalContractCompiler.sol
- packages/contracts-periphery/contracts/testing/helpers/FailingReceiver.sol
- packages/contracts-periphery/contracts/testing/helpers/MockTeleportr.sol
- packages/contracts-periphery/contracts/testing/helpers/Reverter.sol
- packages/contracts-periphery/contracts/testing/helpers/SimpleStorage.sol
- packages/contracts-periphery/contracts/testing/helpers/TestERC20.sol
- packages/contracts-periphery/contracts/testing/helpers/TestERC721.sol
- packages/contracts-periphery/contracts/universal/AssetReceiver.sol
- packages/contracts-periphery/contracts/universal/Transactor.sol
- packages/contracts-periphery/contracts/universal/drippie/Drippie.sol
- packages/contracts-periphery/contracts/universal/drippie/IDripCheck.sol
- packages/contracts-periphery/contracts/universal/drippie/dripchecks/CheckBalanceHigh.sol
- packages/contracts-periphery/contracts/universal/drippie/dripchecks/CheckBalanceLow.sol
- packages/contracts-periphery/contracts/universal/drippie/dripchecks/CheckGelatoLow.sol
- packages/contracts-periphery/contracts/universal/drippie/dripchecks/CheckTrue.sol
- packages/contracts-periphery/contracts/universal/op-erc721/IOptimismMintableERC721.sol
- packages/contracts-periphery/contracts/universal/op-erc721/OptimismMintableERC721.sol
- packages/contracts-periphery/contracts/universal/op-erc721/OptimismMintableERC721Factory.sol
Bumps the version in the periphery package to match that in the bedrock package. 
Complies with the recent change to the [hardhat config compiler](https://github.com/ethereum-optimism/optimism/commit/1489da48f38df84187a9e3cdd7983cfca3bc172f).
Note: the following Libraries/interfaces have version `^0.8.0`: 
/universal/AssetReceiver.sol
/universal/Transactor.sol
/universal/drippie/IDripCheck.sol
/universal/op-erc721/IOptimismMintableERC721.sol
/universal/op-erc721/OptimismMintableERC721.sol
> chore(ctp): Bump solidity version to 0.8.15

- packages/contracts/docs/AddressUpgradeable.md
- packages/contracts/docs/ContextUpgradeable.md
- packages/contracts/docs/Initializable.md
- packages/contracts/docs/L1CrossDomainMessenger.md
- packages/contracts/docs/OwnableUpgradeable.md
- packages/contracts/docs/PausableUpgradeable.md
- packages/contracts/docs/ReentrancyGuardUpgradeable.md
Due to a new version of the openzeppelin contracts,
the docs need to be regenerated. Each time that the
contracts are built, these files are generated.
Merging this commit will make dev on alternative things
less noisy.
> contracts: update docs

- .changeset/dry-bears-beg.md
- packages/contracts-bedrock/contracts/universal/StandardBridge.sol
Use only 1 initializable instead of two different initializable
imports. Using contracts with the same name will break hardhat.
The two different initializable imports were:
```solidity
import { Initializable } from "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
```
```solidity
import { Initializable } from "@openzeppelin/contracts/proxy/utils/Initializable.sol";
```
This standardizes on not using `contracts-upgradeable`.
> contracts-bedrock: standard initializable

- .changeset/quiet-books-design.md
- proxyd/config.go
- proxyd/proxyd.go
- proxyd/server.go
Adds two new config params:
- `enable_request_log`, which enables/disables the full RPC request log
- `max_request_body_log_len`, which configures the maximum number of characters that will be logged for each RPC request. Values over 2000 are ignored.
This should reduce our GCP spend.
> proxyd: Parameterize full RPC request logging

- op-bindings/Makefile
- op-bindings/gen_bindings.sh
Speeds up the `op-bindings` build as foundry doesn't need to recompile the entire set of contracts if you give it the fully qualified name instead of just the name. I noticed significant speed ups with this.
Building in parallel seems to fail due to contention on downloading the compiler: https://github.com/ethereum-optimism/optimism/pull/3040
> op-bindings: speed up build

- .circleci/config.yml
The `js-builder` and `go-builder` are no longer
used, they were replaced by `ci-builder`. Their
dockerfiles have already been deleted from the
repo, this now deletes their reference in the CI
docker build pipeline.
> ci: remove publishing of deprecated images

- .changeset/early-keys-know.md
- packages/contracts-bedrock/package.json
- yarn.lock
Updates the hh forge plugin to the following:
```
"@foundry-rs/hardhat-forge": "^0.1.16"
```
Includes bugfixes for when multiple imports
of contracts with the same name happens.
> contracts-bedrock: update hardhat-forge plugin

- ops-bedrock/devnet-up.sh
- packages/contracts-bedrock/deploy-config/devnetL1.ts
This was being incorrectly set in the rollup json relative to the
HD path supplied to the batcher was. This resulted in L2 reorgs
on the sequencer & the inability to send L2 transactions.
> ops: Properly set devnet batch submitter address

- .changeset/wet-suns-develop.md
- packages/contracts-bedrock/package.json
The `package.json` defines the files that are included
in the `npm` package, the previous glob did not match
all of the typechain artifacts.
> contracts-bedrock: fix typechain export

- .changeset/wet-doors-collect.md
- integration-tests/test/queue-ingestion.spec.ts
Move away from using a nested api on the messenger
and instead use an imported function
> integration-tests: modularize

- Makefile
Adds a helper to the makefile for deleting all of the js
deps. This is useful for when checking out a new branch
and ensuring that the deps are up to date. I find
myself doing this often manually, so adding a make command
makes sense.
> makefile: `clean-node-modules`

- .changeset/cool-items-smell.md
- .circleci/config.yml
- packages/contracts-bedrock/hardhat.config.ts
- packages/contracts-bedrock/tasks/check-l2-config.ts
- packages/contracts-bedrock/tasks/genesis-l2.ts
This updates the hardhat task `genesis-l2` to handle
setting the immutables in the deployed bytecode. This
is necessary because the predeploys "live" in the L2
state and are not deployed. Any immutables must be manually
placed into the bytecode by looking at the compiler output
and then finding the offsets and slicing in the values.
A high level API is exposed for setting arbitrary immutables
with the `replaceImmutables` function. This was inspired by
smock's `computeStorageSlots`.
Longer term, this code will be rewritten in go and be able to
operate on either a LevelDB database (upgrade an existing system)
or a `genesis.json` (good for starting a new network). This is
a requirement because the state surgery is large enough such that
it must bind directly to LevelDB and be …
> contracts-bedrock: in place handling of immutables

- cloudbuild.yaml
- packages/contracts-bedrock/deploy/000-L2OutputOracle.deploy.ts
`getDefaultProvider()` returns a fallback mainnet provider, which doesn't work.
Builds on https://github.com/ethereum-optimism/optimism/pull/3147.
> contracts-bedrock: Fix provider usage in L2OutputOracle deployment script

- .changeset/modern-candles-obey.md
- packages/contracts-bedrock/hardhat.config.ts
- packages/contracts-bedrock/tasks/watch.ts
A hardhat task that lists off important information.
Very helpful for debugging live networks.
Usage:
```
$ npx hardhat watch --network devnetL1
```
It will print off information as the chain makes progress.
> contracts-bedrock: add watch task

- .changeset/many-wasps-notice.md
- packages/contracts-bedrock/deploy/001-OptimismPortal.deploy.ts
It was being deployed with the implementation address
of the `L2OutputOracle` instead of the proxy. This
was preventing output commitments to actually be posted.
> contracts-bedrock: fix deployment

- op-node/cmd/main.go
- op-node/cmd/p2p/cmd.go
- op-node/cmd/p2p/cmd_test.go
- op-node/flags/flags.go
- ops-bedrock/docker-compose.yml
Adds utilities for handling P2P keys. Note that to prevent having to specify irrelevant CLI flags, I created a new `start` command that actually stats the node.
> op-node: Add p2p utils

- op-node/rollup/derive/attributes.go
- op-node/rollup/derive/attributes_queue.go
- op-node/rollup/derive/attributes_queue_test.go
- op-node/rollup/derive/attributes_test.go
- op-node/rollup/driver/step.go
This now uses a passed in timestamp for PreparePayloadAttributes.
This is important because when generating a payload attributes from
a batch it should be using the timestamp of the batch, not the
L2 parent + block time. When we are creating payloads based on the
L2 parent time, that is easy to set there instead of pulling it into
this function.
This enabled/exacerbated a divergence bug where the timestamp of the
batch was not the timestamp that was being set inside
PreparePayloadAttributes.
**Metadata**
- Fixes#ENG-2531
> op-node: Properly set timestamp in PreparePayloadAttributes

- op-node/metrics/metrics.go
- op-node/node/node.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/state.go
Adds support for the following batch derivation metrics:
- 0/1 gauge for if the derivation is idle
- Count of total pipeline resets
- Count of total unsafe payloads received
- Count of total derivation errors
- Gauge tracking the various L1/L2 safe/unsafe heads
> op-node: Derivation metrics

- op-node/metrics/metrics.go
- op-node/rollup/driver/state.go
This will allow us to measure opnode throughput.
> op-node: Add transactions sequenced metric

- packages/sdk/src/utils/contracts.ts
In previous pr we added wsteth as a standard bridge but it turns out it's a dai bridge actually
> fix: wsteth is a dai bridge not a standard bridge

- packages/contracts-bedrock/contracts/libraries/Encoding.sol
- packages/contracts-bedrock/contracts/libraries/Types.sol
- packages/contracts-bedrock/contracts/test/CommonTest.t.sol
- packages/contracts-bedrock/contracts/test/Encoding.t.sol
- packages/contracts-bedrock/contracts/test/Hashing.t.sol
- packages/contracts-bedrock/scripts/differential-testing.ts
- packages/core-utils/src/optimism/deposit-transaction.ts
> unmetered fixes + more tests

- .circleci/config.yml
`no_output_timeout` wasn't being honored because the deposit command produced output on each poll. Instead, use the `timeout` command to kill the process from within the job itself regardless of output.
> ci: Add devnet timeout

- op-node/rollup/derive/batch_queue.go
- op-node/rollup/derive/engine_queue.go
Logging to increase visibility to internal state of pipeline during resets & when dropping batches.
> op-node: More reset & pipeline logging

- op-node/rollup/derive/channel_bank.go
- op-node/rollup/derive/channel_bank_test.go
- op-node/rollup/derive/channel_frame.go
- op-node/rollup/derive/channel_out.go
- specs/derivation.md
This switches the channel frame header over to using fixed integers. This avoids a circular
dependency when filling the serialized frame up to a maximum size. The circular dependency
is caused by the frame data length being a `uvarint` which can vary in size when serialized.
**Metadata**
- Fixes ENG-2371
- Fixes ENG-2537
> op-node: Fixed Integers in channel frame header

- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/engine_update.go
This PR relies on https://github.com/ethereum-optimism/reference-optimistic-geth/pull/40 to return `INVALID` when the payload attributes cannot be processed.
When payload attributes cannot be processed due to a true payload-error (i.e. rpc errors, syncing state, etc. don't count) then we first re-attempt with only the deposits, and then return a critical error if we cannot even process a block with just the deposits.
I've chosen this approach, instead of looking for alternative batches, to keep the batch derivation simple (i.e. allow multiple batches to be queued up with the eager-batch-derivation logic, instead of having to check them 1 by 1 with the engine).
When the typed error handling lands we can handle the deposit processing error as critical, and stop the syncing entirely. Safety …
> op-node: fix invalid payload insertion error handling

- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/l1_traversal.go
- op-node/rollup/derive/progress.go
We missed these important reorg errors in #3130 which caused reorgs to be handled like temporary errors, and not result in a reset of the derivation pipeline, and thus never getting unstuck after a L1 reorg.
> op-node: reorgs should be typed to force pipeline resets [bedrock]

- op-node/metrics/metrics.go
- op-node/rollup/driver/state.go
Old payloads fail to publish, but should not hold back catch-up work of sequencer.
This separates the publishing errors, and sequencing errors, from regular derivation errors.
We meter/log them still, but they are not the same.
And p2p publishing errors are not critical enough to hold back sequencing.
> op-node: separate sequencing and publishing errors. 

- op-node/l1/source.go
- op-node/l1/source_test.go
- op-node/metrics/caching.go
- op-node/metrics/metrics.go
- op-node/node/node.go
- op-node/sources/caching/cache.go
This PR:
- Wraps a LRU cache with metrics
- Defines cache metrics as a group of metrics
- Updates the L1 source cache to use the cache with metrics
- Updates the L1 source cache with increased defaults: this should help respond much faster to L1 reorgs, replaying the old data from the cache instead of fetching everything again. On the testnet we see that a L1 reorg that is past the confirmation depth takes up to 3 minutes to resolve. This aims to fix that, and provide metrics so we can watch it.
Note: I moved the cache wrapper into `op-node/source/caching` package.  I'm thinking we can move `op-node/{l1,l2}` into `op-node/source/{l1,l2}`. And then later update `l2` with the same caching too (see ENG-2280)
Fix ENG-2555
> op-node: Bedrock l1 cache metrics

- .changeset/silent-comics-flash.md
- ops/docker/ci-builder/Dockerfile
geth to v1.10.21
go to 1.19
golangci-lint to 1.48.0
> ops: update ci-builder

- op-node/metrics/metrics.go
- op-node/rollup/driver/state.go
This adds metrics around the L1 reorg depth. Looking at logs, certain reorgs are deeper than expected,
so this helps track down what the actual distribution is.
> op-node: Add L1 reorg depth metrics

- state-surgery/immutables/immutables.go
- state-surgery/immutables/immutables_test.go
Add a package for dealing with immutables so that
the deployed bytecode can be set directly in state.
Each contract from the `op-bindings` package is imported
and deployed to a simulated backend. The `op-bindings`
package is enforced to be up to date by CI. Each of the
contracts was double checked that the arguments passed are
not immutables, the existing immutable values are hardcoded
into the contract itself. To handle the case where immutables
are dynamic, we will need to read in config and pass that
through. The methodology on how to do that is documented
in a TODO message.
The build step runs in CI meaning that changes to the
contract constructor interfaces will result in this
package failing to build.
This code could be slightly modularized to be used in
`op-e2e` for …
> state-surgery: add immutables package

- op-node/rollup/derive/attributes.go
- op-node/rollup/derive/batch_queue.go
- op-node/rollup/derive/batch_queue_test.go
- op-node/rollup/derive/channel_bank.go
- op-node/rollup/derive/channel_bank_test.go
- op-node/rollup/derive/channel_in_reader.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/error.go
- op-node/rollup/derive/l1_retrieval.go
- op-node/rollup/derive/l1_retrieval_test.go
- op-node/rollup/derive/l1_traversal.go
- op-node/rollup/derive/l1_traversal_test.go
- op-node/rollup/derive/progress.go
This PR aims to polish the error handling in the derivation pipeline more (after #3185 introduced initial error typing), and fixes minor issues in it.
Notable changes:
- `NewTemporaryError, NewResetError, NewCriticalError` now only wrap an error. We add the description to the error before we wrap it. Previously there were many places where the error ended up in the description, but then was also wrapped. This duplicated the error description when stringified. Now this can't happen anymore.
- Remove `ReorgErr` in favor of using just using `NewResetError`. They were indicating the same thing, but `ReorgErr` needed to be wrapped by `NewResetError` previously, complicating the error more than necessary.
- When we fail to convert receipts into deposits, or fail to convert L1 header info into a …
> op-node: improve derivation pipeline error handling

- op-node/rollup/derive/attributes_queue.go
- op-node/rollup/derive/batch_queue.go
- op-node/rollup/derive/calldata_source.go
- op-node/rollup/derive/channel_bank.go
- op-node/rollup/derive/channel_in_reader.go
- op-node/rollup/derive/l1_retrieval.go
This explains each stage in a bit better detail.
> op-node: Add comments to pipeline stages

- packages/actor-tests/bedrock/account-sends.ts
- packages/actor-tests/bedrock/deposit-eth.ts
- packages/actor-tests/bedrock/utils.ts
- packages/actor-tests/lib/faucet.ts
- packages/actor-tests/package.json
- packages/actor-tests/tsconfig.json
- yarn.lock
To improve the concurrency of the Bedrock actor tests, I hooked up an ETH faucet. Now, the actors can use the faucet to fund themselves before each run.
> ci: Use faucet in actor tests

- .changeset/lazy-singers-sing.md
- .circleci/config.yml
- packages/sdk/src/cross-chain-messenger.ts
- packages/sdk/src/interfaces/bridge-adapter.ts
- packages/sdk/tasks/deposit-eth.ts
Fixes the eth withdrawal bug when creating withdrawl
transactions that include value. There is no need to
send ETH on L1 when finalizing the withdrawal since
the `OptimismPortal` is holding onto the ETH that will
be unlocked and sent to the user.
co-authored-by: smartcontracts <kelvin@optimism.io>
> sdk: fix eth withdraw bug

- op-node/Makefile
The execution payload fuzzing happens in the `eth` package, not the `l2` package.
> op-node: fix execution payload fuzzing target [bedrock]

- state-surgery/hardhat/hardhat.go
Handle errors when walking the filesystem so that they do
not silently fail.
> state-surgery: handle fs errors

- state-surgery/state/memory_db_test.go
Sometimes `require.Equal` flakes on the comparison
of `big.Int`.
https://github.com/ethereum-optimism/optimism/blob/b31d35b67755479645dd150e7cc8c6710f0b4a56/op-node/rollup/derive/fuzz_parsers_test.go#L42
Co-authored-by: Joshua Gutow <jgutow@optimism.io>
> state-surgery: fix flakey tests

- state-surgery/state/encoding.go
- state-surgery/state/state_test.go
- state-surgery/state/testdata/contract.go
- state-surgery/state/testdata/layout.json
Adds the ability to set bytes32 values in state.
There is a single bytes32 value in our L2 predeploys.
Adds test coverage that the value is set properly and
encoded properly. Both `common.Hash` and hex strings
are supported to be able to be encoded into a bytes32
suitable for storage.
> state-surgery: implement bytes32 handling

- .changeset/pretty-clocks-repeat.md
- packages/contracts/src/contract-defs.ts
- packages/sdk/src/utils/chain-constants.ts
Updates the SDK to load contract addresses from the deployments folder.
Also updates the Contracts package to export addresses from the
deployments folder. More robust to address changes.
> feat(sdk): load addrs from deployments

- state-surgery/hardhat/hardhat.go
For some reason `strings.TrimPrefix` is removing
an extra character sometimes. We want to remove the
`.json` extension and using it will sometimes also
remove the final character in the contract name.
This is problematic because when you call
`hh.GetDeployment`, with the name of the contract,
it will not be able to find the deployment because
the name of the deployment will not match the name
passed in by the user. This instead slices off the
`.json` from the string manually.
> state-surgery: fix string slice

- .circleci/config.yml
Adds per-commit dev builds that get uploaded to our GCR repository. This enables running hive on a per-PR basis.
> ci: Dev builds

- op-node/metrics/events.go
- op-node/metrics/metrics.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/state.go
Improve sync metrics:
- Track L1 block that the derivation pipeline is reading
- Track L1 origin of the L2 unsafe, safe and finalized references
- Track the L2 unsafe payloads we receive, before processing them (useful for latency stat, as well as metering payloads we fail to apply)
- Track new properties for each l1/l2 ref:
- timestamp
- hash (mapping the first 8 bytes of the blockhash to a float64, experiment based on previous eth2 dashboards to find divergences visually and easily)
- sequence number (only for L2 block references)
- latency, a.k.a. the difference between the first time we see the block hash for a specific label, and the timestamp corresponding to that block.
- Track last occurrence time of sync errors, using a new util to de-duplicate some code there
- Hide the metrics …
> op-node: improve sync metrics [bedrock]

- .changeset/moody-yaks-listen.md
- op-chain-ops/genesis/config.go
- packages/contracts-bedrock/deploy-config/devnetL1.json
- packages/contracts-bedrock/deploy-config/goerli.json
- packages/contracts-bedrock/deploy-config/hardhat.json
- packages/contracts-bedrock/hardhat.config.ts
- packages/contracts-bedrock/tasks/genesis-l2.ts
Reduce the amount of config by removing the concept of proxy admin
address because we should be using the address of the deployed
proxy admin contract.
> fix: proxy admin deploy script

- op-node/eth/types.go
- op-node/l1/batching.go
- op-node/l1/batching_test.go
- op-node/l1/receipts.go
- op-node/l1/source.go
- op-node/l1/source_test.go
- op-node/node/node.go
- op-node/rollup/derive/attributes.go
- op-node/rollup/driver/driver.go
- op-node/testutils/mock_l1.go
Previously receipts were being fetched in parallel RPC batches, but there was a deadlock risk due to a race-condition between accepting batch results and scheduling new requests, causing the node to lock up.
This PR gets rid of the old parallel batch fetching, in favor of a new design that:
- Lets the caller parallelize by simply calling the Fetch method in multiple go routines, and avoiding that go routine complexity in the fetcher itself.
- Lets the caller stop/pause/backoff on any fetching error, using multi-error to expose the errors of the individual RPC calls.
- Propagates RPC errors to the caller nicely, instead of the previous logging and poor retry attempts
- Eventually completes and exposes the Results
The `l1.ReceiptsFetcher` wraps the `IterativeBatchCall` to fetch receipts …
> op-node: remove parallel batch fetching / deadlock, introduce iterative batch fetching

- ops-bedrock/Dockerfile.l1
Adds some nice new tracers and is more close to what
we would see on mainnet
> ops-bedrock: use the latest geth release for L1

- .circleci/config.yml
Helps with caching to use the same docker image
across jobs. This updates jobs on an older ubuntu
docker image to the latest ubuntu docker image
provided by circleci.
> ci: use common ubuntu image across jobs

- .circleci/config.yml
- op-chain-ops/genesis/config.go
- op-chain-ops/immutables/immutables.go
- op-chain-ops/immutables/immutables_test.go
- op-node/Dockerfile
- op-node/cmd/genesis/cmd.go
- op-node/cmd/main.go
- op-node/docker.go.work
- op-node/go.mod
- op-node/go.sum
- ops-bedrock/devnet-up.sh
- packages/contracts-bedrock/tasks/check-l2-config.ts
Adds the `genesis` subcommand to the `op-node` so that it can be used to create genesis files. To create a L2 developer genesis file that is suitable for devnets, use the following command:
```bash
$ op-node genesis devnet-l2
```
This name was chosen such that it is obvious that it is creating a genesis block for a devnet instead of trying to upgrade an existing database. The code to upgrade an existing database will be implemented in the future.
This PR also includes a fix to `op-chain-ops` because it was skipping the correct implementation of the `OptimismMintableERC20Factory`, which is required for ERC20 deposits to work.
The hardhat task responsible for checking that a L2 node's predeploys were configured properly was updated to catch this sort of error and then moved …
> feat: generate genesis with op-node

- .changeset/hot-cups-impress.md
- packages/contracts-bedrock/package.json
Fixes issues with npm by moving certain dependencies from "dependencies"
to "devDependencies" and therefore not including them in the bundle that
gets uploaded to npm. These dependencies did not include a package.json
file, which was causing certain versions of npm to complain loudly.
> fix(ctb): move deps to dev to fix npm

- op-node/README.md
Add documentation on how to use the `op-node` to generate
L2 devnet genesis blocks. This will be expanded in the future
to include upgrading pre-bedrock databases.
> op-node: update readme with genesis docs

- op-chain-ops/genesis/config.go
- op-node/cmd/genesis/cmd.go
Deduplicates some code for a common pattern.
Callers will usually pass a network and a path
to a deploy config directory. This comes from
the way that `hardhat-deploy-config` works.
The config directory must include a JSON file
that is named after the network.
> op-chain-ops: add helper function

- op-node/rollup/derive/attributes_queue.go
- op-node/rollup/derive/attributes_queue_test.go
- op-node/rollup/derive/batch.go
- op-node/rollup/derive/batch_queue.go
- op-node/rollup/derive/batch_queue_test.go
- op-node/rollup/derive/batch_test.go
- op-node/rollup/derive/batches.go
- op-node/rollup/derive/batches_test.go
- op-node/rollup/derive/channel_out.go
- op-node/rollup/derive/pipeline.go
- op-node/rollup/types.go
- specs/derivation.md
This adds `parent_hash` to the batch definition, to ensure we never skip a batch. Skipping a batch can cause transactions with invalid nonce values to be inserted into the execution engine, causing reorgs or complete halts.
The `parent_hash` matches the L2 block hash of the block the batch will be building on top of, i.e. the L2 safe head.
To enable this, we have to change the batch-queue processing to only output 1 batch at the time. Without this, the previous L2 block hash would not be available, and so we could not check the hash otherwise.
In a previous iteration of this I considered hashing just the batch inputs, and chaining those hashes. However, we can't include those hashes into the L2 chain elegantly, which is required to find a sync continuation point without loading all …
> op-node/specs: refactor batch queue, add parent_hash to batches, extend testing

- op-proposer/txmgr/txmgr.go
- op-service/rpc/server_test.go
- specs/meta/linting.md
Fixes op-proposer lint in Go 1.19
> op-proposer,op-service: fix txmgr lint + deprecated func lint

- op-node/eth/types.go
- op-node/eth/types_test.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/engine_update.go
- op-node/rollup/driver/step.go
- op-node/sources/engine_client.go
Testnet bugfix:
* The testnet was started without the parent-hash checking (#3221 )
* Reorgs happened (on L1 Goerli testnet, 20+ block deep, well past confirmation distance)
* Frame from data tx was missed again (twice actually). Due to valid reasons: it was just too old, from pre-reorg multiple minutes ago, likely bad L1 data in there too. 
* Batches *after* that frame were still derived, and not dropped, and insertion into engine was attempted
* Nonce errors were hit, but this time we hit a different error path: we received back an RPC error code that we were not properly handling. So the nice payload-attributes validity error we got was assumed to be temporary.
* And then it got stuck retrying those attributes over and over again. At least we have a backoff, but it …
> op-node: handle special engine RPC user-input error codes

- indexer/services/l1/bridge/filter.go
- indexer/services/l2/bridge/filter.go
This PR adds additional helpers to listen for events used to finalize deposits / withdrawals.
These functions will be used to update database state of the deposits / withdrawals in a follow-up PR.
**Metadata**
- Fixes #ENG-2665
> indexer: update l1/l2 filters for new events

- indexer/db/db.go
- indexer/db/l1block.go
- indexer/db/sql.go
- indexer/db/withdrawal.go
- indexer/indexer.go
- indexer/services/l1/bridge/bridge.go
- indexer/services/l1/bridge/eth_bridge.go
- indexer/services/l1/bridge/standard_bridge.go
- indexer/services/l1/service.go
- indexer/services/l2/bridge/bridge.go
- indexer/services/l2/bridge/standard_bridge.go
- indexer/services/l2/service.go
This PR updates the indexer to track deposit / withdrawal finalisations.
The L1 / L2 services are updated to listen to `DepositFinalized` on L2 and `ETHWithdrawalFinalized` / `ERC20WithdrawalFinalized` on L1 respectively.
The `/withdrawal/<address>` API endpoint has been updated to return finalisation status including the L1 block hash / number at which it finalised.
**Metadata**
- Fixes ENG-2665
- Depends on #3323
> indexer: update finalizations

- op-batcher/batch_submitter.go
- op-e2e/geth.go
- op-e2e/system_test.go
- op-node/eth/heads.go
- op-node/flags/flags.go
- op-node/node/config.go
- op-node/node/node.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/pipeline.go
- op-node/rollup/driver/conf_depth.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/state.go
- op-node/service.go
- Add polling of L1 safe and finalized block data (once every ~6 minutes by default, faster in tests, configurable)
- Update op-e2e to mock L1 safe block and finalized block changes - clique doesn't do this naturally. Goerli does, and L1 will, post-merge.
- De-duplicate the L2 head block references: the engine queue 100% needs them to function, whereas the driver was just using them for logging. We can just pull the data from where it's maintained, instead of maintaining copies.
- Clean up sync progress logging: we now log sync progress when we change something in the engine, with the reason why it changed, instead of having to check every possible step for changes.
- Add L1 safe/finalized event handling to driver
- Misc minor style/logging/metrics changes to make naming / structure …
> op-node: poll for L1 safe and finalized data changes, deduplicate L2 head data

- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/engine_queue_test.go
- op-node/rollup/derive/pipeline_test.go
- op-node/testutils/mock_l1.go
- op-node/testutils/mock_l2.go
Update the Engine Queue to maintain a small buffer of L1<>L2 relation data: when a L2 safe block is produced, remember the L1 block the progress was at, this is the L1 block the L2 block was fully derived from.
Once this L1 block is finalized, we can finalize the L2 blocks that were fully derived from up to and including this point.
We only maintain a buffer of `4*32 + 1` items, since finality can only change by reaching new finality over recent data of no more than 4 epochs old. Some obscure testnets have smaller epochs, but buffering a few blocks extra does not hurt.
Per L1 block we only track the latest L2 block that was fully derived from it.
If the buffer is outdated or incomplete then it'll just repair itself as we rotate into new L1 blocks. Finalization cannot cause …
> op-node: supprt block finalization [bedrock]

- batch-submitter/drivers/sequencer/encoding.go
- batch-submitter/drivers/sequencer/encoding_test.go
- bss-core/crypto.go
- bss-core/crypto_test.go
- bss-core/txmgr/txmgr.go
- proxyd/backend.go
- proxyd/integration_tests/mock_backend_test.go
- proxyd/integration_tests/util_test.go
- proxyd/rpc.go
- proxyd/server.go
- proxyd/tls.go
- Go 1.19 introduced some doc markdown formatting, linter picked that up
- Go 1.16 moved away from `ioutil` by making `ioutil` call the `io` and `os` packages under the hood, moving the implementation. It's finally time to fix this now that the linter complains.
> style(batch-submitter,bss-core,proxyd): Fix lint Go

- op-node/rollup/derive/engine_queue.go
> op-node: fix l2_safe missing metrics line

- op-node/Makefile
- op-node/eth/ssz.go
- op-node/eth/ssz_test.go
`(*ExectionPayload).UnmarshalSSZ()` fails to properly validate the `transactionsOffset` and `extraDataOffset` values, allowing a malicious actor to crash multiple op-nodes by gossiping a P2P message containing a specially crafted `SSZExecutionPayload`.
> op-node: Fix OPB-01

- .circleci/config.yml
The go contracts/genesis building code in op-chain-ops + hive devnet replaced it.
> fix(hive): fix CI, do not use op-contracts client in hive

- op-node/node/node.go
Very rare panic, can't hit it with Geth, but hit it with Erigon. When the head signal fires before the driver is fully initialized, it would panic.
> fix(op-node): do not use l2 driver before initialization

- op-batcher/batch_submitter.go
- op-e2e/system_test.go
- op-node/rollup/derive/channel.go
- op-node/rollup/derive/channel_bank.go
- op-node/rollup/derive/channel_bank_test.go
- op-node/rollup/derive/channel_out.go
- op-node/rollup/derive/frame.go
- op-node/rollup/derive/params.go
- op-node/rollup/types.go
- specs/derivation.md
This PR removes the 256 bit channel ID + timestamp. With the timestamp being removed, the channel timeout is now done with block numbers.
**Tests**
The unit tests needed to be modified, but pass. E2E tests pass
> op-node: Switch to 128 bit channel ID & block # timeout

- .circleci/config.yml
- op-batcher/Makefile
- op-e2e/Makefile
- op-node/Makefile
- op-node/eth/account_proof.go
- op-node/eth/ssz.go
- op-node/eth/types.go
- op-node/node/node.go
- op-node/p2p/config.go
- op-node/p2p/discovery.go
- op-node/p2p/gossip.go
- op-node/p2p/host.go
- op-node/p2p/node.go
- op-node/p2p/rpc_server.go
- op-node/p2p/signer.go
- op-node/rollup/derive/attributes_test.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/l1_block_info.go
- op-node/rollup/derive/params.go
- op-node/rollup/derive/payload_util.go
- op-node/service.go
- op-proposer/Makefile
- op-proposer/drivers/l2output/driver.go
This properly wraps errors in the op-node and op-proposer.
This also enables `errorlint` such that it only checks for unwrapped
errors in `fmt.Errorf`. It also checks for cases where we can use
`errors.Is` and `errors.As`. We should migrate to `errors.As`, but may
not be able to fully migrate to `errors.Is` due to certain go idioms.
> Properly wrap errors

- op-node/cmd/genesis/cmd.go
This command will be used in bedrock-regentool to replace the old hardhat scripts.
> op-node: Add additional command to generate L2 configs

- .changeset/wild-feet-listen.md
- .github/workflows/release.yml
- .github/workflows/sync-tests.yml
- ops/docker-compose.yml
- ops/scripts/build-ci.sh
hardhat-node docker image was not being properly published. We were also
using the wrong docker image name.
> fix(ci): properly publish hardhat-node

- op-bindings/Makefile
- op-bindings/gen_bindings.sh
Use `hardhat compile` so that it ensures that the artifacts used by the generator are up to date
> op-bindings: ensure integrity of artifacts

- op-node/rollup/derive/engine_queue.go
The engine may restart, wipe, or be replaced while the op-node is running. We need to handle missing data as a reason to determine the sync start again with a reset.
> op-node: handle when engine changes safe head unexpectedly

- op-node/rollup/derive/engine_queue.go
> op-node: fix missing import in engine queue

- op-node/rollup/derive/engine_queue.go
This calls a FCU to set the unsafe head of the L2 execution client immediately after NewPayload is called on the execution client. This means that the unsafe head in the node state matches the unsafe head on the execution client.
This commit removes the FCU prior to the NewPayload call because we assert that the unsafe block that we are inserting extends the current unsafe head. As such, the L2 execution client is in a state to accept the new block.
**Tests**
No new tests.
> op-node: Call FCU on new unsafe payload

- op-e2e/system_test.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/state.go
We were not passing the L1 finalization signal, preventing the L2 from getting finalized properly.
> op-node: pass L1 finalization for L2 finalization to kick in

- op-chain-ops/genesis/layer_two_test.go
Fixes the tests that depend on the existence of deployments by network in the contracts bedrock deployments directory
> op-chain-ops: fix tests

- packages/contracts-bedrock/hardhat.config.ts
The hardhat config needs to have the network that corresponds to the new deploy artifacts. This adds `alpha-1` to the hh config so that the contracts can be verified easily.
> contracts-bedrock: add in alpha-1 network

- op-chain-ops/genesis/config.go
- op-chain-ops/genesis/setters.go
- op-chain-ops/state/state.go
This wraps some common functionality of state setting into a single function so that it can easily be reused in other components. I'd like to use this function as part of testing, it can be used to populate a `SimulatedBackend` with a set of contracts and their state pre-initialized.
> op-chain-ops: modularize setting the state

- op-chain-ops/state/encoding.go
Adds extra type parsing to allow setting t_bytes32 in mappings.
> op-chain-ops: parse t_bytes32

- indexer/services/l1/bridge/bridge.go
- indexer/services/l2/bridge/bridge.go
This PR adds support for the public alpha testnet on Goerli.
**Tests**
Only updates the contract addresses and chain id.
Need help from @optimisticben to deploy an instance.
> indexer: support public alpha testnet

- indexer/services/l1/bridge/bridge.go
This PR fixes the L1 goerli chain id, should have been 5, but was set to 420 (optimstic goerli) by mistake.
> indexer: fix L1 goerli chain id

- .changeset/sixty-eggs-appear.md
- proxyd/backend.go
- proxyd/integration_tests/rate_limit_test.go
- proxyd/integration_tests/testdata/frontend_rate_limit.toml
- proxyd/server.go
The custom error message wasn't being carried over in batch responses.
> proxyd: Fix error message in tests

- .changeset/famous-pans-battle.md
- .circleci/config.yml
- ops/docker/ci-builder/Dockerfile
- packages/contracts-bedrock/package.json
Changes CI to upload code coverage results generated by the go modules and contracts-bedrock package.
This job doesn't run on this PR because of the Check Changed step, but it was tested in previous iterations of this branch by disabling that step. The results can be seen [here](https://app.codecov.io/gh/ethereum-optimism/optimism/tree/temp-getcoverage). 
Improvements which are not included in this PR but will be added later: 
1. Moving the codecov uploader installation to the ci-builder image.
2. Failing in CI when the coverage threshold decreases.
3. Adding a coverage badge to the README.
> Generate codecoverage and upload to CodeCov

- op-node/cmd/stateviz/main.go
- ops-bedrock/devnet-up.sh
Currently the Bedrock devnet stateviz container is failing to parse the snapshot logs, due to [this change](https://github.com/ethereum-optimism/optimism/commit/9eea16e31dea037a45cd93e8bdd6a59bb20691b6#diff-511cbf4bb175ffd3df8b49e206073b0cc80140ecfe160a92bfd253cfb5728de2R544) switching the logs JSON key from `l2SafeHead` to `l2Safe`. The `stateviz` JSON parser wasn't updated in the process, causing it to error with `failed to decode snapshot log` errors.
**Tests**
This is a bugfix, tested by browsing to http://localhost:9090 locally and checking that it's working. Although I guess we should build an integration test to ensure this doesn't regress in the future.
N/A
> Fix Bedrock devnet stateviz container

- .changeset/fast-mails-hope.md
- packages/contracts-bedrock/contracts/L1/L1StandardBridge.sol
- packages/contracts-bedrock/contracts/universal/StandardBridge.sol
- specs/bridges.md
Very small clean up changes to natspec and spec docs related to the StandardBridge.
> ctb: Natspec say ERC20 instead of ETH where appropriate

- .circleci/config.yml
- op-node/eth/ssz.go
- op-node/eth/ssz_test.go
The length of the ExtraData field was not being checked, which could lead to panics in the MarshalSSZ function.
> op-node: Fix OPB-04

- Makefile
- go.work
- go.work.sum
- op-batcher/go.mod
- op-batcher/go.sum
- op-bindings/go.mod
- op-bindings/go.sum
- op-chain-ops/deployer/deployer.go
- op-chain-ops/go.mod
- op-chain-ops/go.sum
- op-e2e/go.mod
- op-e2e/go.sum
- op-node/go.mod
- op-node/go.sum
- op-proposer/go.mod
- op-proposer/go.sum
- op-service/go.mod
- op-service/go.sum
- ops/scripts/update-op-geth.py
Update op-geth to the latest version on the `optimism-history` branch. This version exposes the customizable simulator backend that we need to merge https://github.com/ethereum-optimism/optimism/pull/3322.
Also adds a small script to automatically update the op-geth version in the future.
> chore: Update op-geth to latest version

- op-node/cmd/stateviz/assets/main.js
Fixes the devnet stateviz container. #3511 was half the fix; but when the stateviz server-side variable was changed from `L2SafeHead`  to `L2Safe` with d5bad2845802a75c8f25b1e3ddd249437541b67f, it rebroke the fix at a different layer: the stateviz javascript. This PR fixes that as well.
**Tests**
Tested by browsing to http://localhost:9090 locally.
> [bedrock devnet] Fix stateviz: update javascript to new L2Safe variable name

- .changeset/mean-islands-rush.md
- proxyd/config.go
- proxyd/integration_tests/batching_test.go
- proxyd/integration_tests/testdata/batching.toml
- proxyd/metrics.go
- proxyd/proxyd.go
- proxyd/server.go
The max batch size will be overwritten if it is over `MaxBatchRPCCallsHardLimit`.
Builds on https://github.com/ethereum-optimism/optimism/pull/3544.
> proxyd: Add batch size metric and configurable max

- codecov.yml
Forge coverage currently includes [some of the test files in the output](https://app.codecov.io/gh/ethereum-optimism/optimism/tree/ci%2Fcodecov-improvements/packages/contracts-bedrock/contracts/test). This will exclude them from code coverage. 
I've also ignored coverage of the go bindings.
> chore: Ignore .t.sol and bindings in codecov

- .circleci/config.yml
- packages/contracts-bedrock/README.md
Updates CircleCI to use workspaces rather than the build cache to pass around node modules and build artifacts. I've found this to save between 1-2 minutes on the yarn install job.
> ci: Use workspace rather than cache

- .changeset/hot-panthers-reply.md
- ops/scripts/deployer.sh
Will allow for e2e testing of the nft bridge scripts on `ops`
> deployer: expose deployments

- .circleci/config.yml
The publish tasks don't need to depend on upstream tests. This will let us run Hive tests earlier in the pipeline, and shave off additional CI runtime.
> ci: Remove publish dependencies

- .circleci/config.yml
Activates CodeCov's [flags](https://docs.codecov.com/docs/flags#tracking-flag-coverage-over-time) feature.
> ci: Add codecov flags per codebase

- .changeset/calm-ladybugs-occur.md
- integration-tests/test/nft-bridge.spec.ts
- packages/contracts-periphery/contracts/L1/L1ERC721Bridge.sol
- packages/contracts-periphery/contracts/L2/L2ERC721Bridge.sol
- packages/contracts-periphery/contracts/universal/op-erc721/ERC721Bridge.sol
- packages/contracts-periphery/test/contracts/L1/L1ERC721Bridge.spec.ts
- packages/contracts-periphery/test/contracts/L2/L2ERC721Bridge.spec.ts
Removes refunds for failed NFT deposits.
**Tests**
Removes tests that no longer apply.
> feat(ctp): no refunds for NFTs

- op-e2e/e2eutils/setup.go
This new name is more idiomatic in go and avoids a confusion with the '642'.
> op-node: Rename uint642big -> uint64ToBig

- packages/contracts-periphery/deploy/nft-bridge/L1ERC721BridgeImplementation.ts
- packages/contracts-periphery/deploy/nft-bridge/L1ERC721BridgeProxy.ts
- packages/contracts-periphery/deploy/nft-bridge/L2ERC721BridgeImplementation.ts
- packages/contracts-periphery/deploy/nft-bridge/L2ERC721BridgeProxy.ts
- packages/contracts-periphery/deploy/nft-bridge/OptimismMintableERC721FactoryImplementation.ts
- packages/contracts-periphery/deploy/nft-bridge/OptimismMintableERC721FactoryProxy.ts
- packages/contracts-periphery/hardhat.config.ts
- packages/contracts-periphery/scripts/deploy-nft-bridge.sh
- packages/contracts-periphery/src/nft-bridge-deploy-helpers.ts
The most important one is the deploy script for the `Proxy` that will end up at the predeploy on L2. There are specific checks for the correct deployer account being used. Will likely require some changes to the hardhat config when doing the actual deployment.
> ctp: fixup deploy scripts for the nft bridge

- op-node/rollup/derive/attributes_queue.go
- op-node/rollup/derive/attributes_queue_test.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/engine_queue_test.go
- op-node/rollup/derive/pipeline.go
The progress API is very nearly removed from the engine queue stage.
**Metadata**
- Fixes ENG-2751
> op-node: Switch attributes queue to be pull based

- op-node/rollup/derive/attributes_queue.go
- op-node/rollup/derive/attributes_queue_test.go
- op-node/rollup/derive/batch_queue.go
- op-node/rollup/derive/batch_queue_test.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/engine_queue_test.go
- op-node/rollup/derive/pipeline.go
The attributes queue actually had pretty few modifications to work with the progress API. The logic of switching the batch queue over was a bit more complex because the batch queue is very stateful, but still not the worst.
**Metadata**
- Fixes ENG-2750
> op-node: Switch batch queue to be pull based

- op-node/rollup/derive/attributes_queue.go
- op-node/rollup/derive/attributes_queue_test.go
- op-node/rollup/derive/batch_queue.go
- op-node/rollup/derive/batch_queue_test.go
- op-node/rollup/derive/channel_bank.go
- op-node/rollup/derive/channel_bank_test.go
- op-node/rollup/derive/channel_in_reader.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/engine_queue_test.go
- op-node/rollup/derive/error.go
- op-node/rollup/derive/pipeline.go
- op-node/rollup/driver/state.go
This is two commits because the intermediate commit was failing a test & the second commit fixes it.
* op-node: Switch channel bank to be pull based
This again requires a fair amount of changes to channel_in_reader.go
for the channel in reader to maintain its progress state.
* op-node: Switch channel in reader to a pull based stage
Like the rest of the changes, this also required modifications to
the next stage - the batch queue in order for it to manage the
progress API. This commit required even more changes than usual.
I changed the pipeline to be reset to a common starting point
and now use the L2SafeHead block to filter out adding batches &
L1 blocks to the batch queue.
**Metadata**
- Fixes ENG-2749
> op-node: Switch channel bank and channel in reader to a pull based stage

- op-node/rollup/derive/attributes_queue.go
- op-node/rollup/derive/attributes_queue_test.go
- op-node/rollup/derive/batch_queue.go
- op-node/rollup/derive/batch_queue_test.go
- op-node/rollup/derive/channel_bank.go
- op-node/rollup/derive/channel_bank_test.go
- op-node/rollup/derive/channel_in_reader.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/engine_queue_test.go
- op-node/rollup/derive/error.go
- op-node/rollup/derive/l1_retrieval.go
- op-node/rollup/derive/l1_retrieval_test.go
- op-node/rollup/derive/l1_traversal.go
- op-node/rollup/derive/pipeline.go
- op-node/rollup/driver/state.go
This makes the L1 Retrieval a purely pull based stage. This commit required large modifications to the channel bank stage in order for the channel bank to maintain its own progress.
**Tests**
L1 Retrieval unit tests pass. I skipped the channel bank unit tests & fixed them up in the next PR (would have been lots of extra work to fix them twice).
**Metadata**
- Fixes ENG-2748
> op-node: Switch L1 Retrieval to pull based

- op-e2e/actions/action.go
Adds core types / base stuff for action testing. Mostly just types and testing wrapper.
Depends on #3586 
**Metadata**
Fix ENG-2834
> op-e2e/actions: action tests base test util

- op-node/testutils/rpc_err_faker.go
Quick and simple util to fake underlying RPC errors, part of the L1 replica and L2 engine actor in action testing.
> op-node: testutils RPC error faker util

- op-node/testlog/testlog.go
To instantiate test loggers as part of action testing, Hive testing, etc. we should hide the testing backend with an interface.
> op-node: testlog now uses interface, to swap testing backend easily

- op-chain-ops/crossdomain/alias.go
- op-chain-ops/crossdomain/alias_test.go
This simplifies the crossdomain aliasing Go code, and removes the unnecessary pointer indirection. Based on discussion here: 
https://github.com/ethereum-optimism/optimism/pull/3587#discussion_r982440508
> op-chain-ops: alias functions without pointers, and geth uint256 type

- .changeset/lazy-drinks-drop.md
- integration-tests/test/nft-bridge.spec.ts
- packages/contracts-periphery/contracts/universal/op-erc721/OptimismMintableERC721Factory.sol
- packages/contracts-periphery/test/contracts/universal/OptimismMintableERC721Factory.spec.ts
These changes make the `OptimismMintableERC721Factory` in line with the bedrock version of the `OptimismMintableERC20Factory`. We might as well follow what we are doing with the new erc20 factory to keep things in line with each other.
These changes are very small, they just rename a function to not follow the deprecated naming scheme, the function now returns an address which makes testing/integration a bit easier and also does a slight refactor to prevent the need to cast a type 3 times.
> contracts-periphery: erc721 factory fixes

- op-e2e/actions/l1_miner.go
- op-e2e/actions/l1_miner_test.go
- op-e2e/actions/l1_replica.go
This introduces a L1 miner actor that can build/seal blocks and include txs from specific accounts in specific order, to build test cases that e.g. the batcher is getting censored or different things happen in specific order.
The starting/including/sealing can be combined to build a block that e.g. only contains batcher txs, for later testing. Or used for fuzzing; we can make randomized blocks in a deterministic way.
Depends on #3601 
**Tests**
A test of the L1 miner block building, empty and non-empty, is included. We can use this actor to build tests for the L2 actors which are next.
**Metadata**
Fix ENG-2759
> op-e2e: Action testing L1 miner

- op-e2e/actions/action.go
- op-e2e/actions/actors.go
- op-e2e/actions/l1_miner.go
- op-e2e/actions/l1_miner_test.go
- op-e2e/actions/l1_replica.go
- op-e2e/actions/l1_replica_test.go
- op-e2e/go.mod
Depends on #3599 and #3600 (will rebase out the commits / diff once those PRs are merged)
Implements L1 replica actor for action testing, with actions to fake RPC errors, ewind it, and reorg to some arbitrary canonical chain.
The L1 miner actor will wrap this, and build actual blocks with actions.
The L1 miner and replica(s) will then serve the L2 rollup nodes and user actors in action testing.
**Tests**
- Basic test of the replica reorg functionality without L1 miner, by generating an artificial chain, although it's more clumsy than when we get the L1 miner actions to build blocks.
- Basic test of the replica RPC error faking
**Metadata**
Fix ENG-2760
> op-e2e: Action testing L1 replica + miner code (combined by mergify)

- op-e2e/actions/l1_miner.go
- op-e2e/actions/l1_replica.go
- op-e2e/actions/l2_verifier.go
- op-e2e/actions/l2_verifier_test.go
This PR adds a L2 verifier actor (rollup node) for action-testing. It follows L1 with derivation actions and allows you to mock some p2p input as an action.
**Tests**
Since we don't have a L2 sequencer actor yet I'm testing just the safe-head part of the L2 sync. It runs through 2 sequence windows, and makes sure blocks are forced in. And that even past the sequence window, it can handle a deep L1 reorg.
The L2 verifier actor will be wrapped by a L2 sequencer actor, and help us test the derivation. The `ActL2PipelineStep` and handling of l1 fields is temporary: we can do this properly once we land the driver refactor that separates this logic/state.
This will help unblock the L2 sequencer actor implementation (although that too would benefit from the …
> op-e2e: action testing - L2 verifier actor

- .circleci/config.yml
- op-e2e/actions/l1_miner.go
- op-e2e/actions/l1_miner_test.go
- op-e2e/actions/l1_replica.go
- op-e2e/actions/l1_replica_test.go
- op-e2e/actions/l2_engine.go
- op-e2e/actions/l2_engine_test.go
- op-e2e/setup.go
- op-e2e/system_test.go
- op-node/node/node.go
Replaces my previous PRs since `t.Parallel()` works fine. Also exposes the listener on the op-node, so that we can use a port of zero and allow the kernel to allocate a port.
> ci: Parallelize op-e2e

- op-node/client/polling.go
- op-node/client/polling_test.go
- op-node/client/rpc.go
The Geth RPC client does not support subscriptions for HTTP endpoints. As a result, users who set an HTTP endpoint for the op-node were unable to sync since the driver never got any L1 head updates. This PR adds a wrapper around `client.RPC` that makes `newHeads` subscriptions work over HTTP. It does this by layering a notifications system that mimicks what Geth does under the hood on top of an HTTP polling loop.
The interface is the same as the one exposed by the raw RPC client. I tried my best to match Geth's subscription semantics, including:
- Closing the client causes all subscribers to get a nil error on their error channels.
- Unsubscribing closes each subscriber's error channel.
- Calling `Unsubscribe` multiple times is safe.
The poll rate is configurable. It default to 250ms, …
> op-node: Add wrapper to support EthSubscribe in HTTP clients

- op-node/p2p/gossip.go
- op-node/p2p/signer.go
Fixes OPB-02.
This is a draft, POC for how I'd do this in signer.go. Two other locations still need fixing which I'll do in a subsequent PR once this is approved.
**Tests**
No new tests are added as it's unclear how this would actually be reachable, however it was decided to include it as "future proofing".
> OPB-02: Raise error on oversized chain id

- op-node/sources/eth_client.go
This function was not being used and could be safely removed.
> op-node: Remove BlockIDRange

- packages/sdk/hardhat.config.ts
- packages/sdk/tasks/finalize-withdrawal.ts
- packages/sdk/tasks/index.ts
Now we no longer need to use one off scripts for testing this kind of thing. The hh task will check to see the status of a transaction hash and then finalize the withdrawal on L1 if the message status is ready for relay. It does this by creating a `CrossChainMessenger`.
> sdk: add hh task for finalizing withdrawal

- .changeset/slow-stingrays-rescue.md
- ops/docker/ci-builder/Dockerfile
Updates the CI builder to install slither from a specific commit, which will allow us to run it on our code without having to [remove the forge test files](https://github.com/ethereum-optimism/optimism/blob/c84c19227fd41aefc72b4af92fef547fc5a3a98c/packages/contracts-bedrock/scripts/slither.sh#L5-L8). 
**Tests**
I tested the build locally.
> Install a specific slither commit

- op-node/rollup/derive/attributes.go
- op-node/rollup/derive/attributes_test.go
- op-node/rollup/driver/sequencer.go
- op-node/sources/eth_client.go
- op-node/testutils/mock_eth_client.go
The previous api would return a receipts fetcher that the caller was responsible for iterating through and then calling `Result` on. This moves this inside the `Fetch` function. This simplifies usage of the API and does not result in performance regression because the receipts hash check requires all receipts to be fetched before
**Tests**
No added tests, but all pass.
> op-node: Simplify Receipts Fetching API

- indexer/db/db.go
- indexer/db/eth.go
- indexer/db/l1block.go
- indexer/db/sql.go
- indexer/db/state_batch.go
- indexer/db/withdrawal.go
- indexer/services/l1/service.go
- indexer/services/l2/service.go
Updates the indexer's DB package to support both Bedrock and the legacy system. 90% of of this is a revert back to Mark's last commit on the indexer pre-Bedrock.
> indexer: Update DB package

- packages/contracts-governance/hardhat.config.ts
Adds the config for using a ledger with hardhat
deploy. The env var `LEDGER_ADDRESS` must be
set for this to work.
Note that hh deploy is buggy and will always
use the default path when creating a `LedgerSigner`. This means the `LEDGER_ADDRESS` env var is useless, it won't actually use that address when doing a
deployment. Basically, if its set then it just means use the ledger's first derived address at the default path.
This should be an easy thing to fix upstream, although kind of annoying. The paths would need to be searched linearly until a matching address is found, I think a better way to configure this is pass either:
- A path + address
- A path
If both are passed, then it should validate that the path matches the address. If a path is passed, then yolo use the …
> contracts-governance: allow deploy by ledger

- op-batcher/batch_submitter.go
- op-proposer/l2_output_submitter.go
- op-service/go.sum
- op-service/metrics/balance.go
- op-service/metrics/balance_test.go
- ops-bedrock/docker-compose.yml
This adds a utility function to the `op-service` package which launches a go rountine
to check the balance of a given account. This is helpful for in process monitoring of
the balance of an account for a specific service (like the batcher or proposer).
**Tests**
Tested locally with devnet.
**Metadata**
- Fixes ENG-2713
> Add balance metrics to op-propose & op-batcher

- op-node/rollup/derive/attributes_test.go
- op-node/rollup/derive/deposit_log.go
- op-node/rollup/derive/deposit_log_test.go
- op-node/rollup/derive/l1_block_info.go
Prevents unhandled panics in the case that unexpectedly large values are passed to `FillBytes`.
**Tests**
No new tests, it's not clear that these errors are actually reachable.
**Metadata**
- Fixes ENG-2613
> op-node: Fillbytes size check in l1 block info

- .changeset/angry-wombats-marry.md
- proxyd/rpc.go
- proxyd/rpc_test.go
The JSON-RPC 2.0 specification indicates that the error object may contain an optional data field. Proxyd currently drops this field from any responses. This PR fixes that.
https://www.jsonrpc.org/specification#error_object
**Tests**
I added a test to check that if a data field is present in the response from a backend, it will be added to the response from proxyd. The existing test should validate that if data field is not present in the response from the backend, the data key should not be present in the JSON response from proxyd.
> fix(proxyd): Fix compliance with JSON-RPC 2.0 spec by adding optional RPCError.Data

- op-node/node/log.go
The handler returned from `log.LvlFilterHandler` wasn't being consumed anywhere, so log level configuration was being ignored.
> op-node: Fix log level handler

- .changeset/loud-pigs-hang.md
- proxyd/backend_rate_limiter.go
- proxyd/cache.go
- proxyd/config.go
- proxyd/frontend_rate_limiter.go
- proxyd/frontend_rate_limiter_test.go
- proxyd/integration_tests/failover_test.go
- proxyd/integration_tests/testdata/frontend_rate_limit.toml
- proxyd/metrics.go
- proxyd/proxyd.go
- proxyd/redis.go
- proxyd/server.go
Integrates the custom rate limiter in the previous PR into the rest of the application. Also takes the opportunity to clean up how we instantiate Redis clients so that we can share them among multiple different services.
There are some config changes in this PR. Specifically, you must specify a `base_rate` and `base_interval` in the rate limit config.
> proxyd: Integrate custom rate limiter

- op-node/client/rpc.go
This fixes an issue where if a short context was supplied to the call it would still take a long time to complete.
> op-node: Use DoCtx in DialRPClientWithBackoff

- .changeset/wet-cameras-cover.md
- proxyd/cmd/proxyd/main.go
- proxyd/config.go
- proxyd/example.config.toml
Log level conf to reduce log output in prod
> adds log level conf to proxyd

- op-node/eth/block_info.go
- op-node/sources/eth_client.go
There was a single usage of BlockInfo.ID() which I replaced with a function called `ToBlockID` which can take either a BlockInfo or a types.Block (it uses an interface consisting of Hash and NumberU64).
This change makes our code that depends on `BlockInfo` much more useful because this
is much easier than manually converting types.
> op-node: Allow *types.Block to satisfy the BlockInfo interface

- .changeset/flat-windows-trade.md
- proxyd/backend_rate_limiter.go
- proxyd/config.go
- proxyd/integration_tests/testdata/backend_rate_limit.toml
- proxyd/integration_tests/testdata/out_of_service_interval.toml
- proxyd/integration_tests/testdata/ws.toml
- proxyd/proxyd.go
The backend rate limiter is in place to protect upstreams like the sequencer. However, in many cases it isn't needed and it causes unnecessary requests to Redis. This PR allows this to be disabled, and disables this by default.
> proxyd: Allow disabling backend rate limiting

- packages/contracts-bedrock/deploy/001-InitImplementations.deploy.ts
The function signature wasn't updated with the arguments.
> contracts-bedrock: Fix L2OO deployment

- op-node/rollup/derive/batch_queue.go
The batch queue was using the previous origin when computing if the origin was behind or not. It would then immediately advance it's internal origin to the next origin (confusingly coming from the `prev` stage). It would take action on the current origin based on out of date data. Specifically, it would not save an origin that should have been saved into the l1Blocks array. This causes errors because the L1 Origin of the safe head would not be present when attempting to derive the next batch after a reset.
**Tests**
Not tested either in a full reproduction or with unit tests. 
**Metadata**
- Fixes ENG-2906
> op-node: Fix reset bug in batch queue

- op-bindings/predeploys/dev_addresses.go
- op-chain-ops/genesis/layer_one.go
- op-chain-ops/genesis/layer_one_test.go
This will make e2e testing that requires and erc20 token that is mintable easy. Just send eth to the
correct address and then you will have an erc20
token.
This will be used for e2e tests for token deposits and withdrawals.
> op-chain-ops: add weth9 as a L1 predeploy

- op-e2e/actions/user.go
Allows a specific transaction value to be sent by a user in the e2e tests
> op-e2e: user action allow set value

- op-e2e/actions/user.go
Add a getter for fetching the last receipt. This
is useful if values from a receipt need to be parsed as input to additional calls
> op-e2e: last receipt getter

- op-node/metrics/metrics.go
- op-node/node/node.go
- op-node/p2p/config.go
- op-node/p2p/gossip.go
- op-node/p2p/host.go
- op-node/p2p/host_test.go
- op-node/p2p/node.go
- op-node/p2p/notifications.go
- op-node/p2p/prepared.go
- op-node/p2p/rpc_server.go
Adds the following peer-to-peer metrics:
- Peer count
- Stream count
- Number of gossip events by type
- Peer-to-peer bandwidth usage by direction
I used libp2p's existing interfaces wherever I could. Note that we still need a backgorund goroutine to pull banwdiwth stats out of the libp2p bandwidth counter.
Meta:
- Fixes ENG-2338
- Fixes ENG-2336
- Fixes ENG-2329
> op-node: Add P2P metrics

- .circleci/config.yml
Updates the authentication method for docker publish jobs to use OIDC instead of a non-expiring service account key
Reference docs: https://circleci.com/docs/openid-connect-tokens/#adding-gcp-to-the-circleci-configuration-file
> INF-11 updates docker-publish jobs to use OIDC auth

- .circleci/config.yml
We were using `--flag` on the uploader, but should have been using `--flags`. 🤡
> ci: Fix incorrect flag naming on codecov upload

- .changeset/friendly-rats-scream.md
- packages/contracts-bedrock/contracts/L1/OptimismPortal.sol
Standardizes the location of initializers to be under constructors.
> fix(ctb): move inits under constructors

- op-node/rollup/driver/conf_depth.go
- op-node/rollup/driver/conf_depth_test.go
The L1 Head block in the conf depth is pulled from the L1 State object. The L1 State is never initialized at startup but instead from the new head channel. This means that prior to the first new head, any code which calls BlockByNumber would always fail if the conf depth was not zero.
> op-node: Skip conf depth check if L1 head is empty

- op-node/rollup/derive/channel.go
- op-node/rollup/derive/params.go
- specs/derivation.md
This pulls it out into it's own constant inside the op-node. This also clarifies where the limit is applied and the implications that the limit has on what batches can be accepted.
**Metadata**
- Fixes ENG-2882
> specs,op-node: Clarify Max RLP Bytes Per Channel

- .snyk
Snyk IaC repo checks does not respect kustomizations, so it's not useful here.
> disable snyk for infra/op-replica

- op-node/rollup/derive/channel_out.go
This ensures that the channel creator respects the limits used in derivation. This returns a sentinel error if the batch would make the channel too large.
**Metadata**
- Fixes ENG-2919
> op-node: Limit decompressed size in channel_out

- specs/derivation.md
- specs/exec-engine.md
This cleans up specs. Specifically:
- We no longer allow right padding on frames.
- Specify that all frames must be parseable in a batcher transaction
- Document changes to `engine_forkChoiceUpdatedV1` made in https://github.com/ethereum-optimism/reference-optimistic-geth/pull/40
**Metadata**
- Fixes ENG-2728
- Fixes ENG-2663
> specs: Remove outdated portions

- l2geth/core/state/statedb.go
- l2geth/core/vm/evm.go
- l2geth/rollup/dump/constants.go
- l2geth/statedumper/dumper.go
This is necessary in order to perform the mainnet OVM ETH and withdrawal hashes migration. Operates using a L2GETH_STATE_DUMP_PATH environment variable that specifies the file that addresses should be dump to. They are not deduplicated. The format of the file is:
```
ETH|<ovm eth address>
MSG|<sender>|<msg>
```
> l2geth: Add OVM ETH and message passer state dump

- .circleci/config.yml
- .gitignore
- Makefile
- bedrock-devnet/README.md
- bedrock-devnet/devnet/__init__.py
- bedrock-devnet/devnet/genesis.py
- bedrock-devnet/devnet/log_setup.py
- bedrock-devnet/main.py
- op-node/cmd/genesis/cmd.go
- packages/contracts-bedrock/deploy-config/devnetL1.json
- packages/sdk/src/cross-chain-messenger.ts
- packages/sdk/src/utils/contracts.ts
- packages/sdk/tasks/deposit-erc20.ts
- packages/sdk/tasks/deposit-eth.ts
Adds a bedrock-devnet script that deploys a local network using the Hardhat deploy scripts. I opted to write this in Python rather than Bash because we're starting to add complexity to our devnet setup, and I find Python much easier and safer to maintain.
Over time, I'll migrate the other devnet-up script to use this Python script as well.
To invoke this script, run `make devnet-up-deploy`. It's included in CI already as a separate testing job.
> ops: Add bedrock-devnet script

- op-e2e/actions/l1_miner.go
- op-e2e/actions/l2_batcher.go
- op-e2e/actions/l2_sequencer.go
- op-e2e/actions/l2_verifier.go
- op-e2e/actions/reorg_test.go
- op-node/rollup/derive/engine_queue.go
This PR tests that a verifier can handle a L1 reorg of 1-block (a.k.a. orphan block) that includes a batch, and then tests what happens if it is then replayed onto a new L1 chain, and if it stays in sync with the sequencer.
**Tests**
See above.
**Metadata**
Fix ENG-2770
> op-e2e: test orphan L1 block with batch and replay batch + keep engine fc state in sync [bedrock]

- op-e2e/actions/reorg_test.go
Depends on #3728 
**Tests**
This tests we can flip-flop as verifier between two L1 chains, with replayed (and temporarily invalid during flip-flop) batches.
TODO: the engine adds one valid previously seen block on top of the unsafe chain, even though the rollup node does not ask it to. It's consolidated fine later on, but this forkchoice state should be synced (or it's a minor geth bug where it's to eager to preserve blocks, which can't happen in PoS where this chain extension is always the head).
**Metadata**
Fix ENG-2766
> op-e2e: flip-flop test

- op-node/rollup/derive/channel_out.go
- op-node/rollup/derive/channel_out_test.go
- specs/derivation.md
The exact requirement is that the input length is less than or equal to the max bytes per channel. This comparison is done with inputLimit in the RLP reader.
**Metadata**
- Fixes ENG-2926
> specs,op-node: Clarify max bytes per channel comparison

- op-chain-ops/genesis/config.go
Improves the error message when reading a deploy config to print the path. Will be helpful for CLI tooling that consumes this function to give a better error message at runtime.
> op-chain-ops: improve error message

- op-node/rollup/derive/channel_bank.go
- op-node/rollup/derive/channel_bank_test.go
- op-node/rollup/derive/frame_queue.go
- op-node/rollup/derive/pipeline.go
- specs/derivation.md
This clarifies the order of pruning & ingesting data into the channel bank.
It also adds a frame queue to enable frame by frame processing to match the specs.
**Metadata**
- Fixes ENG-2879
> specs,op-node: Clarify channel bank pruning

- op-chain-ops/cmd/migrate/main.go
- op-chain-ops/crossdomain/migrate.go
- op-chain-ops/genesis/db_migration.go
- op-chain-ops/genesis/migration.go
- op-chain-ops/go.mod
- op-chain-ops/go.sum
- op-chain-ops/state/wrapped_db.go
Implement the cli command for doing a database migration. This script has a lot of inputs so isn't straight forward to test, need to create some canonical data that we can test this against.
This script parses the inputs to the migration but does not yet use them fully for validation. It performs the migration but still requires the input to be present.
It also adds a wrapper for the legacy l2geth statedb so that it can be passed into functions that expect a geth statedb, making the types match up correctly.
> op-chain-ops: implement migration script

- .circleci/config.yml
- integration-tests/README.md
integration tests are failing to build in ci due to a cache error, try to fix that here
> integration-tests: update readme, try to fix ci build

- .changeset/big-starfishes-jump.md
Bumps the version of the core-utils package so we can trigger a release later. Currently the core-utils package has a type change that was not published to NPM.
> fix(cu): bump version

- codecov.yml
Two changes to the codecov config:
1. Fails CI if bedrock contracts test coverage is reduced by a PR. 
2. Turns on the commenting bot.
> ci: Fail if new bedrock contract code is not 100% tested

- .github/mergify.yml
Updates Mergify rules to support speculative checks. This will allow Mergify to speculatively run checks against multiple queued PRs at once, and reduce the maount of time we spend waiting for PRs to get merged in the queue.
Also removes the changeset nag, and updates the messaging around Mergify queue failures.
> ci: Speculative checks

- op-batcher/channel_manager.go
- op-batcher/driver.go
This splits the `loadBlocksIntoState` function into several different
functions. It now mostly handles L2 reorgs as well.
> op-batcher: Clean up loading into state

- .changeset/sour-ladybugs-confess.md
- packages/contracts-bedrock/contracts/universal/ProxyAdmin.sol
Updates the function ordering for the ProxyAdmin contract to match the function ordering of the original ProxyAdmin by OZ. I think this makes the contract much more readable.
> fix(ctb): update ProxyAdmin ordering

- .circleci/config.yml
This has been causing us a lot of grief over the last few days. Disabling this until I can get to the bottom of why this is so flaky.
> ci: Temporarily disable buggy devnet build

- packages/contracts-bedrock/deploy-config/mainnet-forked.json
- packages/contracts-bedrock/deploy/014-FreshSystemDicator.ts
- packages/contracts-bedrock/deploy/015-MigrationSystemDictator.ts
- packages/contracts-bedrock/hardhat.config.ts
Removes AddressManager from deploy config, not necessary since we can just pull it from the deployments folder.
> fix(ctb): remove AddressManager from config

- op-e2e/actions/l2_batcher.go
- op-e2e/actions/l2_sequencer.go
- op-e2e/actions/system_config_test.go
This PR introduces:
- an action test for batcher key rotation, with reorging, old-key batches, etc.
- an action test for GPO params updating, with L2 tx on block on boundary and L1 fee in receipts
- introduces some minor fixes/helpers in the action-testing
This is part 4/5 to introduce batcher-key and GPO param configuration:
1. Derivation aware of system config (with placeholders for later actual contract/event changes) - #3787
2. Contract changes: system config on L1, and updated L2 contracts - #3788
3. Update bindings, update chainops to use updated bindings and dev-deploy system config, and misc integration like log parsing - #3789
4. Action-test the batcher key change and GPO params change. - #3790
5. Spec updates - #3831
**Tests**
Testing-only, covers the derivation …
> op-e2e: system config action tests

- indexer/integration_tests/bedrock_test.go
- op-e2e/actions/l2_engine.go
- op-e2e/actions/user.go
- op-e2e/actions/user_test.go
- op-e2e/system_test.go
- op-node/withdrawals/utils.go
Withdrawals depend on the proposer working in action-testing. So this is now split from the main user-actor PR (#3628) to integrate with the proposer actor.
Update the withdrawals RPC client input to use minimal interfaces, and refactor to not tightly couple geth and eth client functionality. This enables the use of an instrumented `client.RPC` and mocks.
~~Depends on #3628~~
~~Depends on #3805~~
**Tests**
Test creates a withdrawal tx on L2, includes it, then makes proposal on L1 for the L2 blocks including the withdrawal, includes those on L1, checks the withdrawal period, and then completes the withdrawal.
Fix ENG-2763
> Action-testing: extend user actor with withdrawal txs

- go.work
- op-batcher/go.mod
- op-batcher/go.sum
- op-bindings/go.mod
- op-bindings/go.sum
- op-chain-ops/go.mod
- op-chain-ops/go.sum
- op-e2e/go.mod
- op-e2e/go.sum
- op-node/go.mod
- op-node/go.sum
- op-proposer/go.mod
- op-proposer/go.sum
- op-service/go.mod
- op-service/go.sum
Includes https://github.com/ethereum-optimism/op-geth/pull/23
Pulling these changes into the monorepo so that things can be integrated with `op-e2e`
Will follow up with PRs that clean up `op-e2e` so that they don't get too large
> optimism: update op-geth to the predeploy commit

- packages/contracts-bedrock/deploy/015-FreshSystemDictatorSteps.ts
- packages/contracts-bedrock/deploy/016-MigrationSystemDictator.ts
- packages/contracts-bedrock/deploy/017-MigrationSystemDictatorSteps.ts
Breaks out MigrationSystemDictator steps into their own deployment stage. I'll add post-deployment verification in a separate PR.
> feat(ctb): break out MSD steps

- .prettierrc.js
- packages/contracts-bedrock/hardhat.config.ts
Bumped compiler version from 0.8.10 to 0.8.15 in contracts-bedrock & in .prettierrc.js
**Tests**
No tests required. 
**Metadata**
- Fixes #https://github.com/ethereum-optimism/optimism/issues/3839#issue-1432296592
> Bumped compiler version for contracts-bedrock

- .github/workflows/release.yml
There was a typo in the config for building/publishing the `ethereumoptimism/hardhat-node` docker image.
This fixes that typo so that builds can be properly published to dockerhub.
> ci: fix hardhat-node release

- op-chain-ops/crossdomain/migrate.go
- op-chain-ops/genesis/db_migration.go
This will make debugging the migration much easier by wrapping errors during the migration.
> op-chain-ops: wrap errors

- op-node/sources/receipts.go
We saw `op-node` panic in an internal PoA testnet, I believe due to a reorg that happened during a deploy (having multiple PoA signers with the same key during the deploy). This caused some of the tx receipts returned from the L1 have a `null` `blockNumber` value, causing a `panic: runtime error: invalid memory address or nil pointer dereference` error.
**Tests**
There doesn't appear to be any existing tests for this logic, but happy to add some if I'm missing where those are.
Stacktrace:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xe276b4]
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 217 [running]:
math/big.(*Int).Uint64(...)
/usr/local/go/src/math/big/int.go:384 …
```
> [op-node] Check that BlockNumber is non-nil in the receipt validation

- op-node/rollup/driver/origin_selector.go
- op-node/rollup/driver/origin_selector_test.go
We found a log on a testnet where a batch was rejected because it's timestamp was greater than the origin timestamp + sequencer drift. I looked into origin selection and determined we produce empty blocks if the block time is ahead of the origin + seq drift; however if there is a next origin, it is not enough to produce an empty block, we must change the origin.
I hypothesize that this occurred because the L1 head that the node was looking at was lagging. That would cause the node to keep using an old origin even if the timestamp was past the max drift. I added a unit test which shows this case & would fail without this fix being applied.
**Tests**
Unit tested with a regression test.
**Metadata**
- Fixes ENG-2923
> op-node: Prefer following seq drift instead of conf depth

- op-batcher/channel_manager.go
- op-batcher/driver.go
The channel manager is now responsible for tracking in flight frames and properly handling different error conditions.
A channel is a collection of frames. We have a single frame per L1 transaction.
When frames are submitted to L1 even if all frames are successfully included, their
inclusion may not be timely. The tx confirmation method handles resubmitting frames
if the transaction fails or voiding the entire channel if the channel times out.
It has hook points for how large a range of blocks to select, but does not use them
yet. It simply chooses up to 100 blocks (but it will also not submit channels that
are too large).
**Tests**
No unit tests yet. op-e2e still passing.
> op-batcher: Rewrite ChannelManager

- op-node/rollup/driver/state.go
Make sure to produce a L2 chain up to and including the latest wall clock timestamp. The L1 origin that we adopt doesn't matter in the catchup logic. When producing the block, and older L1 origin can be selected based on the conf depth, but the L2 chain should still be produced.
**Tests**
Fix based on alpha-1 testnet syncing occurence. Can extend testing in e2e for this later.
> op-node: catch up L2 sequencing based on time, not L1 origins

- op-e2e/go.mod
We no longer need these `replace` statements now that the dependencies can be properly resolved with the new go module releases.
> op-e2e: remove temporary go.mod workaround

- op-e2e/actions/user.go
This should hopefully avoid issues with not being able to find the pending block.
> op-e2e: Use head rather than pending block for gas estimation

- indexer/integration_tests/bedrock_test.go
- op-chain-ops/cmd/migrate/main.go
- op-chain-ops/genesis/config.go
- op-chain-ops/genesis/db_migration.go
- op-chain-ops/genesis/layer_two.go
- op-chain-ops/genesis/layer_two_test.go
- op-chain-ops/genesis/testdata/test-deploy-config-devnet-l1.json
- op-e2e/e2eutils/setup.go
- op-e2e/op_geth_test.go
- op-e2e/setup.go
- op-node/cmd/genesis/cmd.go
Now all of the config lives in the `DeployConfig`
and there is a method to read dynamic config values
from disk given a hh or the dev addresses can be
added to the config with `GetDeveloperDeployedAddresses`.
This is useful to deduplicate code that has been changing
a lot, resulting in code changes in many places to get
tests passing again.
This will break hive when we do another release of the go
packages.
Fixes ENG-2993
> fix: more config cleanup

- .changeset/lucky-walls-walk.md
Trigger a release of the hardhat-node docker image because there was a bug that prevented it from being released previously, that bug has been fixed
> hardhat-node: trigger a release

- packages/contracts-bedrock/contracts/L1/L1ERC721Bridge.sol
Removes an old comment block in the L1ERC721Bridge contract.
> fix(ctb): remove old comment block

- op-node/testlog/testlog.go
This increase the default amount of space given to file names & changes the printing
such that if the filename is longer than the padding length, it gets no padding instead
of the full padding.
> testlogger: Nicer output

- .changeset/silver-nails-grab.md
- packages/drippie-mon/src/service.ts
- packages/drippie-mon/tsconfig.json
- packages/fault-detector/src/service.ts
- packages/fault-detector/tsconfig.json
- packages/message-relayer/src/service.ts
- packages/message-relayer/tsconfig.json
- packages/replica-healthcheck/src/service.ts
- packages/replica-healthcheck/tsconfig.json
Improves the way that package versions are imported for BaseServiceV2 services. By importing directly (in typescript, rather than using require) TypeScript will properly embed the package.json in the /dist folder which makes it possible to run the services using the compiled JavaScript.
> fix: better version imports for services

- .circleci/config.yml
- op-e2e/actions/action.go
- op-e2e/system_test.go
- op-node/testlog/testlog.go
This first splits up the go-bedrock job into smaller more discrete jobs to ensure that we are using the same linters & test runner options for all packages. This also improves performance by parallelizing trivially paralleliziable jobs.
The second big change is to use `circlci tests split` to enable parallelism in CI instead of using `t.Parallel`. It is configured with an env var so tests will remain fast with local development, but we cannot use `t.Parallel` in CI because `gotestsum` currently does not do a good job of reporting the specific test that failed (because of the interleaved output) and instead reports multiple tests as failing when there is only one that failed. This improves the experience of using CI and debugging failed tests.
The last change is to add and …
> ci: Split go-bedrock tests & use circle CI parallelism for op-e2e

- .circleci/config.yml
- op-e2e/actions/l2_engine_api.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/l1_traversal.go
This uses the same set of lint options in CI as locally. Because these lints were not being
checked I had to fix several of them.
> Standardize & Fix Lints

- .github/workflows/release.yml
The `hardhat-node` docker image couldn't find the
`Dockerfile` when building. This updates the path to the dockerfile.
> ci: fix hardhat-node docker image build

- op-e2e/actions/l2_engine.go
- op-e2e/actions/reorg_test.go
Changes:
- add configuration option to L2 engine actor
- add action test to restart sequencer execution engine and recover the syncing state, including finalization/safe sync progress.
**Metadata**
Fix ENG-2779
> op-e2e: action test op-geth restart

- .changeset/nine-boats-walk.md
Adds a changeset so that a release can be triggered
This previously bumped the version of `hardhat` being used but that broke the monorepo build due some some leveldb issue in the dtl
> hardhat-node: trigger release

- packages/contracts-bedrock/deploy/017-MigrationSystemDictator.ts
- packages/contracts-bedrock/deploy/018-MigrationSystemDictatorSteps.ts
- packages/contracts-bedrock/src/deploy-utils.ts
Adds checks for the MigrationSystemDictator steps.
> feat(ctb): add MigrationSystemDictator checks

- op-e2e/system_test.go
TestConfirmationDepth was consistently failing on the HTTP versions of the op-e2e test. It was failing at the last line that checked the verifier head block timestamp against the L1 head timestamp. I have changed it to compare the verifier L1 Origin number against the L1 head number.
**Tests**
Ran several times in CI & this seems less flaky.
**Metadata**
- Fixes ENG-3013
> op-e2e: Change final TestConfirmationDepth check

- .circleci/config.yml
Running them sequentially actually turns out to be faster. In addition it turns out to be very hard to split the tests properly. `go list ./...` which was the previous approach splits them by package, but we need to split them by test name. Using `circleci tests glob "**/*.go"` did not work either becaue it was combining files from different packages.
> Disable parallel op-e2e tests in CI

- op-chain-ops/crossdomain/migrate.go
- op-chain-ops/ether/migrate.go
- op-chain-ops/genesis/db_migration.go
- op-chain-ops/genesis/setters.go
This commit adds additional logging to the database migration codepath. This is helpful for understanding what is happening in the code, to understand how much of the migration has already happened.
It may also help catch programmer/configuration errors, although we should have testing to catch that and not rely on the programmer watching the logs to catch issues.
> op-chain-ops: add logging to db migration

- packages/contracts-bedrock/contracts/deployment/MigrationSystemDictator.sol
- packages/contracts-bedrock/deploy/019-MigrationSystemDictatorSteps.ts
Allows the owner of the MigrationSystemDictator to finalize the deployment at any time. Finalizing the deployment will transfer ownership of relevant contracts to the final owner. This is an easier alternative to putting the contract behind a proxy.
> feat(ctb): allow owner to finalize MSD at any time

- .circleci/config.yml
This PR modifies CI to let external contributors more easily contribute. I've split the docker-publish job into a docker-build and docker-publish job. Hive now only depends on the docker-build job (which can be run by external contributors).
This makes one change to the hive job to remove the `docker.pull=true` flag. This is because it loads the image locally but in the case of an external contributor the image will not be published. Docker will use the local image first & then pull other images if they are not present.
I've also removed the conditional step in docker-build. It was previously used for nightly builds, but we do not have those any more (removed in #3330).
**Testing**
I've tested that hive works from just the build step by disabling the publish step. With the …
> CI: Enable Hive to work with external contributors

- go.work.sum
- op-node/Makefile
- op-node/go.mod
- op-node/go.sum
- op-node/rollup/derive/batch_tob_test.go
- op-node/rollup/derive/deposit_log_tob_test.go
- op-node/rollup/derive/l1_block_info_tob_test.go
- op-node/rollup/driver/state_tob_test.go
- op-node/testutils/fuzzerutils/fuzzer_functions.go
Adds tests created by Trail of Bits in the `op-node` package.
The added tests are named:
```
TestBedrockIndexer
TestCanonicalize
TestBuildL2DeveloperGenesis
TestBuildL2DeveloperGenesisDevAccountsFunding
TestBuildL2DeveloperGenesisDevAccountsFunding
TestMissingGasLimit
TestInvalidDepositInFCU
TestRejectCreateBlockBadTimestamp
FuzzBatchRoundTrip
FuzzDeriveDepositsRoundTrip
FuzzDeriveDepositsBadVersion
FuzzParseL1InfoDepositTxDataValid
FuzzParseL1InfoDepositTxDataBadLength
FuzzRejectCreateBlockBadTimestamp
```
**Reviewers please consider the following:** 
- Are the tests operating on correct assumptions about the system?
- Are they a net value add? 
Note that there are some 'todos' from the authors. I have not tried to resolve them and have kept them for posterity. Please …
> op-node: add ToB tests

- packages/contracts-bedrock/hardhat.config.ts
Most ephemeral networks created via the regntool don't need verification. This PR allows verification to be enabled on a case-by-case basis by setting an environment variable.
> ctb: Configurable verification for deployer network

- packages/sdk/tasks/deposit-erc20.ts
Additional tweaks to prevent test flakes in the SDK.
> fix(sdk): test flakes #2

- packages/sdk/tasks/deposit-erc20.ts
Final hotfix for flakes, if this doesn't work then I'll dive into figuring out the root cause. Now we wait 30 seconds and only continue if we haven't seen a reorg for the full 30 seconds.
> fix(sdk): final flake hotfix

- op-batcher/driver.go
- op-batcher/txmgr.go
This PR fixes the typo: `NewTransactionManger` -> `NewTransactionManager`.
> refactor: fix typo `NewTransactionManger`

- ops/docker/ci-builder/Dockerfile
Adds [echidna](https://github.com/crytic/echidna) to the ci-builder dockerfile. 
**Tests**
I tested the build on my machine using `docker build ops/docker/ci-builder`.
> ci: Add echidna to Dockerfile

- .changeset/breezy-rockets-knock.md
- .circleci/config.yml
- packages/contracts-bedrock/README.md
- packages/contracts-bedrock/foundry.toml
- packages/contracts-bedrock/hardhat.config.ts
- packages/contracts-bedrock/package.json
Related to #3944, but this includes only:
- the yarn, hardhat and foundry config changes to run the echidna tests
- adding the job to the ci config
As is, the test commands all end with `|| exit 0` so that they can fail quietly until the test code itself is introduced.
**Testing**
In order to test the new CI job properly, I temporarily (221eb98e434476f60060c618cb14a8290f6f7a97) commented out the `check-changed` step. The job completed successfully [here](https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/9901/workflows/5887a970-bef5-4f31-8341-7947e3f4a266/jobs/232027).
> ci: Add job to run echidna

- .github/mergify.yml
I added this so I could easily stay up to date with changes to the 3 packages in the monorepo I care about following.   Not sure why I added anybody else they never asked to be added
> feat(mergify reviews): Remove Nick and Imran from mergify

- packages/contracts-bedrock/package.json
No need to build the differential ts scripts if we're not using them in the gas snapshot.
> fix(ctb): gas snapshot rm extra build step

- .circleci/config.yml
rebuild and push all images for every git tag and then tag the one image that corresponds to the git tag
this is somewhat wasteful but ensures that the tagging works for any tagging strategy. 
will revisit once we address simplified release process / versioning.
> Fix: build and publish all bedrock docker images before tagging release

- .changeset/orange-bananas-nail.md
- packages/data-transport-layer/src/services/l1-ingestion/service.ts
Updates the DTL to correctly handle the deposit shutoff flag. We put the flag inside the AddressManager because the DTL already had easy access to the AddressManager. We parse the address as a uint256 and check if it's non-zero. By checking this every loop we can smoothly recover if the shutoff flag is reset.
> feat(dtl): handle deposit shutoff

- CONTRIBUTING.md
- specs/deposits.md
- specs/introduction.md
- specs/overview.md
- specs/rollup-node.md
Fix some typos in the spec and `CONTRIBUTING.md`.
> doc: fix spec typos

- op-bindings/bindings/registry.go
- op-chain-ops/state/state.go
Adds a global logger to the `SetStorage` operation. Not ideal that a global logger is used, but that is currently how the logging is handled for the migration. This will help to prevent errors in misconfiguration of the system. In setups like hive, it is difficult to get insight into the state of the system as it is being brought up, so this should log when the system is being brought up. Bad config should stick out, ie setting an empty value because something was left out of the config.
> op-chain-ops: log when setting storage

- op-node/chaincfg/chains.go
- op-node/flags/flags.go
- op-node/service.go
Adds a hardcoded Beta-1 rollup config, and provides the plumbing for us to hardcode rollup configs in the future.
Fixes ENG-3053
> op-node: Hardcode beta-1 config

- op-chain-ops/crossdomain/legacy_withdrawal.go
- op-chain-ops/crossdomain/migrate.go
- op-chain-ops/crossdomain/migrate_test.go
- op-chain-ops/crossdomain/types.go
- op-chain-ops/crossdomain/withdrawal.go
- op-chain-ops/genesis/db_migration.go
- op-chain-ops/genesis/receipts.go
To make withdrawals really easy, we need to add in receipts corresponding to the migrated withdrawals. This will allow the exact same flow to be used when creating the withdrawing transactions as normal
withdrawals.
Closes ENG-3012
> op-chain-ops: add bedrock transition receipts

- specs/glossary.md
This PR fixes the typo: `qn` -> `an` in the `specs/glossary.md`.
> docs: fix typo `qn` -> `an`

- specs/glossary.md
This PR fixes the `l2-output` link in the `specs/glossary.md`.
> docs: fix l2-output link

- op-chain-ops/genesis/config.go
The `L2ToL1MessagePasser` nonce is set to `type(uint32).max` initially to prevent nonce collisions with legacy withdrawals that have been upgraded. The max value for the nonce is `type(uint256).max` so it is not a problem to start at a non zero nonce.
> op-chain-ops: set initial message passer nonce

- .github/CODEOWNERS
Removes `.changesets` from `.CODEOWNERS`. This is generated code and doesn't need an owner. It was also pinging Zach and I on almost every PR.
> Remove changesets dir from codeowners

- op-chain-ops/genesis/db_migration.go
Prevent `nil` dereference by explicitly checking for `nil`. Add in logs to give better understanding of what the script is doing.
> op-chain-ops: better error handling in op-migrate

- op-chain-ops/cmd/op-migrate/main.go
Bugfix for the ancients path in the migration script
> op-migrate: use correct ancient path

- op-chain-ops/genesis/db_migration.go
Check that the L2 genesis block base fee per gas
is not set to `nil`. If it is, it will cause a segfault in `op-geth` on startup after the migration.
It is configured with the key: `"l2GenesisBlockBaseFeePerGas"`
> op-chain-ops: base fee check

- op-chain-ops/genesis/config.go
For both the denominator and elasticity. They cannot be 0.
> op-chain-ops: add 1559 config checks

- op-chain-ops/genesis/db_migration.go
Ensure that the timestamps are monotonic when
creating the bedrock transition block
> op-chain-ops: migrate db monotonic timestamp

- op-chain-ops/ether/migrate.go
- op-chain-ops/genesis/db_migration.go
Adds the `no-check` config flag to the erc20 eth migration codepath
> op-chain-ops: add no check to eth migration

- op-chain-ops/genesis/config.go
- op-chain-ops/genesis/db_migration.go
Adds checks for transition block config. We do not want these values to be 0 because it will mess with eip 1559 in the beginning.
> op-chain-ops: check for transition block config

- op-chain-ops/cmd/op-migrate/main.go
Two new flags are added
- `db-cache`
- `db-handles`
These are passed through the the LevelDB constructor
> op-chain-ops: allow config of LevelDB in `op-migrate`

- .changeset/healthy-steaks-impress.md
- l2geth/rollup/sync_service.go
The ss was not previously being shut down cleanly, which can result in a corrupted db state. This makes the shutdown more clean.
> l2geth: cleanly shut down the syncservice

- op-chain-ops/genesis/testdata/test-deploy-config-devnet-l1.json
- packages/contracts-bedrock/deploy-config/devnetL1.json
- packages/contracts-bedrock/deploy-config/hardhat.json
This should hopefully help some of the reorgs we've seen on the devnets.
I think the devnet was too faster for the sequencer window - particularly at startup.
In addition, I think the switch to using wallclock time may have aggravated the issue of the short sequencer window.
**Metadata**
- Fixes ENG-3036
> Increase sequencer window & sequncer drift

- .circleci/config.yml
`check-changed` needs to depend on `op-chain-ops`. This let a regression through onto `develop`.
> ci: Fix check-changed devnet

- packages/contracts-bedrock/deploy-config/devnetL1.json
- packages/contracts-bedrock/deploy-config/hardhat.json
This parameter needs to be a string, not a number. This was causing devnet builds to fail.
> ctb: Fix devnet

- .circleci/config.yml
The test was occasionally failing because of a slow test.
> CI: Increase contracts-bedrock timeout

- .changeset/shaggy-donkeys-matter.md
- packages/fault-detector/src/helpers.ts
- packages/fault-detector/src/service.ts
- packages/fault-detector/test/helpers.spec.ts
Introduces a new event cache to the fault detector. Requires for running the fault detector against Geth as the L1 node and with certain L1 node providers.
> feat(fd): event cache for Geth L1s

- .changeset/wild-months-carry.md
- packages/contracts-bedrock/README.md
Documents the proposed conventions for organizing our tests.
> docs(ctb): Document the testing conventions

- packages/contracts-bedrock/scripts/forge-test-names.ts
Adds a ts script which checks to ensure that tests conform to the convention. It can be run from within the contracts-bedrock package using `ts-node scripts/forges-test-names.ts`.
The script should eventually run in CI, when all tests are conformant.
Builds on #4122.
> ctb: Add simple script for enforcing test conventions

- specs/withdrawals.md
Clears up wording of the L1 section of the `Withdrawal Flow` in the withdrawals spec.
See @norswap's comment: https://github.com/ethereum-optimism/optimism/pull/4056#discussion_r1038816087
> fix(specs): Clear up explanation of L1 side of withdrawals

- .circleci/config.yml
Upgrades our devnet machine images to use Ubuntu 22.04 to fix issues with Forge and glibc. While there's an open [Forge 
PR](https://github.com/foundry-rs/foundry/pull/3828) to fix this, GitHub is transitioning actions to 22.04 so this issue will happen 
again unless we upgrade.
> ci: Upgrade devnet machine image

- op-chain-ops/genesis/db_migration.go
Ensures that the L2OO starting timestamp is not <= 0. When `-1` is used in migration configs, the negative value was being passed into the genesis block directly. This led to a wraparound, since we cast the timestamp to a `uint64` elsewhere in the code.
> Add additional l2oo sanity check

- .changeset/kind-planes-laugh.md
- packages/data-transport-layer/src/services/l1-ingestion/service.ts
- packages/data-transport-layer/src/services/main/service.ts
- packages/data-transport-layer/src/services/run.ts
Adds a flag to the DTL that will tell the L1 sync to not sync beyond a given block height. Can be used to prepare forked networks.
> feat(dtl): add L1 sync shutoff block flag

- op-node/p2p/discovery.go
`op-node`'s `p2p.advertise.udp` flag says that it will fallback on `p2p.listen.udp` if not set. However in practice, this does not happen.
This PR adds this fallback.
See https://github.com/ethereum-optimism/optimism/blob/cba069eff6d8951ec3d58f72c089a0bb0b8e1f2d/op-node/flags/p2p_flags.go#L83
**Tests**
I've tested this behavior in an internal devnet. It causes the advertised ENR address to have a UDP key/value pair, as verified by https://enr-viewer.com/.
> [op-node] Set fallback UDP port

- op-chain-ops/genesis/config.go
We do not want to set the `_owner` field in the `GovernanceToken`. This assumes that it is preset in the state, so it will not work for spinning up new networks.
> op-chain-ops: remove setting owner in GovernanceToken

- packages/contracts-bedrock/deploy/020-SystemDictatorSteps.ts
Significantly improves the SystemDictator step process by adding clear logs that describe what each step is doing.
> feat(ctb): add nicer log lines to dictator steps

- op-chain-ops/genesis/db_migration.go
This sets the bedrock fork block number in the stored chain config during the migration.
**Tests**
Not tested.
**Metadata**
- Fixes ENG-3076
> Set bedrock block in migration

- packages/contracts-bedrock/deploy/019-SystemDictatorInit.ts
- packages/contracts-bedrock/src/deploy-utils.ts
Removes some unnecessary deploy utils related to the SystemDictator. These utils were originally used because there were two different SystemDictator contracts and both needed to use the same logic. Now that there's only one SystemDictator, there's no need to break the code out into a separate function.
> maint(ctb): remove unnecessary deploy utils

- indexer/integration_tests/bedrock_test.go
- op-e2e/actions/user.go
- op-e2e/system_test.go
- op-node/withdrawals/utils.go
This renames the L2 block field to the L2 Index. This more accurately matches what the L2 output oracle contract expects.
**Tests**
Tested in hive here: https://github.com/ethereum-optimism/hive/pull/66
I think we need a design doc on the API design of the proof withdrawal utilities. I expect that the API might change again - having to pass in the contract is a little bit ugly.
Once this is merged, I'll have to cut a release `v0.10.3` and then update hive with that release.
> Update withdrawal params for two step withdrawals

- op-wheel/Dockerfile
- op-wheel/cheat/cheat.go
- op-wheel/docker.go.work
With these changes I was able to successfully run the `ovm-owners` cheats against a Goerli datadir, run the engine, and execute the L1 migration. The specifics of what I did are in comments.
Note that there's one outstanding issue I didn't fix as part of this PR. The `head-block` command returns garbage, since the `types.Block` structure isn't directly JSON serializable. I figured we could fix that separately since it doesn't touch critical code paths.
Also adds a `Dockerfile` + assorted `go.work` files so that we can deploy this on k8s.
> op-wheel: Updates to make cheats work

- op-chain-ops/genesis/config.go
- op-chain-ops/genesis/layer_one.go
- op-chain-ops/genesis/testdata/test-deploy-config-full.json
- op-e2e/e2eutils/setup.go
- op-e2e/setup.go
- packages/contracts-bedrock/contracts/test/CrossDomainOwnable2.t.sol
- packages/contracts-bedrock/deploy-config/devnetL1.json
- packages/contracts-bedrock/deploy-config/goerli-forked.json
- packages/contracts-bedrock/deploy-config/goerli.json
- packages/contracts-bedrock/deploy-config/hardhat.json
- packages/contracts-bedrock/deploy/017-SystemConfigImpl.ts
- packages/contracts-bedrock/deploy/019-SystemDictatorInit.ts
- packages/contracts-bedrock/src/deploy-config.ts
Removes several unused deployment configuration variables and shifts a few things around. Also removes the systemConfigOwner variable by replacing it with the single unified finalSystemOwner variable.
> maint(ctb): remove unnecessary deploy vars

- op-batcher/Dockerfile
- op-chain-ops/Dockerfile
- op-node/Dockerfile
- op-proposer/Dockerfile
- ops/scripts/tag-bedrock-go-modules.sh
This adds two layers of versioning to builds. The first is providing git information to docker builds. We already pulled the information into the build via make & ldflags, but did not have it available because we did not have the `.git` folder inside docker.
The second is setting a reminder in the `tag-bedrock-go-modules.sh` script to set the version in the `op-node`, `op-batcher`, & `op-proposer`. This should try to correspond to the tag version. This might be able to be scripted, but scripting it is hard, so I chose to prompt the developer.
**Metadata**
- Fixes ENG-3081
> Version binaries

- packages/contracts-bedrock/deploy-config/devnetL1.json
- packages/contracts-bedrock/deploy-config/goerli-forked.json
- packages/contracts-bedrock/deploy-config/hardhat.json
- packages/contracts-bedrock/deploy/017-SystemConfigImpl.ts
- packages/contracts-bedrock/deploy/019-SystemDictatorInit.ts
- packages/contracts-bedrock/deploy/020-SystemDictatorSteps.ts
- packages/contracts-bedrock/src/deploy-config.ts
Makes the finalSystemOwner and controller configuration values required. By making these required, we avoid the massive warnings that come with not setting the values. Much easier than repeating the warnings everywhere.
> feat(ctb): make owner and controller required

- op-heartbeat/Makefile
- op-heartbeat/cmd/main.go
- op-heartbeat/config.go
- op-heartbeat/flags/flags.go
- op-heartbeat/metrics.go
- op-heartbeat/service.go
- op-heartbeat/service_test.go
- op-heartbeat/whitelists.go
- op-node/heartbeat/service.go
Adds implementation files for `op-heartbeat`. Will add CI integration in a separate PR. Notes:
- The implementation is pretty simple. All it does is receive heartbeats and log their fields to stdout.
- The server uses Prometheus metrics to keep track of the number of heartbeats keyed on chain ID and op-node version. This lets us see how quickly different versions of our software are adopted in production.
- To prevent DDoS attacks on our Prometheus metrics, a whitelist is used to restrict the number of chain IDs and versions that will be created as metrics.
- This package uses `op-service`, so it keeps track of HTTP metrics and support pprof automatically.
We can add additional functionality later; my goal here is to have something basic we can use to track version usage as the number of …
> op-heartbeat: Add implementation

- packages/contracts-bedrock/src/deploy-utils.ts
Adds comments to existing deploy utils.
> maint(ctb): add comments to deploy utils

- packages/contracts-bedrock/deploy/000-ProxyAdmin.ts
- packages/contracts-bedrock/deploy/001-AddressManager.ts
- packages/contracts-bedrock/deploy/002-L1StandardBridgeProxy.ts
- packages/contracts-bedrock/deploy/003-L2OutputOracleProxy.ts
- packages/contracts-bedrock/deploy/004-L1CrossDomainMessengerProxy.ts
- packages/contracts-bedrock/deploy/005-OptimismPortalProxy.ts
- packages/contracts-bedrock/deploy/006-OptimismMintableERC20FactoryProxy.ts
- packages/contracts-bedrock/deploy/007-L1ERC721BridgeProxy.ts
- packages/contracts-bedrock/deploy/008-SystemConfigProxy.ts
- packages/contracts-bedrock/deploy/009-SystemDictatorProxy.ts
- packages/contracts-bedrock/deploy/017-SystemConfigImpl.ts
Standardizes the whitespace in deployment files. I have nothing better to do right now.
> maint(ctb): standardized whitespace in deploys

- op-chain-ops/cmd/op-migrate/main.go
- op-chain-ops/ether/cli.go
- op-chain-ops/ether/migrate.go
- op-chain-ops/genesis/check.go
- op-chain-ops/genesis/db_migration.go
Instead of having multiple statedbs created,
use a single statedb and make sure that it is
only committed once. Various APIs are required
for the full migration which wrap the low level
LevelDB at various abstractions. This will ensure
that changes to the statedb are committed to disk.
> op-chain-ops: single database commit

- op-node/client/polling_test.go
- op-node/rollup/derive/calldata_source_test.go
- op-node/rollup/derive/fuzz_parsers_test.go
- op-node/rollup/sync/start_test.go
- op-node/testutils/assertions.go
Mark functions test helpers so filename and line number which call these functions will be reported instead of the test helpers.
> op-node: Mark functions test helpers

- op-wheel/cheat/cheat.go
This PR adds a `cheats` package to `op-wheel` with all the backend logic for the cheating commands: a common pattern to open the database, open a blockchain/state around that, and to modify the head block with state mutations, and several state modifications that we later expose with commands.
Second PR in a stack of 4: base, cheats-logic, engine-logic, commands-frontend:
- #4284
- #4285
- #4286
- #4287
**Tests**
This is a testing tool used in the migration testing. I'm open to testing the backend functionality in CI somewhere, but don't like to cascade the testing with testing of the testing.
**Metadata**
Fix ENG-3078
> op-wheel: geth db cheats logic

- op-wheel/engine/engine.go
- op-wheel/engine/metrics.go
This PR adds a `engine` package to `op-wheel` with all the backend logic for the engine commands: a common engine API dialing function with authentication, and functions to read or modify the engine API.
Third PR in a stack of 4: base, cheats-logic, engine-logic, commands-frontend:
- #4284
- #4285
- #4286
- #4287
**Tests**
This is a testing tool used in the migration testing. I'm open to testing the backend functionality in CI somewhere, but don't like to cascade the testing with testing of the testing.
**Metadata**
Fix #ENG-3084
> op-wheel: execution engine logic

- op-node/client/polling.go
- op-node/client/polling_test.go
- op-node/client/rpc.go
- op-node/cmd/genesis/cmd.go
- op-node/eth/account_proof.go
- op-node/p2p/gossip.go
- op-node/rollup/derive/batch.go
- op-node/sources/batching_test.go
- op-node/sources/eth_client.go
- op-node/sources/eth_client_test.go
- op-node/sources/limit.go
- op-node/sources/receipts.go
- op-node/testlog/testlog.go
- op-node/testutils/rpc_err_faker.go
Replace interface{} with any to make code more readable. Shorter lines is nice too!
Go itself [did this a while back](https://github.com/golang/go/commit/2580d0e08d5e9f979b943758d3c49877fb2324cb)
> op-node: Replace interface{} with any

- packages/contracts-bedrock/contracts/test/MerkleTrie.t.sol
Runs `yarn lint:fix` and applies the changes to the MerkleTrie.t.sol.
The diff is large, but the fact that the gas-snapshot doesn't change should be sufficient evidence that only whitespace if affected.
> ctb: Format MerkleTrie.t.sol

- packages/contracts-bedrock/src/deploy-utils.ts
Cleans up the getAdvancedContract function and removes logic that was originally meant only for use on Kovan which we don't deploy to anymore.
> maint(ctb): clean up getAdvancedContract

- packages/contracts-bedrock/contracts/L1/OptimismPortal.sol
- packages/contracts-bedrock/contracts/L1/ResourceMetering.sol
- packages/contracts-bedrock/contracts/libraries/rlp/RLPReader.sol
- packages/contracts-bedrock/contracts/libraries/trie/MerkleTrie.sol
Adds comments for all structs in the current codebase, except the SystemDictator which is going to be separately documented in the README of contracts-bedrock.
> maint(ctb): comments for structs

- op-chain-ops/genesis/check.go
- op-chain-ops/genesis/db_migration.go
- op-chain-ops/genesis/setters.go
Updaets `op-chain-ops` to correctly check for predeploy address implementations. Previously, every predeploy address in the namespace was being checked for an implementation. Only a select few of these will have implementations at genesis, so I pulled that logic out and instead iterated over the known predeploys to make sure _those_ have impementations. 
Additionally, I updated the logic to exclude certain checks for "special" predeploys like OVM ETH, the proxy admin, and the governance token.
> op-chain-ops: Fix validation logic

- op-node/rollup/derive/channel_out.go
Pre-allocate slice to reduce allocations and CPU for GC
> op-node: Preallocate slice

- packages/contracts-bedrock/contracts/L1/OptimismPortal.sol
- packages/contracts-bedrock/contracts/libraries/Constants.sol
- packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol
Moves the DEFAULT_L2_SENDER variable to Constants.sol since it's being shared by both CrossDomainMessenger and OptimismPortal.
> maint(ctb): move default sender to constants

- .changeset/sharp-colts-yawn.md
- packages/common-ts/src/base-service/base-service-v2.ts
- packages/common-ts/src/base-service/validators.ts
- packages/common-ts/src/common/logger.ts
Updates BaseServiceV2 so that logLevel is a default option to any new instantiation of BaseServiceV2. Avoids people having to include hacky code to set the log level.
> feat(cmn): make logLevel a default option

- .changeset/cool-bears-return.md
- packages/common-ts/src/base-service/base-service-v2.ts
Fixes a bug in BaseServiceV2 where options would not be parsed correctly when passed directly into the constructor rather than via the environment or command line arguments.
> fix(cmn): BaseServiceV2 options parsing bug

- op-node/p2p/discovery.go
- op-node/p2p/prepared.go
- specs/rollup-node-p2p.md
Currently `op-node`'s P2P implementation uses a key called `optimism` to store the node's chain ID and version in its ENR address. However, there's nothing specific about optimism in this key to warrant the key name.
This PR genericizes the key to `opstack`.
**Tests**
This is an RFC; happy to add tests if there is alignment on this.
This is primarily to make Bedrock more forkable / configurable. Some other ideas: make this key configurable via an op-node CLI parameter, or split into two separate ENR keys: `chainid` and `version`.
Some other potential areas for more generic naming are:
- The `optimism` key used in the [L2 genesis configuration](https://github.com/ethereum-optimism/op-geth/commit/68bfa8b473bb8770216517f007b521fab41c5afa#diff-10ff00a15ef …
> [RFC] Bedrock: rename "optimism" ENR key to "opstack"

- .circleci/config.yml
The previous steps (required for this one) had the check changed script. This means that the required build artifacts were not being created and then cause this step to fail.
> CI: Check if we should run in bedrock-echidna-run

- op-e2e/actions/l2_sequencer.go
- op-node/metrics/metrics.go
- op-node/node/server.go
- op-node/node/server_test.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/sequencer.go
- op-node/rollup/driver/state.go
- op-node/rollup/driver/state_tob_test.go
~~Reduces the wait time when sequencing new blocks. The PR referenced in the comment is already merged, and this wait was slowing down sync time on migrated nodes significantly.~~
Refactors the sequencing scheduling to be more timely, reducing the wait time and avoiding one late block from causing the next to be late again too.
Also adds `sequencer_building_diff_seconds/total` and `sequencer_sealing_seconds/total` histogram metrics to track sequencing scheduler accuracy.
Fix ENG-3088
> op-node: Improve sequencer scheduler, improve timeliness of blocks

- .gitignore
- Add lcov.info to git ignore
- these files are generated by coverage reports and can be used by editor to show where coverage exists
> feat: Add lcov.info to gitignore

- .changeset/brown-beans-hunt.md
- packages/contracts-periphery/contracts/foundry-tests/AttestationStation.t.sol
- Fix the initial check that is checking that attestation starts empty to correct value
- remove unused imports
> fix(contracts-periphery): Fix initial check in foundry test

- .changeset/nervous-moose-bake.md
- packages/common-ts/src/base-service/base-service-v2.ts
- packages/drippie-mon/src/service.ts
- packages/fault-detector/src/service.ts
- packages/message-relayer/src/service.ts
- packages/replica-healthcheck/src/service.ts
Makes BaseServiceV2 options "secret" by default. Services will have to explicitly mark options as "public" for those options to be logged and included in metrics. Much more sane than logging everything, especially for anyone using BaseServiceV2 who might not know that this happens under the hood.
> feat(cmn): BSv2 private options by default

- op-chain-ops/genesis/config.go
Add more strict checks for the deploy config so that the fee vault address recipients cannot be `address(0)`.
> op-chain-ops: better config checks

- op-service/crypto/signature.go
- op-service/go.mod
- op-service/go.sum
Adds a helper method `crypto.PrivateKeySignerFn` which generates a `bind.SignerFn` for signing transactions with a private key.
**Tests**
This is a commonly implemented method, tested in #4414.
This is needed to support #4414, given `op-service` is versioned separately.
> Add PrivateKeySignerFn method to op-service/crypto package

- .circleci/config.yml
- op-heartbeat/Dockerfile
- op-heartbeat/docker.go.work
- op-heartbeat/flags/flags.go
- op-heartbeat/service.go
- op-heartbeat/service_test.go
- Adds CI for `op-heartbeat`.
- Adds a healthz endpoint
- Cleans up tests + lint
> op-heartbeat: Add CI, clean up

- .circleci/config.yml
Runs the `check-l2` script in CI in the devnet task
> ci: run check-l2 script in ci

- op-service/log/cli.go
Fixes typo in op-service log handler setup that was causing the level filter to not be applied
> fixes op-service's log handler level filtering

- packages/contracts-periphery/contracts/foundry-tests/Transactor.t.sol
- packages/contracts-periphery/package.json
The `yarn:coverage` command is ran in CI so add
`forge coverage` to that command so the foundry tests also run.
> contracts-periphery: run foundry tests in CI

- op-chain-ops/crossdomain/withdrawal.go
Adds a method to the `Withdrawal` that turns it into a `bindings.TypesWithdrawalTransaction` that is suitable for sending via an `ethclient` when sending a transaction. This will help to deduplicate code.
> op-chain-ops: withdrawal tx helper

- op-e2e/system_test.go
The root cause is that the elements were out of order. There isn't a strong reason that the order of the arrays would be the same so & the thing we care about is that the elements match so I switch the require statement to be that. In the failing test I manually verified that the elements were the same.
Last seen in https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/11438/workflows/e524ab48-9fff-445d-9813-8a4f76046012/jobs/321725.
> Stop TestSystemMockP2P from flaking

- packages/contracts-periphery/contracts/foundry-tests/Optimist.t.sol
- packages/contracts-periphery/contracts/universal/op-nft/AttestationStation.sol
- packages/contracts-periphery/contracts/universal/op-nft/Optimist.sol
The semver should be set to `1.0.0` for production deployment of the nft contracts. This needs to
be merged before prod deployment.
> ctp: bump semver to 1.0.0 for nft contracts

- packages/contracts-bedrock/contracts/L2/L2ERC721Bridge.sol
- packages/contracts-bedrock/contracts/test/OptimismMintableERC20.t.sol
- packages/contracts-bedrock/contracts/universal/IOptimismMintableERC20.sol
- packages/contracts-bedrock/contracts/universal/IOptimismMintableERC721.sol
- packages/contracts-bedrock/contracts/universal/OptimismMintableERC20.sol
- packages/contracts-bedrock/contracts/universal/OptimismMintableERC721.sol
- packages/contracts-bedrock/contracts/universal/StandardBridge.sol
Breaks the OptimismMintableERC20 and OptimismMintableERC721 token interfaces into their own files instead of having one joint file for supported interfaces. This is in preparation for portings tests for the OptimismMintableERC721 and its factory.
> feat(ctb): break out token interfaces

- .changeset/proud-socks-sip.md
- .changeset/silver-kids-search.md
- packages/common-ts/src/common/index.ts
- packages/common-ts/src/common/provider.ts
- packages/fault-detector/src/service.ts
Updates the fault detector to wait for its L1 and L2 RPC providers using a new utility function in common-ts. This will prevent errors that users currently experience with the fault detector.
> feat(fd): have fault detector wait for providers

- codecov.yml
@trianglesphere requested this as the coverage behavior of this package seems to be erratic.
> ci: Add op-e2e to codecov's ignored paths

- packages/contracts-bedrock/package.json
Removes tsconfig.build.tsbuildinfo when running yarn:clean in the contracts package. Was causing issues with the build getting cached.
> fix(ctb): remove new build file on clean

- op-heartbeat/metrics.go
- op-heartbeat/service.go
- op-heartbeat/service_test.go
- op-node/heartbeat/service.go
This PR makes sure the op-heartbeat service doesn't allow users to spam heartbeats from the same IP, which would skew metrics towards spamming clients.
To still get insight into these large users / spammers behind the same IP, we can count events coming from the same IP, and keep track of a histogram that shows the metrics per user scale.
Based on review comment here: https://github.com/ethereum-optimism/optimism/pull/4202#discussion_r1042485949
**Metadata**
Fix ENG-3126
> op-heartbeat: handle heartbeat spamming

- .circleci/config.yml
Updates the lint check in CI. Since lint calls both lint:fix and lint:check under the hood, this will catch issues in the case that the linter and lint:fix aren't using exactly the same rules.
> fix(ci): better lint check

- op-node/p2p/gossip.go
- op-node/p2p/gossip_test.go
Add a simple util function to wrap a gossip validator function  with a guard that can recover from panics, log them, and reject the messages that caused them.
**Tests**
Added a test case to cover the new util function.
**Invariants**
Gossip validation should never unexpectedly panic, but if it does, we want to reject the message from the peer that caused the panic.
This prevents the node from falling over in case of an unexpected problem in the gossip validation pipeline.
**Metadata**
Fix ENG-3114
> op-node: guard against panics in the p2p gossip validator

- go.work
- go.work.sum
- op-batcher/go.mod
- op-batcher/go.sum
- op-bindings/go.mod
- op-bindings/go.sum
- op-chain-ops/go.mod
- op-chain-ops/go.sum
- op-e2e/geth.go
- op-e2e/go.mod
- op-e2e/go.sum
- op-e2e/setup.go
- op-e2e/system_test.go
- op-node/go.mod
- op-node/go.sum
- op-proposer/go.mod
- op-proposer/go.sum
- op-service/go.mod
- op-service/go.sum
- op-wheel/go.mod
- op-wheel/go.sum
- ops/scripts/update-op-geth.py
Test the pending gas limit configurability in https://github.com/ethereum-optimism/op-geth/pull/24
TODO: merge the op-geth PR first, and then update the geth references everywhere. For now I updated only the `go.work` for CI to run.
**Tests**
Test that blocks can be produced, and the verifier can pick up blocks, with consistent block gas limit that does not conflict with the local sequencer or verifier pending gas limit configurations.
Reducing the local pending gas limit helps prevent self-DoS when the tx pool fills up and the gas limit is extremely high (e.g. the opcraft chain)
**Metadata**
Fix ENG-2978
> op-e2e: test op-geth pending gas limit configuration

- op-bindings/predeploys/addresses_test.go
`TestL1BlockSlots` will ensure that the values in the committed storage layout matches the values that are hard coded in `op-geth`. This is important to handle because the storage layout may accidentally change in the future. This will make it very obvious is there are issues with the storage layout changing.
> op-bindings: add test coverage of the L1 fee constants

- packages/contracts-periphery/contracts/testing/helpers/CallRecorder.sol
- packages/contracts-periphery/contracts/testing/helpers/ExternalContractCompiler.sol
- packages/contracts-periphery/contracts/testing/helpers/FailingReceiver.sol
- packages/contracts-periphery/contracts/testing/helpers/Reverter.sol
- packages/contracts-periphery/contracts/testing/helpers/SimpleStorage.sol
- packages/contracts-periphery/contracts/testing/helpers/TestERC20.sol
- packages/contracts-periphery/contracts/testing/helpers/TestERC721.sol
Makes the contracts more lenient in the version
of solc that they can compile with, makes it easier to begin porting the hardhat based tests to `foundry`.
> contracts-periphery: update version on test contracts

- packages/contracts-bedrock/deploy/019-SystemDictatorInit.ts
- packages/contracts-bedrock/src/deploy-config.ts
Fixes a misconfiguration in the deploy script. The decimals value was being used when the scalar should have been used. The decimals value is now a protocol constant, so it no longer needs to be configured. Remove the value from the deploy config.
> contracts-bedrock: remove dead config, fix misconfig

- op-node/sources/batching.go
I noticed the sequencer would halt block production, spitting out the following "temp" message over and over which turned out not to be temporary at all:
```
ERROR[12-19|08:49:49.706] sequencing error      err="temp: failed to fetch L1 block info and receipts: receipt 20 has unexpected tx index 0"
```
The `20` index was curious as it is the default batch size for the batcher. After some debugging, found that the `completed` counter was increasing without being reset, which meant that, upon calling `Reset`, only the first batch would be retried, causing the remainder to be cached in an erroneous state.
This PR resets the `completed` counter to zero in the `Reset` method.
**Tests**
I tested the fix in a testnet environment, and checked that the reproducible error had gone …
> [op-node] Fix bug in batching retries

- packages/contracts-bedrock/deploy/019-SystemDictatorInit.ts
- packages/contracts-bedrock/deploy/020-SystemDictatorSteps.ts
Specifically strictly check the `SystemConfig` proxy so that the correct storage is set.
> contracts-bedrock: more strict deploy checks

- op-heartbeat/go.mod
- op-heartbeat/go.sum
Run `go mod tidy` in op-heartbeat package.
> op-heartbeat: add missing golang-lru module

- specs/assets/batch-deriv-chain.svg
- specs/assets/batch-deriv-pipeline.svg
Adds a white background to `batch-deriv-*.svg` in the specs assets.
**Rationale**
Most users view GitHub in dark mode, and the transparent backgrounds made the descriptions on these images unreadable.
> fix(specs): Add white bg to `batch-deriv-*.svg` images

- .github/mergify.yml
Removes speculative checks since they are increasing CI costs significantly and haven't provided much value. Also adds a new `multiple-reviewers` label to block auto-merge if review from multiple people is required.
> ops: Remove speculative checks, add multiple-reviewers label

- op-service/rpc/server.go
- op-service/tls/cli.go
- op-service/tls/tlsinfo.go
New features for op-service
* adds TLS configuration and https serving support
* adds TLS peer leaf certificate middleware
* adds support for custom http middleware for rpc endpoints
**Tests**
* made sure that PeerTLSMiddleware doesn't break non-https servers
* tested middleware stack manually
**Invariants**
Used by following implementation:
* https://github.com/ethereum-optimism/infrastructure-services/pull/5
> INF-23 tls and custom middleware support for op-service/rpc

- specs/derivation.md
- specs/glossary.md
- specs/rollup-node.md
https://github.com/ethereum/execution-apis/pull/327 updated the file names so we had to update our links.
> specs: Update links

- ops/check-changed/main.py
This caused unnecessary build errors.
> check-changed: Always rebuild non-PR builds

- packages/contracts-bedrock/deploy/000-ProxyAdmin.ts
- packages/contracts-bedrock/deploy/001-AddressManager.ts
- packages/contracts-bedrock/deploy/002-L1StandardBridgeProxy.ts
- packages/contracts-bedrock/deploy/003-L2OutputOracleProxy.ts
- packages/contracts-bedrock/deploy/004-L1CrossDomainMessengerProxy.ts
- packages/contracts-bedrock/deploy/005-OptimismPortalProxy.ts
- packages/contracts-bedrock/deploy/006-OptimismMintableERC20FactoryProxy.ts
- packages/contracts-bedrock/deploy/007-L1ERC721BridgeProxy.ts
- packages/contracts-bedrock/deploy/008-SystemConfigProxy.ts
- packages/contracts-bedrock/deploy/009-SystemDictatorProxy.ts
- packages/contracts-bedrock/deploy/010-L1CrossDomainMessengerImpl.ts
- packages/contracts-bedrock/deploy/011-L1StandardBridgeImpl.ts
- packages/contracts-bedrock/deploy/012-L2OutputOracleImpl.ts
- packages/contracts-bedrock/deploy/013-OptimismPortalImpl.ts
- packages/contracts-bedrock/deploy/014-OptimismMintableERC20FactoryImpl.ts
- packages/contracts-bedrock/deploy/015-L1ERC721BridgeImpl.ts
- packages/contracts-bedrock/deploy/016-PortalSenderImpl.ts
- packages/contracts-bedrock/deploy/017-SystemConfigImpl.ts
- packages/contracts-bedrock/deploy/018-SystemDictatorImpl.ts
- packages/contracts-bedrock/deploy/019-SystemDictatorInit.ts
Adds a new "setup" tag to deploy steps that can be executed ahead of the Bedrock migration. Runs everything except the SystemDictator steps.
> feat(ctb): deploy setup tag

- op-batcher/batcher/driver.go
- op-batcher/batcher/txmgr.go
- op-e2e/actions/l2_proposer.go
- op-proposer/proposer/driver.go
- op-proposer/proposer/l2_output_submitter.go
Passes the `context.Context` from the op-batcher / op-proposer into the `SignerFn`. This allows the SignerFn to make remote requests to external tx-signing services, and gives the ability for the caller to cancel those requests if needed.
**Tests**
No logic changes implemented, just passing the context through.
> [op-batcher / op-proposer] Provide context to signer function

- op-e2e/actions/blocktime_test.go
- op-e2e/actions/l2_engine.go
TestLargeL1Gaps tests the case that there is a gap between two L1 blocks which is larger than the sequencer drift.
This test has the following parameters:
L1 Block time: 4s. L2 Block time: 2s. Sequencer Drift: 32s
It generates 8 L1 blocks & 16 L2 blocks.
Then generates an L1 block that has a time delta of 48s. It then generates the 24 L2 blocks.
Then it generates 3 more L1 blocks.
At this point it can verify that the batches where properly generated.
Note: It batches submits when possible.
**Metadata**
- Fixes ENG-3135
> op-e2e: Add Large L1 gap blocktime test

- .circleci/config.yml
Failed devnet jobs will now dump op-node, op-geth, batcher, proposer, and l1 logs in distinct steps in order to make debugging easier. Also disables CCI's Docker Layer Caching, which was introducing issues. The cache sometimes gets stale, leading to situations where the tested software doesn't match the source being pulled.
> ci: Dump devnet logs on error, disable DLC

- .github/CODEOWNERS
The specs are likely to be under a lot of scrutiny in the coming weeks, and many changes will be needed. More codeowners will facilitate this.
> ci: Add more codeowners to specs

- .github/workflows/release.yml
- ops/docker/Dockerfile.packages
Adds `balance-monitor` to docker build and publish steps. 
It uses the `Dockerfile.packages` file, and GHA per @mslipper's guidance.
> ci: Add Dockerfile and build in CI

- op-chain-ops/cmd/op-migrate/main.go
- op-chain-ops/ether/migrate.go
- op-chain-ops/genesis/check.go
- op-chain-ops/genesis/db_migration.go
- op-chain-ops/genesis/layer_two.go
- op-chain-ops/genesis/layer_two_test.go
- op-chain-ops/genesis/migration/params.go
- op-chain-ops/genesis/setters.go
- packages/contracts-bedrock/tasks/check-l2.ts
- specs/predeploys.md
This PR fixes a bug in `op-chain-ops` that could cause state to become erroneously erased during the L2 migration. While testing the Goerli migration in check mode, I encountered an issue where `db.GetState` was returning null storage slots for the legacy message passer during the withdrawals portion of the migration. Upon further inspection, I discovered that we were using `db.CreateAccount` in the `setProxies` method. `db.CreateAccount` will erase the state associated with the passed-in address, so I updated `setProxies` to check if the account exists first. I also added a map of predeploys that should _not_ be touched as part of the migration process at all. At the end of the migration process, I iterate over these "untouchable" contracts and make sure that their code matches a preset …
> op-chain-ops: Fix state migration, add post-checks

- op-e2e/actions/l1_replica.go
- op-e2e/actions/l1_replica_test.go
- op-e2e/actions/l2_sequencer_test.go
- op-e2e/actions/reorg_test.go
- op-e2e/migration_test.go
- op-e2e/setup.go
- op-node/eth/types.go
- op-node/flags/flags.go
- op-node/flags/util.go
- op-node/node/client.go
- op-node/node/node.go
- op-node/service.go
- op-node/sources/batching.go
- op-node/sources/batching_test.go
- op-node/sources/eth_client.go
- op-node/sources/eth_client_test.go
- op-node/sources/l1_client.go
- op-node/sources/l2_client.go
- op-node/sources/receipts.go
- op-node/sources/types.go
PR changes:
- Add "RPC provider kind: an enum that identifies different groups of L1 RPC providers, based on the different endpoints they offer
- Add "ReceiptsFetchingMethod": an enum, and bitfield, of the different receipts fetching methods that may be available.
- Make `sources.EthClient` initialize initially available methods based on the RPC kind specified by the user, and reduce those based on RPC errors. The user can specify "any" if they want the node to figure it out by trial and error. The default is "basic", which has the current behavior, so the user is not surprised by error/warning logs in their L1 node or op-node.
- Simplify `IterativeBatchCall` so that the `[]V -> result` conversion is separate, and simplify the receipts validation function signature (no …
> op-node,op-e2e: optimize L1 receipts fetching by supporting different methods

- packages/contracts-bedrock/deploy/020-SystemDictatorSteps-1.ts
- packages/contracts-bedrock/deploy/021-SystemDictatorSteps-2.ts
- packages/contracts-bedrock/src/deploy-utils.ts
Breaks out the SystemDictator steps into two files so that the steps that get executed before the system is shut down can easily be separated from the steps that executed after the system gets spun back up. Idea here is that you would execute with the tag "steps1", wait for the legacy system to come down, migrate the L2, then execute with the tags "steps2" to complete the upgrade.
> feat(ctb): break out system dictator steps

- specs/withdrawals.md
Fixes a line in the `withdrawals.md` spec that referred to an incorrect contract.
> fix(specs): `L2WithdrawalVerifier` -> `OptimismPortal`

- op-chain-ops/crossdomain/migrate.go
Update the migrated withdrawals to be version 0 based on the new scheme that is introduced in https://github.com/ethereum-optimism/optimism/pull/4562. This is a safety measure to ensure that withdrawals cannot be double withdrawn and that ether stuck in the L1xdm cannot be stolen in the case of a withdrawal with value reverting.
> op-chain-ops: make the migrated withdrawals version 0

- op-chain-ops/genesis/config.go
- op-chain-ops/genesis/db_migration.go
- op-chain-ops/genesis/genesis.go
- op-chain-ops/genesis/testdata/test-deploy-config-full.json
- op-e2e/e2eutils/setup.go
- op-e2e/setup.go
- packages/contracts-bedrock/deploy-config/devnetL1.json
- packages/contracts-bedrock/deploy-config/goerli-forked.json
- packages/contracts-bedrock/deploy-config/goerli.json
- packages/contracts-bedrock/src/deploy-config.ts
Removes the config option for being able to set
the coinbase of the bedrock transition block.
It is now always set to the sequencer fee vault
predeploy. This is one less config option that needs to be set correctly. The coinbase is always set to the sequencer fee vault in bedrock blocks.
> bedrock: hardcode L2 genesis coinbase

- op-chain-ops/genesis/config.go
The `DeployConfig` value for the `GasPriceOracleScalar` should not be allowed to be set to 0. If it is set to 0, it would effectively make the L1 portion of the fee nothing. This isn't useful since eip1559 is enabled which required ether to be burnt with execution, meaning that free transactions are not allowed on the network.
If this value is set to 0, it is most likely a bug in the config and we do not want to lose money by charging no L1 portion of the fee.
> op-chain-ops: do not allow 0 scalar

- .changeset/odd-parents-cheer.md
- ops/docker/ci-builder/Dockerfile
Updates the version of slither in the CI builder. 
Should fix the echidna tests which were failing in CI once the docker image is updated.
> ci: Update slither version to 0.9.1

- packages/contracts-periphery/package.json
In the latest [version action](https://github.com/ethereum-optimism/optimism/commit/a17b49fafa8b0141ae45c2b979f432f2468fd7ba), `contracts-bedrock` was updated to `v0.11.1`, which broke `contracts-periphery`'s CI. Temporarily downgrades `contracts-periphery`'s `contracts-bedrock` dependency to `v0.11.0` so that it will build.
> fix(ctp): Downgrade `contracts-bedrock` dep to fix CI

- packages/data-transport-layer/package.json
- yarn.lock
Typescript type resolution here is really wierd.  TIL it doesn't match nodes resolution perfectly.   In a git submodule it would resolve to leveldb in parent before it would find a resolution in option.   This blocked me from adding optimism monorepo as submodule in gateway.
Fix: add @types package to data transport layer so it resolves right away in that package.
> fix(data transport layer): Fix typescript type resolution

- packages/contracts-bedrock/tasks/check-l2.ts
Allows the URL to be configured via CLI params for the `check-l2` task
- `--rpc-url`
Also optionally accepts a chain id via CLI and asserts that the remote chain id matches what is passed in via CLI, only if a value is passed in via CLI.
- `--chain-id`
Can also skip the very long predeploy checking at the beginning and add in some logs that ensure progress is happening with `--skip-predeploy-check true`
cc @mslipper 
Closes ENG-3171
> contracts-bedrock: check-l2 configurable url

- .circleci/config.yml
Moving away from publishing images to bedrock-goerli-development to the new oplabs-tools-artifacts GAR repo.
> Update docker publish target to oplabs-tools-artifacts/images

- op-chain-ops/genesis/check.go
- op-chain-ops/genesis/db_migration.go
Makes the extradata for the bedrock transition block a public variable. This is useful for exporting the value to be imported in other packages where assertions can be made to ensure that the extradata is correct.
When fetching the `L2OutputOracle`'s configured starting block number, the L2 block with that number can be fetched and then we can assert that it has the magic extradata.
```bash
$ cast call 0x02Ac1923480E7fd234e7F2Fd11596b9F20372374 'startingBlockNumber()(uint256)'
3855343
```
```bash
$ cast block 3855343 --json | jq -r .extraData
0x424544524f434b
```
Now check like so:
```bash
$ cast --to-ascii 0x424544524f434b
BEDROCK
```
> op-chain-ops: export bedrock transition block extradata

- .circleci/config.yml
Changes the circleci config such that `op-e2e`'s action tests run in CI.
> fix(op-e2e): Include `action` tests in CI

- .circleci/config.yml
- yarn.lock
Does what it says on the tin. First commit should fail.
> ci: Fail CI if yarn.lock changes

- op-chain-ops/genesis/check.go
- op-chain-ops/genesis/db_migration.go
- op-chain-ops/genesis/setters.go
Makes the spec for the migration process much more simple by wiping the storage of the predeploys expect for special cases. The contracts that do not have their storage wiped are:
- GovernanceToken
- WETH9
- LegacyMessagePasser
- LegacyERC20ETH
- DeployerWhitelist
> op-chain-ops: wipe predeploy storage

- op-e2e/actions/blocktime_test.go
- op-e2e/actions/l1_replica_test.go
- op-e2e/actions/reorg_test.go
- op-e2e/actions/sync_test.go
- op-e2e/e2eutils/setup.go
Adds a test to `op-e2e` for an L1 reorg that is larger than a sequence window.
**Steps**:
1. Create an L1 actor
2. Ask the L1 actor to build three sequence windows of empty blocks
2.a alice submits a transaction on l2 with an l1 origin of block # 35
2.b in block # 50, include the batch that contains the l2 block with alice's transaction as well as all other blocks before it.
3. Ask the L2 sequencer to build a chain that references these L1 blocks
4. Ask the batch submitter to submit remaining unsafe L2 blocks to L1
5. Ask the L1 to include this data
6. Rewind chain A 21 blocks
7. Ask the L1 actor to build one sequence window + 1 empty blocks on chain B
8. Ask the L1 actor to build an empty block in place of the batch submission block on chain A
9. Ask the L1 actor to create another empty …
> feat(op-e2e): Deep reorg test

- op-node/rollup/derive/batches.go
- op-node/rollup/derive/batches_test.go
- specs/derivation.md
This adds a check to the batch queue to verify that supplied batches have a timestamp that is greater than or equal to the L1 origin timestamp. The sequencer should not sequence batches like this, but it was not being enforced in the derivation process.
**Tests**
I added a unit test for this & manually confirmed that the unit test will fail if the fix is not included.
**Metadata**
- Fixes ENG-3156
> op-node: Enforce min L2 timestamp

- op-node/p2p/config.go
Adds default boot nodes. Specifiying `--bootnodes` will override them.
> op-node: Add default boot nodes

- codecov.yml
CodeCov needs some additional configuration to be useful with the monorepo. Setting checks to informational will prevent them from failing the build until we get CodeCov working properly.
> ci: Make CodeCov checks informational

- .circleci/config.yml
- op-e2e/system_tob_test.go
Disables parallel test execution so we can get to the bottom of the withdrawal test's fflakiness.
> ci: Temporarily disable parallel e2e tests

- bedrock-devnet/devnet/genesis.py
- packages/contracts-bedrock/deploy-config/devnetL1.json
Reduces the block time in devnet tests to 3s from 15. This cuts the deployed contracts test runtime down to 12m from 20m, and the genesis contracts test down from 12m to 9m.
> ci: Reduce block time in devnet tests

- packages/sdk/hardhat.config.ts
- packages/sdk/tasks/deposit-eth.ts
This allows the script to be able to be used with
test networks more easily.
Usage:
```bash
export L1_RPC=...
export PRIVATE_KEY_DEPLOYER=0x...
npx hardhat deposit-eth \
--l2-provider-url ... \
--to 0x9C822C992b56A3bd35d16A089d99AEc870eF8d37 \
--amount 0.0001 \
--network final-migration-rehearsal
```
The following transactions were created using this commit on the `final-migration-rehearsal` network:
L1 Deposit Transaction hash: 0x23f42a9d18b41bd32d90026b2324dbab64a45e942fe3897dd67a56989b940e11
L2 Withdrawing Transaction hash: 0x5b1108b61b7ec97f99c3c5c312913d465e87feaec2ab805087be55d342d5e17d
L1 Proving Withdrawal Transaction hash: 0xfe8c8beae69bdca1af35f04cfa635ea7d959abf0270f082a4ab41d680d7fe35b
L1 Finalizing Withdrawal Transaction hash: …
> sdk: allow `deposit-eth` task to work with artifacts

- .circleci/config.yml
- packages/contracts-bedrock/contracts/echidna/FuzzAddressAliasing.sol
- packages/contracts-bedrock/contracts/echidna/FuzzBurn.sol
- packages/contracts-bedrock/contracts/echidna/FuzzEncoding.sol
- packages/contracts-bedrock/contracts/echidna/FuzzHashing.sol
- packages/contracts-bedrock/contracts/echidna/FuzzOptimismPortal.sol
- packages/contracts-bedrock/contracts/echidna/FuzzResourceMetering.sol
- packages/contracts-bedrock/invariant-docs/AddressAliasing.md
- packages/contracts-bedrock/invariant-docs/Burn.md
- packages/contracts-bedrock/invariant-docs/Encoding.md
- packages/contracts-bedrock/invariant-docs/Hashing.md
- packages/contracts-bedrock/invariant-docs/L2OutputOracle.md
- packages/contracts-bedrock/invariant-docs/OptimismPortal.md
- packages/contracts-bedrock/invariant-docs/README.md
- packages/contracts-bedrock/invariant-docs/ResourceMetering.md
- packages/contracts-bedrock/invariant-docs/SystemConfig.md
- packages/contracts-bedrock/package.json
- packages/contracts-bedrock/scripts/invariant-doc-gen.ts
Adds a script to generate invariant documentation for all `forge` & `echidna` invariant tests. 
**Metadata**
fixes ENG-3106
> feat(ctb): Invariant docgen

- .changeset/orange-penguins-reply.md
- packages/contracts-bedrock/contracts/test/invariants/CrossDomainMessenger.t.sol
- packages/contracts-bedrock/invariant-docs/CrossDomainMessenger.md
- packages/contracts-bedrock/invariant-docs/README.md
Adds an actor-based invariant test for the L1 XDM requested by @smartcontracts.
**Invariant**
A call from the `OptimismPortal` to the `L1CrossDomainMessenger`'s `relayMessage` function can never revert if the proper minimum gas limits are supplied.
There are two minimum gas limits we need to worry about:
* **[OUTER]** - Minimum gas required for the call from the `OptimismPortal` to the L1 XDM's `relayMessage` function. This is found by calling the L1 XDM's `baseGas` function with the message payload + the inner min gas limit.
* **[INNER]** - Minimum gas required for the call from the L1 XDM to the `target` contract.
**Tests**
Added `invariants/CrossDomainMessenger.t.sol`
**Metadata**
Closes ENG-3172
> tests(ctb): Add invariant test for `minGasLimit`s in the L1 XDM's `relayMessage` fn

- op-batcher/batcher/txmgr.go
Since #4555, we can pass a context to the signing function for e.g. signing with a different backend. Right now the batcher's context is being early-cancelled, so fix that. 
**Tests**
Using existing tests
**Invariants**
**Metadata**
> fix: don't cancel context before passing to signer

- .circleci/config.yml
- packages/contracts-bedrock/tasks/check-l2.ts
Add additional check for the genesis magic value.
This ensures that the L2OutputOracle's starting
block number is set correctly.
> contracts-bedrock: check-l2 checks for genesis magic

- op-node/rollup/output_root.go
Cleans up the implementation of the `ComputeL2OutputRoot` function. No need for the intermediate `bytes.Buffer`.
cc @protolambda
> op-node: ComputeL2OutputRoot cleanup

- op-node/rollup/derive/channel_bank.go
- op-node/rollup/derive/frame_queue.go
- op-node/rollup/derive/pipeline.go
- specs/derivation.md
The channel-bank spec was inconsistent with the implementation and design-doc changes. And missing the frame-queue abstraction.
Fix:
- spec clarifies we prune until total_size <= MAX_CHANNEL_BANK_SIZE
- spec matches pruning/reading etc. order of design doc and implementation
- ChannelBank now drops all timed-out-frames before reading more data, not just the first.
- FrameQueue is reset properly now (and Reset signature matches now)
- FrameQueue is specified now
- Move the relevant channel-bank parts from L1 retrieval into the channel bank spec
> op-node,specs: fix framequeue reset, fix channel-bank and frame-queue specs

- packages/contracts-bedrock/tasks/check-l2.ts
The value needs to be read from the proxy, not the implementation.
> ctb: Fix check-l2 magic check

- packages/contracts-bedrock/deploy-config/goerli.json
Commits the production Goerli configuration for Bedrock.
**Metadata**
- Fixes ENG-3143
> feat(ctb): commit prod Goerli config

- .circleci/config.yml
Tag filters were not applied to docker-publish job in the release workflow so they were not kicking off on new tags.
> fixes docker-publish job not running on release workflow

- op-node/flags/p2p_flags.go
- op-node/p2p/cli/load_config.go
- op-node/p2p/cli/load_signer.go
- op-node/p2p/config.go
- op-node/p2p/gossip.go
- op-node/p2p/host.go
- op-node/p2p/host_test.go
- op-node/p2p/node.go
- op-node/p2p/prepared.go
- op-node/p2p/signer.go
- op-node/service.go
PR diff is large due to p2p-config loading that moved into its own package (to avoid import cycle). No functionality changes to the config loading, aside from new gossip config variables that map to gossipsub configurables (see [gossipsub spec](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.0.md#parameters)):
- D: Configure GossipSub topic stable mesh target count, a.k.a. desired outbound degree, number of peers to gossip to
- Dlo: Configure GossipSub topic stable mesh low watermark, a.k.a. lower bound of outbound degree
- Dhi: Configure GossipSub topic stable mesh high watermark, a.k.a. upper bound of outbound degree, additional peers will not receive gossip
- Dlazy: Configure GossipSub gossip target, a.k.a. target degree for gossip only (not …
> op-node: gossip flood-publish, cli gossip configuration

- packages/contracts-bedrock/contracts/deployment/SystemDictator.sol
- packages/contracts-bedrock/deploy/020-SystemDictatorSteps-1.ts
- packages/contracts-bedrock/deploy/021-SystemDictatorSteps-2.ts
Moves the SystemConfig upgrade/initialization logic into Step 1 of the SystemDictator contract. This means that the Sequencer is correctly able to spin up between steps 2 and 3.
> feat(ctb): set up SystemConfig in step 1

- packages/contracts/deployments/goerli/README.md
> Put a warning that this info is no longer valid

- .changeset/weak-pianos-repair.md
- ops/docker/ci-builder/Dockerfile
- ops/docker/foundry/Dockerfile
- packages/contracts-bedrock/README.md
Updates foundry to 2ff99025abade470a795724c10648c800a41025e https://github.com/foundry-rs/foundry/tree/2ff99025abade470a795724c10648c800a41025e
This update is specifically for fixing a bug with contract verification with forge. After updating to this version, contract verification just worked.
To install this version, run the command:
```bash
$ foundryup -C 2ff99025abade470a795724c10648c800a41025e
```
> deps: update foundry

- .changeset/unlucky-rats-sit.md
- packages/data-transport-layer/src/services/l1-ingestion/service.ts
Fixes a bug in the DTL that caused it to not be able to sync beyond the deposit shutoff block. This would happen because the TO block would be less than the FROM block which would cause certain providers to throw an error.
> fix(dtl): sync beyond deposit shutoff block

- op-chain-ops/crossdomain/message.go
Adds json struct tags to the `CrossDomainMessage` type. This is useful for reading and writing this type to a file. The `Data` field must be updated to a `hexutil.Bytes` in a subsequent PR.
Part of breaking up https://github.com/ethereum-optimism/optimism/pull/4539
> op-chain-ops: add in json struct tags to cdm

- op-chain-ops/crossdomain/migrate.go
- op-chain-ops/crossdomain/withdrawal.go
Use `hexutil.Bytes` in the `Withdrawal` type so that when writing and reading from JSON, it correctly serializes the data as a 0x prefixed hex string. Without this, it will some base64 looking serialization. Be sure to cast to a byte slice before doing any abi packing, otherwise it will cause errors.
Part of breaking https://github.com/ethereum-optimism/optimism/pull/4539 into smaller pieces
> op-chain-ops: `Withdrawal` type use `hexutil.Bytes`

- packages/contracts-bedrock/src/deploy-config.ts
- specs/glossary.md
Channel timeouts used to be given in seconds, now they're given in number of L1 blocks. This PR fixes two places where the old description was still present.
> Fix `channelTimeout` docs

- .changeset/rich-trains-exist.md
- packages/common-ts/src/base-service/base-service-v2.ts
This changes base service v2 to not throw an error if an unknown command argument is passed in.
why:
When we use base service v2 in tests we can't pass flags into jest such as --watch or --update because
base service v2 will throw an error
> fix: Allow unknown options in base service v2

- .changeset/good-paws-deliver.md
- l2geth/cmd/utils/flags.go
- l2geth/eth/config.go
Follows upstream by setting a default gascap for rpc
> l2geth: default gascap

- .changeset/kind-dodos-rest.md
- packages/common-ts/src/common/provider.ts
Fixes a small bug in waitForProvider where the name of the provider was being incorrectly logged.
**Metadata**
> fix(cmn): waitForProvider logging bug

- op-node/cmd/main.go
- op-node/p2p/config.go
- op-node/p2p/prepared.go
This should fix the disable p2p flag which previous caused a panic.
> op-node: Fix disable p2p

- op-e2e/actions/l2_sequencer.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/origin_selector.go
- op-node/rollup/driver/origin_selector_test.go
- op-node/rollup/driver/sequencer.go
- op-node/rollup/driver/sequencer_test.go
- op-node/rollup/driver/state.go
Subset of original #4758
As sequencer it didn't follow the safety-over-liveness priority, and ignored the sequencer conf depth to try and handle sequencer time drift.
This however is dangerous because of the recent verifier "fix" in (good fix, but incomplete):
- When the max time drift is exceeded and the next origin cannot be found, then old origin would be used, causing the batch to be dropped.
- But the sequencer still produces blocks after this, which can have later origins & include transactions again, building on top of the empty block with old origin.
This means that as a verifier you end up dropping the empty batch with old origin, causing a halt (of safe blocks) until the sequencer window forces an empty block to be created. *This already went wrong once due to a …
> op-node: ensure sequencer selects L1 origin within sequencer time drift and use conf depth util

- .dockerignore
Make docker context way smaller by ignoring node modules
> :zap: add node_modules and .vscode to dockerignore

- op-node/eth/account_proof.go
- op-node/sources/eth_client.go
The spec for `eth_getProof` says that the storage `value` is a `QUANTITY` type: https://eips.ethereum.org/EIPS/eip-1186. In geth this is [implemented](https://github.com/ethereum-optimism/op-geth/blob/optimism-history/ethclient/gethclient/gethclient.go#L76) as a `*big.Int`.
`op-node` uses a `hexutil.Bytes` value for unmarshaling responses from JSON. This expects `0x` prefixed hex values with even numbers of digits: https://cs.opensource.google/go/go/+/refs/tags/go1.19.5:src/encoding/hex/hex.go;l=94-100 (and translated to a different error [here](https://github.com/ethereum-optimism/op-geth/blob/985086bf2a5c61e76a8ce7c74ac029660751e260/common/hexutil/hexutil.go#L237-L239)). This causes the hex decoding to fail with errors like:
```
failed to fetch proof of storage slot …
```
> [op-node] Fix ReadStorageAt for 0-prefixed values

- op-heartbeat/whitelists.go
Add past versions, and some possible near future versions, to get more detailed version metrics.
> op-heartbeat: allow more versions in heartbeat service

- op-node/rollup/derive/channel_in_reader.go
Removes a duplicated word in a comment.
**Tests**
No tests as no actual code changed.
> op-node: Remove duplicated word in comment.

- specs/withdrawals.md
The spec incorrectly stated that the call was forwarded at both the proof verification call and during the finalization call. They are actually only forwarded once the finalisation call completes, so remove the mention of forwarding from the proof verification step.
> fix(spec): Withdrawal calls are not forwarded during the proof verification call

- specs/derivation.md
The process to create a new block via the engine API only returns the block and doesn't import it. So an explicit call to engine_newPayload is required to import the payload before making it canonical. The actual code performs this call ([here](https://github.com/ethereum-optimism/optimism/blob/5d4010601586a620bfdc67391162718d0dd906d0/op-node/rollup/derive/engine_update.go#L130)), but it was missed in the spec description.
Also adds the missing `exec-engine-comm` URL definition for the "Communication with the Execution Engine" link.
> fix(spec): Add missing call to engine_newPayload

- op-node/rollup/derive/attributes_queue.go
- op-node/rollup/derive/engine_queue.go
Fixes two minor typos discovered while reading through the codebase. Note that the second one is actually in a warning log so will change user visible behaviour.
> chore(op-node): Fix two typos

- .changeset/wet-files-knock.md
- packages/chain-mon/.env.example
- packages/chain-mon/package.json
- packages/chain-mon/src/index.ts
- packages/chain-mon/src/wd-mon/service.ts
Adds a new service (`wd-mon`) to the `chain-mon` package.
**Tests**
I've added no tests, but tested against the Goerli network. The functionality used is very basic.
I would like to add an integration test in a future PR.
> feat(mon): Add withdrawal monitor to chain-mon

- specs/withdrawals.md
Fixes the linter error in [CI](https://circleci.com/gh/ethereum-optimism/optimism/440180).
> fix(specs): Use alias syntax to address long lines

- packages/contracts-bedrock/.gas-snapshot
- packages/contracts-bedrock/contracts/periphery/TransferOnion.sol
- packages/contracts-bedrock/contracts/test/TransferOnion.t.sol
Adds the `TransferOnion` contract which can be used to batch send tokens. The set of transfers are committed to during contract initialization, and the token owner must approve the `TransferOnion` contract and then anybody can unwrap the commitment to the transfers.
The transfers are committed to with a hash onion. This is a simple vector commitment that must be linearly unwrapped. Each hash commits to the next hash and the very first hash is `bytes32(0)`.
> contracts-bedrock: add TransferOnion contract

- .changeset/nervous-years-explain.md
- packages/data-transport-layer/.depcheckrc
- packages/data-transport-layer/package.json
- packages/data-transport-layer/src/services/main/service.ts
- packages/fault-detector/src/helpers.ts
- packages/fault-detector/src/service.ts
- packages/fault-detector/test/helpers.spec.ts
- yarn.lock
Updates the fault detector to support Bedrock networks. Bedrock support is slightly hacky because we still also need to support the legacy system until mainnet has been upgraded to Bedrock. We will want to update the fault detector again once mainnet is upgraded to simplify the service and remove the legacy components.
Closes #4652
> feat(fd): support Bedrock networks

- packages/contracts-bedrock/deploy-config/devnetL1.json
The sequencer drift was larger than the sequencing window. This can cause reorgs. To fix I reduced the drift to 10s, which is lower than the 45 second sequencing window specified via the L1 block time and the window size.
> ci, ctb: Reduce devnet sequencer drift

- op-e2e/setup.go
- op-node/go.mod
- op-node/go.sum
- op-node/p2p/cli/load_signer.go
- op-node/p2p/gossip.go
- op-node/p2p/gossip_test.go
- op-node/p2p/signer.go
- op-node/p2p/signer_test.go
Fixes the p2p `SigningHash` function to correctly include the chainID in the resulting hash.
**Tests**
Added tests to confirm that each input to `SigningHash` affects the generated hash.
*Important*: this is a backwards incompatible change for p2p gossip. Once the sequencer is upgraded with this fix, any node that hasn't been upgraded will reject all gossip because of the difference in how signing hash is calculated. If backwards compatibility is required, we'll have to add support for accepting gossip signed with either the old or new hash and give time for users to upgrade before changing the hash used by the sequencer to sign.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3341/sherlock-067-125-chain-id-is-clobbered-in-p2p-signing-hash
> fix(op-node): Include chainID in p2p signing hash

- op-batcher/batcher/driver.go
- op-batcher/batcher/txmgr.go
- op-e2e/actions/l2_proposer.go
- op-proposer/proposer/l2_output_submitter.go
- op-service/txmgr/txmgr.go
- op-service/txmgr/txmgr_test.go
This makes the transaction manager responsible for determining the gas price. It also provides the ability to easily add a check if the gas price bump is correct or not.
This fixes the bug where the proposer fails when it redoes gas estimation. Gas re-estimation is no longer done. This is fine because we have a minimal set of different transactions that use a consistent amount of gas.
**Metadata**
- Fixes CLI-3233
> txmgr: Simplify resubmit logic and scaffolding

- packages/contracts-bedrock/contracts/libraries/Predeploys.sol
The `GovernanceToken` never had a field in the `Predeploys` contract, this commit adds it.
> contracts-bedrock: add gov token to predeploys contract

- op-chain-ops/genesis/config.go
- op-chain-ops/genesis/testdata/test-deploy-config-devnet-l1.json
- op-chain-ops/immutables/immutables.go
- op-chain-ops/immutables/immutables_test.go
- op-e2e/e2eutils/setup.go
- op-e2e/setup.go
Adds in additional sanity checks for the config validity to prevent accidental bad configurations of the L2 predeploys. Ensures that specific values are set in the immutables. Note this this makes the immutables config specific to optimism, previously it was implemented in a generic way using a map so that it could be used with other projects that are doing similar things with setting contracts in state with their immutables preset. We could turn it into a struct instead of using a map which could make it easier to use.
Tests were updated as the data in the tests failed the validation.
> op-chain-ops: more strict checks for config validity

- packages/contracts-bedrock/deploy-config/getting-started.json
- packages/contracts-bedrock/deploy-config/getting-started.ts
- packages/contracts-bedrock/hardhat.config.ts
Adds the getting-started network and configuration for the OP Stack Getting Started guide.
> feat(ctb): add getting-started network

- .changeset/orange-panthers-impress.md
- proxyd/config.go
- proxyd/go.mod
- proxyd/go.sum
- proxyd/integration_tests/rate_limit_test.go
- proxyd/integration_tests/testdata/frontend_rate_limit.toml
- proxyd/server.go
This allows us to set global limits on individual RPCs that ignore any origin/user agent exemption.
> proxyd: Add global flag to method overrides

- packages/contracts-bedrock/contracts/test/L1CrossDomainMessenger.t.sol
Use the named function arguments syntax for encoding the nonce in the L1CrossDomainMessenger tests. This reduces the cognitive overhead of ensuring that the tests
are correct. I had to spend the mental energy figuring out what the arguments were over and over again so i elimated the problem by moving to the kargs syntax.
I believe that tests should require the least amount of mental overhead as possible to confirm their correctness. This is a single commit that reduces the mental overhead of ensuring our test suite is correct.
> contracts-bedrock: use kwargs syntax for nonce versioning in tests

- packages/contracts-bedrock/contracts/libraries/Types.sol
This standardizes the solidity pragma to be `^0.8.0` for `Types`. All of the other libraries are set to this version, and it makes the code more portable for projects that want to import it. It will have no impact on the deployed bytecode.
> contracts-bedrock: fix the solc version for Types

- packages/contracts-bedrock/contracts/universal/Semver.sol
Allows contracts to import semver that are at least solidity version 0.8.0. This allows a wider range of contracts to be able to use the `Semver` contract, which doesn't need to be strictly at a higher version.
Fixes build issues in https://github.com/ethereum-optimism/optimism/pull/4879
> contracts-bedrock: relax semver solidity version

- integration-tests/hardhat.config.ts
- packages/contracts-bedrock/contracts/universal/OptimismMintableERC721.sol
Previously any solidity version greater than or equal to 0.8.15 was allowed, this updates it such that exactly 0.8.15 is allowed. This matches the style of the other contracts in the system.
> contracts-bedrock: be explicit with mintable erc721 token version

- op-node/rollup/derive/batch_queue.go
- op-node/rollup/derive/batch_queue_test.go
- specs/derivation.md
This fixes a bug in auto batch generation. If we get to the end of a sequence window without batches from the batcher, we start creating empty batches to advance the chain. Batches are generated in the range `[prev l2 block time + L2 blocktime, L1 origin time + time to following L1 block)`. In the case that the batcher is online with a conf depth and then goes offline, the L2 block time is greater than the L1 block time that is several blocks past the L1 origin and it would try to advance the L1 origin without generating at least one batch for every L1 origin. 
**Tests**
Added a regression test.
**Metadata**
- Fixes CLI-3378
> op-node: Fix invalid advance in the batch queue

- .circleci/config.yml
- specs/meta/linting.md
Since we have merged the Bedrock Go modules it seems to take longer to run the Go linter, resulting in CI failures. I suspect because every `op-...` package is linted separately, but it still compiles/analyzes the module as a whole.
This PR increases the timeout from the default 1 minute to 2 minutes, as well as updating the linting docs to reflect the exact command we use in CI.
> ci: change Go lint timeout from 1m (default) to 2m

- op-node/rollup/derive/batches.go
- op-node/rollup/derive/batches_test.go
- specs/derivation.md
Subset of original #4758.
Handle rare case when L1 block time gap is larger than the sequencer time drift  to not halt safe head.
**Tests**
See new unit tests to cover new sequencer time drift handling.
**Invariants**
- Ensure `L2 time >= L1 origin time` at all times
- Ensure max sequencer time drift is respected, but make exception to always preserve L1 Origin advancement and above invariant.
See design doc.
Fix CLI-3354
> op-node: handle when L1 time gap is larger than sequencer time drift

- packages/contracts-bedrock/scripts/slither.sh
It was looking in the wrong directory for the `build-info` file directory.
> ci: fix slither

- .changeset/soft-poets-juggle.md
A changeset was not included in the PR that added
`CrossDomainOwnable3`, so adding a changeset now.
https://github.com/ethereum-optimism/optimism/pull/4882
> contracts-bedrock: add changeset

- specs/deposits.md
It seems there is an inconsistency in the `sourceHash` calculation for the attributes deposited transactions between the spec and the actual implementation. Looking at the [implementation code](https://github.com/ethereum-optimism/optimism/blob/develop/op-node/rollup/derive/deposit_source.go#L36) the inner keccak should surround both `l1BlockHash` and `seqNumber` rather than just `l1BlockHash`.
> fix(spec): attributes deposited source hash calculation

- op-batcher/batcher/config.go
- op-batcher/batcher/driver.go
- op-batcher/batcher/txmgr.go
Currently the signer factory is called twice, once for creating the `txmgr.Config`, and once for passing to `NewTransactionManager`. The one in the `txmgr.Config` is available to the `NewTransactionManager` method, so we can clean up the `SignerFnFactory` from `batcher.Config` and remove the duplicate factory call.
**Tests**
No logic changes, just a cleanup.
> [op-batcher] Remove duplicate signer

- packages/contracts-bedrock/src/deploy-utils.ts
Adds a logline that logs the deployed contract name and address when doing a deployment. This will give better visual feedback when doing deployments.
It matches the logline that happens when a deployment is skipped.
> contracts-bedrock: deploy log

- op-chain-ops/crossdomain/precheck_test.go
Update to op-geth version changes the function signature, this commit fixes it so that the correct function signature is used.
> op-chain-ops: fix merge conflict issue

- op-node/rollup/derive/l1_block_info.go
- op-node/rollup/derive/l1_block_info_test.go
The function selector was not being checked on unmarshal, which allows for invalid block data to pass validation.
Fixes CLI-3389
> op-node: Return error when unmarshaling L1Info txs with invalid function selectors

- packages/contracts-bedrock/contracts/deployment/SystemDictator.sol
- packages/contracts-bedrock/deploy/020-SystemDictatorSteps-1.ts
- packages/contracts-bedrock/deploy/021-SystemDictatorSteps-2.ts
This reverts commit 654ea9598100dd5823645ad3b70d5e13afcf910a.
I recommend we redo this commit as another PR that ensures that the dynamic config is set at the right time
You can see that this moves the initialization of the `L2OutputOracle` back to `step5`. There is an assertion at the top of step five
```
require(dynamicConfigSet, "SystemDictator: dynamic oracle config is not yet initialized");
```
This ensures that the dynamic config is set for the `L2OutputOracle` before it is initialized.
This check was not moved to `step1`, meaning that its possible to initialize the oracle with null config
https://github.com/ethereum-optimism/optimism/pull/4940 is a start at fixing the problem
> Revert "fix(ctb): initialize L2OO in dictator step 1"

- .changeset/fifty-schools-think.md
The next time that a release is triggered, build and publish the `ci-builder` docker image. This will cause it to be used in CI for builds, meaning that we will need to update our foundry versions for local development.
This can be done with the following command:
```bash
foundryup -C edf15abd648bb96e2bcee342c1d72ec7d1066cd1
```
> ci-builder: add changeset

- op-node/chaincfg/chains.go
- op-node/cmd/main.go
- op-node/node/node.go
- op-node/rollup/types.go
- op-node/rollup/types_test.go
- Output the version as part of startup log
- Output human-readable banner describing the rollup config
- Add the `IsRegolith` check on rollup config, for the planned hardfork
**Tests**
Tested different variants of the config, and edge-cases of regolith activation.
**Metadata**
Fix CLI-3445
> op-node: regolith rollup config attribute

- op-e2e/op_geth.go
- op-e2e/op_geth_test.go
Introduce `l2_geth` test util to reduce the boiler plate code required for op-geth tests. Actual test coverage is unchanged currently but this will make it much easier to add additional tests for op-geth specific behaviour.
> op-e2e: Introduce op-geth e2e test util

- op-node/rollup/driver/sequencer.go
Small logging fix: It was logging a zeroed payload-ID instead of the new payload-ID when starting block-building.
This also adds the L2 parent block as log information, to get a better idea of what block is actually being built.
> op-node: fix stale payload-ID in sequencer log

- .changeset/weak-onions-think.md
- ops/docker/ci-builder/Dockerfile
- packages/contracts-bedrock/package.json
- yarn.lock
Updates:
- Foundry version in the ci-builder to: `8f3fca9c608d58981daaffe11e7f8076644cb753`
- `forge-std` version in `contracts-bedrock` dependencies to: `fd86115ed6aba8e234ee0fb86c12fe35eff0b2a0`
Includes two new variants of the `expectCall` cheatcode that are necessary to properly test #4954 ++ Includes a changeset for a new release of the `ci-builder` package.
> feat(ci-builder/ctb): Update foundry & `forge-std`

- op-e2e/actions/l2_sequencer.go
- op-e2e/actions/l2_sequencer_test.go
- op-node/metrics/metrics.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/pipeline.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/metered_engine.go
- op-node/rollup/driver/sequencer.go
- op-node/rollup/driver/sequencer_test.go
- op-node/rollup/driver/state.go
On Goerli we have hit an interesting sequencer edge-case:
- The sequencer conf-depth is lower than the verifier conf-depth
- The L1 reorgs with a reorg-depth in-between these
- The verifier only ever sees the good chain
- The sequencer builds an unsafe L2 block with a L1 origin that doesn't match the canonical chain
- The verifier code-path drops the batch because of the bad L1 origin (epoch) value
- The verifier code-path patiently waits for the sequencer to provide an alternative L2 batch with good origin, because the sequencing window has not elapsed yet.
- The sequencer code-path doesn't undo the unsafe L2 block with bad L1 origin, nor does the verifier code-path
This situation locks up the chain until the sequencing window elapses. To prevent this, we need the …
> op-node: handle sequencer errors with derivation-levels, reset when L1 origins are inconsistent

- .circleci/config.yml
- op-batcher/Dockerfile
- op-node/Dockerfile
- op-proposer/Dockerfile
- ops/scripts/ci-docker-tag-op-stack-release.sh
Combines the Docker build/publish jobs into one, and makes them all depend on a `hold` job that asks for approval. The `hold` step allows someone from the `release-managers` security group to approve the build before it is released. Without this step, tags created by automation tools like GitHub Actions will not be pushed.
I also added automatic release tags to each Docker build.
> ci: Combine release jobs, add release approval

- packages/contracts-periphery/contracts/foundry-tests/AttestationStation.t.sol
Because of copy paste pasta this test had relics from AssetReceiver
> fix(contracts-periphery): Fix attestation station test name

- packages/contracts-bedrock/contracts/L1/ResourceMetering.sol
Replaces a hardcoded number in `ResourceMetering`
with the syntax `1 gwei` which is easier to verify for correctness. The following cast command shows
that the number was correct.
```
$ cast --to-unit 1000000000 gwei
1
```
> contracts-bedrock: use `1 gwei` over hardcoded number

- packages/atst/src/commands/read.spec.ts
- packages/atst/src/commands/read.ts
- check to see if attestation is all whitespace
- if it's all whitespace warn user they might need --data-type option
> fix(atst): Explicitly warn user if they need to pass in a data type

- .changeset/nasty-chairs-agree.md
- packages/atst/src/cli.ts
- packages/atst/src/index.ts
- packages/atst/src/lib/encodeRawKey.ts
- packages/atst/src/lib/parseAttestationBytes.spec.ts
- packages/atst/src/lib/parseAttestationBytes.ts
- packages/atst/src/lib/readAttestation.spec.ts
- packages/atst/src/lib/stringifyAttestationBytes.ts
- was returning a string when we should return `0x${string}`
- Makes it so users have to cast it when using it with wagmi
> fix(atst): return correct typescript types for bytes

- op-batcher/batcher/channel_manager.go
When send tx failed, the frame should strip the version. fix #4937 
**Metadata**
- Fixes #4937 
- Fixes CLI-3428
> op-batcher/batcher/channel_manager: when send tx failed, the frame should strip the version

- op-e2e/setup.go
- op-node/p2p/cli/load_signer.go
- op-node/p2p/gossip_test.go
- op-node/p2p/signer.go
Both legacy and new hashes are still accepted to avoid incompatibility if other nodes upgrade before the sequencer is upgraded.
**Metadata**
- Second step for https://linear.app/optimism/issue/CLI-3341/sherlock-067-125-chain-id-is-clobbered-in-p2p-signing-hash
> op-node/p2p: Use the new block signing hash when producing gossip

- op-node/p2p/host_test.go
`TestDiscovery` timeout had been incorrectly reduced from 60 seconds to just 10 seconds as part of an attempt to fix intermittency.  That timeout is too short to pass reliably so return it to a 60 second total timeout.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3133/fix-testdiscovery-in-op-node
> op-node/p2p: Extend time out for discovery test

- op-node/cmd/stateviz/main.go
- op-node/http/http.go
- op-node/metrics/metrics.go
- op-node/node/server.go
- op-node/server/http.go
Sets reasonable timeouts on ppc, metrics and stateviz servers.
Used the default timeouts from Geth RPC since they seem reasonable and are battle-tested.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3345/sherlock-261-http-services-dont-set-timeouts
> op-node: Set timeouts on http servers

- .changeset/sixty-days-explain.md
- packages/atst/src/lib/prepareWriteAttestation.ts
- packages/atst/src/lib/prepareWriteAttestations.ts
- packages/atst/src/types/AttestationReadParams.ts
Another bug ori found
ChainId defaults to 10.  That means if using a network other than 10 user has to be explicit about chainId needlessly.
- make it so chainId defaults to undefined (aka the currently connected chain)
> fix(atst): Default chainId to undefined instead of 10

- op-e2e/actions/l2_sequencer_test.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/engine_queue_test.go
Each time we reach a new L1 origin in the EngineQueue stage, check it indicates the L2 block is non-canonical and reset if so.
**Tests**
Add tests that drive the engine queue stage and advance the L1 origin to cover each case being checked.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3405/check-l1-origin-of-unsafe-head-when-we-traverse-in-engine-queue-stage
> op-node/rollup/derive: Check origin of L2 unsafe head match new L1 origin

- .circleci/config.yml
Builds docker images for chain-mon on every push
> INF-89 adds chain-mon docker builds to circleci

- op-node/cmd/batch_decoder/fetch/fetch.go
- op-node/cmd/batch_decoder/main.go
- op-node/rollup/derive/params.go
Provides a utility for fetching batches. It downloads all transactions sent to the batch inbox & stores them for later inspection. It logs transaction hashes that do not come from the authorized senders.
**Tests**
Manually tested.
This is part of a series of patches to build out this tool to help debug batches.
**Metadata**
- Fixes CLI-3557
> op-node/cmd/batch_decoder: Fetch batches

- go.mod
- go.sum
- indexer/go.mod
- op-e2e/op_geth_test.go
- ops-bedrock/Dockerfile.l2
- packages/contracts-bedrock/deploy-config/devnetL1.json
op-e2e: Add test to reproduce eth_getLogs failure
**Tests**
**Invariants**
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3555/error-from-eth-getlogs-when-regolith-enabled
- Fixes https://linear.app/optimism/issue/CLI-3561/eth-getlogs-fails-on-pre-bedrock-blocks
> devnet: Enable Regolith from genesis when deploying the local devnet

- .circleci/config.yml
Updates CI config for hive to run the op-geth optimism branch, not the old optimism-history branch.
> hive: Update op-geth image used for hive tests

- .changeset/three-apes-study.md
- packages/fault-detector/src/service.ts
Fault detector was using L2OutputOracle.latestOutputIndex() to query the total number of outputs submitted, which was off by one. Correct function is L2OutputOracle.nextOutputIndex(). Caused crashes of the fault detector on startup if no outputs had been submitted to the L2OO yet.
> fix(fd): use correct fn for getTotalElements

- .circleci/config.yml
- op-e2e/system_tob_test.go
This gains about a 2x increase in the op-e2e test speed (16 mins -> 8 mins).
I needed to roll back a change I made to how TestMixedWithdrawalValidity was
being ran because that test did not handle the subtests being ran in parallel.
> op-e2e: Run CI in parallel

- .changeset/poor-buses-hug.md
- op-chain-ops/crossdomain/migrate.go
- op-chain-ops/crossdomain/migrate_test.go
- packages/sdk/src/cross-chain-messenger.ts
- packages/sdk/src/utils/message-utils.ts
- packages/sdk/test/utils/message-utils.spec.ts
More accurately computes the gas limit for a migrated withdrawal. This is useful to prevent the gaslimit for large transactions from going over the consensus level block gas limit. It is unlikely for a transaction to go over the block gas limit, but this is a preventative fix just in case.
Closes CLI-3336
> migration: update migrated withdrawal gas limit

- specs/deposits.md
The spec mistakenly defines the `to` field of user deposited transactions to be equal to zero when `isCreated` is `true`. While the emitted log must be enforced to be zero, the actual transaction produced by the derivation process must have `to` set to `null`.
I use the term `null` as that is what Ethereum RPCs will use, but would you like me to instead use `nil` to match up more nicely with go conventions and the geth implementation?
> fix(spec): use correct to field for contract creation deposits

- .changeset/wicked-ads-pump.md
- packages/contracts-bedrock/.env.example
- packages/contracts-bedrock/deploy/020-SystemDictatorSteps-1.ts
- packages/contracts-bedrock/deploy/021-SystemDictatorSteps-2.ts
- packages/contracts-bedrock/src/deploy-utils.ts
Facilitates deployments on Goerli and Mainnet by printing simulation page URLs.
Manually tested.
> feat(ctb): Print tenderly simulation URLs during deployment

- packages/contracts-bedrock/deploy-config/getting-started.json
Updates the getting-started network to enable Regolith from genesis.
> Enable Regolith in getting-started network

- packages/contracts-bedrock/contracts/libraries/LegacyCrossDomainUtils.sol
- packages/contracts-bedrock/contracts/test/Encoding.t.sol
- packages/contracts-bedrock/contracts/test/Hashing.t.sol
Although it may seem obvious, we were not directly testing that Bedrock's V0 hashing and encoding schemes match those of the legacy system.
**Tests**
Two tests: 
1. `testFuzz_encodeCrossDomainMessage_matchesLegacy_succeeds`
2. `testFuzz_hashCrossDomainMessageV0_matchesLegacy_succeeds`
> Directly test bedrock v0 encoding and hashing against legacy implementations

- op-e2e/system_test.go
Fixes a flaky `op-e2e` system test introduced by peer scoring. Added sequencer is likely eating bandwidth, timing out the test.
> fix(op-e2e): Flaky Peering Score Test

- specs/derivation.md
- specs/exec-engine.md
- specs/network-upgrades.md
The specs were incomplete, and lacked information about the L2 fee charging: the predeploys were defined, but the usage was not clear. This PR specifies this as part of the execution-engine spec, including the L1-cost function update implemented in regolith.
**Metadata**
Fix CLI-3550
> specs: specify fees, fee-vaults, and include L1-cost function detail of Regolith

- op-chain-ops/ether/migrate.go
- op-chain-ops/ether/migrate_test.go
This was set to the wrong boolean. `dryRun` is the opposite of `commit` which is confusing. This PR refactors to use consistent naming throughout.
> op-chain-ops: Fix dry run param

- op-batcher/batcher/channel_builder.go
- op-batcher/batcher/channel_manager.go
- op-batcher/batcher/channel_manager_test.go
- op-batcher/batcher/driver.go
- op-batcher/batcher/tx_data.go
- op-node/rollup/derive/test/random.go
- op-node/testutils/random.go
Introduces two separate types for frame data and tx data to make a clear
distinction between the two. Also prepares the batcher for future changes
when it will support sending multiple frames per tx.
**Tests**
Added a regression test to validate that requeued transactions have the same data (and don't prepend 0 version bytes) and that transaction data can be parsed correctly.
I added a random L2 block generator. Because of dependency cycles, I couldn't put it into package `op-node/testutils` since it uses a function from the `derive` package. Hence added the random generator to a new package `op-node/rollup/derive/test`, following the pattern to create testing code dependent on a package in a `.../test` sub-package.
Cleaner solution of #5050
> op-batcher: Refactor frame & tx data handling

- op-node/rollup/derive/channel_bank.go
Some important logs were being dropped, make sure to log to the logger, not the global one without handler.
> op-node: fix channel logging

- .changeset/chilled-melons-speak.md
- packages/contracts-bedrock/.env.example
- packages/contracts-bedrock/deploy/020-SystemDictatorSteps-1.ts
- packages/contracts-bedrock/deploy/021-SystemDictatorSteps-2.ts
- packages/contracts-bedrock/src/deploy-utils.ts
Allows adding an env var, `CAST_COMMANDS` which when set will print the cast command that should be run to cause the awaited action.
> feat(ctb): Optionally print cast commands during migration

- LICENSE
- README.md
Fixes one grammatical error
Updates the Discord link in the README.md file to be consistent with the Discord link within the community-hub repository's README.md file (https://github.com/ethereum-optimism/community-hub). This change improves consistency and reduces the risk of confusion for users. 
Updates License to reflect current year
**Tests**
discord-gateway.optimism.io directs to the correct webpage. 
Per my previous pull request (https://github.com/ethereum-optimism/community-hub/pull/679), discord-gateway.optimism.io is preferred.
> Fix one grammatical error, update Discord link in README.md, and update License

- packages/contracts-bedrock/deployments/goerli/L1CrossDomainMessengerProxy.json
- packages/contracts-bedrock/deployments/goerli/L1StandardBridgeProxy.json
This commit migrates the proxy artifacts for the bridge and messenger to the contracts-bedrock goerli directory. Previously they only existed in the legacy system's deployments directory but they are still in use here.
> contracts-bedrock: migrate goerli proxy deploy artifacts

- op-e2e/setup.go
- op-e2e/system_test.go
- op-node/flags/flags.go
- op-node/node/client.go
- op-node/node/config.go
- op-node/node/node.go
- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/payloads_queue.go
- op-node/rollup/derive/payloads_queue_test.go
- op-node/rollup/derive/pipeline.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/state.go
- op-node/service.go
- op-node/sources/sync_client.go
Adds an alternative backup sync method via RPC to the `op-node`.
The new CLI flag, `l2.backup-unsafe-sync-rpc`, feeds into the new `sources.L2SyncEndpointSetup`, which lives in the node config. This flag is optional- if it is not present, alternative sync will not be enabled. 
If the flag is set, a `sources.SyncClient` is initialized alongside the driver, which spawns a new event loop that the driver's state loop can communicate back and forth with in order to fetch missing blocks from a backup RPC.
**Tests**
- `op-e2e` - `TestSystemMockAltSync`
- Modified `TestPayloadsQueue` in the `op-node` to account for the `PayloadsQueue` changes.
**Metadata**
- Closes ENG-3218
> feat(op-node): Add alternative backup sync method via RPC

- op-chain-ops/cmd/check-migration/main.go
- op-chain-ops/ether/cli.go
- op-chain-ops/ether/migrate.go
- op-chain-ops/ether/precheck.go
- op-chain-ops/ether/precheck_test.go
- op-chain-ops/genesis/check.go
- op-chain-ops/genesis/db_migration.go
After some research, I discovered that we can iterate over Geth's storage in parallel as long as we don't share the state database. This PR updates the OVM ETH check script to parallelize state iteration across 64 workers. The parallelization works by partitioning storage keyspace based on the number of workers. To optimize further, I also moved the state balance checking into the main iteration loop to avoid unnecessary iteration. Note that state mutation must be done serially. Overall, this should safe about 40 minutes during the migration.
This PR was tested by running it against a mainnet data directory. The entire process took approximately one hour. As part of this testing I discovered an invalid check in `check.go`, which was verifying the wrong storage slot in the withdrawals …
> op-chain-ops: Add parallel migration

- op-node/rollup/types.go
Fixes the order of checked chain ids in error message and aims to make clear where each of the compared ids comes from. 
**Metadata**
- Fixes #4892
> Fix backwards log in op-node

- op-node/rollup/derive/engine_queue.go
- op-node/rollup/derive/engine_queue_test.go
- op-node/rollup/derive/pipeline.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/sequencer.go
- op-node/rollup/driver/state.go
Previous race-condition (code of a week ago):
- verifier code queues up payload attributes to force-insert, while syncing batches from L1 eagerly
- verifier code fails to confirm the started block building work
- sequencer tries to build alternative block, accesses the engine, which then first completes the still open work
- verifier code doesn't dequeue the payload attributes, and tries to re-apply them after sequencer finishes
- it's invalid to build a block on top of itself
This was found through logs provided by Conduit, thank you for bug-reporting!
Recently there was a PR to force-cancel building jobs unconditionally: #5065 
This PR fixes the race-condition problem by clearing the state, but introduced other problems:
- temporary errors result in force-cancellation, …
> op-node: handle sequencer during catch-up, handle when engine state invalidates attributes

- packages/contracts-bedrock/scripts/differential-testing/utils.go
Fixes minor lint issue that kept being picked up locally, but not in CI, since the small Go program used in JS isn't part of the linted modules.
```
golangci-lint run -E goimports,sqlclosecheck,bodyclose,asciicheck,misspell,errorlint --timeout 2m -e "errors.As" -e "errors.Is" ./...
```
> differential-testing: fix lint issue in diff testing

- .changeset/tricky-donkeys-lick.md
Adds changesets for several packages that need to be re-released because they were incorrectly not released due to a bug in the release process.
> fix(ci): add changesets for packages to rerelease

- op-batcher/batcher/channel_builder.go
- op-batcher/batcher/channel_builder_test.go
Fixes CLI-3648
**Context**
If the `MaxFrameSize` is configured to be greater than 0 and less than 23, unexpected behavior will occur where the channel builder will call it's channel out `OutputFrame` function, passing in the `MaxFrameSize` as the max frame size. Inside the channel out `OutputFrame` function though, a frame overhead of 23 is subtracted from the passed in max size. If this is less than 23, this operation will underflow, causing the frame to be filled to a nearly unbounded `uint64`. The `OutputFrame` function will then return an unexpected, extremely large frame.
**Solution**
This pr validates that the configured `MaxFrameSize` is **not** less than 23, erroring with a `ErrSmallMaxFrameSize`.
**Additional Info**
Another PR will properly fix the channel out …
> fix(op-batcher): MaxFrameSize Validation

- patches/@changesets+cli+2.26.0.patch
Reintroduces a patch to the changesets cli that was required for private packages to be released and tagged properly.
> fix(ci): reintroduce changesets patch

- op-proposer/proposer/l2_output_submitter.go
Logs the L2OutputOracle version and address after building a client to call it. This is generally useful information to have and future implementations of the `op-proposer` will need to function differently depending on the version to keep the software compatible with both permissioned and permissionless output proposal submission.
> op-proposer: log L2OutputOracle version + address

- op-batcher/batcher/batch_submitter.go
- op-batcher/batcher/channel_builder.go
- op-batcher/batcher/channel_builder_test.go
- op-batcher/batcher/channel_manager.go
- op-batcher/batcher/channel_manager_test.go
- op-batcher/batcher/config.go
- op-batcher/batcher/driver.go
- op-batcher/metrics/metrics.go
- op-batcher/metrics/noop.go
- op-e2e/migration_test.go
- op-e2e/setup.go
- op-node/rollup/derive/channel_out.go
- op-node/rollup/derive/l2block_util.go
- op-service/metrics/event.go
- op-service/metrics/ref_metrics.go
This PR adds metrics to the batcher. The following metrics are recorded:
* channel 
* opened
* closed
* fully submitted
* timed out
* L2 blocks loaded into queue
* L2 blocks added to channel
* batch transaction
* submitted
* success
* failed
Some metrics are implemented as simple events (like tx success), other contain many data dimensions, like `RecordL2BlocksAdded`.
Also added info logging of different stats when channels are closed. This has also long been overdue.
**Open Tasks**
Some open tasks were not done yet as to limit this PR's size.
- CLI-3642 - Some reusable components were taken from the `op-node` metrics, namely `RefMetrics` and `EventMetrics`, and copied into package `op-service/metrics`. The duplicated code should be removed in a follow-up by making the …
> Batcher Metrics

- op-chain-ops/ether/migrate.go
- op-chain-ops/ether/migrate_test.go
The error channel in the OVM_ETH migration is buffered. In rare cases, errors were written to this channel in such a way that they were not processed by the collector goroutine. This meant that errors were not being caught by the `lastErr != nil` check, and were instead triggering the total supply check below.
This error reliably reproduces when running the new TestMigrateBalancesRandomMissing test. This test generates a random state, and randomly removes an address/allowance from the witness data. It runs this 100 times per test. We didn't catch this with the other random test because it doesn't exercise the error handling codepath.
> op-chain-ops: Fix data race in error handling

- .circleci/config.yml
- packages/common-ts/.depcheckrc
- packages/common-ts/package.json
- packages/common-ts/test/metrics.spec.ts
- yarn.lock
Tests for common-ts were not being executed in CI because the command being triggered was "yarn test:coverage" and this command was a noop for common-ts. Also fixes a bug in the tests that wasn't caught by CI because of this.
**Metadata**
- Fixes #5214
> fix(ci): run tests for common-ts

- ops/docker/ci-builder/Dockerfile
- packages/contracts-bedrock/contracts/test/Bytes.t.sol
- packages/contracts-bedrock/package.json
- yarn.lock
Bumps:
`forge`: `8f3fca9c608d58981daaffe11e7f8076644cb753` -> `da2392e58bb8a7fefeba46b40c4df1afad8ccd22`
`forge-std`: `1.4.0` -> `1.5.2`
and uses the new `expectSafeMemory` cheatcode for our `Bytes.slice` memory safety test.
> chore(ctb): Bump `forge` & `forge-std`

- CONTRIBUTING.md
Adds Go to the list of dependencies in the CONTRIBUTING guide.
> maint: add Go to dependency list

- op-node/p2p/peer_gater.go
Previously a warning was logged that the peer failed to block/unblock on every attempt, even when it succeeded.  Was also missing a label for the peer ID.
**Metadata**
- https://linear.app/optimism/issue/CLI-3646/peer-scoring-not-working
**TODOs**
> op-node/p2p: Fix logging when a peer fails to be blocked or unblocked

- op-e2e/system_test.go
The gas limit must be set to 30 million to ensure that the default deposit gas market config is safe to use. This was missed when https://github.com/ethereum-optimism/optimism/pull/5233 was merged.
> op-e2e: bump gas limit so its safe

- specs/meta/devnet.md
That's the correct value, not 8546 (which is, IIRC, websocket for L1).
> fix(devnet): Updated the L2 address to 9545

- op-node/flags/flags.go
- op-node/rollup/driver/config.go
- op-node/rollup/driver/state.go
- op-node/service.go
Some OP chains are sensitive to reorg, specifically, these chains may have an upper threshold beyond which a reorg can occur. This PR comes for reorg-sensitive OP chains.
In order to prevent deep reorgs, this PR propose a new configuration parameter called `cfg.SequencerMaxSafeLag` to OP-Node. Before block generation, OP-Node will check the difference between `l2Unsafe.Number` and `l2Safe.Number`, and if the result is greater than `cfg.SequencerMaxSafeLag`, it will cancel the current block-generation plan and wait for the next ticker.
By default, this flag is disabled.
**Tests**
I have tested it manually. If you believe that additional test cases should be included, please let me know.
**Metadata**
- Resolve #5059
> op-node: delay creating blocks when safe lag exceeds limit

- op-node/rollup/derive/system_config_test.go
Adds test coverage for the system config derivation for each different type of event. It would be nice to fuzz this in the future.
Replaces https://github.com/ethereum-optimism/optimism/pull/5249
> op-node: system config derive tests

- packages/contracts-bedrock/README.md
- packages/contracts-bedrock/scripts/FeeVaultWithdrawal.s.sol
Adds a script for doing FeeVault withdrawals.
Used on goerli to generate this transaction: https://goerli-optimism.etherscan.io/tx/0x2ea5ce60e4fb3826a24611e9ae095754b170ab55e7757dc1dfe6bcd840b219bd
The command for running the script is included in the docstring
> contracts-bedrock: fee vault withdrawal script

- op-batcher/batcher/config.go
- op-batcher/batcher/driver.go
- op-e2e/actions/l2_proposer.go
- op-e2e/setup.go
- op-proposer/proposer/config.go
- op-proposer/proposer/l2_output_submitter.go
- op-proposer/proposer/utils.go
- op-service/txmgr/cli.go
- op-service/txmgr/txmgr.go
- op-service/txmgr/txmgr_test.go
This adds several flags to control the behavior of the transaction manager a bit better.
This also configures timeouts across all the op-batcher & op-proposer a bit better.
**Metadata**
- Fixes CLI-3594
**TODOs**
> txmgr: Configure timeouts better

- packages/sdk/src/cross-chain-messenger.ts
Fix linting issues in the SDK. Ran `yarn lint --fix` and committed the diff.
> sdk: fix linting

- specs/proposals.md
Small refactor of the specs to begin mention of the permissionless output proposals. Updates the specs around the `L2OutputOracle` to differentiate between v1 and v2
Closes CLI-3481
> specs: add permissionless L2OutputOracle

- bedrock-devnet/devnet/__init__.py
- packages/contracts-bedrock/deploy/000-ProxyAdmin.ts
- packages/contracts-bedrock/deploy/001-AddressManager.ts
- packages/contracts-bedrock/deploy/002-L1StandardBridgeProxy.ts
- packages/contracts-bedrock/deploy/003-L2OutputOracleProxy.ts
- packages/contracts-bedrock/deploy/004-L1CrossDomainMessengerProxy.ts
- packages/contracts-bedrock/deploy/005-OptimismPortalProxy.ts
- packages/contracts-bedrock/deploy/006-OptimismMintableERC20FactoryProxy.ts
- packages/contracts-bedrock/deploy/007-L1ERC721BridgeProxy.ts
- packages/contracts-bedrock/deploy/008-SystemConfigProxy.ts
- packages/contracts-bedrock/deploy/009-SystemDictatorProxy.ts
- packages/contracts-bedrock/deploy/010-L1CrossDomainMessengerImpl.ts
- packages/contracts-bedrock/deploy/011-L1StandardBridgeImpl.ts
- packages/contracts-bedrock/deploy/012-L2OutputOracleImpl.ts
- packages/contracts-bedrock/deploy/013-OptimismPortalImpl.ts
- packages/contracts-bedrock/deploy/014-OptimismMintableERC20FactoryImpl.ts
- packages/contracts-bedrock/deploy/015-L1ERC721BridgeImpl.ts
- packages/contracts-bedrock/deploy/016-PortalSenderImpl.ts
- packages/contracts-bedrock/deploy/017-SystemConfigImpl.ts
- packages/contracts-bedrock/deploy/018-SystemDictatorImpl.ts
- packages/contracts-bedrock/deploy/019-SystemDictatorInit.ts
- packages/contracts-bedrock/deploy/020-SystemDictatorSteps-1.ts
- packages/contracts-bedrock/deploy/021-SystemDictatorSteps-2.ts
Prepares for adding in L2 deployment scripts by adding a `l1` tag to the deploy scripts that should run on L1. Also add the tag flag to the deployment that happens in CI. The L2 contract deployments will be added in another commit. It is not a problem if the L2 contracts are deployed to L1 in a testing environment but using tags to save time and gas should be done. Also lints a few lines of code where awaits are nested, nested awaits are difficult to read.
> contracts-bedrock: add l1 deploy tag

- op-batcher/batcher/driver.go
- op-batcher/metrics/metrics.go
- op-batcher/metrics/noop.go
- op-proposer/metrics/metrics.go
- op-proposer/metrics/noop.go
- op-proposer/proposer/l2_output_submitter.go
- op-service/txmgr/metrics/noop.go
- op-service/txmgr/metrics/tx_metrics.go
- op-service/txmgr/txmgr.go
- op-service/txmgr/txmgr_test.go
- 1/n PR for #5291 
- Adding metrics for transaction manager
- Embed and initialize from `op-proposer` and `op-batcher`
- Add L1 Gas fee metrics
```
HELP op_proposer_default_txmgr_tx_fee L1 gas fee for a transaction in GWEI
op_proposer_default_txmgr_tx_fee 89488
```
**Tests**
**Invariants**
**Metadata**
**TODOs**
[RND]: …
> op-service/txmgr : add tx manager metrics

- specs/derivation.md
fix specs about finalized l2 blocks
> specs: fix finalized L2 blocks description in diagram section

- packages/contracts-bedrock/contracts/L2/L1FeeVault.sol
The docstring for `L1FeeVault` was not bumped
properly. This commit bumps the commit message.
We should have automation around this kind of thing to prevent it from happening in the future.
> contracts-bedrock: fix semver tag

- .changeset/good-clocks-relax.md
- packages/data-transport-layer/src/services/l1-ingestion/service.ts
Adds logging that will make it obvious that the shutoff block has been reached. Without this logging, it may be possible to mistake that the shutoff block has been reached because it has been set.
> data-transport-layer: better logging around shutoff block

- packages/contracts-periphery/contracts/foundry-tests/OptimistAllowlist.t.sol
- packages/contracts-periphery/contracts/universal/op-nft/OptimistAllowlist.sol
This contract will serve as the source of truth for whether someone can mint an Optimist NFT. In the next PR, will update Optimist.sol to use OptimistAllowlist to check mint eligibility.
Right now, it checks 3 signals
- attestations from our multisig (ALLOWLIST_ATTESTOR) - we've already issued ~70 of these
- attestations from the Coinbase Wallet Quest 
- attestations from the OptimistInviter contract (for people who claimed invites)
> feat(contracts-periphery): create OptimistAllowlist contract

- README.md
- docs/op-stack/README.md
- docs/op-stack/src/.vuepress/theme/components/Anchor.js
- docs/op-stack/src/docs/contribute.md
- packages/atst/README.md
Update discord invite links.
CI was breaking because some of the docs, like the readme, are being checked for uptime, to make sure it's not a dead link. The `discord-gateway.optimism.io` site is no longer used, so those links need to be updated. I also changed the `https://discord.optimism.io` in the op-stack docs, since that one still redirects to the now disabled `discord-gateway`.
> discord: update discord invite links

- op-chain-ops/cmd/rollover/main.go
- op-chain-ops/util/util.go
Adds some nice to have logging that makes it much
more obvious that the rollover scripts are working as intended. Its very important to have good introspection into what they are doing to be sure that we know
how to solve any problems that may arise.
> op-chain-ops: cleanup rollover scripts

- op-service/txmgr/metrics/noop.go
- op-service/txmgr/metrics/tx_metrics.go
- op-service/txmgr/txmgr.go
- Add metrics to track confirmed tx latency
- Add metrics to track how many time tx gas price had to be bumped beofre it got included
**Tests**
**Invariants**
**Metadata**
**TODOs**
> txmgr: add more tx metrics

- op-e2e/actions/l2_batcher_test.go
- op-e2e/actions/l2_engine.go
- op-e2e/actions/l2_engine_test.go
- op-e2e/actions/l2_sequencer_test.go
- op-program/l2/engineapi/l2_engine_api.go
- op-program/l2/engineapi/test/l2_engine_api_tests.go
Separate the op-e2e engine API implementation from the backend. The engine API will be used in the fault proof program as well with an oracle based backend.
The engine api implementation has moved to its own module since it will now be production code, not just part of the e2e infrastructure.
**Tests**
Introduced the `l2_engine_api_tests.go` file which provides a set of tests using a pluggable backend. This tests the engine API code better but also allows testing compatibility with each engine backend, reusing the same tests.  Currently the op-e2e backend is all that calls these tests.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3740/l2-execution-engine-api
**TODOs**
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be1 …
> op-e2e: Separate engine API implementation from backend

- packages/contracts-bedrock/contracts/deployment/SystemDictator.sol
- packages/contracts-bedrock/deploy-config/hardhat.json
- packages/contracts-bedrock/deploy/020-SystemDictatorSteps-1.ts
- packages/contracts-bedrock/src/deploy-utils.ts
Adds a `phase1()` methods to the MSD which consolidates the various stepN() methods into two groups.
This is the first PR in a series that will significantly reduce the number of multisig transactions which need to be executed.
I tested this primarily by running the deploy scripts locally.
```
npx hardhat deploy --tags setup,phase1,phase2
```
> fix(ctb): Update hardhat.json to fix hh deploy

- packages/contracts-bedrock/deploy/020-SystemDictatorSteps-1.ts
- packages/contracts-bedrock/src/deploy-utils.ts
1. Creates a reusable function `doOwnershipTransfer` which deduplicates the logic for transferring ownership of the 4 system contracts to the MSD.
2. Combines the `awaitCondition` call for each of those transfers into a single call at the end. This provides better support for a `multicall` based transfer, by printing out all the info required to create a batch of transactions at once. It also still supports a 'one at a time' transfer approach, as it will check all contracts before progressing.
> feat(ctb): Add doOwnershipTransfer to deploy utils

- op-service/metrics/event.go
- op-service/txmgr/metrics/noop.go
- op-service/txmgr/metrics/tx_metrics.go
- op-service/txmgr/txmgr.go
- op-service/txmgr/txmgr_test.go
Adds more metrics to the transaction manager. Also simplifies metric recording a little bit.
**TODOs**
> txmgr: Add more metrics

- .circleci/config.yml
- op-e2e/actions/l2_batcher_test.go
- op-e2e/migration_test.go
- op-e2e/op_geth_test.go
- op-e2e/system_tob_test.go
This fixes go based CI in several ways
1. Set test.parallel flag so it matches the actual amount of CPUs request
2. Add more calls to t.Parallel in op-e2e
3. Reduce the amount of blocks in TestBigL2Txs to reduce the test time.
CI Time for op-e2e goes from 16 min -> 4:30 min.
**Metadata**
- Fixes CLI-3762
> ci: Update op-e2e

- op-program/l2/engineapi/block_processor.go
- op-program/l2/engineapi/l2_engine_api.go
- op-program/l2/engineapi/test/l2_engine_api_tests.go
Make the block processing logic easier to follow and reusable by extracting it from the engine api. Besides its current usage to create blocks in the engine api it will be used to import blocks in the oracle based engine backend. Only real difference between creating and importing blocks is that when importing you commit the changes to the DB and a couple of extra verifications that the output roots all match.
**Tests**
Mostly covered by existing tests since this is just rearranging existing functionality but added a couple around verifying the gas limit wasn't changed too much.
**Metadata**
- Part of https://linear.app/optimism/issue/CLI-3741/l2-oracle-backed-execution-engine
> op-program: Extract block processing logic from engine api

- packages/contracts-periphery/config/deploy/ethereum.ts
- packages/contracts-periphery/config/deploy/goerli.ts
- packages/contracts-periphery/config/deploy/hardhat.ts
- packages/contracts-periphery/config/deploy/localhost.ts
- packages/contracts-periphery/config/deploy/mainnet.ts
- packages/contracts-periphery/config/deploy/optimism-goerli.ts
- packages/contracts-periphery/config/deploy/optimism.ts
- packages/contracts-periphery/deploy/op-nft/OptimistAllowlistImpl.ts
- packages/contracts-periphery/deploy/op-nft/OptimistAllowlistProxy.ts
- packages/contracts-periphery/deploy/op-nft/OptimistImpl.ts
- packages/contracts-periphery/deploy/op-nft/OptimistInviterImpl.ts
- packages/contracts-periphery/deploy/op-nft/OptimistProxy.ts
- packages/contracts-periphery/src/config/deploy.ts
- packages/contracts-periphery/src/helpers/setupProxyContract.ts
- Adds deploy script for OptimistAllowlistImpl
- Adds deploy script for OptimistAllowlistProxy
- Updates deploy scripts for Optimist
- Refactors some common logic into setupProxyContract (checking implementation & admin for proxy is set correctly then updating them if necessary)
Tested locally against hardhat to check.
**Overall deploy flow**
- Deploy OptimistInviterImpl
- Deploy OptimistInviterProxy
- Deploy OptimistAllowlistImpl
- Deploy OptimistAllowlistProxy
- Deploy OptimistImpl
==========> Up to this point we can just run `hardhat deploy --tags OptimistImpl`
- Manually submit transaction to OptimistProxy admin multisig to upgrade (but not initialize) implementation to the new OptimistImpl
> feat(ctp): add deploy script for OptimistAllowlist & Optimist

- op-program/cmd/main.go
- op-program/l2/db.go
- op-program/l2/db_test.go
- op-program/l2/fetcher.go
- op-program/l2/fetcher_test.go
- op-program/l2/oracle.go
Adds an implementation of `ethdb.KeyValueStore` sufficient to be used for block processing.
Also adds separate oracle method to access code by hash to support the way Geth now adds a prefix to the hash when storing new code values in the database.
Removed the context from oracle methods and stored one as a property in the fetcher implementation. This isn't the typical golang pattern but it fits better here as we'll need to support a fully synchronous, local execution mode where having a context doesn't make sense and a context isn't passed into the `ethdb.KeyValueStore` methods.
**Tests**
Tested the database adapter methods directly for low lever behaviour, as well as a backing for an op-geth statedb to ensure the database behaviour is compatible with the real code using …
> op-program: Implement oracle backed database

- op-program/l2/engine_backend.go
- op-program/l2/engine_backend_test.go
- op-program/l2/engineapi/block_processor.go
- op-program/l2/engineapi/l2_engine_api.go
- op-program/l2/engineapi/test/l2_engine_api_tests.go
- op-program/l2/oracle.go
Implements an engine API backend that utilises information from the L2 oracle.
**Tests**
Reuses the existing engine API tests to verify the integration between the engine API and backend, plus a bunch of unit tests 
**Metadata**
- Part of https://linear.app/optimism/issue/CLI-3741/l2-oracle-backed-execution-engine
**TODOs**
> op-program: Implement oracle backed engine API backend

- op-program/cmd/main.go
- op-program/cmd/main_test.go
- op-program/config/config.go
- op-program/config/config_test.go
- op-program/flags/flags.go
- op-program/l2/engine.go
- op-program/l2/engine_test.go
- op-program/l2/l2.go
Implement wrapper methods required by derive.Engine. This is pretty much just sugar over the existing backend methods, performing some additional conversions.
Adds flags to specify the l2 execution genesis and agreed l2 starting head.
Builds on #5361 
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3741/l2-oracle-backed-execution-engine
> op-program: Implement wrapper methods required by derive.Engine

- op-wheel/commands.go
- op-wheel/engine/engine.go
Implement `--allow-gaps` block building option to use with the `op-wheel engine auto` and `op-wheel engine block` commands. This allows it to behave like skipped slots on the L1 beacon chain, where the timestamp can make larger jumps in slots, while the block height still increments by 1.
cc @maurelian for L1 part of migration testing.
> op-wheel: add --allow-gaps flag to engine block building commands

- op-chain-ops/genesis/config.go
- op-chain-ops/genesis/genesis.go
- packages/contracts-bedrock/deploy-config/mainnet.json
- packages/contracts-bedrock/deploy-config/mainnet.ts
Prevent the `SystemConfig` to revert during deploy time by making the default L2 gas limit be 30 million. When the L2 gas limit is too small, it can cause issues with deposits because the deposits consume L2 gas.
> op-chain-ops: sanity check gas limit

- op-chain-ops/cmd/op-migrate/main.go
- op-chain-ops/genesis/config.go
The migration script entrypoint failed due to the
L1StartingBlockTag in the `DeployConfig` being set to `nil`. This adds a `nil` check as well as some better logging. The lower level methods for the usage of block tags are also used instead of manually accessing the values internal to the struct, this is what geth does internally.
> op-chain-ops: migrate error handling

- op-e2e/system_test.go
Small test setup fixes:
- Disable batcher to see L2 gossip effect in isolation. Adjusting the block time doesn't work well when it runs in a laggy environment.
- Increase timeouts.
- Only start sequencing after the verifiers are running, to give the verifiers a proper chance of receiving the first few payloads, instead of publishing those while the verifiers might not be fully up and running yet.
> op-e2e: fix p2p gossip flakiness

- op-node/rollup/derive/channel_bank.go
Logs when reading from a channel to match the log when it creates the channel.
> op-node: Log when reading channels

- op-batcher/metrics/metrics.go
- op-service/metrics/event.go
- op-service/txmgr/metrics/tx_metrics.go
Adds the subsystem back to event metrics.
**TODOs**
> op-service/metrics: Add subsystem to event metrics

- op-program/client/l1/client.go
- op-program/client/l1/client_test.go
- op-program/client/l1/oracle.go
- op-program/client/l2/engine_backend.go
- op-program/host/cmd/main_test.go
- op-program/host/config/config.go
- op-program/host/config/config_test.go
- op-program/host/flags/flags.go
- op-program/host/l1/fetcher.go
- op-program/host/l1/fetcher_test.go
- op-program/host/l1/l1.go
Provides an implementation of `derive.L1Fetcher` that uses data from the L1 oracle interface. Currently the only implementation of this fetches information from an L1 node but it's now done in a way that could be replaced with a pre-populated oracle for offline replay.
Adds the `--l1.head` CLI arg to the host program which sets the head block for L1 that the derivation pipeline stops processing at. This allows the fault proof program to process up to a specific "safe" L2 block rather than continuing processing until the latest L1 chain head.
**Tests**
Lots of unit tests.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3745/fetching-l1-oracle
- Fixes https://linear.app/optimism/issue/CLI-3746/oracle-backed-l1-fetcher
> op-program: Implement oracle based L1 fetcher

- op-program/client/l2/db.go
- op-program/client/l2/db_test.go
- op-program/client/l2/engine_backend.go
- op-program/client/l2/engine_backend_test.go
- op-program/client/l2/oracle.go
- op-program/host/l2/fetcher.go
- op-program/host/l2/fetcher_test.go
Modify the L2 oracle interface so that it panics if the requested data isn't available and no errors are ever returned. This fits the on-chain execution model better.
> op-program: Modify L2 oracle to not return error

- op-batcher/batcher/channel_manager.go
- op-batcher/batcher/driver.go
- op-service/txmgr/txmgr.go
Found a couple of potential nil panics. Fix.
**Tests**
No tests added. Tested that the bugs were fixed locally. Was able to reproduce running E2E tests in parallel, when testing #5398.
> [op-batcher] Bug: panics on nil access

- op-node/sources/batching.go
- op-node/sources/batching_test.go
- op-node/sources/receipts.go
Adds support to op-node's batching implementation that uses unbatched calls when batchSize == 1, to support nodes that don't support JSON-RPC batching.
An alternative implementation would be to add a new node-provider-specific receipt fetcher that avoids RPC batching. This current PR seems more compatible with other future uses of the batching implementation.
**Tests**
Added new tests.
Some node providers don't support batched JSON-RPC calls, for example AWS's [managed node offering](https://docs.aws.amazon.com/managed-blockchain/latest/ethereum-dev/ethereum-nodes.html). This PR allows running op-stack nodes using AWS as the L1 node.
**TODOs**
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7c984953&pvs=4 …
> [op-node] Add support for non-batched RPC calls when batchSize == 1

- op-e2e/actions/l2_engine_test.go
- op-program/client/l2/engine_backend.go
- op-program/client/l2/engine_backend_test.go
- op-program/client/l2/engineapi/l2_engine_api.go
- op-program/client/l2/engineapi/test/l2_engine_api_tests.go
- op-program/host/l2/fetcher.go
- op-program/host/l2/fetcher_test.go
- op-program/host/l2/l2.go
As part of importing new blocks, the engine-api checks to see if the block has already been imported. The FPP L2 code needs to ensure this doesn't trigger a request to the oracle for that block. In fetching mode that will cause it to fetch a block beyond the agreed chain head and skip execution of the block and in replay mode it will result in a panic because the block data isn't (or shouldn't be) available.
Updated the engine API to request the existing block by hash and number and the oracle backend then avoids requesting the block from the oracle if it is above the agreed l2 head starting point.
Since unknown blocks can't be requested (the oracle would panic), removed that test and a few nil checks that are no longer relevant.
Finally, updated the l2 fetcher so that it …
> op-program: Fix l2 engine API to avoid fetching L2 blocks after the agreed head

- op-node/sources/batching.go
- op-node/sources/batching_test.go
- op-node/sources/receipts.go
Reverts ethereum-optimism/optimism#5426
The change caused CI to fail here: https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/16566/workflows/c3c21446-c755-45e1-9ce9-f2914e3bcc7d/jobs/612077/steps
cc @mdehoog 
We'll look into the CI failure, but reverting for now.
> Revert "[op-node] Add support for non-batched RPC calls when batchSize == 1"

- op-e2e/actions/blocktime_test.go
Fix a flaky test by manually incrementing the nonce, instead of relying on the tx pool which may or may not present the right nonce value.
> op-e2e: fix TestLargeL1Gaps flake

- .circleci/config.yml
Our CCI usage more than doubled over the last few months. After looking at the config, we were using xlarge VMs for Docker build/publish steps as well as Slither which cost 40 credits/minute. I reduced those to values I think are more appopriate, and reduced some of our Docker instance sizes as well.
> ci: Reduce executor size

- op-e2e/actions/sync_test.go
- op-node/rollup/derive/engine_queue.go
Finalize while syncing. The last finalized L1 signal is now always retained in the engine queue, even if it does not match recently processed L1 blocks (the `finalityData` buffer). When the finalized L1 block is past the current traversed L1 origin, the engine queue will now try to verify it's on the correct chain, and finalize it. It only does so every 64 L1 blocks, based on the last attempt, to avoid frequent repeats and duplicate work.
**Tests**
Added an action test to create a finalized L1 chain, and then make the verifier sync it, and verify it finalizes even after getting a signal for data it didn't traverse to yet at the time of the signal.
**Metadata**
Fix CLI-3794
**TODOs**
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be …
> op-node: finalize while syncing

- op-node/sources/batching.go
- op-node/sources/batching_test.go
- op-node/sources/receipts.go
Redo of #5426 (reverted in #5430), with a flaky test fix. The test was flaky because there was a chance that the mocked method could be called early if the `select` didn't return due to the context being closed. The fix is to introduce an early check of the `ctx.Err()` to the `Fetch` method: https://github.com/ethereum-optimism/optimism/blob/916513af6e4d708706bcaf0d2d1ba17b03fe9910/op-node/sources/batching.go#L90-L93
Copied previous description below:
Adds support to op-node's batching implementation that uses unbatched calls when batchSize == 1, to support nodes that don't support JSON-RPC batching.
An alternative implementation would be to add a new node-provider-specific receipt fetcher that avoids RPC batching. This current PR seems more compatible with other future …
> [op-node] Add support for non-batched RPC calls when batchSize == 1 (flaky test fixed)

- op-program/client/mpt/db.go
- op-program/client/mpt/trie.go
- op-program/client/mpt/trie_test.go
Add `mpt.ReadTrie` and `mpt.WriteTrie` util funcs to load/dump Merkle Patricia Trie lists (as used in tx, receipt, and withdrawal lists in ethereum) from/to a pre-image collection.
TBD:
- These functions use panics currently, because we'd exit the program with critical error anyway if the MPT data is invalid. Do we intend to use these functions elsewhere? We may otherwise want to add the error returns still.
- The `trie.Reader` and `trie.NodeReader` functions in geth seem promising, but use some private types, do we want to change this in op-geth, to get rid of the DB shim workaround (quite hacky TBH)?
**Tests**
- Round trip some random collections of list elements.
- Empty list case
- Basic case for easy debugging
**Metadata**
Fix CLI-3827
**TODOs**
[RND]: …
> op-program: trie list pre-image read/write util funcs

- op-program/preimage/hints.go
- op-program/preimage/hints_test.go
- op-program/preimage/oracle.go
- op-program/preimage/oracle_test.go
Implement pre-image oracle communication. Follows specs in #5412 : this implementation of the raw pre-image interface can function over blocking syscalls. As well as the pre-image hints (one directional and optional, see specs)
**Tests**
Round-trip through the read/write sides, and check unexpected EOF. There's not really any strictly invalid string, other than lengths having to make sense, but since the program is trusted we don't impose limits here.
**Metadata**
Fix CLI-3825
> op-program: pre-image oracle communication

- op-program/client/l2/engine_backend_test.go
- op-program/client/l2/engineapi/l2_engine_api.go
Normally only post-merge blocks (with difficulty of 0) are allowed, but the genesis block is often configured with non-zero difficulty even for chains that are post-merge from genesis.
**Tests**
Set a non-zero difficulty in the genesis block when running tests.
**Invariants**
Still can't have any blocks other than genesis with non-zero difficulty, so the chain has to be post-merge.
> op-program: Allow genesis block to have non-zero difficulty.

- op-batcher/batcher/channel_builder_test.go
- op-e2e/op_geth.go
- op-node/eth/block_info.go
- op-node/rollup/derive/test/random.go
- op-node/sources/eth_client.go
- op-node/sources/types.go
- op-node/testutils/l1info.go
- op-program/client/l1/cache_test.go
- op-program/client/l1/client_test.go
- op-program/host/l1/fetcher_test.go
Adds a `HeaderRLP` method to `BlockInfo` to allow accessing the RLP of the block header which is required by op-program.
To support this the op-node `EthClient` now stores header data internally using the `eth.BlockInfo` interface rather than `HeaderInfo`. The `HeaderInfo` struct has been made internal to its module and is now a small wrapper over the geth `*types.Header` which adds block hash caching and the `BlockInfo` methods.  This ensures the data required to create the header RLP is available and the `types.Header` RLP serialisation can be used without introducing additional code into `op-node` that needs to be updated for hard forks.  The geth header was already being created as part of calculating the block hash when the RPC wasn't trusted so this isn't new …
> Add a HeaderRLP method to BlockInfo

- op-node/rollup/sync/start.go
fix error log content in func FindL2Heads
**Tests**
no need
**Invariants**
**Metadata**
**TODOs**
> fix: error log content in start.go

- op-node/sources/debug_client.go
- op-node/testutils/mock_debug_client.go
- op-program/client/l1/hints.go
- op-program/client/l2/hints.go
- op-program/host/cmd/main.go
- op-program/host/l1/l1.go
- op-program/host/l2/l2.go
- op-program/host/prefetcher/prefetcher.go
- op-program/host/prefetcher/prefetcher_test.go
Implements a pre-fetcher that takes in the hints from `HintReader.NextHint` and request for preimages from `OracleServer.NextPreimageRequest` and then populates the KV store by fetching required data.
Modifies the op-program main to use this fetcher and an in-memory KV store as the backing for oracle requests. This makes the fetching mode run using the same key/value requests and access as non-fetching mode would just using hints to fetch the required data on demand.
Builds on #5463 and #5465
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3747/store-oracle-content-in-key-value-store
> op-program: Populate preimage store

- .circleci/config.yml
Adds a CCI job to publish `ci-builder` into GCR rather than using changesets. Subsequent PRs will update the Dockerfiles across the monorepo to use the GCR-based `ci-builder` rather than the one on Docker hub.
To release a new version of the CI builder, push a tag that starts with `ci-builder/v`.
> ops: Move ci-builder into GCR

- op-program/preimage/hints.go
- op-program/preimage/hints_test.go
Attempt to recover the hint read stream when the NextHint callback fails
**Metadata**
- Fixes CLI-3848
> op-program: Hint reader recovery

- .circleci/config.yml
Docker context was set to the `Dockerfile` rather than the containing directory.
> ops: Fix the CI builder docker context

- op-chain-ops/cmd/withdrawals/main.go
- op-chain-ops/crossdomain/migrate.go
- op-chain-ops/crossdomain/migrate_test.go
- packages/sdk/src/utils/message-utils.ts
- packages/sdk/test/utils/message-utils.spec.ts
Clean up the script that is used to migrate legacy withdrawals.
This script is very important for testing the legacy withdrawal
migration.
A bug was introduced with #4911
which was a sherlock audit fix. This was a bug because the change
resulted in the withdrawal hashes changing, meaning that the storage
slots computed client side also changed. This resulted in breaking the
script. This commit reverts this change. The changes landing in
#5470 will cause the
buffer in the gas limit for the  migrated withdrawals to be too small,
so we can reintroduce this code behind a switch with the network.
Its not ideal that the migration code isn't going to match 1:1
with goerli but thats ok because we will be able to thoroughly
test it.
> op-chain-ops: legacy withdrawal script refactoring

- .circleci/config.yml
- .github/workflows/release.yml
- ops/docker/ci-builder/package.json
- package.json
`ci-builder` no longer uses changesets for releases. It is now built + published using CCI like our other Go packages are. This PR removes `ci-builder` from changesets, and migrates the CCI config to use the version on Google Artifact Registry.
> ci: Remove ci-builder from changesets

- op-program/Makefile
Update the build command for `op-program` to adapt to the host/client split.
Currently this isn't built in CI (only the tests) as we aren't building docker images for op-program yet. https://linear.app/optimism/issue/CLI-3838/op-program-docker-build will add that and actually use this make target.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3851/fix-op-program-make-target
> op-program: Fix op-program Makefile

- op-program/host/cmd/main.go
- op-program/host/cmd/main_test.go
- op-program/host/config/config.go
- op-program/host/config/config_test.go
- op-program/host/flags/flags.go
Update the setup code for op-program to support running in offline mode.  A `--datadir` CLI arg is added to specify the directory to use to store preimage data. If the `--l1` and `--l2` options are specified the preimages are fetched, otherwise only the pre-populated preimages are used to replay the derivation.
In-memory kv store is still supported in fetching mode if no `--datadir` is supplied because it makes testing easier (and the host part of op-program is essentially just a test harness).
**Tests**
Tests for the new CLI arg and config option. Will need to add e2e tests to cover the setup changes.
Builds on #5463, #5465 and #5452
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3748/read-only-execution-mode
> op-program: Support running in offline mode.

- op-program/host/cmd/main_test.go
- op-program/host/config/config.go
- op-program/host/config/config_test.go
- op-program/host/l2/l2.go
op-program `Config` struct now accepts a `ChainConfig` to specify the L2 chain configuration rather than a path to the L2 genesis file to load.  This avoids programmatic callers like the e2e tests from needing to write out the genesis config to a file.
Downside is it makes `main_test` more complex as it now _does_ have to write out a genesis file but that's well encapsulated.
**Tests**
Updated unit tests
Builds on #5466 
**Metadata**
- Part of https://linear.app/optimism/issue/CLI-3817/fpp-e2e-tests
> op-program: Pass a ChainConfig to the Config struct rather than a file path

- op-program/client/driver/driver.go
- op-program/client/driver/driver_test.go
- op-program/host/cmd/main.go
- op-program/host/cmd/main_test.go
- op-program/host/config/config.go
- op-program/host/config/config_test.go
- op-program/host/flags/flags.go
Adds a `--l2.blocknumber` option that the derivation will stop at and check the claim. This avoids the need to find a L1 head that includes exactly the batches required to derive the L2 block the claim is from and none beyond that.
Also found that `main_test` was getting tests interfering with each other when run in parallel. That shouldn't be possible, but something in the cli lib seems to do it so unmarking them as parallel safe.
**Tests**
Added unit tests.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3818/fpp-halt-execution-when-target-l2-block-reached
> op-program: Specify l2 block number to stop derivation at

- op-e2e/setup.go
- op-e2e/system_fpp_test.go
- op-program/host/cmd/main.go
- op-program/host/host.go
Add e2e test for FPP. Sets up a very simple chain (separate ticket opened to send some transactions) and then runs the FPP to 
Moves the `FaultProofProgram` method out of the main.go so it can be imported as a library module by the e2e tests.
Builds on #5487 
**Metadata**
- fixes https://linear.app/optimism/issue/CLI-3817/fpp-e2e-tests
> op-program: Add e2e test for FPP

- packages/contracts-bedrock/contracts/test/SafeCall.t.sol
Currently ci fails since the `to` address passed into `SafeCall` is fuzzed with the ffi interface address, resulting in the test failing. This simply adds an assumption that the `to` address is not the ffi interface contract address.
> fix(contracts-bedrock): SafeCall FFI Interface Fuzzing

- packages/sdk/src/adapters/standard-bridge.ts
This caused a firefox-specific error where, err.stack was not defined and therefore threw an uncaught exception. Since there is not a reliable way to determine the type of JSON RPC error and since we expect non standard tokens to hit this code path, we should just default to returning false whenever an error is caught in this function.
> FE-1002: supportsTokenPair should return false whenever the check catches an error

- op-program/host/host.go
- op-program/host/prefetcher/prefetcher.go
- op-program/host/prefetcher/prefetcher_test.go
- op-program/host/prefetcher/retry.go
- op-program/host/prefetcher/retry_test.go
Adds wrappers for the L1 and L2 sources to retry methods on failure using exponential backoff. There is effectively no limit to the maximum number of retries because if the prefetch fails the fault proof program will just fail, so it matches the op-node behaviour of carrying on trying.
**Tests**
Unit tests added for the retry logic.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3780/add-retry-logic-to-fetchers
> op-program: Add retrying to L1 and L2 fetchers

- op-program/host/prefetcher/prefetcher.go
- op-program/host/prefetcher/prefetcher_test.go
- op-program/preimage/iface.go
The exact same receipt RLP may result from different transactions in different blocks so ErrAlreadyExists must be handled when storing trie nodes.
**Tests**
Added unit test.
> op-program: Handle pre-images that already exist

- packages/atst/src/README.md
Changing contants to con**s**tants.
> fix(packages/atst): Typo in README.md

- op-e2e/system_fpp_test.go
- op-program/client/program.go
- op-program/host/host.go
- op-program/preimage/hints.go
- op-program/preimage/hints_test.go
Building on #5395, we separate host-client communication to use pipes rather than function calls. This lets us later run the client  on a separate execution environment.
To avoid Oracle requests from racing ahead of a hint prefetch, hint writes now block until a prefetch has completed. This is done by making the hints pipe bidirectional.
**Metadata**
- Fixes CLI-3753
> op-program: host-client interaction via I/O pipes

- .circleci/config.yml
- packages/atst/src/lib/getEvents.spec.ts
A test was flaky because it's using public endpoint for goerli.
This is a low value test so rather than waste time setting up anvil to run with a alchemy key I just quickly disabled it
> fix(ci): Disable flaky atst test

- op-program/host/host.go
- op-program/host/kvstore/local.go
- op-program/host/kvstore/local_test.go
- op-program/host/kvstore/splitter.go
- op-program/host/kvstore/splitter_test.go
- op-program/preimage/iface.go
Adds a separate kvstore implementation to allow the host to serve local config via type 1 keys without having to add them to the global KV store.
The read side of this in the client program will come as part of https://linear.app/optimism/issue/CLI-3751/oracle-based-bootstrap 
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3850/fpp-separate-global-and-local-kv-lookups
> op-program: Add separate keystore for local keys

- .changeset/rare-moose-itch.md
- op-chain-ops/cmd/check-migration/main.go
- op-chain-ops/cmd/op-migrate/main.go
- op-chain-ops/cmd/withdrawals/main.go
- op-chain-ops/crossdomain/migrate.go
- op-chain-ops/crossdomain/migrate_test.go
- op-chain-ops/genesis/check.go
- op-chain-ops/genesis/db_migration.go
- packages/sdk/src/cross-chain-messenger.ts
- packages/sdk/src/utils/message-utils.ts
- packages/sdk/test/utils/message-utils.spec.ts
Updates the gas limit in the migrated withdrawals codepath
to ensure that enough gas is used. This is required after https://github.com/ethereum-optimism/optimism/pull/5470
is merged
**Tests**
There is test coverage here that prevents a regression. We will need to run this tooling as part of the migration rehearsals to be super sure.
Closes CLI-3856
> fix: withdrawal gas limit

- proxyd/go.mod
- proxyd/go.sum
- proxyd/pkg/avg-sliding-window/sliding.go
- proxyd/pkg/avg-sliding-window/sliding_test.go
This change introduces a sliding window package to proxyd.  This package will be used to collect dynamic values from health checks to determine is a backend is correctly serving traffic. 
The sliding window support float64 metrics and can be used to calculate rolling average (useful for latency) or rolling sum (useful for success/error rates).
**Tests**
Unit tests provided for the package. It inspects the internal values as well the external expected results after clocked operations.
**Invariants**
n/a
This change is part of the Consensus Aware RPC Proxy: https://www.notion.so/oplabs/Consensus-Aware-RPC-Proxy-0138e029af814e4cbca2740c7888e02d
**Metadata**
- Fixes https://linear.app/optimism/issue/INF-148/sliding-avg-window
**TODOs**
[RND]: …
> proxyd: sliding window

- op-program/host/cmd/main_test.go
- op-program/host/config/chaincfg.go
- op-program/host/config/config.go
- op-program/host/flags/flags.go
The op-goerli chain config is now automatically provided when specifying `--network=goerli`.  The OP Goerli config has previously just been embedded in the bootstrap database so has to be defined in this PR.
**Tests**
Updated CLI and config tests.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3873/fpp-make-goerli-chain-config-available
> op-program: Embed goerli L2 chain config

- op-node/chaincfg/chains.go
- op-program/host/cmd/main_test.go
Remove beta-1 config. `--network=beta-1` is no longer supported as the network has been shut down.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3887/remove-beta-1-network-definition
**TODOs**
> op-node: Remove beta-1 config

- op-program/client/program.go
- op-program/host/cmd/main.go
- op-program/host/host.go
Now that the op client bootstraps via the oracle we don't need to pass any command line args to it.
**Metadata**
- Part of https://linear.app/optimism/issue/CLI-3890/fpp-dangerous-exec-command-warning
> op-program: Do not pass args to detached client program

- proxyd/backend.go
- proxyd/consensus_poller.go
- proxyd/integration_tests/consensus_test.go
- proxyd/integration_tests/testdata/consensus_responses.yml
- proxyd/pkg/avg-sliding-window/sliding.go
This change
* integrates the sliding window into the proxyd healthchecks
* add two more checks for backend consensus state: minimum peer count and node syncing
**Tests**
Modified current tests to comply with new checks.
**Invariants**
n/a
* Sliding window: https://github.com/ethereum-optimism/optimism/pull/5531
* This change is part of the Consensus Aware RPC Proxy: https://www.notion.so/oplabs/Consensus-Aware-RPC-Proxy-0138e029af814e4cbca2740c7888e02d
**Metadata**
- Fixes https://linear.app/optimism/issue/INF-147/health-checks
**TODOs**
> proxyd: use health metrics slide window

- op-node/eth/ssz.go
- op-program/Makefile
- op-program/client/cmd/main.go
Adds an entry point specifically for the fault proof program and updates the makefile to build the host and client. Also always builds a MIPs version of the client binary suitable for execution inside cannon.
Note the change in `ssz.go` to "fix" 32bit compatibility.  It may be better to just error when `ExtraData` is longer than 32 bytes given it's defined as a List with max length 32 bytes but there's a test specifically checking we can marshal a value longer than that.
**Metadata**
- https://linear.app/optimism/issue/CLI-3878/fpp-create-client-executable
> op-program: Build op-program client binary

- proxyd/backend.go
- proxyd/integration_tests/consensus_test.go
- proxyd/integration_tests/testdata/consensus.toml
- proxyd/integration_tests/testdata/consensus_responses.yml
This change makes the background act as a load balancing using the consensus group as targets.
We aim to get a uniform random distribution between healthy nodes, and use degraded nodes as a fallback.
The same retry mechanism applies - meaning if a supposed host can't serve the request, the backend group still will try the next candidate.
**Tests**
Modified current tests to comply with new behavior.
**Invariants**
n/a
* This change is part of the Consensus Aware RPC Proxy: https://www.notion.so/oplabs/Consensus-Aware-RPC-Proxy-0138e029af814e4cbca2740c7888e02d
**Metadata**
- Fixes https://linear.app/optimism/issue/INF-131/round-robin-load-balancing
**TODOs**
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7 …
> proxyd: round-robin load balancing for consensus group

- op-e2e/build_helper.go
- op-e2e/system_fpp_test.go
- op-program/host/cmd/main.go
- op-program/host/cmd/main_test.go
- op-program/host/config/config.go
- op-program/host/flags/flags.go
- op-program/host/host.go
Require the user to specify the client program to run as an executable when using detached mode. Removes the env var approach to toggling between the host and client executables.
This makes the host program much more similar to the actual VM which executes an arbitrary program and means that it is executing the actual client executable rather than calling it programatically.
Downside is that the e2e test now needs to build the client program executable so it can execute it. This is done by executing `make` from the e2e test which isn't particularly pleasant. It does mean the test remains completely standalone without relying on the user compiling the executable before running it though.
**Tests**
Updated existing tests.
Builds on #5546 
**Metadata** …
> op-program: Specify client program to run as an executable

- specs/deposits.md
The RLP order in the specs was not consistent with the code.
**Metadata**
- Fixes #5558
**TODOs**
> fix: deposited tx type RLP encoding specs

- .changeset/config.json
- .github/workflows/release.yml
- Add concurrency to prevent corner case of a race condition with releases where the second one happens first
- Change base branch to master
- add a comment
The github changeset action was already configured to work correctly outside of the base branch
> feat: One branch changesets

- packages/contracts-bedrock/tasks/check-l2.ts
Optimizes the `check-l2` `checkPredeploys` task by using ethers' `JsonRpcBatchProvider` for the L2 provider. Previously, this check involved 4096 separate requests.
Reduces the mean `check-l2` time on an M1 Max with a local devnet by `68.8%`.
**Metadata**
Closes CLI-3672
> feat(ctb): Optimize `check-l2.ts`

- op-e2e/system_fpp_test.go
- op-program/host/cmd/main.go
- op-program/host/cmd/main_test.go
- op-program/host/config/config.go
- op-program/host/config/config_test.go
- op-program/host/flags/flags.go
- op-program/host/host.go
- op-program/host/host_test.go
- op-program/preimage/hints.go
- op-program/preimage/oracle.go
Adds a server mode to the op-program host so that it inits the prefetchers and key-value store but doesn't run the actual fault proof program. Instead it listens for preimage hints and requests via additional file handles using the same protocol as the fault proof client does.
This is designed so that the FPVM can remain completely agnostic to the program it runs, it simply forwards any preimage requests from the program to the FPP host in server mode.  In on-chain mode the FPVM would ignore all hints and retrieve pre-images from the oracle contracts - this just allows running the off-chain emulation in MIPS mode to create the full trace.
**Tests**
Added a test specifically for server mode and unit tests around the new config and CLI args.
Builds on …
> op-program: Add server mode

- README.md
Updates the README to better conform to the language we've been using. Optimism is not a blockchain, but OP Mainnet is.
> maint: update README to fix Optimism wording

- op-batcher/Dockerfile
- op-chain-ops/Dockerfile
- op-exporter/Dockerfile
- op-node/Dockerfile
- op-program/Dockerfile
- op-proposer/Dockerfile
- op-wheel/Dockerfile
- ops-bedrock/Dockerfile.stateviz
Update docker files to use `golang:1.19.9-alpine3.16` instead of `golang:1.19.0-alpine3.15` as there's a bug in the MIPS compiler in 1.19.0 (https://github.com/golang/go/issues/54991) which causes it to fail with the latest op-geth changes.  There isn't an `alpine3.15` version with the updated golang compiler so updating from `alpine:3.15` to alpine:3.16` for the images as well to be consistent with what we compile on.
**Metadata**
- Required for https://linear.app/optimism/issue/CLI-3867/update-op-geth-to-upstream-1116-release and https://github.com/ethereum-optimism/optimism/pull/5514
**TODOs**
> Update docker files to use golang:1.19.9 and alpine3.16

- op-chain-ops/cmd/check-migration-quick/main.go
Adds a new tool that can be used as part of the migration that checks a minimal amount of information to ensure that the database migration was successful. It checks the extradata in the block header for the bedrock magic and errors if its not found. It will log information about the block header as well.
Closes CLI-3915
> op-chain-ops: check-migration-quick

- packages/contracts-bedrock/scripts/differential-testing/differential-testing.go
For whatever reason the contract test op-geth version got overridden so we need to update it here.
**Metadata**
- Fixes CLI-3916
> Update differential testing script to geth 1.11.6

- ops-bedrock/docker-compose.yml
> ops-bedrock: Remove unused OFFLINE_GAS_ESTIMATOR envar

- op-batcher/flags/flags.go
- op-proposer/flags/flags.go
- op-service/txmgr/cli.go
This makes `op-rpc` flags optional in the proposer.
This also removes legacy flags from the txmgr (they are still retained in the batcher/proposer).
> op-proposer,txmgr: Cleanup flags

- ops/check-changed/main.py
Add go.mod and go.sum to rebuild all patterns.
Any new go code winds up using these dependency definitions by default and they don't change often so it's safer to rebuild everything when they change to avoid surprises. For example the last op-geth update let a compile error slip through in contract differential testing (https://github.com/ethereum-optimism/optimism/pull/5588).
> ci: Add go.mod and go.sum to rebuild all patterns

- op-program/host/prefetcher/retry.go
Tiny tweak to logging so we know whether an error came from L1 or L2.
> op-program: Improve logging to differentiate between L1 and L2 fetch errors

- packages/contracts-bedrock/deploy-config/mainnet.ts
Updates the `mainnet.ts` deploy-config to re-export the object defined in `mainnet.json` to de-duplicate values ~~and re-define values inline~~.
**Metadata**
- Fixes CLI-3913
> fix: Re-export json in typescript deploy-configs

- op-challenger/challenger/config.go
Building off #5568, this PR introduces new changes to the `op-challenger` service.
The `op-challenger` is a naive, honest challenge agent that can be run as a standalone service for permissionless output proposal validation.
In the initial iteration of PoPs, only a permissioned set of challenge agents can dispute outputs as part of the **Attestation Dispute Game**. But once Fault Dispute Games are implemented, disputing outputs will be permissionless.
This PR adds configuration logic to the challenger service, as similar as possible to the `op-proposer` and other op-stack services.
Future PRs will introduce L2OutputOracle event listeners, DisputeGameFactory creation, and DisputeGame responses.
Fixes CLI-3940
> feat(pops): Challenger Config Logic

- op-challenger/metrics/metrics.go
- op-challenger/metrics/noop.go
This PR adds metrics to the challenger service.
Challenger metrics is nearly identical to the proposer service, with the following additional endpoints. (More can be added in future prs, but these are the core data series we should collect to track the challenger service).
```go
RecordValidOutput(l2ref eth.L2BlockRef)
RecordInvalidOutput(l2ref eth.L2BlockRef)
RecordOutputChallenged(l2ref eth.L2BlockRef)
```
Building off #5568, this PR introduces new changes to the `op-challenger` service.
The `op-challenger` is a naive, honest challenge agent that can be run as a standalone service for permissionless output proposal validation.
In the initial iteration of PoPs, only a permissioned set of challenge agents can dispute outputs as part of the **Attestation Dispute Game**. But once Fault …
> feat(pops): Challenger Metrics

- op-proposer/metrics/metrics.go
Quick fix for the `op-proposer` `metrics.go` to change the `Info` and `Up` fields to be unexported following @trianglesphere's comment on the `op-challenger` metrics here: https://github.com/ethereum-optimism/optimism/pull/5604#discussion_r1185337831.
> fix(op-proposer): Make Info and Up Fields Unexported

- op-batcher/metrics/metrics.go
Quick fix for the `op-batcher` `metrics.go` to change fields to be un-exported.
> fix(op-batcher): Unexport Metrics Fields

- op-e2e/system_test.go
Don't rely on timing for the L2 sequencer reorg in TestMissingBatchE2E.
**Metadata**
- Fixes CLI-2998
> op-e2e: wait for observed seq reorg in TestMissingBatchE2E

- .circleci/config.yml
- op-program/Makefile
- op-program/verify/cmd/goerli.go
Schedules a job in CI ever 4 hours to verify a segment of the Goerli chain with the fault proof program.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3891/fpp-create-goerli-verification-ci-job
> op-program: Setup CI job to periodically verify goerli outputs

- .circleci/config.yml
- Makefile
Moves the bedrock markdown link check to a daily scheduled job rather than being run on every PR. This should make it less likely that we'll get blocked for spamming sites with suspicious looking requests and will at least reduce the noise on PRs if we do.
Slack notification of failures is going to the new `notify-link-check` channel.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3912/move-link-checking-to-a-scheduled-job
> ci: Change bedrock link checker to run nightly instead of on every PR

- proxyd/rewriter.go
- proxyd/rewriter_test.go
Block numbers are sometimes hashes, and the marshalling decides based on the contents.  We need to support accepting `BlockNumberOrHash` in tag rewrites.
Example request:
```
{"auth":"none","body":"{\"jsonrpc\":\"2.0\",\"id\":12,\"method\":\"eth_getStorageAt\",\"params\":[\"0xae851f927ee40de99aabb7461c00f9622ab91d60\",\"0x65a7ed542fb37fe237fdfbdd70b31598523fe5b32879e307bae27a0bd9581c08\",\"0x1c4840bcb3de3ac403c0075b46c2c47d4396c5b624b6e1b2874ec04e8879b483\"]}","lvl":"info","msg":"Raw RPC request","req_id":"06d2e2e291ce6528958c","t":"2023-05-04T21:45:24.548498655Z"}
```
**Tests**
Add new test to cover this code path
**Invariants**
n/a
This is part of the project Consensus Aware RPC Proxy: https://www.notion.so/oplabs/Consensus-Aware-RPC-Proxy-0138e029a …
> proxyd/fix: rewrite should support BlockNumberOrHash

- proxyd/backend.go
- proxyd/config.go
- proxyd/consensus_poller.go
- proxyd/example.config.toml
- proxyd/proxyd.go
Alchemy does not support `net_peerCount`, so we should skip this particular check.  This change adds the ability to skip peer count check per backend.
**Tests**
Manual
**Invariants**
n/a
**Fixes**
- INF-197
**TODOs**
> proxyd: skip peer count config per backend

- .changeset/tough-flies-fetch.md
- packages/sdk/src/cross-chain-messenger.ts
- We saw 2 users of the sdk run into issues where they failed to set bedrock true and the error message wasn't very helpful
- add a console.warn if bedrock is false
- in future version of sdk we can make bedrock the default
> feat(sdk): Add a bedrock warning

- Makefile
It regularly rejects requests from CI due to DoS prevention even though the link is valid.
> ci: Exclude explorer.optimism.io from link checker.

- packages/contracts-bedrock/contracts/dispute/IBondManager.sol
- packages/contracts-bedrock/contracts/dispute/IDisputeGame.sol
- packages/contracts-bedrock/contracts/dispute/IInitializable.sol
- packages/contracts-bedrock/contracts/dispute/IVersioned.sol
- packages/contracts-bedrock/contracts/libraries/DisputeTypes.sol
Following the iterative introduction of the `op-challenger`, we introduce dispute game contracts iteratively in a `contracts-bedrock/contracts/dispute` directory. This PR adds a few initial interfaces and types.
> feat(pops): Clobbered pops/dispute-game-contracts, seaport-style

- op-node/chaincfg/chains.go
As per migration discussion today, this introduces a stubbed out `Mainnet` chain config so day-off in-place diff is reduced.
> feat(op-node): Stub Mainnet Chain Config

- packages/sdk/src/utils/message-utils.ts
Updates the arithmetic to use bignumber to ensure there are no overflows or loss of precision
> message-utils: use BigNumber

- packages/sdk/src/utils/message-utils.ts
Updates the `migratedWithdrawalGasLimit` function in the SDK's `message-utils.ts` to mimic the new behavior of `MigrateWithdrawalGasLimit` in #5648.
**Metadata**
Closes CLI-3970
> feat(sdk): Update `message-utils` to mimic `MigrateWithdrawalGasLimit`

- proxyd/config.go
- proxyd/consensus_poller.go
- proxyd/example.config.toml
- proxyd/integration_tests/consensus_test.go
- proxyd/integration_tests/testdata/consensus.toml
- proxyd/proxyd.go
Add a configurable limit to the maximum number of blocks a backend is allowed to lag behind.
When a backend is lagging too far, it is ignored from the consensus.
**Tests**
Integration tests + manual
**Invariants**
n/a
**Metadata**
- Fixes INF-201
**TODOs**
> feat(proxyd): add limit to consensus block lag

- proxyd/consensus_poller.go
- proxyd/metrics.go
This change adds the following consensus metrics:
* Consensus group count
* Ability to see which backends are currently banned (0/1 gauge per backend)
* Peer count per backend
* Sync status per backend
* Update delay (ms) per backend
**Tests**
Deployed to dev and checked in Grafana dashboard
**Invariants**
n/a
**Metadata**
- Fixes INF-204
**TODOs**
> feat(proxyd): moar consensus metrics

- op-program/verify/cmd/goerli.go
Uses the latest output if there isn't an output after the current finalized block and checks it's at or before the finalized block.
Avoids failures like https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/17993/workflows/fa162c20-dc53-4c24-b2e3-7312e9574116/jobs/702292
> op-program: Update goerli verification script to handle long safe head stalls

- op-program/client/l2/db_test.go
- op-program/verify/cmd/goerli.go
`println` is a golang builtin that shouldn't be used. Switch to using `fmt.Println` instead.
> op-program: Remove println

- op-node/node/server.go
Removes the deprecated `Public` field in go-ethereum `rpc.Api` instantiation.
Reference: https://github.com/ethereum/go-ethereum/pull/25059
> fix(op-node): Remove Deprecated Public rpc.Api Field

- op-chain-ops/cmd/withdrawals/main.go
This PR improves performance of the withdrawals script by using a concurrency-limited set of goroutines rather than batches. This allows transactions to always fill the mempool. Additionally, fixes a bug with nonce management where failed transactions would bump the nonce and cause nonce gaps in the mempool, leading to stuck transactions.
> Performance + nonce management improvements to withdrawals script

- .changeset/mighty-cameras-check.md
- .circleci/config.yml
- packages/sdk/package.json
- packages/sdk/setupVitest.ts
- packages/sdk/src/adapters/eco-bridge.ts
- packages/sdk/src/adapters/index.ts
- packages/sdk/src/utils/chain-constants.ts
- packages/sdk/test-next/bridgeEcoToken.spec.ts
- packages/sdk/test-next/proveMessage.spec.ts
- packages/sdk/test-next/testUtils/ethersProviders.ts
- packages/sdk/test-next/testUtils/viemClients.ts
- packages/sdk/vitest.config.ts
- yarn.lock
Adds the ECO bridge to the sdk
https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/366/files
- The bridge has slightly different interface so requires a custom `supportsTokenPair`. Created a new eco-bridge adapter.
- adds ECO bridge to constants
- adds viem and some helper functions
> feat(sdk): add custom bridge address for ECO

- op-node/p2p/sync.go
This PR adds a global rate limit to outgoing P2P unsafe sync requests in addition to the existing local rate limit. The global rate limit outgoing & ingoing rate limits have the same parameters.
This PR also modifies the rate limit parameters. I have increased the burst values (the size of a full token bucket) and in the case of the per peer rate limit decreased the rate. This was done because the burst values were smaller than the per second limits.
Lastly, `clientErrRateCost` must be the same as the per peer rate limit burst because if you request more tokens than the burst, the request will be rejected & the code will not achieve it's goal of delaying future requests to a peer where the request failed.
**Tests**
No tests.
**Metadata**
- Fixes CLI-3967
> op-node: Modify p2p unsafe sync rate limits

- .changeset/eleven-experts-crash.md
- packages/contracts-bedrock/package.json
**Tests**
Hardhat was listed as a dependency when it should be a dev dependency. Was breaking some external monorepo stuff when adding a package that relied on contracts-bedrock because hardhat was being resolved from there and not from the top level.
> fix: hardhat dev dependency

- op-wheel/cheat/cheat.go
The header wasn't being copied, which was leading to issues finding the latest block when starting Geth against a cheated L1 disk. This PR uses the Geth `CopyHeader` utility to safely copy the header.
> op-wheel: Copy the header safely

- proxyd/config.go
- proxyd/integration_tests/testdata/caching.toml
- proxyd/proxyd.go
This change removed the left over configs from the cache refactoring. They were preventing proxyd to start with cache enabled.
**Tests**
Tested manually. Deployed to dev. Can see service starting correctly and cache metrics showing in grafana: https://optimistic.grafana.net/d/TRHRXiBVk/proxyd-k8s?orgId=1&refresh=10s&var-instance=dev-client-internal-devnet-proxyd-l1-consensus&var-backend_name=All&var-method=All&from=now-2d&to=now
**Invariants**
n/a
This change is part of the Consensus Aware RPC Proxy: https://www.notion.so/oplabs/Consensus-Aware-RPC-Proxy-0138e029af814e4cbca2740c7888e02d
**Metadata**
- Fixes https://linear.app/optimism/issue/INF-227/fixproxyd-clean-up-cache-initialization
**TODOs**
[RND]: …
> fix(proxyd): clean up cache initialization

- go.mod
- op-node/p2p/store/extended.go
- op-node/p2p/store/iface.go
- op-node/p2p/store/scorebook.go
- op-node/p2p/store/scorebook_test.go
- op-node/p2p/store/serialize.go
- op-node/p2p/store/serialize_test.go
Starts building an extended peer store that supports persisting peer scores. Not currently hooked up and lacking pruning of old entries, but defines the interface and has a sensible implementation for persisting scores.
**Tests**
Unit tests for persistence functions.
**Invariants**
**Metadata**
- https://linear.app/optimism/issue/CLI-3246/persist-peer-scores
> op-node: Add extended peer store to store scores

- op-service/clock/clock.go
- op-service/clock/deterministic.go
- op-service/clock/deterministic_test.go
Defines a `Clock` interface that's almost identical to the standard `time.*` functions. This enables services to use a common abstraction of time.  The system clock based implementation just delegates to the existing `time.*` methods for production use and a stub implementation makes it easy to test time-dependent functions.
Currently not used, but will be required to test GC functions for the extended peer store (https://github.com/ethereum-optimism/optimism/pull/5746)
**Tests**
Stub clock has unit tests.
**Metadata**
- https://linear.app/optimism/issue/CLI-3246/persist-peer-scores
> op-service: Define an abstract Clock

- op-challenger/challenger/oracle.go
- op-challenger/challenger/oracle_test.go
Split out of #5636, this adds a simple tested function for building a filter query for the `L2OutputOracle` `OutputProposed` event.
> feat(op-challenger): L2OutputOracle Filter Query.

- op-node/p2p/store/extended.go
- op-node/p2p/store/gc.go
- op-node/p2p/store/gc_test.go
- op-node/p2p/store/scorebook.go
- op-node/p2p/store/scorebook_test.go
- op-node/p2p/store/serialize.go
- op-node/p2p/store/serialize_test.go
Adds periodic pruning of peer score entries.
Builds on #5747 and #5746.
**Tests**
Unit tests cover new functionality.
Works by recording the time scores were last updated for each peer along with the peer scores, then a background job scans entries for ones that can be removed. This is a similar but slightly simplified model to the GC used by the peer store address book.
There are a few values that are currently hard coded like the time between GC runs, time before expiry and maximum batch size when pruning. These could potentially be moved to an options object but don't seem like they're worth exposing as CLI options so hard coded seems ok for now. More importantly the current values used are pretty arbitrary and need to be reviewed.
Peer store …
> op-node: GC for peer scores

- proxyd/backend.go
- proxyd/metrics.go
This change records metrics for sliding window changes: latency, network request count and network request error.
**Tests**
Manual tests.
**Invariants**
n/a
This change is part of the Consensus Aware RPC Proxy: https://www.notion.so/oplabs/Consensus-Aware-RPC-Proxy-0138e029af814e4cbca2740c7888e02d
**Metadata**
- Fixes https://linear.app/optimism/issue/INF-243/record-sliding-window-metrics
**TODOs**
> record sliding window metrics

- op-chain-ops/genesis/setters.go
Sanity check that empty bytecode is not set in the state for the `Proxy`. There are other checks for this after the migration happens and this never should happen so this is just a sanity check to catch a problem earlier in the process.
> op-chain-ops: sanity check not empty bytecode

- .circleci/config.yml
- op-chain-ops/Makefile
There have been fuzz tests in `op-chain-ops` for awhile but they have not been being ran in CI. This enables the fuzzing in CI following the same pattern as fuzzing for `op-node`.
> op-chain-ops: enable fuzzing

- proxyd/backend.go
- proxyd/metrics.go
This change ensure latency is reported in millisenconds.
**Tests**
Manual tests.
**Invariants**
n/a
This change is part of the Consensus Aware RPC Proxy: https://www.notion.so/oplabs/Consensus-Aware-RPC-Proxy-0138e029af814e4cbca2740c7888e02d
**Metadata**
- Fixes https://linear.app/optimism/issue/INF-245/normalize-latency-in-ms
**TODOs**
> feat(proxyd): normalize latency metrics in ms

- op-node/p2p/gating/expiry.go
- op-node/p2p/gating/expiry_test.go
- op-node/p2p/gating/mocks/ExpiryStore.go
- op-node/p2p/node.go
- op-node/p2p/store/extended.go
- op-node/p2p/store/iface.go
- op-node/p2p/store/ip_ban_book.go
- op-node/p2p/store/ip_ban_book_test.go
- op-node/p2p/store/peer_ban_book.go
- op-node/p2p/store/peer_ban_book_test.go
- op-node/p2p/store/records_book.go
- op-node/p2p/store/scorebook.go
- op-node/p2p/store/scorebook_test.go
This generalizes the score-book implementation, so we can use the same pattern with peer-bans and IP-bans.
The new peerstore temp-ban interface is then used by the ban-expiry connection gater (not enabled in p2p node yet).
The connection gater now first checks the inner blocking gater (i.e. perma bans), and then completely independently checks temp-bans. This is important, since we want to prune the temp-ban data in the peerstore, but don't want it to cause inconsistencies with perma-bans, so I decoupled them. The ban-expiration record itself signifies a temporary ban.
This also adds `BanPeer(id, expiration)` and `BanIP(ip, expiration)` helpers to the p2p node. Unban by setting the time to 0 time struct. We should consider exposing these via the p2p RPC like we do with …
> op-node: persist p2p bans with expiration time, update ban-expiry gater

- go.mod
- go.sum
- op-e2e/actions/system_config_test.go
- op-e2e/op_geth_test.go
- op-e2e/system_test.go
Tests that the pending block matches the latest block, a change introduced in https://github.com/ethereum-optimism/op-geth/pull/93
~~Added a temporary `go.mod` change so it runs CI with that op-geth PR. We should merge the geth PR first, and then update the go.mod to point at the main branch.~~ Matches latest `optimism` branch op-geth commit now (previous v1.11.6 changes were included before this PR already, and don't really affect the op-node other than e2e testing, this strictly introduces the receipt L1-fee overhead metadata fix and the pending-block change).
> op-e2e: pending block test + op-geth update

- proxyd/Dockerfile
- proxyd/backend.go
- proxyd/consensus_poller.go
- proxyd/consensus_tracker.go
- proxyd/example.config.toml
- proxyd/integration_tests/consensus_test.go
- proxyd/integration_tests/testdata/consensus.toml
- proxyd/integration_tests/testdata/consensus_responses.yml
- proxyd/metrics.go
- proxyd/rewriter.go
- proxyd/rewriter_test.go
- proxyd/tools/mockserver/handler/handler.go
This change adds the ability to track `finalized` and `safe` block tags within a backend group. It uses the same consensus poller mechanism, and converge to the lowest block.
Those tags are not used to form a consensus, only to maintain a consistent view from client perspective.
It shallowly check the values for sanity, i.e. tag values should never decrease, and `finalized` <= `safe` <= `latest`. In case of an unexpected scenario, we ban the backend and try to re-establish the consensus. If all backends are observing the same reorg, all of them will be banned and we'll stop serving traffic temporarily. 
Note this is a very rare event and we are trying to prevent overreacting to a bad node.
Re-establishing the consensus may result in `safe` or `finalized` to drop in the …
> feat(proxyd): track consensus for {safe,finalized} blocks and rewrite tags

- packages/contracts-bedrock/deploy-config/mainnet.json
Sets the proxy admin owner to the gnosis safe on L2. I double checked that `proxyAdminOwner` is the appropriate config value, as you can see [here](https://github.com/ethereum-optimism/optimism/blob/06245265f0c741c2f316d40052115ebcefeeb6e3/op-chain-ops/genesis/config.go#L471). There is a different config value for the L1 that is the `finalSystemOwner` as seen [here](https://github.com/ethereum-optimism/optimism/blob/06245265f0c741c2f316d40052115ebcefeeb6e3/packages/contracts-bedrock/deploy/021-SystemDictatorSteps-2.ts#L311) and
[here](https://github.com/ethereum-optimism/optimism/blob/06245265f0c741c2f316d40052115ebcefeeb6e3/packages/contracts-bedrock/contracts/deployment/SystemDictator.sol#L436) as well as [here](https://github.com/ethereum-optimism/optimism/blob/06245265f …
> contracts-bedrock: mainnet proxy admin owner config

- packages/contracts-bedrock/deploy-config/mainnet.ts
Fixes the export so it works as expected with hardhat deploy config.
Ported from `feat/mainnet`
> contracts-bedrock: fix mainnet deploy-config export

- proxyd/README.md
Updates the readme for proxyd with new consensus awareness behavior.
**Metadata**
https://linear.app/optimism/issue/INF-244/update-readme-with-consensus-behavior
> feat(proxyd): update readme

- packages/contracts-bedrock/contracts/test/invariants/Burn.Eth.t.sol
- packages/contracts-bedrock/contracts/test/invariants/Burn.Gas.t.sol
- packages/contracts-bedrock/invariant-docs/Burn.Eth.md
- packages/contracts-bedrock/invariant-docs/Burn.Gas.md
- packages/contracts-bedrock/invariant-docs/README.md
I have added `Burn.Eth.t.sol` and `Burn.Gas.t.sol`  files.
**Invariants**
It is noted that:
According to original `FuzzBurn.sol` echidna test file
`
unchecked {
if (postBurnGas - preBurnGas > value || preBurnGas - value > preBurnGas) {
failedGasBurn = true;
}
}
`
I notice that the logic should has been that it tries to falsify invariant (at least value gas was burnt). In other words, it should be that if the gas burned is less that the value pass, `failedGasBurn` should then be set to be true. Hence, the invariant cant be hold.
So, I have implement the new logic in `Burn.Gas.t.sol` as followed:
`       
unchecked {
if (postBurnGas - preBurnGas <= value && preBurnGas - value > preBurnGas) {
failedGasBurn = true;
}
}
`
Apologize if my understanding is wrong.
**Metadata**
- …
> contracts-bedrock: Convert Echidna tests  to Forge invariants for Burn library 

- proxyd/README.md
- proxyd/cache.go
- proxyd/cache_test.go
- proxyd/methods.go
- proxyd/rewriter.go
- proxyd/rewriter_test.go
This change adds support for `debug_getRawReceipts` method.
**Tests**
Added new tests.
**Invariants**
We cache only requests that are block hash, block numbers should never be cached.
https://www.notion.so/oplabs/Consensus-Aware-RPC-Proxy-0138e029af814e4cbca2740c7888e02d
**Metadata**
https://linear.app/optimism/issue/INF-257/add-debug-getrawreceipts-to-rewrite-methods
**TODOs**
> feat(proxyd): add support to rewrite debug_getRawReceipts

- op-node/chaincfg/chains.go
Update `chains.go` for the May 31 migration rehearsal.
> chore(rehearsal): Update `chains.go`

- proxyd/integration_tests/consensus_test.go
- proxyd/integration_tests/testdata/consensus.toml
- proxyd/metrics.go
This change adds a new metric to track degraded backends.
https://www.notion.so/oplabs/Consensus-Aware-RPC-Proxy-0138e029af814e4cbca2740c7888e02d
**TODOs**
> feat(proxyd): add metric for degraded backend

- ops/docker/ci-builder/Dockerfile
Adds the `mockery` tool to the `ci-builder` docker container. See https://github.com/ethereum-optimism/optimism/pull/5839 for PR that introduces usage of `mockery` in CI.
**Tests**
N/A
**Invariants**
N/A
❓How do I go about adding this to the [CHANGELOG.md](https://github.com/ethereum-optimism/optimism/blob/develop/ops/docker/ci-builder/CHANGELOG.md) file? Seems like it was autogenerated in the previous change but it wasn't clear to me where/how to update that.
**Metadata**
- Unblocks #5839 
**TODOs**
> ci: add mockery tool to ci-builder docker container

- op-wheel/cheat/cheat.go
- op-wheel/commands.go
Allows it to set into the state arbitrary code at an arbitrary account. This will make it very easy to patch contracts that contain immutables. Then we can patch the contracts to have different immutables without needing to update the proxies and worry about that.
We can also cheat the impl of the multisig to be a call forwarder so that we do not need to cheat so many storage slots and forget about particular slots.
> op-wheel: add cheat code command

- packages/contracts-bedrock/contracts/test/invariants/Encoding.t.sol
- packages/contracts-bedrock/invariant-docs/Encoding.md
I have converted the echidna test for Encoding.sol  to Forge invariant tests
- https://github.com/ethereum-optimism/ecosystem-contributions/issues/49
**Metadata**
- Fixes #[Convert Echidna tests to Forge invariantes #4980] 
**TODOs**
> contracts-bedrock: Convert Echidna tests to Forge invariants for Encoding library

- op-chain-ops/cmd/rollover/main.go
Handle the case where a deposit is sent after
the dtl shutoff block is set. This change requires an archive node to be used.
> op-chain-ops: fix rollover script

- op-proposer/proposer/l2_output_submitter.go
Ensures that the error is wrapped when failing to create contract bindings to include the address. This is helpful for when the wrong address is passed in and no contract code exists at that particular account.
> op-proposer: log address on failed contract bindings

- op-batcher/batcher/channel_manager.go
- op-batcher/metrics/metrics.go
- op-batcher/metrics/noop.go
This adds metrics to track the size of pending blocks (rather than just the number).
It is expressed in a counter & a gauge. There is no new counter for the pending size
in channels because that counter already exists as the `input_bytes` metrics.
Note: This is based off of the `op-batcher/v1.0.9-rc.1` tag.
> op-batcher: Add metrics for pending L2 transaction data size

- op-challenger/challenger/challenger.go
- op-challenger/challenger/oracle.go
- op-challenger/challenger/subscription.go
- op-challenger/cmd/entrypoint.go
- op-challenger/cmd/main.go
- op-challenger/cmd/watch/cmd.go
- op-challenger/cmd/watch/oracle.go
- op-challenger/config/logging.go
- Sets up the `op-challenger` subcommand dispatch.
- Adds an L2OutputOracle `OutputProposed` event watcher as part of the `watch` subcommand.
**Metadata**
Fixes CLI-4062
> feat(op-challenger): Oracle Watcher

- op-challenger/challenger/challenger.go
- op-challenger/challenger/factory.go
- op-challenger/challenger/factory_test.go
- op-challenger/cmd/watch/cmd.go
- op-challenger/cmd/watch/factory.go
Stacked ontop of #5831, this pr contains the logic for the `watch factory`
subcommand to listen for newly created dispute games from the dispute
game factory.
**Metadata**
Fixes CLI-4063
> feat(op-challenger): DisputeGameFactory Watcher

- indexer/go.mod
- indexer/node/bigint.go
- indexer/node/bigint_test.go
- indexer/node/client.go
- indexer/node/client_test.go
- indexer/node/fetcher.go
- indexer/node/fetcher_test.go
The Fetcher will be used to drive new batches of headers to check. This can be used against both the L1 and L2 instances. Not super clear why the indexer currently duplicates this logic in both L1/L2
Follow up
1. Implement the processor which will poll the Fetcher
2. Investigate if we can utilize a subscription for new headers instead of polling
3. More robust implementation for the `EthClient` interface. See some of the comments on this PR
> [indexer] consolidate retrieval of finalized headers

- op-node/chaincfg/chains.go
Finalize the mainnet rollup config in the `op-node` chain config.
**Checklist**
> feat(op-node): Finalize Mainnet Rollup Config [release branch]

- .circleci/config.yml
- op-bootnode/bootnode/entrypoint.go
- op-bootnode/cmd/main.go
- op-bootnode/flags/flags.go
Added an implementation of a standalone bootnode that simply runs op-node's discovery process.
**Tests**
Test coverage is mostly provided by op-node's existing P2P package. We may want to add some E2E tests for this wrapper.
This is the bootnode implementation that Base runs in production. It also supports bootstrapping networks before genesis, as only a small amount of genesis information is required to run a bootnode:
- L2 chain ID
- L2 genesis timestamp
- L2 block time
- L2 genesis block number (defaults to 0)
> op-bootnode

- op-batcher/batcher/channel.go
- op-batcher/batcher/channel_builder.go
- op-batcher/batcher/channel_builder_test.go
- op-batcher/batcher/channel_manager.go
- op-batcher/batcher/channel_test.go
The metrics recorded the value of channelBuilder.NumFrames(). But this was only the number of pending frames in the frames queue.
This PR adds a new method TotalFrames() and separate numFrames tracking to distinguish between the number of pending frames and total frames of a channel.
**Tests**
Added test for `PendingFrames` and `TotalFrames`
Fixes `num_frames` metrics of the batcher, which was mostly recording `1`s instead of the real total number of frames.
**Metadata**
- Fixes CLI-4073
**TODOs**
> op-batcher: Fix num_frames metrics

- .changeset/rotten-cheetahs-guess.md
- packages/fault-detector/package.json
- packages/fault-detector/tsconfig.json
- yarn.lock
Running the fault detector saw a bunch of stuff to fix to make debugging easier both in prod and locally
- replace ts-node with tsx.  Tsx is better faster and more likely to "just work" without headaches
- add a dev script that will reload the server when changes happen
- add a serve script to serve the production build
- add a preview script to preview the production build
- turn on source maps with --enable-source-maps
> feat(fault-detector): Better package.json

- indexer/cmd/indexer-refresh/main.go
- indexer/database/blocks.go
- indexer/database/bridge.go
- indexer/database/contract_events.go
- indexer/database/db.go
- indexer/indexer.go
- indexer/node/bigint.go
- indexer/node/client.go
- indexer/node/client_test.go
- indexer/node/fetcher.go
- indexer/node/fetcher_test.go
- indexer/processor/l1_processor.go
- indexer/processor/l2_processor.go
- indexer/processor/processor.go
Introduce a `processor` modules that exposes `L1Processor` and `L2Processors`. These structs define the core logic that indexes new batches retrieved from the fetcher. All database operations for a given batch are wrapped in a database transaction.
The L1 & L2 processors simply index block headers right now.
- `indexer-refresh` command was updated such that the new indexer can now be run e2e.
- `EthClient#FinalizedBlockHeight` switched to "latest" blocktag instead of "finalized" blocktag to avoid dealing with issues with the local devnet. We'll address this
- L1Processor needs some additional config such that it doesn't start from genesis. It should start from the L1 block corresponding to L2 genesis
> feat(indexer) processor module with basic l1Processor & l2Processor

- .github/CODEOWNERS
Adds the `go-reviewers` as the codeowner for the `op-bootnode` package
> fix(op-bootnode): Add go-reviewers as codeowner

- op-e2e/system_test.go
The existing TestWithdrawals test attempts to assert that the total fees of the prove and finalize transactions are accounted for in the L1 balance.  But, it re-uses the `calcGasFees` function and passes in the `GasTipCap` and the `GasFeeCap` from the L2 transaction, not from the actual L1 transactions.  In the event that the gas fee differs on the L2 from the L1, then the test will fail.
To keep the diff small, this change simply multiplies the GasUsed and `EffectiveGasPrice` from the receipts.  This could be moved into a helper function like `calcGasFees`.  Using the `EffectiveGasPrice` seems just as good or better than relying on the parameters of the original transaction, and could be similarly utilized higher in the test for the L2 fees.  If we really want to get the parameters from …
> op-e2e: Fix bug in TestWithdrawals

- packages/contracts-bedrock/deploy/017-SystemConfigImpl.ts
- packages/contracts-bedrock/deploy/019-SystemDictatorInit.ts
- packages/contracts-bedrock/src/constants.ts
Add deploy time checks to ensure that the config invariants are sane. There is an invariant such that the L2 gas limit must be larger than the amount of gas used by the system transaction plus the amount of gas that deposits can purchase on L1. This invariant is held checked in the migration code but not the typescript deployment code.
Closes CLI-3774
> contracts-bedrock: deploy time checks

- indexer/api/api.go
- indexer/api/api_test.go
> feat(indexer): Add healthz to api

- indexer/Makefile
- build indexer-referesh with make indexer-refresh
> feat(indexer): Add indexer-refresh to makefile

- README.md
Remove broken link to `infra/op-replica` in the README.  op-replica was removed in 23150b8b85c20a83782c3b5a73ced9bad527bc0d
> README: Remove broken link to infra/op-replica

- indexer/database/bridge.go
- indexer/database/contract_events.go
- indexer/indexer.go
- indexer/processor/l1_processor.go
- indexer/processor/l2_processor.go
When starting the processor, the optimism contracts should be supplied. We watch these contracts and index as batches are processed.
- Skip L1 blocks that do not have optimism activity.
- Contract configuration. Right now the L1/L2 contracts are the hardcoded local devnet addresses
> feat(indexer): index all L1 & L2 contract events

- indexer/api/api_test.go
the indexer api_test.go is failing to compile because it wasn't updated after a [recent UUID related change](https://github.com/ethereum-optimism/optimism/pull/5968), this PR fixes the error by using a random UUID for the affected test cases.
> fix UUID related compile failure

- .circleci/config.yml
The contracts-tests job is no longer required because the `contracts` package no longer exists. This results in the CI job running all of the typescript tests for each of the packages in parallel, wasting CI resources.
> ci: delete dead job

- op-bindings/bindings/registry.go
Ensure that the deployed bytecode is properly formatted hex to ensure that an empty value is not returned. This should never happen but is a sanity check to ensure that unexpected values are not returned.
> op-bindings: error handling

- op-node/rollup/types.go
Common mistake is to connect to the wrong RPC. But the logs were making this very confusing, since got/expected values were swapped and formatted incorrectly. This fixes that.
> op-node: fix chain ID/hash check errors

- packages/contracts-bedrock/contracts/test/invariants/ResourceMetering.t.sol
- packages/contracts-bedrock/invariant-docs/ResourceMetering.md
I have converted invariant logics in  `FuzzResourceMetering.sol` and added those ported ones into `invariants/ResourceMetering.t.sol` invariant  file.
- https://github.com/ethereum-optimism/ecosystem-contributions/issues/49
-
**Metadata**
- Fixes #[Convert Echidna tests to Forge invariantes #4980]
> contracts-bedrock: Convert Echidna tests to Forge invariants for ResourceMetering

- op-node/sources/types.go
Alchemy returns `-32600` (generic) instead of `-32601` ("unknown method") for unsupported RPC methods. We should make the op-node fall-back to the wider-supported receipt fetching methods when it hits this error, to avoid sync stalling. It already will log warnings about it falling back, and tries the advanced receipt fetching methods later again.
> op-node: handle -32600 receipts err code, and always fallback to err msg

- .changeset/few-shoes-deny.md
- packages/fault-detector/src/helpers.ts
- expected failure was logged as an error and not a warning
- log as warning instead so it doesn't ping alerts
> fix(fault-detector): Change expected error to a warning

- ops/scripts/ci-docker-tag-op-stack-release.sh
- ops/tag-service/tag-service.py
Fixes the tag-service action for ci-builder introduced in #6043
> chore(ops): Fix ci-builder release action

- op-program/host/host.go
- op-service/client/retry.go
- op-service/client/retry_test.go
When the retrying RPC client has to retry a request, log a warning so the user knows that something didn't work. Will fix op-program goerli-verify job timing out because it went 10 minutes with no output and provide useful information to the user when things aren't working correctly.
> op-service: Log a warning when an RPC request has to be retried

- packages/contracts-bedrock/contracts/test/invariants/OptimismPortal.t.sol
- packages/contracts-bedrock/invariant-docs/OptimismPortal.md
I have converted deposit logics in  `EchidnaFuzzOptimismPortal.sol` and added those ported ones into `OptimismPortal.t.sol` invariant  file.
- https://github.com/ethereum-optimism/ecosystem-contributions/issues/49
**Metadata**
- Fixes #[Convert Echidna tests to Forge invariantes #4980] 
**TODOs**
> contracts-bedrock: Convert Echidna tests to Forge invariants for OptimismPortal

- op-node/p2p/store/iface.go
- op-node/p2p/store/scorebook_test.go
- op-node/p2p/store/serialize_test.go
Adds `scoreDiff` implementations to support incrementing and decaying application score elements.
**Tests**
Added unit tests.
**Metadata**
- https://linear.app/optimism/issue/CLI-3732/implement-p2p-req-resp-peer-scoring
> op-node: Add peer score diffs to increment and decay application scores

- op-challenger/fault/alphabet_provider.go
- op-challenger/fault/alphabet_provider_test.go
- op-challenger/fault/types.go
Introduces the simple `AlphabetProvider` tracing provider to the `op-challenger`.
**Metadata**
Fixes CLI-4115
> feat(op-challenger): AlphabetProvider Tracer

- packages/contracts-bedrock/STYLE_GUIDE.md
***Description***
Update the style guide to use triple slash natspec instead of seaport. Pending approval, subsequent prs will migrate the contract comment styling across `contracts-bedrock` following this PR being merged.
> feat(ctb): Style Guide Updates

- op-chain-ops/genesis/layer_one.go
This commit uses the deploy config value `fundDevAccounts` to determine if the standard `test test ...` accounts used by hardhat/foundry should be prefunded with ether. This makes testing using the devnet a bit easier.
Note that this code will be removed in the future because it is part of the devnet where the genesis is prepopulated with the contracts. It is not tenable to maintain 2 devnets, one with prepopulated genesis and one with a deployed genesis.
> op-chain-ops: fund L1 devnet accounts

- op-challenger/fault/cmd/main.go
- op-challenger/fault/position.go
- op-challenger/fault/position_test.go
This adds support for the generalized index & tests for the position object.
**Tests**
Adds lots of tests.
> game solver: Add generalized index & tests to position

- op-node/p2p/sync.go
Fix test issues where the test-logger was being used after the test shut down.
The `TestMultiPeerSync` defers the `.Close()` calls on the sync clients, but those then completed the wait-group in the sync client, before logging about the shutdown. This caused a race where the logger would panic because of the unexpected log.
The fix is to move the log before the `wg.Done()`.
Reviewing the code further there also seems to be a case where we could have a warn-log while the client was already shutting down. We now return early in `AddPeer` if we're closing already, to ensure post-shutdown AddPeer calls cannot accidentally create logs that make the test flake.
> op-node: log shutdown before releasing client waitgroup

- op-service/txmgr/price_bump_test.go
- op-service/txmgr/txmgr.go
- op-service/txmgr/txmgr_test.go
Currently the txmgr retry logic will not bump a transaction's tip and max-fee in the case the latest suggested values are lower than the original values.  When a transaction is stuck in the mempool (e.g. due to too low fees or bad gaslimit estimate) this regularly results in retry failures with error message "resubmitted already known transaction" or "replacement transaction underpriced".
This PR imposes a mandatory fee increase with each retry (up to a point) to ensure a retried tx isn't immediately rejected in this manner.
We also see txs get stuck in the mempool because of extremely high gaslimit estimation (e.g. gaslimit nearly equals block gas limit).  In these cases, increasing fees alone does not solve the problem. To fix this scenario, this change makes the txmgr …
> require fee increase & gas re-estimation for retried transactions

- op-challenger/fault/cmd/main.go
- op-challenger/fault/position.go
- op-challenger/fault/position_test.go
- op-challenger/fault/solver.go
Simplify the API by using uint64 as the trace index everywhere & return a new position object instead of mutating it when attacking or defending.
> op-challenger API Cleanups

- packages/contracts-bedrock/.gas-snapshot
- packages/contracts-bedrock/contracts/test/L1StandardBridge.t.sol
Following @tynes [comment](https://github.com/ethereum-optimism/optimism/pull/6099#discussion_r1239095697), this pr splits out the change to remove the semver check on the `L1StandardBridge`.
> fix(ctb): Remove Semver Check L1StandardBridge.t.sol

- packages/contracts-bedrock/scripts/FeeVaultWithdrawal.s.sol
- packages/contracts-bedrock/scripts/interfaces/IGnosisSafe.sol
- packages/contracts-bedrock/scripts/outputs/DeleteOutput.s.sol
- packages/contracts-bedrock/scripts/universal/EnhancedScript.sol
- packages/contracts-bedrock/scripts/universal/GlobalConstants.sol
- packages/contracts-bedrock/scripts/universal/SafeBuilder.sol
- packages/contracts-bedrock/scripts/upgrades/PostSherlock.s.sol
- packages/contracts-bedrock/scripts/upgrades/PostSherlockL2.s.sol
Updates all Solidity files in `packages/contracts-bedrock/scripts/**` from seaport comment
styling to triple slash natspec.
> fix(ctb): Update Solidity Scripts to Triple Slash Natspec

- docs/op-stack/src/docs/build/getting-started.md
- Restrict the not for production warning. It's not `cast wallet` that is insecure, just `cast wallet new`.
- Fix numbering in #configure-your-network
- Add warning related to `direnv` installation
- Remove no longer relevant request (to replace <RPC>, which no longer appears in a command line)
- Add creating a deployment directory for getting-started
- Fix the `L2OO_ADDR` table line
- Update file name for bridge
Closing: DEVRL-1020
> fix(docs/op-stack): Changes related to the move from hardhat to foundry

- .semgrepignore
The code generated by abigen triggers a lot of
semgrep scan issues so ignore that directory
> semgrep: ignore op-bindings/bindings

- specs/messengers.md
Fixed typo in `messengers.md` describing message passing from L1 to L2.
> fixed messengers.md

- packages/contracts-bedrock/scripts/slither.sh
The `contracts-bedrock-slither` job has been timing out due to a lack of output from slither until compilation has completed. This PR adds the `--ignore-compile` flag to slither and builds the contracts prior to invoking it so that the build progress is emitted to stdout as it goes.
> chore(ci): Fix slither timeout

- packages/contracts-bedrock/scripts/DeployConfig.s.sol
Hides new config behind a particular chain id so that it doesn't try to be parsed in the getting started guide. We will implement a form of fallback config in the future.
Fixes https://github.com/ethereum-optimism/optimism/issues/6141
> deploy-config: temp fix for new config

- op-challenger/fault/agent.go
- op-challenger/fault/cmd/examples/full.go
- op-challenger/fault/cmd/examples/solver.go
- op-challenger/fault/game.go
- op-challenger/fault/game_test.go
- op-challenger/fault/orchestrator.go
- op-challenger/fault/solver.go
- op-challenger/fault/solver_test.go
This adds the ability for the `Move` function to counter the root claim. Because the root claim does not have a parent & we no longer looked at the parent pair, we now iterate claims, not pairs of claims.
This also touches a lot of the example code to remove setting it up with the initial counter claim.
**Tests**
Unit tests to be able to counter the root claim.
> op-challenger: Counter the root claim

- op-challenger/fault/types.go
Add ContractIndex & ParentContractIndex to Claim.
This data is only used when interacting with the contracts.
> op-challenger: Add ContractIndex & ParentContractIndex to Claim

- package.json
- Add extra protection so if folks accidentally use yarn from muscle memory they don't mess up their node modules and need to rm -rf node_modules to fix
> feat: Add script to stop people from accidentally using yarn install

- .changeset/fuzzy-lobsters-wait.md
- .circleci/config.yml
- packages/core-utils/src/optimism/hashing.ts
- packages/sdk/src/cross-chain-messenger.ts
- packages/sdk/test-next/messageStatus.ts
Fixes https://github.com/ethereum-optimism/optimism/issues/6035
- Made a breaking change after goerli bedrock release to migrate legacy withdrawals message hashesto v1.
- the message hash what is used from l2 withdrawal logs to generate the message hash on l1
- Any legacy withdrawal made prebedrock will be v0
- any legacy withdrawal made post bedrock will be v1
To figure out if a message is relayed we check for `RelayedMessage` event for message hash
Check for both v0 and v1
> fix(sdk): check for both v0 and v1 messages when looking for RelayedMessages

- op-e2e/actions/l2_verifier.go
- op-e2e/system_adminrpc_test.go
- op-node/node/api.go
- op-node/node/server_test.go
- op-node/rollup/driver/driver.go
- op-node/rollup/driver/state.go
- op-node/sources/rollupclient.go
Add `admin_sequencerActive` RPC method.
Returns true if the node is actively sequencing, otherwise false. This is essentially a parallel with the `eth_mining` API from execution clients.
**Tests**
Updated e2e tests for admin API to cover the new endpoint.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-4160/rpc-to-get-current-sequencer-state
> op-node: Add `admin_sequencerActive` RPC method

- op-node/flags/flags.go
- op-service/metrics/cli.go
- op-service/pprof/cli.go
- op-service/rpc/cli.go
These flags are	not actually required to run the op-node. They now default to 0.0.0.0 for the address & 8545 for the port.
> op-node: Remove RPC flags from the required flag list

- .changeset/cyan-games-change.md
- .changeset/shy-yaks-smell.md
https://github.com/ethereum-optimism/optimism/pull/6148 changed the the build directory for the contracts-bedrock package. This is causing the most recent canary release of the sdk to not build properly: 
```
Error: Cannot find module '@eth-optimism/contracts-bedrock/forge-artifacts/L1StandardBridge.sol/L1StandardBridge.json'
Require stack:
- /__w/gateway/gateway/node_modules/.pnpm/@eth-optimism+sdk@0.0.0-20230629165646_ethers@5.7.2/node_modules/@eth-optimism/sdk/dist/utils/contracts.js
- /__w/gateway/gateway/node_modules/.pnpm/@eth-optimism+sdk@0.0.0-20230629165646_ethers@5.7.2/node_modules/@eth-optimism/sdk/dist/utils/index.js
- /__w/gateway/gateway/node_modules/.pnpm/@eth-optimism+sdk@0.0.0-20230629165646_ethers@5.7.2/node_modules/@eth-optimism/sdk/dist/index.js
- …
```
> Add changeset for #6148

- .changeset/breezy-spoons-hope.md
- packages/fault-detector/package.json
- packages/fault-detector/test/helpers.spec.ts
- pnpm-lock.yaml
Fixes the issue in the changesets release, would like to merge this and then retrigger a changesets release to get a new version of the sdk out. https://github.com/ethereum-optimism/optimism/actions/runs/5415582130/jobs/9844098993
> fault-detector: bump contracts-bedrock version

- .github/workflows/publish-canary.yml
- package.json
- To be 100% safe don't use nx cache on releases
- We currently don't use remote cache but if we do it's always best to build clean
- This action as a bot does not have access to the git shas something we will need to add to our workflows manually
> fix: Skip nx cache on releases

- op-challenger/fault/game.go
- op-challenger/fault/game_test.go
- op-challenger/fault/loader.go
- op-challenger/fault/loader_test.go
Creates a net-new component to the game-solver/challenger to load and track
`Claim`s from a fault dispute game contract through polling.
**Metadata**
Fixes CLI-4126
> feat(op-challenger): Claim Loader

- op-challenger/fault/responder.go
- op-challenger/fault/responder_test.go
- op-challenger/fault/types.go
Implements the naive fault responder. The fault responder satisfies the `Responder` interface and engages a fault dispute game via the tx manager to attack or defend a given response claim.
This is a very basic first iteration whereby the fault responder's only course of action is to `Attack` or `Defend`.
**Tests**
Multi-path unit tests around the `faultResponder`'s `Respond` function exist in `responder_test.go`. This is the only public facing function for the `Responder` interface and both the happy and sad paths are tested.
**Metatada**
Fixes CLI-4127
> feat(op-challenger): FaultResponder

- .changeset/cuddly-panthers-trade.md
- packages/sdk/src/cross-chain-messenger.ts
- packages/sdk/test/cross-chain-messenger.spec.ts
fixes https://github.com/ethereum-optimism/optimism/issues/5983
- fixes multicall3 withdrawals for sdk
- I have tests for this in https://github.com/ethereum-optimism/optimism/pull/6024 passing locally but they fail ci for unrelated reasons
- they are failing because the packages I yarn installed broke other packages
- I plan on fixing this in it's own seperate pr via upgrading some packages and implementing no-hoisting for affected packages to make them less fragile
> fix(sdk): Fix multicall3 support for sdk

- op-challenger/fault/responder_test.go
- op-e2e/actions/l2_proposer.go
- op-proposer/proposer/l2_output_submitter.go
- op-service/txmgr/mocks/TxManager.go
- op-service/txmgr/txmgr.go
-  proposal transaction errors were commonly being logged due to another esoteric EstimateGas quirk, which this PR cleans up by making sure the head of the L1 chain is sufficiently advanced before submitting the output proposal.
- changes a spammy info log to debug
- changes the warning log message on failure to fetch receipt to info level since this is typical behavior when txs are replaced with increased fees
- documentation added to explain some of the expected logging outcomes
- fixes function name typo
Context: it turns out that "EstimateGas" actually defaults to estimating gas at "Latest" block state instead of "Pending" block state (the godoc in ethclient is outdated, though a PR to update it is [here](https://github.com/ethereum/go-ethereum/pull/27508)).   This means estimate gas …
> prevent op-proposer Send tx failure errors & clean up op-proposer logging

- .circleci/config.yml
- ops-bedrock/Dockerfile.l1
Updates to the latest geth for the devnet to ensure that our system works against the latest changes
to L1
> ops: update L1 geth for devnet

- indexer/docker-compose.yml
- Add processor to docker-compose
- this is still a wip
> feat(indexer): Add processor to docker-compose

- op-batcher/flags/flags.go
- op-challenger/game/disk.go
- op-challenger/game/scheduler/coordinator.go
- op-challenger/game/scheduler/coordinator_test.go
- op-e2e/system_test.go
- op-node/node/superchain_test.go
- op-node/p2p/host_test.go
- op-node/rollup/derive/channel_bank.go
- op-service/sources/batching/test/abi_stub.go
- op-service/txmgr/queue_test.go
In the current go 1.21 version used in the project, slices are no longer an experimental feature and have entered the standard library
> all: use the built-in slices library
