packages/docs/src/core/src/integrating-tests.rst, packages/docs/src/core/src/limitations.rst, packages/docs/src/core/src/spec/design.rst, packages/docs/src/core/src/spec/execution-manager.rst, packages/docs/src/core/src/spec/jump-transpilation.rst, packages/docs/src/core/src/spec/overview.rst, packages/docs/src/core/src/spec/solc-transpiler.rst, packages/docs/src/core/src/spec/transpilation-details.rst, packages/docs/src/core/src/troubleshooting.rst
Updating docs content where applicable and format from md to rst.
=> Updating docs formatting

packages/ovm/src/contracts/ExecutionManager.sol, packages/ovm/src/contracts/testing-contracts/InvalidOpcodes.sol, packages/ovm/test/contracts/execution-manager.call-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.code-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.context-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.create-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.purity-checking.spec.ts, packages/ovm/test/contracts/execution-manager.storage-opcodes.spec.ts, packages/ovm/test/contracts/revert-test.spec.ts, packages/ovm/test/contracts/simple-storage.spec.ts, packages/ovm/test/helpers.ts
Makes ExecutionManager.sol always return an address from ovmCREATE and ovmCREATE2. It will be the 0 address if the create failed. This is to make it work how the EVM works currently.
- Fixes # [YAS-171](https://optimists.atlassian.net/browse/YAS-171)
=> Never revert on ovmCREATE*

packages/solc-transpiler/package.json, packages/solc-transpiler/src/compiler.ts, yarn.lock
If the required version of solc isn't currently in use solc will [download the required version of itself][1]. Normally you can pass "version" in the the truffle config to trigger this behavior but our truffle version field is already filled with a path to our custom solc compiler. Instead we pass the environment variable `SOLC_VERSION` which triggers it.
Truffle expects `compile` to be synchronous so we can't do anything asynchronous in that function. To get around this we use `execSync` which executes synchronously.
[1]: https://github.com/ethereum/solc-js/blob/5c1280ca2c73dfba58bad21849b16eb1fa5618e5/README.md#using-a-legacy-version
=> Add support for custom solc versions

.github/workflows/build-test-lint.yml, packages/docs/src/core/src/integrating-tests.rst, packages/examples/package.json, packages/examples/truffle-config-ovm.js, packages/ovm-truffle-provider-wrapper/README.md, packages/ovm-truffle-provider-wrapper/index.ts, packages/ovm-truffle-provider-wrapper/package.json, packages/ovm-truffle-provider-wrapper/tsconfig.json, packages/ovm-truffle-provider-wrapper/tslint.json
Creates simple library to shim in the Truffle Provider changes required to use Truffle + OVM.
- Fixes # [YAS-169](https://optimists.atlassian.net/browse/YAS-169)
=> Adding ovm-truffle-provider-wrapper

packages/core-db/package.json, packages/core-utils/package.json, packages/docs/package.json, packages/examples/package.json, packages/optimistic-game-semantics/package.json, packages/ovm-truffle-provider-wrapper/package.json, packages/ovm/package.json, packages/rollup-contracts/package.json, packages/rollup-core/package.json, packages/rollup-dev-tools/package.json, packages/rollup-full-node/package.json, packages/solc-transpiler/package.json
=> Release 0.0.1-alpha.9

packages/ovm/src/contracts/DataTypes.sol, packages/ovm/src/contracts/ExecutionManager.sol, packages/ovm/src/contracts/testing-contracts/SimpleTxOrigin.sol, packages/ovm/test/contracts/tx-origin.spec.ts, packages/rollup-dev-tools/src/tools/transpiler/opcode-replacer.ts, packages/rollup-dev-tools/src/tools/transpiler/static-memory-opcodes.ts, packages/rollup-dev-tools/test/transpiler/opcode-replacer.spec.ts, yarn.lock
- Fixes # [Yas-159 - Implement tx.origin for EOA calls](https://optimists.atlassian.net/browse/YAS-159)
=> Implement tx.origin for EOA calls

packages/core-db/package.json, packages/core-utils/package.json, packages/docs/package.json, packages/docs/src/core/src/integrating-tests.rst, packages/optimistic-game-semantics/package.json, packages/ovm-truffle-provider-wrapper/README.md, packages/ovm-truffle-provider-wrapper/index.ts, packages/ovm-truffle-provider-wrapper/package.json, packages/ovm/package.json, packages/ovm/test/contracts/execution-manager.call-opcodes.spec.ts, packages/rollup-contracts/package.json, packages/rollup-core/package.json, packages/rollup-dev-tools/package.json, packages/rollup-full-node/exec/aggregator.js, packages/rollup-full-node/exec/fullnode.js, packages/rollup-full-node/exec/startFullnode.sh, packages/rollup-full-node/exec/stopFullnode.sh, packages/rollup-full-node/index.ts, packages/rollup-full-node/package.json, packages/rollup-full-node/src/exec/aggregator.ts, packages/rollup-full-node/src/exec/fullnode.ts, packages/solc-transpiler/package.json, yarn.lock
* Adding wrapper to `ovm-truffle-provider-wrapper` that kicks off local full-node and stops it after tests
* Separating js to kickoff fullnode and aggregator and js that can be referenced to configure fullnode and aggregator.
- Fixes # [YAS-177](https://optimists.atlassian.net/browse/YAS-177)
=> Add ability to seamlessly start fullnode in Truffle

packages/ovm/package.json, packages/ovm/src/app/utils.ts, packages/ovm/src/contracts/ExecutionManager.sol, packages/ovm/test/app/utils.spec.ts, packages/ovm/test/helpers.ts, packages/rollup-full-node/src/app/handler.ts
Other changes:
* Add a separate function for getting ovm transaction metadata
* Move `CallingWithEOA` event into the `CallEOA` function and add an argument to simplify event parsing
- Fixes # [YAS-184 - Add better tests for Event parsing](https://optimists.atlassian.net/jira/software/projects/YAS/boards/2?selectedIssue=YAS-184)
=> Add tests for convertInternalLogsToOvmLogs

.github/workflows/npm_publish.yml, package.json
Automates the process of deploying to npm.
Note this hasn't been tested yet. I'll run and debug it by merging to the `published` branch once it's merged into master.
- Fixes [YAS-175](https://optimists.atlassian.net/browse/YAS-175)
=> Add a GitHub workflow for publishing to NPM

packages/core-utils/src/app/misc.ts, packages/ovm/package.json, packages/ovm/src/app/ovm.ts, packages/ovm/src/app/utils.ts, packages/ovm/src/types/ovm.ts, packages/ovm/test/app/utils.spec.ts, packages/ovm/test/contracts/contract-address-generator.spec.ts, packages/ovm/test/contracts/execution-manager.call-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.code-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.context-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.create-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.executeCall.spec.ts, packages/ovm/test/contracts/execution-manager.purity-checking.spec.ts, packages/ovm/test/contracts/execution-manager.recover-eoa-address.spec.ts, packages/ovm/test/contracts/execution-manager.storage-opcodes.spec.ts, packages/ovm/test/contracts/rlp-encode.spec.ts, packages/ovm/test/contracts/state-manager.spec.ts, packages/ovm/test/contracts/tx-origin.spec.ts, packages/ovm/test/helpers.ts, yarn.lock
Add a test to ensure EXTCODECOPY returns zeroed bytes when the provided range is out of bounds or the provided address is invalid.
* Add `executeOVMCall`, `encodeMethodId` and `encodeRawArguments` test helpers
* Use those helpers where applicable
* Removed unused variables with `tslint`
- Do we want to enable `noUnusedLocals` and `noUnusedParameters` in our `tsconfig` to prevent unused variables?
- Fixes # [YAS-119](https://optimists.atlassian.net/browse/YAS-119)
=> Refactor tests and test EXTCODECOPY Failure Behavior

packages/core-db/package.json, packages/core-utils/package.json, packages/docs/package.json, packages/optimistic-game-semantics/package.json, packages/ovm-truffle-provider-wrapper/index.ts, packages/ovm-truffle-provider-wrapper/package.json, packages/ovm/package.json, packages/rollup-contracts/package.json, packages/rollup-core/package.json, packages/rollup-dev-tools/package.json, packages/rollup-full-node/package.json, packages/solc-transpiler/package.json
The rollup fullnode import is missing in the truffle provider wrapper, causing the spawned subprocess to not be able to find the fullnode. This fixes that by importing it in the truffle provider wrapper's index.ts file.
=> Fixing truffle provider wrapper import so that sub-process works

packages/core-db/package.json, packages/core-utils/package.json, packages/core-utils/src/app/transport/server/json-rpc-errors.ts, packages/docs/package.json, packages/optimistic-game-semantics/package.json, packages/ovm-truffle-provider-wrapper/package.json, packages/ovm/package.json, packages/ovm/src/app/utils.ts, packages/ovm/src/types/index.ts, packages/rollup-contracts/package.json, packages/rollup-core/package.json, packages/rollup-dev-tools/package.json, packages/rollup-full-node/package.json, packages/rollup-full-node/src/app/fullnode-rpc-server.ts, packages/rollup-full-node/src/app/test-web3-rpc-handler.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/src/exec/fullnode.ts, packages/rollup-full-node/src/types/errors.ts, packages/rollup-full-node/src/types/web3-rpc-handler.ts, packages/rollup-full-node/test/app/fullnode-rpc-server.spec.ts, packages/solc-transpiler/package.json
Right now transactions that revert don't return the proper payload. This ticket fixes it such that reverts conform to standard revert payloads.
- Fixes # [YAS-210](https://optimists.atlassian.net/browse/YAS-210)
=> Fixing return payload for reverts

packages/core-db/package.json, packages/core-utils/package.json, packages/core-utils/src/app/buffer.ts, packages/core-utils/test/app/buffer.spec.ts, packages/docs/package.json, packages/optimistic-game-semantics/package.json, packages/ovm-truffle-provider-wrapper/package.json, packages/ovm/package.json, packages/rollup-contracts/package.json, packages/rollup-core/package.json, packages/rollup-dev-tools/package.json, packages/rollup-dev-tools/src/tools/transpiler/jump-replacement.ts, packages/rollup-dev-tools/test/helpers.ts, packages/rollup-dev-tools/test/transpiler/constructor-transpilation.spec.ts, packages/rollup-dev-tools/test/transpiler/transpile.jump.spec.ts, packages/rollup-full-node/package.json, packages/solc-transpiler/package.json
Before this, all PUSHs for the JUMP table JUMPDESTs were PUSH32s. This makes them all PUSH2s.
- Fixes # [YAS-235](https://optimists.atlassian.net/browse/YAS-235)
=> Optimizing JUMP table PUSH32s

packages/core-db/package.json, packages/core-utils/package.json, packages/docs/package.json, packages/optimistic-game-semantics/package.json, packages/ovm-truffle-provider-wrapper/package.json, packages/ovm/package.json, packages/ovm/src/app/utils.ts, packages/ovm/src/contracts/ExecutionManager.sol, packages/ovm/src/types/index.ts, packages/ovm/src/types/transactionReceipt.ts, packages/ovm/test/app/utils.spec.ts, packages/ovm/test/helpers.ts, packages/rollup-contracts/package.json, packages/rollup-core/package.json, packages/rollup-dev-tools/package.json, packages/rollup-full-node/package.json, packages/rollup-full-node/src/app/fullnode-rpc-server.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/solc-transpiler/package.json, yarn.lock
Makes revert messages flow through from the contract where the revert is called to the caller.
- Fixes # [YAS_244](https://optimists.atlassian.net/browse/YAS-244)
-  [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.
=> Making revert messages flow through to the caller

packages/core-utils/src/app/misc.ts, packages/rollup-full-node/src/app/test-web3-rpc-handler.ts, packages/rollup-full-node/test/app/test-handler.spec.ts
Fix `evm_increaseTime` bugs:
* `evm_increaseTime` should accepts numbers as well as hex strings
* `evm_revert` should revert changes made by `evm_increaseTime`
- Fixes # [YAS-243](https://optimists.atlassian.net/browse/YAS-243)
=> Fix evm_increaseTime bugs

packages/rollup-full-node/src/app/fullnode-rpc-server.ts, packages/rollup-full-node/test/app/fullnode-rpc-server.spec.ts
Making the Full Node handle batch RPC requests.
- Fixes # [YAS-246](https://optimists.atlassian.net/browse/YAS-246)
=> Making Full Node Handle batch RPC Requests

.github/workflows/dev-ecr-deploy.yml, Dockerfile, docker-compose.yml
Using linked packages instead of those in npm. 
Allows for deployments to dev that reflect repo changes and don't require publish to npm.
=> Using linked packages instead of those in npm

packages/core-utils/src/app/misc.ts, packages/rollup-full-node/package.json, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/test/app/test-handler.spec.ts, packages/rollup-full-node/test/contracts/untranspiled/EmptyContract.sol
Support historical code lookups if the block number is current
- Fixes # [YAS-208](https://optimists.atlassian.net/browse/YAS-208)
=> Support historical code lookups if the block number is current

packages/rollup-full-node/src/app/web3-rpc-handler.ts
Fixes issue where we were returning 0x10 for getTransactionCount instead of 0xa. The issue was that we were calling .toString(16) on a BigNumber, not a number.
None
None
=> Fix bug w/ conversion of nonce to hex

Dockerfile, docker-compose.yml, docker/geth/entrypoint.sh, packages/rollup-full-node/exec/wait-for-nodes.sh, packages/rollup-full-node/src/app/utils/environment.ts, packages/rollup-full-node/src/app/utils/l2-node.ts
* Modifying geth Dockerfile to bootstrap if not already bootstrapped and run
* Adding wait-for-nodes.sh script to make rollup-full-node wait for external node instances to start before starting up
- Fixes # [YAS-272](https://optimists.atlassian.net/browse/YAS-272)
=> Yas 272/geth config changes

packages/core-utils/src/app/misc.ts, packages/core-utils/src/app/test-utils.ts, packages/ovm/src/contracts/ExecutionManager.sol, packages/ovm/test/contracts/execution-manager.call-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.context-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.executeCall.spec.ts, packages/ovm/test/contracts/execution-manager.l1-l2-opcodes.spec.ts, packages/ovm/test/contracts/simple-storage.spec.ts, packages/ovm/test/contracts/tx-origin.spec.ts, packages/ovm/test/helpers.ts
...instead of when calling ovmTimestamp
Transpiled calls to ovmTimestamp don't check the result of the call so
requires are ignored. Instead we check validity of the timestamp in
`executeUnsignedEOACall`. This required us to set valid timestamps in
other calls to the ExecutionManager as well.
- Fixes # [YAS-192](https://optimists.atlassian.net/browse/YAS-192)
=> `require` timestamp is set on execution

packages/ovm/src/app/utils.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts
Fixing issue where fetching a receipt for a tx hash that we do not have results in an error.
=> Receipt Query Fix

docker/geth/Dockerfile, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/test/integration/message-passing-integration.spec.ts, packages/test-synthetix-synth/truffle-tests/contracts/Owned.js
1. Uses forked Geth which disables contract code size limits
2. Ensures that we don't try to get transaction receipts until the transaction is mined.
=> Geth Compatibility

packages/ovm/src/contracts/ExecutionManager.sol, packages/ovm/test/contracts/execution-manager.call-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.context-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.l1-l2-opcodes.spec.ts, packages/ovm/test/helpers.ts
`ExecutionManager#executeTransactionRaw` just called `executeTransaction` so it was no longer needed. Remove `ExecutionManager#executeTransactionRaw` and use `ExecutionManager#executeTransaction` instead.
- Fixes # [YAS-256](https://optimists.atlassian.net/browse/YAS-256)
=> Remove `ExecutionManager#executeTransactionRaw`

packages/solc-transpiler/src/compiler.ts
When, for example, we transpile an interface, we will use `solc.compile`, which will output an empty bytecode and null deployedBytecode object. We shouldn't be trying to transpile non-existent bytecode
=> Null-Checking for bytecode in solc-transpiler

aws/README.md, aws/dev/full-node/docker-compose.yml, aws/dev/full-node/ecs-params.yml
Adds information on how to create an environment in AWS
=> Adding environment creation / maintenance instructions

docker/README.md, docker/publish-geth-container.sh, docker/publish-rollup-fullnode-container.sh
Adds scripts to publish our docker containers to AWS
- Fixes # [YAS-300](https://optimists.atlassian.net/browse/YAS-300)
=> Adding publish scripts for publishing docker containers to ECR.

packages/rollup-full-node/src/app/web3-rpc-handler.ts
Fixes bugs with metamask, ethers. You should be able to do a call() without setting a from address, but currently we require a from address. This is a temporary fix.
=> Add dummy from address for calls

packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/src/types/web3-rpc-handler.ts, packages/rollup-full-node/test/app/web-rpc-handler.spec.ts
Add `eth_getBalance` endpoint
- Fixes # [YAS-301](https://optimists.atlassian.net/browse/YAS-301)
=> Add `eth_getBalance` endpoint

packages/ovm/src/app/utils.ts, packages/ovm/src/contracts/L2ExecutionManager.sol, packages/ovm/test/contracts/l2-execution-manager.spec.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/src/types/web3-rpc-handler.ts, packages/rollup-full-node/test/app/web-rpc-handler.spec.ts
Also makes sure that returned receipts have the correct OVM tx hash instead of EVM tx hash.
- Fixes # [YAS-312](https://optimists.atlassian.net/browse/YAS-312)
=> Add eth_getTransactionByHash endpoint

packages/rollup-full-node/exec/fullnode-test.js, packages/rollup-full-node/package.json
Allows the deployment of a local full node in test mode (using ganache). This is necessary for many projects which require you to spin up a local ganache node to start testing (e.g. tornado cash, moloch dao).
- Fixes # YAS304
=> Add test mode script for full node

packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/test/app/web-rpc-handler.spec.ts
Previously we were filtering transactions in parseInternalBlock that weren't equal to the ZERO_ADDRESS. The zero hash is actually 32 bytes instead of the 20 byte ZERO_ADDRESS. The filter condition was also reversed  which it why it was passing tests.
=> Fix parseInternalBlock transaction filtering bug

aws/dev/full-node/docker-compose.yml, aws/dev/full-node/ecs-params.yml, aws/synthetix/dev/full-node/docker-compose.yml, aws/synthetix/dev/full-node/ecs-params.yml, docker-compose.yml, docker/publish-the-graph-container.sh, docker/the-graph/Dockerfile, docker/the-graph/wait-for-ovm.sh, packages/test-ovm-full-node/src/simple-storage-stress-test.ts, packages/test-ovm-full-node/src/stress-test.ts
Creates The Graph container entrypoint, build, and push scripts and updates the docker-compose.yml file to start the full stack.
- Fixes # [YAS-298](https://optimists.atlassian.net/browse/YAS-298)
=> The Graph Container

packages/ovm/src/contracts/L2ExecutionManager.sol, packages/ovm/test/contracts/l2-execution-manager.spec.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/test/app/web-rpc-handler.spec.ts
Map internal transactions to external (OVM) transactions. Previously we were querying internal transaction hashes by internal transaction hashes. Now we correctly query external (OVM) transaction hashes and update applicable fields.
=> Map internal transactions to external (OVM) transactions

packages/rollup-full-node/src/app/web3-rpc-handler.ts
This allows `sendRawTransaction(...)` to not wait for the OVM -> EVM tx mapping transaction to proceed processing, reducing latency.
- Fixes # [YAS-326](https://optimists.atlassian.net/browse/YAS-326)
=> Adding tx detail cache to sendRawTransaction

packages/rollup-full-node/src/app/test-web3-rpc-handler.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/src/types/web3-rpc-handler.ts, packages/rollup-full-node/test/app/test-web-rpc-handler.spec.ts
Adds the test rpc endpoint for eth_accounts
- Fixes # YAS291
=> Add eth_accounts endpoint

packages/core-utils/src/app/misc.ts, packages/rollup-full-node/src/app/test-web3-rpc-handler.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/test/app/test-web-rpc-handler.spec.ts, packages/rollup-full-node/test/contracts/transpiled/CallerStorer.sol
This PR makes the test web3 handler be much more permissive with accounts, making the `eth_sendTransaction` parameters compliant with the specification.  Note that behavior does differ a little bit from other RPC provision--instead of only allowing this on accounts which are unlocked, we bypass/override signature checking and allow any `.from` to be valid in the test case.
Is there a cleaner way to do this, short of incorporating a full-blown account management system into the provider?  Chatted with @karlfloersch for a bit about it; we concluded not.
- Fixes YAS 292
=> YAS 292: fix test provider's `eth_sendTransaction` behavior

packages/ovm/src/app/utils.ts, packages/ovm/src/contracts/ExecutionManager.sol, packages/ovm/test/app/utils.spec.ts, packages/rollup-full-node/src/app/utils/l2-node.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/test/app/test-web-rpc-handler.spec.ts, packages/rollup-full-node/test/app/web-rpc-handler.spec.ts, packages/rollup-full-node/test/contracts/transpiled/SimpleReversion.sol
PR adds support for propagating internal EVM error messages up to the OVM caller for both `eth_call` and `eth_sendTransaction`
We previously were able to accomplish this by having the EM's event logs indicate reverts, but not having the internal transactions themselves revert.  Now that we are not waiting for transactions to be mined, we had to go back to the model where a reverting OVM transaction reverts the internal EVM transaction, too.  This adds a bit of complication for receipts, but it's manageable. 
Also incorporates some random bugfixes from a hotfix branch of @K-Ho 's.
- Should we remove `allowRevert` from EM which appears to be only ever set to true?  My bias is towards leaving it for now as we may need to change things up again in the future.
- Fixes YAS 328
=> Surfacing revert messages for eth_call and eth_sendRawTransaction

packages/ovm/src/app/utils.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/src/types/web3-rpc-handler.ts, packages/rollup-full-node/test/app/web-rpc-handler.spec.ts
Fix eth_getLogs bugs
Note:
Logs need to be converted to objects via `JSON.parse(JSON.stringify(x))`
because the Log object's logIndex type is a `number` where here we need
to set it to a `string` (the hex encoded number).
Fixes:
* address
* logIndex
* transactionHash
- Fixes # [YAS-303](https://optimists.atlassian.net/browse/YAS-303)
=> Fix eth_getLogs bugs

.github/workflows/synthetix-prod-ecr-deploy.yml
=> Fixing prod CD script

packages/rollup-full-node/src/app/web3-rpc-handler.ts
Fixes bugs with Synthetix getLogs - full credit to @ben-chain !!
=> Remove "to" field override in getLogs

aws/synthetix/dev/README.md, aws/synthetix/dev/full-node/docker-compose.yml, aws/synthetix/dev/full-node/ecs-params.yml, aws/synthetix/prod/geth/ecs-params.yml, aws/synthetix/prod/web/README.md, aws/synthetix/prod/web/docker-compose.yml, aws/synthetix/prod/web/ecs-params.yml, aws/synthetix/uat/geth/ecs-params.yml, aws/synthetix/uat/web/README.md, aws/synthetix/uat/web/docker-compose.yml, aws/synthetix/uat/web/ecs-params.yml, packages/rollup-full-node/src/app/routing-handler.ts, packages/test-ovm-full-node/src/simple-storage-stress-test.ts
Updating deployment scripts for The Graph, the router / routed servers, and updating CPU shares.
- Fixes # [YAS-333](https://optimists.atlassian.net/browse/YAS-333)
=> Updating environment deploy scripts with new containers

packages/rollup-full-node/src/app/web3-rpc-handler.ts
Reverts ethereum-optimism/optimism-monorepo#113
Turns out this does not fix how we are parsing the logs & instead just breaks a test.
To properly fix `getLogs` we will likely need to use a `codeContractAddress` to `ovmContractAddress` mapping to look up the `ovmContractAddress` of arbitrary logs.
=> Revert "Remove "to" field override in getLogs"

package.json, packages/core-utils/src/app/log.ts, packages/ovm/src/app/utils.ts, packages/rollup-full-node/package.json, packages/rollup-full-node/src/app/test-web3-rpc-handler.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts, packages/rollup-full-node/src/types/web3-rpc-handler.ts, packages/rollup-full-node/test/app/web-rpc-handler.spec.ts, yarn.lock
* Add type checks for RPC call parameters
* Concatenate logs onto a single line to reduce noise
* Concatenate log parsing logs onto a single line
- Fixes # [YAS-322](https://optimists.atlassian.net/browse/YAS-322)
=> Clean up logging

packages/core-utils/src/app/test-utils.ts, packages/core-utils/src/app/transport/client/json-rpc-client.ts, packages/core-utils/src/app/transport/client/simple-client.ts, packages/rollup-full-node/src/app/fullnode-rpc-server.ts, packages/rollup-full-node/src/app/routing-handler.ts, packages/rollup-full-node/src/types/errors.ts, packages/rollup-full-node/test/app/routing-handler.spec.ts
Right now the router throws when it receives JSON RPC Errors. It should just forward those along as is. This change makes it do that.
=> Making Router handle JSON RPC Errors

packages/rollup-full-node/src/app/routing-handler.ts, packages/rollup-full-node/test/app/routing-handler.spec.ts
The router still logs FormattedJsonRpcErrors as errors, even though they should not be. This fixes that.
=> Fixing catch of formatted json rpc error

.github/workflows/synthetix-prod-ecr-deploy.yml, .github/workflows/synthetix-uat-ecr-deploy.yml
Makes it so that merge to UAT / PROD does not automatically restart servers. We will likely want to be more intentional with timing
=> No automated deploys to UAT or PROD

aws/synthetix/prod/web/ecs-params.yml, aws/synthetix/uat/web/ecs-params.yml, docker/the-graph/wait-for-ovm.sh
Adding ability to clear The Graph data by setting CLEAR_DATA_KEY environment variable.
- Fixes # [YAS-336](https://optimists.atlassian.net/browse/YAS-336)
=> Ability to clear The Graph data

aws/synthetix/dev/full-node/docker-compose.yml, aws/synthetix/prod/web/docker-compose.yml, aws/synthetix/uat/web/docker-compose.yml, docker/the-graph/wait-for-ovm.sh
- Changing sh script `&&` -> `-a` and braces because of version of sh on debian.
- Changing the DEV / UAT / PROD scripts to mount the postgres & IPFS volumes
=> changing sh script because of version of sh on debian

aws/synthetix/prod/web/docker-compose.yml, aws/synthetix/uat/web/docker-compose.yml, docker-compose.yml
updating config so The Graph points directly at the tx node.
=> updating config so The Graph points directly at the tx node

packages/core-utils/src/app/log.ts, packages/ovm/src/app/utils.ts
We  buffer interim debug log statements while converting EVM event logs to OVM event logs. Sometimes the volume of data logged (buffered) is large enough to cause our node to run out of memory. This makes it so we don't buffer nearly as much info.
- Fixes # [YAS-339](https://optimists.atlassian.net/browse/YAS-339)
=> Stopping our event parsing logging from OOMing our read-only node

packages/rollup-full-node/src/app/account-rate-limiter.ts, packages/rollup-full-node/src/app/routing-handler.ts, packages/rollup-full-node/test/app/account-rate-limiter.spec.ts, packages/rollup-full-node/test/app/routing-handler.spec.ts
Adding logic to refresh environment variable config at some frequency so small configuration changes can be updated without restarting.
- Fixes # [YAS-340](https://optimists.atlassian.net/browse/YAS-340)
=> Environment Variable Refresh

packages/docs/src/core/src/spec/jump-transpilation.rst, packages/docs/src/core/src/spec/overview.rst, packages/docs/src/core/src/spec/transpilation-details.rst, packages/ovm/config/.env.example, packages/ovm/deploy/execution-manager.ts, packages/ovm/deploy/safety-checker.ts, packages/ovm/package.json, packages/ovm/src/contracts/ExecutionManager.sol, packages/ovm/src/contracts/L2ExecutionManager.sol, packages/ovm/src/contracts/SafetyChecker.sol, packages/ovm/test/contracts/execution-manager.create-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.purity-checking.spec.ts, packages/ovm/test/contracts/safety-checker.spec.ts, packages/ovm/test/contracts/whitelist-mask-generator.spec.ts
Renames our Purity Checker to Safety Checker as it does not technically enforce that contracts are pure funcitons.
- 
-
-
=> Renaming Purity Checker -> Safety Checker

packages/rollup-full-node/src/exec/fullnode.ts
Fixing bug where $DELETE$ can get set as env var sometimes
=> Fixing bug where $DELETE$ can get set as env var sometimes

Dockerfile, Dockerfile.dev, README.md, aws/synthetix/prod/web/docker-compose.yml, aws/synthetix/uat/web/docker-compose.yml, docker-compose.dev.yml, docker-compose.yml, packages/core-utils/src/app/log.ts, packages/docs/src/core/src/spec/jump-transpilation.rst, packages/docs/src/core/src/spec/overview.rst, packages/docs/src/core/src/spec/transpilation-details.rst, packages/ovm/config/.env.example, packages/ovm/deploy/execution-manager.ts, packages/ovm/deploy/safety-checker.ts, packages/ovm/package.json, packages/ovm/src/app/utils.ts, packages/ovm/src/contracts/ExecutionManager.sol, packages/ovm/src/contracts/L2ExecutionManager.sol, packages/ovm/src/contracts/SafetyChecker.sol, packages/ovm/test/contracts/execution-manager.create-opcodes.spec.ts, packages/ovm/test/contracts/execution-manager.purity-checking.spec.ts, packages/ovm/test/contracts/safety-checker.spec.ts, packages/ovm/test/contracts/whitelist-mask-generator.spec.ts, packages/rollup-full-node/config/env_var_updates.config, packages/rollup-full-node/src/app/account-rate-limiter.ts, packages/rollup-full-node/src/app/routing-handler.ts, packages/rollup-full-node/src/exec/fullnode.ts, packages/rollup-full-node/test/app/account-rate-limiter.spec.ts, packages/rollup-full-node/test/app/routing-handler.spec.ts
=> Prod release 5/4

packages/core-utils/src/app/log.ts, packages/core-utils/test/app/log.spec.ts
Making logging always log a single line, never multiple. We can easily format after the fact by replacing new line replacements.
- Fixes # [YAS-364](https://optimists.atlassian.net/browse/YAS-364)
=> Making log statements a single line

packages/rollup-full-node/src/app/web3-rpc-handler.ts
Handling failed transaction gracefully in getTransactionReceipt(...)
- Fixes # [YAS-366](https://optimists.atlassian.net/browse/YAS-366)
=> Handling failed transaction error

packages/rollup-contracts/contracts/L1ToL2TransactionQueue.sol, packages/rollup-contracts/contracts/RollupList.sol, packages/rollup-contracts/test/rollup-list/L1ToL2TransactionQueue.spec.ts
Implementation of L1ToL2 Transaction Queue. I will eventually separate the RollupList into RollupQueue and RollupStack contracts to clean up this code, but will do so once I implement the rest of the queues/stacks and know what the best way to do that separation is.
- Should we move the L1ToL2TransactionPasser into the `rollup-contracts` package?
- Fixes #YAS371
=> L1 To L2 Transaction Queue

packages/rollup-contracts/contracts/SequencerBatchSubmitter.sol, packages/rollup-contracts/test/rollup-list/SequencerBatchSubmitter.spec.ts
Helper contract that allows the sequencer to submit both a state commitment batch and tx batch in a single transaction. This is the contract that will be whitelisted for instant submission to the CanonicalTransactionChain.
NOTE: This PR builds off of #143  
- Fixes #YAS-408
=> Sequencer Batch Submitter

packages/ovm/config/.env.example, packages/ovm/deploy/safety-checker.ts, packages/ovm/test/contracts/safety-checker.spec.ts, packages/ovm/test/contracts/whitelist-mask-generator.spec.ts, packages/rollup-core/src/app/constants.ts, packages/rollup-core/src/types/opcodes.ts, packages/rollup-dev-tools/src/tools/transpiler/opcode-whitelist.ts
`CHAINID`, opcode `0x46` was added in the Istanbul hard fork and is used in Uniswap V2- update opcode types to add this opcode and whitelist it in both the SafetyChecker and Transpiler. Also adds the other opcode added in the hard fork, `SELFBALANCE`, `0x47` - this should be blacklisted for both the Transpiler and SafetyChecker
Note, CHAINID still needs to be transpiled - this is listed as YAS-414
- Fixes #YAS-413
=> Add CHAINID and SELFBALANCE opcodes

README.md, packages/docs/developer-documentation/getting-started/README.md, packages/test-ERC20-Waffle/README.md
Updates docs discord links to be permanent.
=> Fix discord links

packages/rollup-full-node/src/app/utils.ts, packages/test-ERC20-Waffle/test/erc20.spec.js, packages/test-ovm-full-node/test/library-support.spec.ts
Adds a function `addHandlerToProvider`, which allows the shimming of `send` of any provider, so they are processed by the OVM `fullNodeHandler`. 
Also, cleans up the `createMockProvider` function.
We could just get rid of createMockProvider and instead enforce anyone who uses waffle to just create their own provider and call `addHandlerToProvider(provider)`. Thoughts?
- Fixes #YAS-419
=> Better utils for creating OVM Providers

packages/test-ERC20-Truffle/package.json
=> Add ovm truffle provider wrapper as dep

packages/contracts/contracts/optimistic-ethereum/ovm/ExecutionManager.sol, packages/contracts/contracts/optimistic-ethereum/ovm/FullStateManager.sol, packages/contracts/contracts/optimistic-ethereum/ovm/PartialStateManager.sol, packages/contracts/contracts/optimistic-ethereum/ovm/StateManager.sol, packages/rollup-full-node/src/app/utils.ts, packages/rollup-full-node/src/app/web3-rpc-handler.ts
Fixes issues with events not having the correct address by simply storing a reverse mapping of code contract address -> ovm contract address and mapping event/log code contract addresses to ovm addresses when parsing.
- Should we completely remove event emissions from the Execution Manager? (this would probably require a new ticket)
- Fixes #YAS-488
=> Fix Event Parsing

packages/rollup-full-node/src/app/util/l2-node.ts
Closes https://github.com/ethereum-optimism/optimism-monorepo/issues/136
Confirmed the bug as described in #136, implemented the given solution and confirmed that it fixes the problem.
To reproduce, be sure to rebuild the typescript and the `optimism-monorepo_rollup-full-node` docker image so that the changes are included in the container. In the `docker-compose.yml` file, comment out the `L2_WALLET_PRIVATE_KEY` environment variable and add the `L2_WALLET_MNEMONIC` environment variable like so:
```
- L2_WALLET_MNEMONIC=abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about
```
Run `docker-compose up` and you should be able to see the logline from the rollup full node: `Initialized wallet from mnemonic. Address: 0x...`.
- I think that part of the …
=> rollup-full-node: fix wallet init from mnemonic

packages/rollup-core/src/app/data/consumers/queued-geth-submitter.ts, packages/rollup-core/src/app/data/data-service.ts, packages/rollup-core/src/app/data/producers/l2-chain-data-persister.ts, packages/rollup-core/src/app/l2-node-service.ts, packages/rollup-core/src/types/data/l1-data-service.ts, packages/rollup-core/src/types/l2-node-service.ts, packages/rollup-core/src/types/types.ts, packages/rollup-core/test/app/l2-chain-data-persister.spec.ts, packages/rollup-core/test/app/l2-node-service.spec.ts, packages/rollup-core/test/app/queued-geth-submitter.spec.ts, packages/rollup-core/test/integration/geth-submitter-integration.spec.ts
Adds L1RollupTxId to RollupTransactions so it can be passed in submissions to geth.
Also renames BlockBatches and decreases their size from all of the batches that were in one L1 block to a single batch from a single event log from an L1 block.
- Fixes # [YAS-550](https://optimists.atlassian.net/browse/YAS-550)
=> Add L1RollupTxId to RollupTransaction

packages/contracts/test/deployment/deployment.spec.ts, packages/contracts/test/deployment/geth-input-dump.spec.ts, packages/test-ERC20-Truffle/package.json
Quick PR which adds a script (added in our test suite) for creating a state dump. Also, add in a quick fix which optimizes the ExecutionManager by caching the `StateManager` address.
- Partially fixes YAS 350
=> Add geth dump input and optimize ExecutionManager

db/scripts/4_create_views.sql
Adding `block_number` to fields in the `next_queued_geth_submission` view to fix a dependent query.
=> fixing missing block_number in view

packages/contracts/contracts/optimistic-ethereum/ovm/SafetyChecker.sol
* Replace ops array with a uint256
* Replace 2 ** op with 1 << op
* Add a fast outer opcode check to the list of if statements
Running tests now (they pass), shouldn't change any functionality, and uses about 40% of previous gas. There's more possible, but this is the low hanging fruit, closes #209
=> Halve gas used by SafetyChecker

packages/contracts/contracts/optimistic-ethereum/ovm/StateTransitioner.sol, packages/contracts/test/contracts/ovm/StateTransitioner.spec.ts
This ticket was originally to cover preventing max call depth inconsistency between L1 and L2.  However, it turns out due to [EIP 150](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md), there is already an implicit upper bound on the call stack due to an exponential dropoff of max allottable gas per CALL.
This ticket enforces that sufficient gas is provided to the fraud proof so that EIP150 does not allow for multiple execution results based on input gas.
Note: this logic might be better off directly within `executeTransaction` (would remove the need for `MAX_EXECUTE_TRANSACTION_OVERHEAD` in STioner), but that breaks a ton of tests.  We can revisit next time tests get an overhaul.
- Fixes YAS 562
=> Ensuring sufficient gas for L1 determinism

packages/ovm-toolchain/buidler.config.ts, packages/ovm-toolchain/package.json, packages/ovm-toolchain/src/buidler-plugins/buidler-ovm-node.ts, packages/ovm-toolchain/src/ganache.ts, packages/ovm-toolchain/test/test-buidler/erc20.spec.ts, packages/ovm-toolchain/test/test-waffle-v2/core/create2.spec.ts, packages/ovm-toolchain/test/test-waffle-v2/core/libraries.spec.ts, packages/ovm-toolchain/test/test-waffle-v2/core/precompiles.spec.ts, packages/ovm-toolchain/test/test-waffle-v2/core/timestamps.spec.ts, packages/ovm-toolchain/test/test-waffle-v2/erc20.spec.ts, yarn.lock
This is a patch for the `ovm-toolchain` package that "fixes" issues with gas estimation in `ganache` and `buidler`. I hijacked the `estimateGas` functions of each to simply return the block gas limit because (for whatever reason) gas estimation doesn't work.
=> Fixed issues with gas estimation in ovm-toolchain

packages/core-db/src/app/ethereum/ethereum-block-processor.ts
Fixes issue where we don't re-throw when block subscription errors are caught, causing us to move on with block syncing and not re-fetch.
=> fixing issue where we can silently fail and stall block processing

packages/ovm-toolchain/buidler.config.ts, packages/ovm-toolchain/package.json, packages/ovm-toolchain/src/buidler-plugins/buidler-ovm-node.ts
Updates the buidler ovm node plugin to expose a function `startOvmNode` that can be called within a task based on an `ovm` flag. This is needed for how Synthetix has their Buidler config set up.
None
- Fixes #YAS-634
=> Update Buidler OVM node plugin to work within tasks

packages/contracts/package.json, packages/core-db/package.json, packages/core-utils/package.json, packages/ovm-toolchain/package.json
Updated package.json files for newly published packages
Question for @kfichter - can we make the `contracts` and `ovm-toolchain` packages public?
- Fixes #YAS-632
=> Published new packages

packages/rollup-core/src/app/data/consumers/canonical-chain-batch-submitter.ts, packages/rollup-core/src/types/errors.ts, packages/rollup-core/test/app/canonical-chain-batch-submitter.spec.ts, packages/rollup-services/src/exec/services.ts
Adds validation that matches smart contract validation to Batch Submitter jobs to not submit (and pay for) transactions that will predictably fail.
- Fixes # [YAS-593](https://optimists.atlassian.net/browse/YAS-593)
=> Don't submit batches that will fail smart contract validation

packages/ovm-toolchain/package.json, packages/ovm-toolchain/src/buidler-plugins/buidler-ovm-compiler.ts, yarn.lock
Adds a config option:
``` 
config: {
solc: {
native: true
}
}
```
That will use the native `solc` compiler. This is necessary to quickly test changes to the solidity compiler, as compiling to `solcjs` take ~25 minutes.
None
- Fixes #YAS-636
=> Add native solc option

packages/ovm-toolchain/buidler.config.ts, packages/ovm-toolchain/package.json
This PR is to aid in the testing of `YAS-637`, allowing us to test the v0.6 solc fork w/ `native` against the `ovm-toolchain`.
- Fixes #
=> Add native flag to ovm toolchain tests

packages/contracts/contracts/test-helpers/FraudTester.sol
This ticket covers YAS 618, which was a bug in our fraud tester.  Somehow, upon revisiting, the bug appears gone.  Woo!
N/A
- Fixes YAS 618
=> Re-enabling FraudTester deployment check

packages/ovm-toolchain/src/buidler-plugins/buidler-ovm-node.ts
Patch to fix the ovm node for synthetix tests
- Fixes
=> Added init step for ovm node

packages/ovm-toolchain/src/waffle/waffle-v2.ts
This small PR adds a check in our `waffleV2` export that `_web3Provider` is defined, as some dev environments with strict `tsconfig`s previously rejected builds because the dependency `invokes an object which is potentially undefined`.
=> ovm-toolchain: check waffle provider defined

packages/contracts/contracts/optimistic-ethereum/chain/CanonicalTransactionChain.sol, packages/contracts/contracts/optimistic-ethereum/chain/StateCommitmentChain.sol, packages/contracts/test/contracts/chain/CanonicalTransactionChain.spec.ts, packages/contracts/test/contracts/chain/StateCommitmentChain.spec.ts, packages/contracts/test/contracts/ovm/FraudVerifier.spec.ts, packages/contracts/test/contracts/ovm/StateTransitioner.spec.ts, packages/contracts/test/contracts/ovm/execution-manager/ExecutionManager.create-opcodes.spec.ts, packages/contracts/test/contracts/ovm/execution-manager/ExecutionManager.executeCall.spec.ts, packages/contracts/test/contracts/queue/L1ToL2TransactionQueue.spec.ts, packages/contracts/test/contracts/queue/RollupQueue.spec.ts, packages/contracts/test/contracts/queue/SafetyTransactionQueue.spec.ts, packages/contracts/test/test-helpers/types/batch.ts, packages/core-db/src/app/ethereum/ethereum-block-processor.ts, packages/core-utils/src/app/test-utils.ts, packages/rollup-core/src/app/data/consumers/canonical-chain-batch-submitter.ts, packages/rollup-core/src/app/data/consumers/state-commitment-chain-batch-submitter.ts, packages/rollup-core/src/app/data/data-service.ts, packages/rollup-core/src/app/data/producers/log-handlers.ts, packages/rollup-core/src/types/data/l1-data-service.ts, packages/rollup-core/src/types/data/types.ts, packages/rollup-core/src/types/errors.ts, packages/rollup-core/test/app/canonical-chain-batch-submitter.spec.ts, packages/rollup-core/test/app/log-handlers.spec.ts, packages/rollup-core/test/db/l1-data-service.dbspec.ts
Adds a `startsAtIndex` field for sequencer batch appends to prevent race conditions from causing errors.
- Fixes # [YAS-635](https://optimists.atlassian.net/browse/YAS-635)
=> Adding startsAtIndex to sequencer batch appending

packages/ovm-toolchain/src/ganache.ts
This adds a default argument to the `wrap` function so that it doesn't throw an error when no argument is provided. Both of the unwrapped `ganache.server` and `ganache.provider` handle the case of no argument being passed in, right now an empty object must be passed in to prevent an error from being thrown for the wrapper versions. This will allow both wrapped versions to be called without an argument.
=> ovm-toolchain: default arg for ganache construction

.github/workflows/testnet-ecr-build-push.yml, .github/workflows/uat-ecr-build-push.yml
Adding build & push task on merge to uat and testnet, respectively
- Fixes # [YAS-530](https://optimists.atlassian.net/browse/YAS-530)
=> Adding build & push task on merge to uat and testnet, respectively

packages/provider/README.md, packages/provider/src/app/network.ts
This adds in the url for the public ropsten node so that the provider can be instantiated like:
```js
const provider = new OptimismProvider('gorli')
```
This would set the hostname as `rinkeby.optimism.io`.
Also notes this in the `README.md`
- What is the actual url that is going to be used?
=> provider: add in gorli support

packages/core-db/src/app/ethereum/ethereum-block-processor.ts
Making it so that after the first tx in a block is final, we check to make sure it is in the same block and if not re-fetch the block by number to handle re-orgs.
=> Fixing Block Subscription Re-orgs

packages/contracts/src/deployment/contract-deploy.ts, packages/core-db/src/app/ethereum/ethereum-block-processor.ts
Fixes infinite error loop on syncing an empty block by waiting for the block X blocks after it to exist.
=> Fixing block hang on syncing empty blocks

docker-compose.example.yml, packages/core-db/src/app/ethereum/ethereum-block-processor.ts, packages/core-db/test/app/ethereum/ethereum-block-processor.spec.ts, packages/core-db/test/app/ethereum/utils.ts
Simplifies block subscription by finalizing the block X blocks ago when a block is received. Also adds more tests for the transition between syncing past blocks and current/future blocks.
=> Simplifying block subscription

packages/provider/src/app/signer.ts
Previously our `OptimismSigner`'s `provider` was the `Web3Provider` (from metamask) and `optimism` was set to the `OptimismProvider`. This leads to issues where `signer.provider` is used by default. This PR changes `signer.provider` to be the `OptimismProvider` and adds `signer.web3` which is the `Web3Provider` (from metamask)
- Fixes #
=> Set signer.provider to OptimismProvider

packages/provider/src/app/provider.ts
Adds additional txmeta fields from l2geth
https://github.com/ethereum-optimism/go-ethereum/pull/35
=> provider: include txmeta in transaction response

packages/contracts/contracts/optimistic-ethereum/ovm/ExecutionManager.sol, packages/contracts/contracts/optimistic-ethereum/ovm/precompiles/DeployerWhitelist.sol, packages/contracts/test/contracts/ovm/StateTransitioner.spec.ts, packages/contracts/test/contracts/ovm/execution-manager/ExecutionManager.executeCall.spec.ts
This PR sets up the previously created `DeployerWhitelist` to be an OVM precompile, and fixes the context before it is called, so that it may use OVM storage.
- The whitelist is associated with OVM address `0x4200000000000000000000000000000000000002`.
- The whitelist now uses `function initialize(address _owner, bool _allowArbitraryDeployment)` in place of a constructor.
=> Setup whitelist as OVM precompile

db/scripts/3_create_l2_tables.sql, packages/rollup-core/src/app/constants.ts, packages/rollup-core/src/app/data/consumers/canonical-chain-batch-submitter.ts, packages/rollup-core/src/app/data/producers/log-handlers.ts, packages/rollup-core/test/app/log-handlers.spec.ts
Accounting for 66-byte signatures.
Updating:
* Rollup tx format documentation in canonical chain batch submitter
* log-handlers to parse rolled up txs as having 66-byte signatures
* Queries that account for total tx size to be 150 bytes without calldata instead of 149
=> Accounting for 66-byte signatures

db/scripts/4_create_views.sql, packages/rollup-core/src/app/data/data-service.ts, packages/rollup-core/src/types/data/l2-data-service.ts, packages/rollup-core/test/db/helpers.ts, packages/rollup-core/test/db/l2-data-service.dbspec.ts, packages/rollup-core/test/db/verifier-data-service.dbspec.ts
Fixes an issue where state batches and tx batches may be built in differing orders, leading to fraudulent batches being posted on-chain.
- Fixes #295
=> Fixing Tx / State Batch Creation Inconsistencies

packages/core-utils/src/app/crypto.ts, packages/rollup-core/src/app/data/data-service.ts, packages/rollup-core/src/app/data/producers/l1-chain-data-persister.ts, packages/rollup-core/src/app/data/producers/log-handlers.ts, packages/rollup-services/src/exec/services.ts
Fix our L1ToL2Transaction ingestion logic so that it passes some integration tests which I will add to the integration tests repository shortly.
- @willmeister does the change `rollupTransaction.l1TxLogIndex = l.logIndex` look right to you?
- Partially addresses https://github.com/ethereum-optimism/optimistic-rollup-integration-tests/issues/9
=> Fix L1ToL2 tx postgres ingestion

packages/core-db/src/app/queue/sequential-processing-data-service.ts, packages/rollup-core/src/app/data/consumers/canonical-chain-batch-submitter.ts, packages/rollup-core/src/app/data/data-service.ts, packages/rollup-core/src/app/data/producers/l1-chain-data-persister.ts, packages/rollup-core/src/types/data/l2-data-service.ts, yarn.lock
Implements `getBatchSubmissionBlockNumber` to enable the batch submission to work with L1 to L2 message passing
=> rollup-core: little fixes

packages/contracts/src/deployment/index.ts, packages/core-utils/src/app/scheduled-task.ts, packages/rollup-services/src/exec/services.ts
Right now ScheduledTask, on which all microservices are based, does recursive calls when it doesn't need to. This fixes that.
=> Removing ScheduledTask Recursion

packages/contracts/src/deployment/index.ts, packages/core-utils/src/app/scheduled-task.ts, packages/rollup-services/src/exec/services.ts
Reverts ethereum-optimism/optimism-monorepo#307
@tynes has been debugging most of today to figure out what was causing his tests to begin failing and it seems to have been something in this commit.
Let's add this back in ASAP but to unblock @tynes let's revert for now
=> Revert "Removing ScheduledTask Recursion"

.github/workflows/push-to-integration-repo.yml
Reverts ethereum-optimism/optimism-monorepo#321
We don't actually need this, proper instructions can be found here: https://github.com/ethereum-optimism/optimism-integration/pull/11
=> Revert "be sure to commit gitmodules"

packages/rollup-core/src/app/data/consumers/canonical-chain-batch-submitter.ts
Makes batch submission logic more thorough
=> rollup-core: better batch submission logic

packages/contracts/contracts/optimistic-ethereum/bridge/L2CrossDomainMessenger.sol, packages/contracts/package.json, packages/contracts/test/contracts/bridge/L2CrossDomainMessenger.spec.ts, packages/ovm-toolchain/package.json, yarn.lock
=> Backwards compatibility for Authenticated Addresses

.github/workflows/build-test-lint-batch-submitter.yml, packages/batch-submitter/package.json, packages/batch-submitter/src/batch-submitter.ts, packages/batch-submitter/test/batch-submitter/batch-submitter.spec.ts, packages/batch-submitter/test/batch-submitter/mockchain-provider.ts, yarn.lock
Quick PR to remove an unused 'cache' and add a couple nice tests.
=> Add batch-submitter to CI, remove blockCache & improve tests

packages/batch-submitter/src/exec/run-batch-submitter.ts
Before the CTC address was used without resolving from the address manager. This fixes that error and now we resolve the CTC from the address resolver
=> Resolve ctc address from address resolver

packages/batch-submitter/src/batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/batch-submitter/test/batch-submitter/batch-submitter.spec.ts, packages/batch-submitter/test/batch-submitter/mockchain-provider.ts
Takes the CTC address out of the BS config & instead pulls it from the L2Geth node.
=> Use `rollup_getInfo` endpoint for ctc address & more

packages/batch-submitter/src/batch-submitter/batch-submitter.ts, packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/batch-submitter/test/batch-submitter/transaction-batch-submitter.spec.ts
Before there was an issue where the state commitment chain was calculating the state & end based on the L2 chain's start & end. Instead we want to calculate the state and end based on what is finalized in the CTC.
None
=> Fix the state batch submitter state & end

.github/workflows/integration.yml
Build less in CI now that all images are public
=> gitflows: build less in ci now that images are public

packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/test/batch-submitter/transaction-batch-submitter.spec.ts
Submits blocks with `lastL1BlockNum` and fixes  an off by 1 error was simply that we weren't pulling the *last* block
because I forgot to add +1 to the `end` value because it's exclusive. I
was treating it as inclusive.
=> Temp fix lastL1BlockNum & small off by 1

packages/provider/package.json, packages/provider/src/app/utils.ts, yarn.lock
Fixes the encoding in the provider
=> Fix provider encoding

packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
Fixes where the l1BlockNum is updated -- puts it right next to where it gets used.
=> Move l1BlockNum update into sequencer batch append

packages/batch-submitter/src/batch-submitter/index.ts, packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
Tested the batch submitter against L1 and made a few fixes which solved the remaining issues. This should allow the batch submitter to be run against testnet without an issue.
The `lastL1BlockNumber` logic is very dumb and should be replaced ASAP with the correct logic added to L2Geth.
- Fixes https://github.com/ethereum-optimism/roadmap/issues/176
=> Fix batch submitter

packages/batch-submitter/src/batch-submitter/batch-submitter.ts, packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/batch-submitter/test/batch-submitter/transaction-batch-submitter.spec.ts
Changes batch submitter to pull addresses from the address manager!
=> Pull addresses from address manager

packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts
A quick change to the state root batch submission to intentionally commit fraud if we so desire. (useful for the fraud proof security drill! The point is we'd get caught if we ever did this!!)
=> Allow batch submitter to intentionally commit fraud

packages/batch-submitter/package.json, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts
Fixes a bug where multi-timestamp batches break.
=> Fix multi-timestamp batch

packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
Fixes batch submitter monotonicity for contexts that have 0 sequencer txs, but >0 queued txs. This PR sets these contexts' block number and timestamp to the block number and timestamp of the first subsequent queued tx in the context
- 
-
-
=> Fix batch submitter monotonicity

packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/batch-submitter/test/batch-submitter/transaction-batch-submitter.spec.ts
Adds a config option to disable queue batch append transactions
=> rollup: disable queue batch append flag

packages/docs/protocol-specifications/ovm/ovm-components.md
Update links to repo, contracts-v2.
- 
-
-
=> Fix broken links

packages/provider/src/app/utils.ts
It looks like the `from` key is missing in the `allowedTransactionKeys` list, which means a signer (with a "from" address) cannot use `call(transaction)`. Only providers can call this function, which I think is an issue as many dApps are using signers and not providers to interact with the read only functions in smart contracts.
Here is the error:
```
Error: invalid transaction key: from (argument="transaction", value={"data":"[DATA]","to":"[CONTRACT ADDRESS]","from":"[SIGNER ADDRESS]"}, code=INVALID_ARGUMENT, version=)
```
=> added "from" in allowedTransactionKeys list

packages/provider/package.json
=> provider: v0.0.1-alpha.14

packages/ovm-toolchain/README.md, packages/ovm-toolchain/src/index.ts, packages/watcher/.gitignore, packages/watcher/README.md, packages/watcher/exec/run-watcher.js, packages/watcher/index.ts, packages/watcher/package.json, packages/watcher/src/index.ts, packages/watcher/src/watcher.ts, packages/watcher/tsconfig.json, packages/watcher/tslint.json
Adds the watcher tool, which allows front-ends to watch for cross domain messages and receive the transaction receipt of the cross domain message when it is relayed to its destination.
- 
-
-
=> Add watcher tool

packages/core-utils/src/coders/ecdsa-coder.ts, packages/core-utils/test/batch-encoder.spec.ts
- Deletes the `CreateEOA` serialization logic
- Adds a fix for assertion on the tx type when decoding
=> fix: coder

packages/core-utils/package.json, packages/core-utils/src/coders/ecdsa-coder.ts, packages/core-utils/src/coders/types.ts, packages/core-utils/test/batch-encoder.spec.ts
Adds `0x` prefixes where they are missing as well as decodes the `v` value in the signature as an integer to follow how ethers does it.
=> fix: core-utils signature

packages/provider/src/app/provider.ts
We should be operating on the raw transaction information. In order to do this we need to not filter out the `rawTransaction` field on the `getTransaction` response in Geth.
=> Add rawTransaction to transaction output

packages/watcher/exec/run-watcher.js, packages/watcher/package.json, packages/watcher/src/watcher.ts
Fix for watcher to close event listener after an event is found
- 
-
-
=> Close event listener in watcher

integration-tests/test/rpc.spec.ts, ops/docker-compose.yml
fixes #430 
* It seems like the batch submitter sometimes does not submit L2 batches. Locally, this is fixable by stopping and re-starting it. I diff'ed the logs between a "good" test run and a flaky run and found out
* the rpc-spec was also flaky sometimes due to trying to use an already used nonce, we fix this by using an address whose nonce does not depend in the tests
=> fix: bring the batch submitter last to avoid CI flakiness

.editorconfig
Adds a basic `.editorConfig`. This will pretty much eliminate any issues with extra whitespace creeping in at EOL, resulting in 'dirty' commits. 
Many editors will inherit settings from this file, but VSCode requires an [extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) to support it. 
Learn more: https://editorconfig.org/.
**Metadata**
- Fixes None
=> chore: add a basic .editorConfig

ops/docker-compose.yml, ops/docker/Dockerfile.batches, ops/docker/Dockerfile.deployer, ops/docker/Dockerfile.dtl, ops/docker/Dockerfile.monorepo, ops/docker/Dockerfile.relayer, ops/scripts/batches.sh, ops/scripts/deployer.sh, ops/scripts/dtl.sh, ops/scripts/geth.sh, ops/scripts/relayer.sh
This PR fixes the docker image names as the schema is `repository/org/image:tag`, this was previously naming things `image:tag` (`ethereumoptimism:builder`) which implies that they are the same service. This would make it impossible to do versions as the tag is meant to specify the version. This updates the schema to be `org/image:tag` (`ethereumoptimism/builder:latest`) where `latest` is used as the tag and what was previously the tag is now the image.
It also adds `exec` to the docker entry scripts per https://cloud.google.com/solutions/best-practices-for-building-containers. This will make PID1 inherited by the command that is ran at the end of the entry script meaning that it will receive signals from docker/k8s correctly
=> docker: correctly tag and fix entrypoints

integration-tests/test/rpc.spec.ts, l2geth/eth/api_backend.go
Until https://github.com/ethereum-optimism/contracts/pull/300 is merged, we cannot accept transactions with an ETH value set. This PR prevents the sequencer from accepting transactions with a value set as well as adds an RPC level integration test for the functionality.
=> geth: only accept txs with a 0 value

ops/docker-compose.yml, ops/docker/Dockerfile.deployer, packages/contracts/bin/deploy.ts
As title, disables building via the [`--noCompile`](https://github.com/wighawag/hardhat-deploy/blob/master/src/index.ts#L359-L361) flag, saving us 1m+ of CI time
=> perf: do not compile contracts on docker-compose

ops/scripts/geth.sh
`docker-compose up` wasn't working on my machine due to a race condition between geth and the DTL starting. This adds the required coordination to the geth dockerfile entrypoint so that it waits for the DTL
=> docker: have geth wait for dtl to be up before starting

integration-tests/package.json, l2geth/package.json, package.json, packages/batch-submitter/package.json, packages/data-transport-layer/package.json, packages/message-relayer/package.json, patches/@changesets+cli+2.16.0.patch, yarn.lock
Adds a patch from a [discussion in Changesets](https://github.com/atlassian/changesets/issues/399) which allows a package to be automatically tagged, even though it is marked as private. This will allow us to use changesets' publish flow to publish NPM packages automatically, and then we'll only need to add an additional job for publishing docker images.
=> choretag private packages w/o publishing them to NPM

.github/workflows/release.yml, package.json
adds the publish step to the changesets action, so that packages get published to npm alongside everything else
=> ci: publish npm packages on release

.changeset/spotty-sloths-repeat.md, packages/contracts/package.json, packages/core-utils/package.json, packages/hardhat-ovm/package.json, packages/smock/package.json
`package.json` was missing the correct `files` tag, in order to publish the entire package to npm
=> fix: add build files to the published npm package

integration-tests/test/fee-payment.spec.ts, integration-tests/test/native-eth.spec.ts
Adds a test that runs an `estimateGas` for `weth.transfer`. This is an attempt to reproduce the "used too much gas" problem with estimate gas. The call to `eth_estimateGas` fails but the transaction actually is not out of gas
=> test: estimate gas for wETH transfer

.changeset/hip-mugs-smell.md, packages/contracts/package.json, packages/contracts/scripts/build.sh
* Allows importing OVM contract as:
```solidity
import "@eth-optimism/contracts/OVM/accounts/OVM_ECDSAContractAccount.sol";
import "@eth-optimism/contracts/iOVM/...";
import "@eth-optimism/contracts/libraries/...";
```
* Removes the `copyfiles` build steps, these were not required as we can package `artifacts` and `artifacts-ovm` via the `files` field in package.json
* Adds a `prepublish` step which copies over `contracts/optimistic-ethereum/**` to the top level directory
=> fix: package contracts with correct paths

.changeset/four-humans-draw.md, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
Our batch submitter has been reverting with error logs we haven't encountered in the past (see linked issue). This PR deletes the related codepaths that should not be active and adds logs that may help us debug the issue.
See linked issue.
**Metadata**
- Attempts to debug https://github.com/ethereum-optimism/optimism/issues/455
=> fix: l1 block number logic debug and logging

packages/contracts/src/hardhat-deploy-ethers.ts
Unfortunately there is a build error that does not show on CI.
```
$ hardhat compile --show-stack-traces
Error: src/hardhat-deploy-ethers.ts(59,26): error TS2339: Property 'deployments' does not exist on type 'HardhatRuntimeEnvironment'.
Error: src/hardhat-deploy-ethers.ts(60,34): error TS2339: Property 'getNamedAccounts' does not exist on type 'HardhatRuntimeEnvironment'.
Error: src/hardhat-deploy-ethers.ts(69,13): error TS2339: Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'.
Error: src/hardhat-deploy-ethers.ts(88,30): error TS2339: Property 'deployments' does not exist on type 'HardhatRuntimeEnvironment'.
Error: src/hardhat-deploy-ethers.ts(90,13): error TS2339: Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'.
Error: …
```
=> fix: revert hardhat type usage

packages/contracts/addresses.md, packages/contracts/package.json, packages/contracts/scripts/generate-markdown.js
Credit to Pacien Boisson @pakocrew
Please review carefully as this will be the source of truth for the near future
=> contracts: script for making markdown file with all our contract addresses

.changeset/angry-queens-reflect.md, packages/core-utils/src/base-service.ts, packages/data-transport-layer/src/services/main/service.ts, packages/data-transport-layer/src/services/server/service.ts
Adding extra logs to DTL to improve overall observability. 
DTL started with better logging than batch submitter, so most of these are on initialization and whenever we respond to API calls. Open to changing these to `.debug` instead! 
**Metadata**
https://github.com/ethereum-optimism/roadmap/issues/860
=> feat: add extra logs to DTL

.gitignore
Noticed this from discussion: https://github.com/ethereum-optimism/optimism/pull/480#discussion_r615918652
=> build: data-transport-layer leveldb file is gitignored

README.md
Adds a note about usage of `docker-compose logs`
=> docs: explain usage of dc logs

.github/workflows/ts-packages.yml
As title.
I suggest we remove the Node versions matrix from unit tests. It doesn’t really do anything useful IMO, and we’re not using any bespoke Node features to really worry about it.
=> ci: test single node version

.changeset/seven-bulldogs-kneel.md, l2geth/core/vm/ovm_state_manager.go
Simple fix to a logger error where not enough arguments are passed. The logger expects a string followed by key value pairs. This PR adds the second argument to complete the key value pair.
=> l2geth: fix log error

.changeset/rude-moons-kiss.md, l2geth/accounts/abi/abi.go
This adds back in geohot's optimization:  https://github.com/ethereum-optimism/go-ethereum/commit/8d13a77e4916393b87ea3601590eea9f004ce09e
It was recently [removed]( https://github.com/ethereum-optimism/go-ethereum/commit/9e1ca7e30a927df064ed9f0469a29f316c91a731) but is still useful as it is still in the [hot code path](https://github.com/ethereum-optimism/optimism/blob/c4266faf369c929bf555951df5810b6522c7a248/l2geth/core/vm/ovm_state_manager.go#L40).
Below is a picture from the `pprof` CPU profiling before these changes
This PR adds a cache to `abi.Method.ID` so that each call doesn't result in a bunch of hashing and reduces the amount of time that is spent in that method significantly.
It was generated with the following script on top of …
=> optimization: add back in the abi caching

ops/scripts/wait-for-sequencer.sh
As title, to prevent PRs from running for hours if there's an issue when bringing up the stack.
=> ci: add 90s timeout when waiting for sequencer to be up

.github/CODEOWNERS
I've not spent time looking a the `core-utils` code yet, and don't see it as a high priority to get up to speed on.
=> Remove self as a core-utils code owner

README.md
Adds `yarn build:integration` into the set of commands for running integration tests.
An alternative might be to build with Lerna.
=> docs: Add build step in integration-tests dir

integration-tests/test/rpc.spec.ts
Adds a test case for `eth_getBalance` confirming that `eth_getBalance` RPC calls return the same value as the `balanceOf` function on `OVM_ETH`.
=> test: add rpc test for eth_getBalance

.changeset/perfect-feet-love.md, integration-tests/contracts/OVMContextStorage.sol, integration-tests/contracts/OVMMulticall.sol, integration-tests/test/ovmcontext.spec.ts
Re-adds tests that were left behind as part of the monorepo migration.
These tests specifically cover `NUMBER` opcode which was fixed in https://github.com/ethereum-optimism/go-ethereum/pull/280 as well as the returned values from `rollup_getInfo`. This RPC endpoint returns the current rollup context as well as the OVM context. There is a bug that requires an assertion to be fixed, this PR could either be rebased on top of a fix or merged with a ticket to fix the problem in the future. If #477 doesn't fix the bug then it should be easy to do so after #477
=> test: ovm context

.changeset/tough-bugs-invent.md, l2geth/rollup/sync_service.go, l2geth/rollup/sync_service_test.go
This PR fixes a problem with the verifier/replica where it does not keep track of the current gas price. This is bad because it would make them not usable for `eth_estimateGas`. For `eth_estimateGas` to work, the node must know the current L1 gas price.
It abstracts the update L1 gas price logic into its own function and then adds it to the verifier codepath so both the verifier and the sequencer keep track of the L1 gas price.
It builds off of:
- https://github.com/ethereum-optimism/optimism/pull/438/commits/2f6b0ecb78a423315a9c6a83958153255b3295e5
- Small change from #477 - testing the `SyncService.updateL1GasPrice` directly
Related:
- https://github.com/ethereum-optimism/optimism/issues/515
=> l2geth: replica gas estimation fix

packages/smock/.github/CODEOWNERS
Removing `packages/smock/CODEOWNERS` because it duplicates (likely overrides) the file in root.
=> fix: delete extraneous CODEOWNERS file

ops/scripts/batches.sh, ops/scripts/deployer.sh, ops/scripts/dtl.sh, ops/scripts/geth.sh, ops/scripts/relayer.sh
Cleans up the error logs in the `docker-compose` entrypoint files by using `curl --silent --output /dev/null`. It reduces the spam at the beginning of the local network coming online.
=> ops: cleaner docker-compose startup logs

.changeset/thin-dodos-reply.md, l2geth/core/rawdb/rollup_indexes.go, l2geth/core/rawdb/schema.go, l2geth/eth/api_backend.go, l2geth/internal/ethapi/api.go, l2geth/internal/ethapi/backend.go, l2geth/les/api_backend.go, l2geth/rollup/sync_service.go
Adds the changes from #477 that add in the `VerifiedIndex` to leveldb as well as to the `rollup_getInfo` API. It also adds higher level functions on top of `SyncService.{GetLatestIndex,GetLatestEnqueueIndex}` that abstract away the possibility of a `nil` value being returned called `SyncService.{GetNextEnqueueIndex,GetNextIndex}`.
An additional PR will build on top of this one that refactors the `SyncService`. As of this PR, certain methods are not yet consumed but that is intentional as to bucket together a set of related changes.
Addresses:
- https://github.com/ethereum-optimism/optimism/pull/477#discussion_r615360154
- https://github.com/ethereum-optimism/optimism/pull/477#discussion_r615360325
=> l2geth: add `VerifiedIndex` to DB and API

.changeset/calm-days-sleep.md, .changeset/few-bags-roll.md, packages/core-utils/package.json, packages/core-utils/src/base-service.ts, packages/core-utils/src/common/metrics.ts, packages/data-transport-layer/src/services/l1-ingestion/service.ts, packages/data-transport-layer/src/services/l2-ingestion/service.ts, packages/data-transport-layer/src/services/main/service.ts, packages/data-transport-layer/src/services/server/service.ts, packages/message-relayer/src/service.ts, yarn.lock
We want to be collecting metrics in our TypeScript services. This PR adds a Metrics class to core-utils and uses it in base-service. 
The metrics class will be used to collect metrics in batch-submitter and data-transport-layer.
=> feat: add metrics to core-utils 

.changeset/long-days-march.md, packages/batch-submitter/package.json, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/core-utils/package.json, packages/core-utils/src/common/logger.ts, yarn.lock
Batch submitter errors weren't being properly sent to Sentry before, due to the way the destination was initialized. This PR adds multi-stream functionality to `Logger`, and has been tested and sends `log.error`s in the Batch Submitter to Sentry.
This now writes to both Sentry and `stdout`!
=> fix: send batch-submitter error logs to sentry

.changeset/slimy-rocks-exist.md, l2geth/cmd/utils/flags.go, l2geth/rollup/sync_service.go
The timestamp and blocknumber in the OVM context must be updated on a L1 to L2 transaction (`enqueue`) or can be updated at anytime by the sequencer. It is currently cheaper to submit batches when the timestamp changes less often, but that results in degraded user experience. This lowers the default timestamp refresh from 15 minutes to 3 minutes. This means that if an `enqueue` transaction does not occur for 3 minutes, then the sequencer will query the tip of L1 and set the OVM context based on the current L1 timestamp and blocknumber. Note that in practice, the "tip" trails L1 by a configurable number of blocks
=> l2geth: shorter default timestamp refresh

.changeset/wise-onions-type.md, packages/batch-submitter/src/exec/run-batch-submitter.ts
Error must be provided inside of an `err` object.
=> fix: fix incorrectly provided error object to pino

.changeset/calm-books-hope.md, packages/data-transport-layer/src/services/l2-ingestion/service.ts, packages/data-transport-layer/src/services/main/service.ts, packages/data-transport-layer/src/services/run.ts, packages/data-transport-layer/src/services/server/service.ts
The DTL currently prioritizes transactions sourced from L2 instead of transactions sourced from L1. This was a quick patch required for sequencer maintenance, the source of truth should generally be L1. This allows the client to specify a query param that says to source the transaction from L1 or from L2 
Related to https://github.com/ethereum-optimism/optimism/pull/477
Previously query params had no impact on the DTL. The DTL has a backing index for both transactions ingested from the L1 contracts (CTC + SCC) and an index for transactions pulled from a sequencer (`eth_getBlockByNumber`). The DTL has preferred different data sources over time. Before this PR, the config option `showUnconfirmedTransactions` being set to true would prefer the L2 …
=> dtl: add query param based querying for txs

.changeset/violet-beers-unite.md, integration-tests/test/native-eth.spec.ts, l2geth/core/rollup_fee.go, l2geth/core/rollup_fee_test.go
Fixes https://github.com/ethereum-optimism/optimism/issues/515. 
Does *not* introduce `nonCallDataL1GasOverhead` since we do not have a standard way to estimate / calculate it yet and seems to be a micro optimization.
=> Calculate fees correctly based on zero/non-zero bytes

.changeset/empty-boxes-repair.md, l2geth/rollup/client.go, l2geth/rollup/sync_service.go, l2geth/rollup/sync_service_test.go
Adds the batch fetching API to the `RollupClient` so that it can be used to fetch batches from the DTL. Follow up PRs will use this code to sync as the verifier and also to ensure that the L2 transactions match what has been batch submitted as the sequencer.
This is required for https://github.com/ethereum-optimism/optimism/pull/477
=> l2geth: rollup client batch api

.changeset/selfish-ladybugs-pull.md, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
While discussing metrics, @K-Ho raised that batch submitter should not be fixing monotonicity errors (which should now be fully handled by geth). We want to be notified if it is, because that means there is a monotonicity violation and we need to debug geth. This PR logs an error when we fix monotonicity errors in batch submitter, which will then notify us through Sentry.
`log.error`s are piped to sentry which notifies us.
=> chore: log errors on monotonicity fixes

.changeset/curly-tables-behave.md, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/Abs_L1TokenGateway.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/Abs_L2DepositedToken.sol, packages/contracts/test/contracts/OVM/bridge/assets/OVM_L1ERC20Gateway.spec.ts
Hello World, I've made a few tweaks.
**Summary**
This PR fixes an issue that manifests when deploying `Abs_L1TokenGateway.sol` contract behind a delegate proxy. This was probably missed as your proxied `OVM_L1ETHGateway.sol` is not using `Abs_L1TokenGateway.sol` directly, and [the re-implementation avoids the bug](https://github.com/ethereum-optimism/optimism/blob/1743a6d179d4449586c133f5aed18779761093b1/packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ETHGateway.sol#L28).
Additionally it makes L1 `deposit/depositTo` & L2 `withdraw/withdrawTo` gateway functions virtual and external.
While implementing LINK Optimism bridge contracts, a bug manifested with proxy deployments. The  `Abs_L1TokenGateway.DEFAULT_FINALIZE_DEPOSIT_L2_GAS` was actually a …
=> Fix bridge contracts upgradeability

.changeset/big-parents-glow.md, packages/batch-submitter/exec/run-batch-submitter.js, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/data-transport-layer/src/services/server/service.ts
[Binding the version](https://docs.sentry.io/platforms/node/configuration/releases/#bind-the-version) enables releases to be tagged on Sentry, allowing us to identify errors being resolved by new releases.
=> feat: add Sentry release automation

packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts
Ported original PR: https://github.com/ethereum-optimism/data-transport-layer/pull/72
=> feat: Attempt to decode txs as RLP first

packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/Abs_BaseCrossDomainMessenger.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L2CrossDomainMessenger.sol, packages/contracts/test/contracts/OVM/bridge/base/OVM_L1CrossDomainMessenger.spec.ts, packages/contracts/test/contracts/OVM/bridge/base/OVM_L2CrossDomainMessenger.spec.ts, packages/contracts/test/helpers/codec/bridge.ts
Adds a test for the reentrancy modifier on `OVM_L1CrossDomainMessenger.relayMessage()`
**Metadata**
=> Test the reentrancy modifier on OVM_L1CrossDomainMessenger.relayMessage()

.changeset/red-humans-grin.md, packages/batch-submitter/src/batch-submitter/batch-submitter.ts, packages/batch-submitter/src/batch-submitter/index.ts, packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/batch-submitter/test/batch-submitter/batch-submitter.spec.ts, packages/batch-submitter/test/batch-submitter/transaction-batch-submitter.spec.ts, packages/core-utils/src/common/index.ts
This PR adds `Metrics` to each batch submitter, which enables us to start collecting metrics. It does not yet start to track specific metrics (which will be implemented in followup PRs when our prom server is running).
Here is the list of default metrics being collected: 
https://github.com/siimon/prom-client/blob/96f7495d66b1a21755f745b1367d3e530668a957/lib/defaultMetrics.js#L5-L17
=> feat: add default metrics tracking to batch-submitter

.changeset/breezy-queens-help.md, ops/docker/Dockerfile.batch-submitter, ops/docker/Dockerfile.message-relayer, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/data-transport-layer/src/services/server/service.ts
There are two issues on Sentry now:
- release: Discarded invalid value
- exception.values.0.stacktrace.frames: Discarded invalid value
These commits address them:
- build: use npm script to start base service based services
- fix: remove invalid slash character from sentry release name
- fix: set stackAttributeKey to conventional 'err' key
=> Ensure Sentry configuration works via updates to services

.github/workflows/release.yml
Adds a Github action for publishing the `deployer` image. This is required for running the system against `kind` for local development
=> ops: publish deployer image

.changeset/eight-dancers-learn.md, packages/smock/package.json, packages/smock/src/common/hardhat-common.ts, packages/smock/src/smockit/binding.ts, packages/smock/src/smockit/smockit.ts, packages/smock/src/smockit/types.ts, packages/smock/src/smoddit/smoddit.ts, packages/smock/test/smockit/function-manipulation.spec.ts, packages/smock/test/smockit/smock-initialization.spec.ts, yarn.lock
Hardhat ^2.2.0 introduces breaking changes because they've moved over from `ethereumjs-vm@^4` to `ethereumjs-vm@^5`. This PR should make `smock` compatible with ^2.2.0 while also maintaining backwards compatibility.
=> feat[smock]: Add support for hardhat 2.2.0

packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/Abs_BaseCrossDomainMessenger.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L1CrossDomainMessenger.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L1MultiMessageRelayer.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L2CrossDomainMessenger.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ERC20Gateway.sol, packages/contracts/contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol, packages/contracts/contracts/optimistic-ethereum/libraries/bridge/OVM_CrossDomainEnabled.sol
Pretty basic PR, just some cleanup to various contracts.
=> style[contracts]: Various minor stylistic improvements

.changeset/seven-kids-smash.md, packages/contracts/bin/deploy.ts
Previously the types were not being parsed correctly for the deploy script. This parses the config options correctly. Ideally we can remove this by having a wrapper for `hardhat deploy` in the `scripts` directory and then `yarn deploy` calls `./scripts/deploy.sh`
=> fix: proper config parsing for `bin/deploy.ts`

.changeset/wild-experts-explode.md, packages/contracts/bin/deploy.ts
This re-adds the `OVM_Sequencer` and `Deployer` from the previous `deploy.js`, see https://github.com/ethereum-optimism/contracts/blob/55167711ed2658ff22ccba3a5a466c4298049f4c/bin/deploy.js#L114
Users on discord have mentioned they depended on this
=> contracts: add sequencer and deployer to addresses.json

.changeset/smooth-beds-rhyme.md, packages/contracts/package.json
`package.json` wasn't correctly exporting our typechain artifacts. This should fix it. Requires a new release for people to use this, though. Fixes #505
=> fix[contracts]: Update contracts package.json to export typechain artifacts

l2geth/internal/ethapi/api.go
Removes the `eth_sendRawEthSignTransaction` endpoint
=> l2geth: remove eth_sendRawEthSignTransaction endpoint

ops/scripts/deployer.sh
Set some flags in `deployer.sh` that will cause the script to end early if any commands exit with a non 0 exit code. This prevents `yarn deploy` from failing and then the dump being served without the `addresses.json`
Updated to just `set -e`
See the linux man page for set: https://ss64.com/bash/set.html
```
-e  Exit immediately if a simple command exits with a non-zero status, unless
the command that fails is part of an until or  while loop, part of an
if statement, part of a && or || list, or if the command's return status
is being inverted using !.  -o errexit
```
This means that if `yarn deploy` fails, then the entire script will fail
=> ops: set e in deployer entrypoint script

.changeset/violet-falcons-hunt.md, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L1CrossDomainMessenger.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L2CrossDomainMessenger.sol, packages/contracts/contracts/optimistic-ethereum/iOVM/bridge/messaging/iAbs_BaseCrossDomainMessenger.sol
Adds a new event `FailedRelayedMessage` to `L1CrossDomainMessenger` and `L2CrossDomainMessenger`, to be emitted in the case that a relay failed. Alternative described in #587 was simply to add a `success` boolean to `RelayedMessage`, but some of our services rely on the current `RelayedMessage` event and I didn't want to break anything. I think this is good enough.
**Metadata**
- Fixes #587
=> feat[contracts]: Have Messenger contracts emit an event on failed relay

.github/workflows/geth.yml, .github/workflows/integration.yml, .github/workflows/ts-packages.yml
Makes the CI run on all branches which start with `v` indicating that it is a 'version' branch which we can use to prototype breaking changes.
Notes:
- We don't want to publish releases on all `v` branches so I didn't include them `release.yml`
- Example branch that this applies to: https://github.com/ethereum-optimism/optimism/tree/v0.3.0-rlp
=> feat: let test CI run on all release branches

integration-tests/test/native-eth.spec.ts
Trying to see if using a fixed address will solve the flickering integration test.
=> fix[integration-tests]: Use fixed address in gas estimation test

.changeset/rich-steaks-train.md, packages/batch-submitter/src/batch-submitter/batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/core-utils/src/common/logger.ts
`pino-sentry` only logs context wrapped in the `extra` field. this PR merges our context object into `extra` so we can see the contexts of all errors Sentry catches.
```js
log.error('test error v2', {
err: 'error!!',
time: 12345,
isError: true,
})
```
https://sentry.io/organizations/optimismpbc/issues/2359518167/
=> feat: add sentry error context

ops/scripts/geth.sh
Allows for a configurable L2Geth verbosity. This is nice for being able to modify the loglevel dynamically in the integration tests. There is a bit of a security concern re: arbitrary code execution so I made sure to quote the value. This only runs in the integration tests so I don't think its that big of a concern.
=> ops: configurable l2geth verbosity

.changeset/old-cycles-invite.md, packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ProxyEOA.sol, packages/contracts/test/contracts/OVM/accounts/OVM_ProxyEOA.spec.ts
Fixes #550. Very simple change, ensures that our implementation storage slot is correct. Also emits the right event whenever the contract is upgraded.
=> feat[contracts]: Make ProxyEOA compatible with eip1967

.changeset/old-mirrors-doubt.md, integration-tests/test/ovmcontext.spec.ts, l2geth/core/state_transition_ovm.go, l2geth/internal/ethapi/api.go
Uses the correct `block.number` and `block.timestamp` for `eth_call`. It was previously using the block number and timestamp of the L2 block instead of the L1 based context.
**Metadata**
Fixes https://github.com/ethereum-optimism/optimism/issues/530
=> l2geth: fix eth call evm context

.changeset/bright-rice-pump.md, packages/data-transport-layer/src/services/server/service.ts, packages/hardhat-ovm/src/index.ts
Not sure what happened here. Seems a linting error snuck by CI.
=> fix: Fix various minor linting errors not caught by CI

.changeset/calm-flies-drive.md, packages/data-transport-layer/src/services/run.ts
Clean up the config parsing for the DTL to use lowercase config params. It is possible to configure via CLI like so:
```bash
$ yarn start --server-port 7878
```
It is backwards compatible with the previous way that we have been configuring, which is via prefixed env vars
=> dtl: standardize config

.changeset/twelve-items-sing.md, packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
Removes a single line of logic in `ovmEXTCODECOPY` that we don't make use of anymore.
=> fix[contracts]: Remove some old ovmEXTCODECOPY logic

.changeset/chilly-grapes-greet.md, l2geth/internal/ethapi/api.go, l2geth/rollup/sync_service.go
Sets the raw RLP encoding at the API layer in the `txmeta`
=> l2geth: set rlp encoded tx in txmeta in RPC layer

.changeset/mean-comics-rush.md, l2geth/core/vm/evm.go, packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol, packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol, packages/contracts/contracts/optimistic-ethereum/iOVM/execution/iOVM_ExecutionManager.sol, packages/contracts/test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts, packages/contracts/test/contracts/OVM/execution/OVM_ExecutionManager.gas-spec.ts
Makes `ExecutionManager` return a `bytes memory` value. Simplifies `evm.go` in geth quite significantly. Also gets rid of a lot of annoying hacks/breaking bugs that people have been experiencing calling certain contracts.
=> feat: Have ExecutionManager pass data upwards

.changeset/thirty-radios-sniff.md, l2geth/eth/api_backend.go, l2geth/internal/ethapi/api.go
This PR will prevent transactions via RPC that include a value and calldata. It also moves another Optimism specific check lower into the callstack as to make the diff more controlled
=> rpc: only allow txs with no calldata when there is value

ops/docker-compose.yml
This PR turns the `env_file` syntax into using an array instead of an object. According to the [docs](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option), this is the correct syntax
**Metadata**
- Hopefully fixes problems with `docker-compose` on osx
=> ops: use list syntax for env_file

.changeset/fuzzy-gorillas-accept.md, integration-tests/test/fee-payment.spec.ts, integration-tests/test/rpc.spec.ts, l2geth/core/state_transition.go, l2geth/core/state_transition_ovm.go, l2geth/eth/api_backend.go, packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol, packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol, packages/contracts/contracts/optimistic-ethereum/libraries/rlp/Lib_RLPWriter.sol, packages/contracts/test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
Adds basic value transfer support to `OVM_ECDSAContractAccount`. As per convo with @ben-chain, we've restricted value transfer as follows:
1. Value can only be transferred alongside a `CALL`.
2. If value is attached to the transaction, the `CALL` is *not* executed and the user must provide no input data.
=> feat[contracts]: Add value transfer support to ECDSAContractAccount

.changeset/grumpy-bananas-brush.md, packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts, packages/data-transport-layer/test/unit-tests/services/l1-ingestion/handlers/sequencer-batch-appended.spec.ts
Removes the legacy decoding because it is no longer needed post regenesis
=> dtl: remove legacy encoding

.changeset/two-houses-work.md, packages/contracts/scripts/build.sh
This PR fixes the script that is called during `yarn build`
- Remove call to `yarn run build:typescript:ovm` which does not exist
- Adds shebang to top of file
- Builds the typescript, contracts and ovm contracts
- Uses `set -e` to fail script execution if any commands exit with non-zero exit code
=> contracts: fix build script

packages/contracts/scripts/build.sh
there's a race condition somewhere in hardhat which does not generate the artifacts
in the correct directory sometimes, causing our tests to fail with 'artifact not found'
This issue was introduced in https://github.com/ethereum-optimism/optimism/pull/642
=> fix(contracts): do not build ovm and contracts concurrently

.github/workflows/integration.yml, .github/workflows/ts-packages.yml, integration-tests/hardhat.config.ts, integration-tests/package.json, packages/contracts/hardhat.config.ts, packages/contracts/package.json, yarn.lock
Adds [hardhat-gas-reporter](https://github.com/cgewecke/hardhat-gas-reporter) package and base configuration to unit and integration test runs. Disabled by default, enabled via `ENABLE_GAS_REPORT` environment variable.
Note that I investigated using `codechecks` for better report presentation and also benchmarking gas cost diff against `master` in CI however the owner of that `krzkaczor` said it's going be decommissioned in near future so didn't want to integrate us with "abandonware" :)
**Metadata**
Resulted from investigating issue #500 and the need to benchmark gas costs on L1
=> Add optional gas reporting to unit test run

.changeset/chatty-clouds-melt.md, .github/workflows/integration.yml, examples/hardhat/README.md, examples/hardhat/contracts/ERC20.sol, examples/hardhat/deploy/ERC20.deploy.js, examples/hardhat/hardhat.config.js, examples/hardhat/package.json, examples/hardhat/test/erc20.test.js, package.json, packages/contracts/hardhat.config.ts, packages/contracts/scripts/build.sh, packages/contracts/test/contracts/OVM/execution/OVM_ExecutionManager/nuisance-gas.spec.ts, packages/hardhat-ovm/package.json, packages/hardhat-ovm/src/index.ts, packages/hardhat-ovm/src/type-extensions.ts, yarn.lock
Replaces #501 with a single PR for the `optimism-tutorial`. 
Additional PRs to follow for the following repositories:
1. [Waffle-ERC20-Example](https://github.com/ethereum-optimism/Waffle-ERC20-Example)
2. [Truffle-ERC20-Example](https://github.com/ethereum-optimism/Truffle-ERC20-Example)
3. [l1-l2-deposit-withdrawal](https://github.com/ethereum-optimism/l1-l2-deposit-withdrawal)
=> docs: add hardhat example + ci

.github/workflows/ts-packages.yml, package.json
Using the `--since master` flag has been a gigantic footgun. I think it's better to just run all unit tests on CI, they're pretty fast anyway.
=> ci: always run all tests

ops/docker-compose.yml
Uses `docker-compose`'s `depends_on` feature which prevents starting containers out of order. This helped me locally to avoid what appears to be a race condition with services starting out of order leading to non-deterministic behaviour spinning up a local network. I think this will aid #570
=> build: add depends_on feature of docker-compose

ops/docker-compose.yml
This PR sets `builder.scale` to `0` so that it doesn't start with `docker-compose up`. This is useful for the command:
```bash
$ docker-compose up --abort-on-container-exit
```
This will allow for quicker debugging when it comes to https://github.com/ethereum-optimism/optimism/issues/570. As soon as one of the containers fails, it will exit the entire command
=> ops: docker-compose builder scale 0

integration-tests/.prettierrc.json, integration-tests/prettier-config.json
Seems to have been missed in #649
=> build: fix wrongly named prettier config file in integration-tests

.changeset/blue-needles-clap.md, packages/data-transport-layer/src/services/server/service.ts
Fixes an off by one error in the DTL that prevents a replica from syncing. The replica will always think that the DTL is syncing due to an off by one with the block number that the transaction is in when indexed in L2geth vs the index of the transaction in the canonical transaction chain. The genesis block is not batch submitted which makes the CTC index 1 less than the corresponding index in L2geth. There is a single transaction per block in L2geth meaning that the blocknumber can reliably correspond to the CTC index if the off by one is taken into account
=> dtlL fix syncing off by one

.changeset/beige-keys-hammer.md, .changeset/brown-bananas-deny.md, .changeset/tough-lamps-hammer.md, l2geth/rollup/client.go, packages/core-utils/src/common/hex-strings.ts, packages/core-utils/test/common/hex-utils.spec.ts, packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts, packages/data-transport-layer/src/services/l2-ingestion/handlers/transaction.ts, packages/data-transport-layer/src/types/database-types.ts
This will index the value field in the DTL. Without this change, value is not propagated through to verifiers and replicas
=> dtl: index the value field

.github/workflows/integration.yml, examples/hardhat/package.json, examples/waffle/package.json
Annoying an entire folder without removing it from the workspace is frustrating if the names of the `package.json` packages do not equal the name of packages. We could do something like [what is proposed in this thread](https://github.com/lerna/lerna/issues/1370) i.e.,
```bash
lerna run yarn --scope={$(ls ./packages | xargs echo | sed 's/ /,/g')}
```
But `ls` doesn't work.
A short-term fix is to rename the `test` command. This makes it more explicit what the test is (i.e., integration) and is a simple fix.
Fixes https://github.com/ethereum-optimism/optimism/issues/702
=> build: change test script name to avoid wrongly considered unit tests

.changeset/famous-dragons-eat.md, packages/data-transport-layer/package.json, packages/data-transport-layer/src/services/server/service.ts, yarn.lock
Add prom bundle to measure http endpoint latency metrics in the DTL. 
The issue originally also planned to add a counter to a legacy endpoint, but that PR has been closed: https://github.com/ethereum-optimism/optimism/pull/567#discussion_r618905970 I can patch this up if this will be in the release candidate.
**Metadata**
https://github.com/ethereum-optimism/optimism/issues/636
=> feat[dtl]: add endpoint metrics

ops/scripts/batches.sh, ops/scripts/deployer.sh, ops/scripts/dtl.sh, ops/scripts/geth.sh, ops/scripts/relayer.sh
This will help us debug any local issues with Docker failing to correctly wait for the right services and with passing addresses around during local development
=> build: add --fail and --show-error to usage of curl for awaiting service readiness

packages/batch-submitter/.env.example, packages/batch-submitter/src/batch-submitter/batch-submitter.ts, packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts
Our services currently run without knowing their environment, which adds extra overhead to how we distinguish errors and metrics between mainnet, kovan, and soon goerli. This PR adds `NODE_ENV` and `ETH_NETWORK` to the batch submitter and the related logic for Sentry and prom-client, so we can distinguish between local dev and deployments.
I plan to make an equivalent PR for the data transport layer, but that requires a bigger refactor related to service-base so want to get this reviewed first.
**Metadata**
- https://github.com/ethereum-optimism/optimism/issues/491
=> feat: add node_env to batch submitter

packages/contracts/hardhat.config.ts
Now that we have [merged `kall` support into the mainline compiler](https://github.com/ethereum-optimism/solc-bin/commit/11123332d88c823e8831c5e5ed042f9abc6accab), we can update the funky import.
I believe that the root cause of all of this was a caching layer in the `builder`.
**Metadata**
- Fixes https://github.com/ethereum-optimism/optimism/issues/675
=> chore: use primary ovm-solc

.changeset/olive-fishes-share.md, packages/hardhat-ovm/src/index.ts
Implementing proposed fix from https://github.com/ethereum-optimism/optimism/issues/674.
=> fix: ensure hardhat does not fail if no input sources provided

examples/waffle/package.json
Prevents unnecessary publishing from accidentally happening.
=> build: make erc20 example private

.changeset/light-needles-brush.md, examples/waffle/test/erc20.spec.js, integration-tests/test/native-eth.spec.ts, integration-tests/test/rpc.spec.ts
Fixes the waffle example to no longer use `eth_sendTransaction`. This endpoint depends on having a key in the node. This updates the test to depend on a local key and use `eth_sendRawTransaction`
The sequencer shouldn't be exposing that endpoint
**Metadata**
=> examples: fix waffle example + gas changes in tests

ops/scripts/batches.sh, ops/scripts/dtl.sh, ops/scripts/geth.sh, ops/scripts/relayer.sh
Inspired by @tynes' comment https://github.com/ethereum-optimism/optimism/commit/7e6f39335da5e7dbffca503cbf9621f07f32f466#r50244089
=> build: add set -e to various bash scripts that we want to error loudly

.github/workflows/integration.yml, .github/workflows/release.yml, integration-tests/hardhat.config.ts, integration-tests/test/setup-docker-compose-network.js, ops/docker-compose.yml, ops/docker/Dockerfile.integration-tests, ops/docker/Dockerfile.monorepo, ops/scripts/build-ci.sh, ops/scripts/integration-tests.sh
=> Dockerize Integration Tests

.changeset/dry-bugs-relax.md, packages/hardhat-ovm/src/index.ts
As title, to avoid errors like the one specified [here](https://github.com/ethereum-optimism/optimism/issues/664#issuecomment-831433480).
=> fix(hh-ovm): defaults to 0 gasPrice if none provided

.changeset/curly-pumas-wait.md, .changeset/kind-plants-tickle.md, l2geth/internal/ethapi/api.go
This PR blocks certain endpoints from being available for users based on the environment variable `USING_OVM`. We need to turn this env var into an actual flag and have it select a `consensus.Engine`, but will leave that for future work. The blocked endpoints are:
- `eth_fillTransaction`
- `eth_sign`
- `eth_sendTransaction`
- `eth_signTransaction`
It also adds in the `txmeta.rawTransaction` field in an additional place where transactions are serialized based on user input. This code path should no longer be reachable because it is behind `eth_sendTransaction`.
=> fix: prevent eth sendtransaction

.changeset/forty-hotels-brake.md, l2geth/internal/ethapi/api.go
Protects a `nil` reference of the block during `eth_call`. This is a problem because some of the L2 EVM context is based on L1 values. In particular the block number and timestamp are not the L2 values but instead are the L1 values. During `eth_call`, the correct block number and timestamp must be set. The current approach reads a historical block from the db and pulls out the timestamp and blocknumber from that block. The L1 timestamp and L1 blocknumber are serialized as part of the `TransactionMeta` in the db.
=> l2geth: docall protect nil block

.changeset/great-clouds-call.md, .changeset/weak-suits-burn.md, l2geth/core/vm/evm.go, packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol
This PR ABI decodes the results from the EVM execution. Previously we were just slicing bytes, which worked in some cases. Once we started to return different ABIs, the slicing no longer worked. I observed some pretty unexpected results being assigned to `ret` and `success` with just the slicing.
There have been problems around `eth_estimateGas` failing - I believe this is due to the fact that `simulateMessage()` and `run()` return different ABI encoded types and the parsing was the same for both. This is an attempt to solve the problem once and for all, so that `eth_call` and `eth_estimateGas` are stable and work the same as `eth_sendRawTransaction`
=> l2geth + contracts:  standard interface for systems contracts and userland contracts

ops/scripts/build-ci.sh
=> ci: use correct service name when building integration tests

packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol, packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_DeployerWhitelist.sol, packages/contracts/contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol, packages/contracts/contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol, packages/contracts/contracts/optimistic-ethereum/libraries/trie/Lib_MerkleTrie.sol
If a function does not need to be accessed from within the contract, it should be labelled external because: 
1. The use of the function is made semantically clearer to reviewers
2. It should save gas, though the optimizer may address that (but fewer optimizer changes is also a benefit).
=> Restrict visibilities to external

.changeset/good-poets-march.md, l2geth/rollup/client.go
No longer parse the type field that is returned from the API and just go with the standard type. This feature is deprecated since there is no longer a concept of transaction type
=> fix: remove type check in rollup client

.github/workflows/ts-packages.yml, .gitignore, package.json, packages/contracts/README.md, packages/contracts/package.json, yarn.lock
**Description:**
This PR should run a new `Test Coverage` job in the Github Actions `typescript / contracts` workflow. 
**Worth noting:**
- Gas regression tests (ie. in files ending with `.gas.spec.ts`) were previously labelled with `@skip-on-coverage`. Those tests  will not be run during test coverage (per [.solcover.js](https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/.solcover.js#L8-L9)).
- Some 'behavioral' tests (ie. non-gas metering tests) are currently breaking during test coverage generation. This is not great, but I think it's OK to allow for now. The alternative is to skip those tests too, but that will reduce the accuracy of our coverage reports.
See other comments in my self-review.
=> Generate test coverage for contracts in CI

.changeset/quiet-cherries-wave.md, packages/hardhat-ovm/src/index.ts
Fixes the long-elusive https://github.com/ethereum-optimism/optimism/issues/675 where builds were failing on M1 macs.  There is a better fix for this long-term, but we should merge this in now to unblock M1 users.
We barked up the wrong tree on this one for a while because it looked an awful lot like a caching issue, but turned out to be something else: it seems that on M1s, the hardhat `TASK_COMPILE_SOLIDITY_RUN_SOLC` does not run, probably because it does not see an M1 build, and therefore wants `TASK_COMPILE_SOLIDITY_RUN_SOLCJS` to be run directly.  The fix here routes this task back to `TASK_COMPILE_SOLIDITY_RUN_SOLC` on the first pass, because `hh-ovm` already enforces that we run solcjs, and within that task we do the `//  @unsupported: …
=> fix(hh-ovm): Working builds for M1 macs

.changeset/violet-comics-reflect.md, packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts
Checks to make sure that the `decoded` transaction is not null before attempting to reference its `value`
=> dtl: prevent null reference in L1 handler

.changeset/cyan-days-act.md, packages/data-transport-layer/src/services/l1-ingestion/service.ts
Adds better error logging to the DTL. Previously it would log an empty object for the error and now it logs the stack as well as the error message
=> dtl: error logging with message, stack and code

.github/workflows/ts-packages.yml
Temporarily removes `codechecks` from CI until https://github.com/ethereum-optimism/optimism/issues/767 is fixed
This will allow CI to pass again, the problem is due to a bug in `codechecks`
=> temp: remove codechecks

.changeset/thin-horses-change.md, packages/contracts/contracts/optimistic-ethereum/libraries/trie/Lib_MerkleTrie.sol, packages/contracts/contracts/optimistic-ethereum/libraries/trie/Lib_SecureMerkleTrie.sol, packages/contracts/contracts/test-libraries/trie/TestLib_MerkleTrie.sol, packages/contracts/contracts/test-libraries/trie/TestLib_SecureMerkleTrie.sol
Removes `Lib_MerkleTrie.verifyExclusionProof` and the various references to it. We haven't been using this method at all, I don't see why it needs to remain in the codebase. 
**Metadata**
- Fixes #770
=> fix[contracts]: Remove verifyExclusionProof

.changeset/beige-keys-hammer.md, .changeset/brown-bananas-deny.md, .changeset/tough-lamps-hammer.md, .changeset/violet-comics-reflect.md, l2geth/rollup/client.go, packages/core-utils/src/common/hex-strings.ts, packages/core-utils/test/common/hex-utils.spec.ts, packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts, packages/data-transport-layer/src/services/l2-ingestion/handlers/transaction.ts, packages/data-transport-layer/src/types/database-types.ts
This backports two commits from `v0.3.0-rc` that allow for the DTL and l2geth to handle values. This will allow for the syncing of a replica to be 1:1 with state roots. Currently, values are not supported but there was a bug that allowed transactions with value to slip through and there are some txs on mainnet right now that have value. Their blocknumbers are:
- 7
- 10644
- 17210
- 26523
- 26525
The lack of value parsing causes the `ecrecover` to differ which results in a different account to have its nonce incremented.
This PR should make it so that the values are propagated and the correct accounts have their nonces incremented, maintaining correct state roots in replicas
=> fix: backport value fixes

.github/workflows/ts-packages.yml, packages/contracts/package.json, yarn.lock
Undoes the temp removal of codechecks in #768 following a fix from maintainer
=> Reinstate codechecks

packages/contracts/src/contract-data.ts, packages/contracts/tsconfig.json
Add deployment artifacts into built distributed code to enable easy use by other packages.
=> Add deployment artifacts into built distributed code.

.changeset/fluffy-mangos-rest.md, packages/core-utils/src/coders/ecdsa-coder.ts, packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts
The bug in the enums has returned with recent changes to the batch submitter and l2geth. The enum scheme is being deprecated very shortly in `v0.3.0`, this patch is meant to fix verifiers that sync from L1 because `ETH_SIGN` transactions were submitted starting in batch 338 with a 2 enum instead of a 1 enum. This is due to the raw transaction bytes being used for batch submission because l2geth would mutate the first byte previously to fit what the contracts needed.
This code will be deleted in `v0.3.0`
=> fix: tx enums

packages/batch-submitter/package.json, packages/common-ts/package.json, packages/contracts/package.json, packages/core-utils/package.json, packages/data-transport-layer/package.json, packages/hardhat-ovm/package.json, packages/message-relayer/package.json, packages/smock/package.json, yarn.lock
We didn't have `tslint` and its various plugins as part of the `package.json` of every package. As a result, we accidentally broke CI when pruning old packages. This fixes that problem and ensures every package has a reference to tslint and the appropriate plugins.
=> chore: Explicitly add tslint and plugins to deps of every package

integration-tests/contracts/ConstructorReverter.sol, integration-tests/contracts/Reverter.sol, integration-tests/test/rpc.spec.ts, integration-tests/test/shared/utils.ts
This PR adds some tests which can now all pass with the ABI-decoded geth output.  This will prevent future regressions in how the node handles exceptions.
- Solves https://github.com/ethereum-optimism/optimism/issues/648
=> test(integration-tests): add reversion RPC coverage

tsconfig.build.json, tsconfig.json
Removes skipLibCheck, paths, and baseUrl from base typescript config. It's not clear from the commit history why these were added, and the integration tests have passed for me locally on a fresh build with these changes added.
=> Remove unnecessary tsconfig arguments

.changeset/nasty-bees-remain.md, packages/message-relayer/src/service.ts
This PR will have the message relayer check the address manager and compare its address against the address in the message relayer if there is an address set at `OVM_L2MessageRelayer`
This will help to surface misconfigurations in the future more quickly
=> message-relayer: add in address check for better error alerting

.changeset/early-hats-sell.md, integration-tests/contracts/ERC20.sol, integration-tests/hardhat.config.ts, integration-tests/package.json, integration-tests/test/erc20.spec.ts, l2geth/accounts/abi/abi.go, l2geth/internal/ethapi/api.go
Attempting to add some tweaks to geth that will fix #773. Essentially just porting the code over from the latest upstream version of Geth (with a few tweaks to make the types match up).
**Metadata**
Fixes #773
=> feat[l2geth]: Pass up contract revert reasons during DoEstimateGas

.changeset/sour-onions-burn.md, l2geth/scripts/start.sh
This PR adds websocket port parsing to the `l2geth` start script found at `scripts/start.sh`. This script is very useful for local development when you don't want to have to rebuild the docker images
=> l2geth: start script ws

.changeset/pink-buttons-hang.md, packages/batch-submitter/src/exec/run-batch-submitter.ts
Splits up the batch submitter sequencer keys and proposer keys to allow for a different `sequencer account` and `proposer account`. This avoids nonce race conditions when submitting tx batches & state batches
=> feat: add proposer & sequencer signers to BS

.changeset/kind-bears-think.md, packages/contracts/package.json
Moves the following dependencies within `@eth-optimism/contracts` to `devDependencies`:
- @openzeppelin/contracts
- @openzeppelin/contracts-upgradeable
- @typechain/hardhat
- ganache-core
Also removes a duplicated `solidity-coverage` dependency. 
I don't think any of these packages are needed in the main dependencies. `ganache-core` is the primary one I'm skeptical of, but it's only used within `bin/take-dump.ts`. I'm hoping that this will make the whole package browser compatible.
=> maintenance[contracts]: move various deps to dev deps

packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ETHGateway.sol
Adds a docstring to the `donateETH` function
=> Feat: migrate eth gateway docstring

.changeset/gorgeous-countries-listen.md, l2geth/miner/worker.go
Fixes a bug in the prevent monotonicity logic where the updated timestamp is not used. The old code updated the `L1Timestamp` on the transaction struct but didn't pass it along to the block header. The timestamp for evm execution is pulled from the block timestamp. This will prevent the same bug from happening again
=> fix: geth miner timestamp bug

packages/common-ts/src/common/logger.ts, packages/hardhat-ovm/src/index.ts, tslint.base.json
Updates `tslint.base.json` to require that `if` statements use curly braces. Also lints files to pass that check.
=> style: require curly braces for if statements

integration-tests/test/rpc.spec.ts
Just adding more RPC coverage to prevent future regressions!
**Metadata**
- Fixes OP-357
=> integration-tests: Add coverage for eth_call out-of-gas messages

.changeset/thin-rockets-clean.md, l2geth/scripts/start.sh
Updates the local dev script `scripts/start.sh` with the new mainnet values post `v0.3.0` regenesis and also adds a CLI flag to disable turning on the sync service. This is useful for general debugging purposes
=> l2 geth: start script mainnetv3

l2geth/cmd/utils/flags.go, l2geth/rollup/client.go, l2geth/rollup/sync_service.go, l2geth/rollup/sync_service_test.go
Updates to https://github.com/ethereum-optimism/optimism/pull/552 that refactor codepaths into more reusable code paths
Now the general syncing logic all goes through the same codepaths. New methods are added to the rollup client that allow for a shared interface between each so that the syncing logic can be generalized. All syncing is based on indices of transactions or batches, so a remote tip index is fetched and then compared against the current known tip and then the transactions in that range are fetched.
Comments are added to `SyncService.applyTransactionToTip` that describe the way that it mutates `SyncService` internal state or incoming transactions. These side effects 1) update the L2 EVM context (blocknumber and timestamp) and 2) guarantee monotonicity by giving …
=> l2geth: sync spec refactor

.changeset/config.json, .github/workflows/release.yml
Now that `develop` is the default branch, we should generate packages from the branch for testing deployments.
Added the `develop` branch to the workflows:
- geth unit tests
- integration
- Release
- typescript / contracts
=> Update Github Actions for the develop branch

.changeset/chatty-walls-rescue.md, packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ProxyEOA.sol, packages/contracts/test/contracts/OVM/accounts/OVM_ProxyEOA.spec.ts
Temporarily disables upgrades within `OVM_ProxyEOA` to prevent users from changing their EOA to a contract that doesn't pay fees. Will be re-enabled once we have a whitelisting system for contracts that are guaranteed to pay fees correctly (or figure out some alternative mechanism entirely).
=> feat[contracts]: temporarily disable EOA upgrades

.changeset/flat-bananas-perform.md, packages/contracts/contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol, packages/core-utils/src/events.ts, packages/data-transport-layer/src/services/l1-ingestion/service.ts
Updates `AddressSet` so that the `_name` of the changed contract is indexed and that the `_oldAddress` is emitted along with the `_newAddress`. Speeds up some event searching within the `data-transport-layer`. Seems like something quick and useful to sneak into 0.4.0. Would address https://github.com/ethereum-optimism/optimism/issues/625.
=> feat[contracts]: Update Lib_AddressManager.AddressSet event to speed up data transport layer

.changeset/old-ladybugs-camp.md, .changeset/tasty-bottles-decide.md, packages/batch-submitter/.env.example, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/common-ts/package.json, packages/common-ts/src/common/metrics.ts, packages/common-ts/test/metrics.spec.ts, yarn.lock
Added light server to batch submitter to serve `/metrics` endpoint for our dashboards.
**Metadata**
- Fixes OP-701
=> feat[batch-submitter]: add lightweight metrics server

.changeset/kind-cows-draw.md, packages/data-transport-layer/package.json, packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts, packages/data-transport-layer/src/services/l2-ingestion/handlers/transaction.ts, packages/data-transport-layer/src/types/database-types.ts, packages/data-transport-layer/src/utils/constants.ts, packages/data-transport-layer/test/unit-tests/services/l1-ingestion/handlers/sequencer-batch-appended.spec.ts, packages/data-transport-layer/test/unit-tests/services/l2-ingestion/handlers/transaction.spec.ts
This PR adds in RLP serialization for when syncing from L2. This is required for matching state roots if syncing in replica mode
=> dtl: fix replica tx indexing

.changeset/cyan-spiders-listen.md, l2geth/rollup/client.go, packages/data-transport-layer/src/services/l2-ingestion/handlers/transaction.ts
Fixes a bug where there is non-determinism with state roots with replica syncing
The problem was introduced when switching to RLP - previously, sending a transaction to `address(0)` would mean contract creation because we were using a custom serialization. Now that we are using RLP, the target of `RLP(null)` signifies a contract creation. This passes through that information correctly to replicas
Fixes https://github.com/ethereum-optimism/optimism/issues/877
=> optimism: syncing dtl with correct contracts

packages/batch-submitter/.env.example, packages/batch-submitter/src/exec/run-batch-submitter.ts
Fixes reading the default prom server env vars before we switch over to fully using bcfg.
unblocks @optimisticben !
**Metadata**
=> fix[batch-submitter]: read metrics env vars correctly

.changeset/little-emus-cover.md, l2geth/miner/worker.go
Removes the `panic` from the miner
=> l2geth: remove miner panic

README.md
Reverts ethereum-optimism/optimism#914, per @gakonst comment there:
> This was not missing because integration tests bring the network up #699. This PR should be reverted, or an additional change should be made in the readme that runs the integration tests like `NO_NETWORK=1 yarn test:integration`, so that the network doesn't get brought up via this [flag](https://github.com/ethereum-optimism/optimism/blob/develop/integration-tests/test/setup-docker-compose-network.js#L5)
=> Revert "docs: add docker-compose up step to README"

.changeset/cuddly-ravens-smile.md, integration-tests/test/rpc.spec.ts, l2geth/internal/ethapi/api.go
This PR fixes a bug where reverts would not be correctly propagated during `eth_call`. I based these changes on similar logic performed in upstream geth: https://github.com/ethereum/go-ethereum/blob/3e795881ea6d68c32da5da3c95f0d458a64e35c3/internal/ethapi/api.go#L948-L955.
Should fix that last issue we were having with uniswap tests.
=> fix[l2geth]: fix a bug where call reverts would not be propagated

.changeset/sharp-roses-admire.md, packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol, packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ProxyEOA.sol, packages/contracts/test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts, packages/contracts/test/contracts/OVM/accounts/OVM_ProxyEOA.spec.ts
This changes our disabling of upgradability from being done in the proxy to being done in the ECDSAContractWallet. This way we only need to self upgrade a single contract instead of every single EOA
A change which was prompted by Platocrat's great presentation!
=> fix:  disable upgradability from ECDSA Account

.github/label-requires-reviews.yml, .github/labeler.yml, .github/workflows/label-requires-reviews.yml
Update the labeler action to add a new label (`2-reviewers`) for sensitive paths.
Add a new action (`require-reviewers`) which fails unless a PR labeled with `2-reviewers` has 2 or more reviews.
Instead of the inverse match I went this route as this check need to a reviewer count higher then the repo settings.
The `require-reviewers` check needs to be made required on the `develop` branch for this action's intent to be enforced.
=> Github action to require 2 reviewers

packages/contracts/contracts/chugsplash/L2ChugSplashDeployer.sol, packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol, packages/contracts/test/contracts/OVM/execution/OVM_ExecutionManager.gas-spec.ts, packages/contracts/test/contracts/chugsplash/L2ChugSplashDeployer.spec.ts
Adds a flag that will cause the EM to redirect all transactions to the `L2ChugSplashDeployer` while an upgrade is active. Makes sure that we won't have any weird behavior while an upgrade is in progress.
=> feat[contracts]: add ability to pause EM during upgrades

l2geth/cmd/geth/main.go, l2geth/cmd/geth/usage.go, l2geth/cmd/utils/flags.go, l2geth/rollup/config.go, l2geth/rollup/sync_service.go, l2geth/rollup/sync_service_test.go
This adds in L2 state polling in the `sequence` and `verify` loops to pull out the L2 gas price that is set inside of the `OVM_GasPriceOracle` being worked on here: https://github.com/ethereum-optimism/optimism/pull/912
This is fully backwards compatible with the config option `EnableL2GasPolling` as it defaults to false. The config option `GasPriceOracleAddress` will set the address that it reads from, this should default to the `0x42..` address that the contract lives at. Having this address be configurable will let us deploy it to L2 and then update the network with the correct address configured and have it start working. Note that infrastructure providers will also need to reconfigure with the address that the contract ends up being deployed to. …
=> l2geth: gaslimit encoding state polling

yarn.lock
These were deps which were pulled on top due to hoisting, now that we no-hoist examples, they're no longer required.
=> chore: remove unused lockfile info

.changeset/witty-houses-happen.md, packages/hardhat-ovm/src/index.ts
For some reason we were using the completely incorrect URL when modifying the `hardhat-ethers` object. I don't know if this was an error on our part or some sort of dependency that broke, so using `||` to remain backwards compatible if it indeed was an updated dependency. Also moves the step where we update the provider to the very end of the modification code so we can avoid weird issues when overriding `getSigners`.
**Metadata**
- Fixes #935
=> fix[hardhat-ovm]: use correct url when creating ethers object

.changeset/rotten-pillows-change.md, integration-tests/contracts/TestOOG.sol, integration-tests/test/rpc.spec.ts, l2geth/internal/ethapi/api.go
Adds an integration test for contract deployments that run out of gas. Also updates the returned error message to be more clear, following the same pattern that upstream geth uses: https://github.com/ethereum/go-ethereum/blob/154ca32a8ade0a7d2461d0eb432361261a51a395/internal/ethapi/api.go#L1061
**Metadata**
- Fixes #761
=> test[integration-tests]: add an integration test for contract deployments that run out of gas

.changeset/rude-chefs-sniff.md, packages/contracts/contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol, packages/contracts/contracts/optimistic-ethereum/iOVM/bridge/messaging/iOVM_L1CrossDomainMessenger.sol, packages/contracts/contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitioner.sol, packages/contracts/contracts/optimistic-ethereum/libraries/trie/Lib_MerkleTrie.sol, packages/contracts/contracts/optimistic-ethereum/libraries/trie/Lib_SecureMerkleTrie.sol, packages/contracts/contracts/test-libraries/trie/TestLib_MerkleTrie.sol, packages/contracts/contracts/test-libraries/trie/TestLib_SecureMerkleTrie.sol, packages/contracts/test/contracts/OVM/bridge/base/OVM_L1CrossDomainMessenger.spec.ts, packages/contracts/test/contracts/OVM/bridge/base/OVM_L1MultiMessageRelayer.spec.ts, packages/contracts/test/contracts/OVM/verification/OVM_StateTransitioner.spec.ts, packages/contracts/test/contracts/libraries/trie/Lib_MerkleTrie.spec.ts, packages/contracts/test/helpers/trie/trie-test-generator.ts, packages/message-relayer/package.json, packages/message-relayer/src/service.ts
Optimizes `Lib_MerkleTrie` functions by skipping an unnecessary RLP decoding step. I'm really not sure *why* I originally implemented this step, but this alternative is totally fine and should save a bunch of gas.
=> feat[contracts]: optimize MerkleTrie by skipping an RLP decoding step

.changeset/twelve-peas-compete.md, packages/message-relayer/src/service.ts
Updates the `message-relayer` to automatically remove any events from the cache that are no longer necessary. We ended up holding these cached events forever and would eventually get OOM killed.
=> fix[message-relayer]: avoid getting OOM killed

.changeset/two-suits-care.md, l2geth/cmd/utils/flags.go
Adds an env var `METRICS_ENABLE` for the `MetricsEnabledFlag` CLI arg.
=> fix(l2geth): add an env var METRICS_ENABLE for MetricsEnabledFlag

.changeset/tame-stingrays-retire.md, packages/hardhat-ovm/src/index.ts
Currently the hardhat-ovm plugin isn't allowing for private keys for accounts from hardhat.config.js (it's always looking for mnemonic). This PR adds support for private key account config option as allowed by [hardhat config](https://hardhat.org/config/).
**Metadata**
=> fix[hardhat-ovm]: Allow for private key config option for signers

.github/workflows/publish-canary.yml, .github/workflows/release.yml
This pull request does two things:
1. Removes the auto-publishing of new tagged npm packages and Docker images from merge to `develop`
2. Introduces a new tool usable via the [Actions](https://github.com/ethereum-optimism/optimism/actions) tab on Github which allows a developer to publish `npm` versions and Docker images at a [snapshot](https://github.com/atlassian/changesets/blob/main/docs/snapshot-releases.md) given a branch. For example: `0.0.0-canary-127312312` may be the tag name for every package.
(1) solves the issue of us needing to make changes to our code before we merge to `master`, which is true "stable" branch. (2) gives us the tool we need once (1) is done to still be able to test on `k8s` and other production-like environments.
=> Remove auto-publishing on develop; add canary tool

.changeset/neat-melons-lie.md, packages/smock/src/smockit/smockit.ts, packages/smock/test/contracts/TestHelpers_BasicReturnContract.sol, packages/smock/test/smockit/function-manipulation.spec.ts
Fixes a bug where smock would not correctly handle overloaded functions. Let's call this a feature. Yay!
=> feat[smock]: add support for overloaded functions

.changeset/chilled-books-grab.md, .changeset/dull-fishes-type.md, l2geth/rollup/client.go, packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts, packages/data-transport-layer/src/services/l2-ingestion/handlers/transaction.ts, packages/data-transport-layer/src/types/database-types.ts
Represents gas limit as a string within `DecodedSequencerBatchTransaction`s in order to avoid issues where particularly large gas limits would crash the DTL.
=> fix[dtl]: represent gas limit as a string to avoid issues with large gas limits

.changeset/cold-cows-cross.md, integration-tests/hardhat.config.ts
Reduces the timeout on integration tests from 100 to 20 seconds. I think this is a reasonable compromise between the developer experience of running and testing on a laptop (possibly requiring more time), and the time required to run a test in CI (average is about 4 seconds).
The current timeout of 100 seconds is much more than necessary.  I suspect it’s probably a relic from before running yarn test:integration properly handled waiting for the sequencer to come up.
=> chore: reduce hardhat timeout to 20 seconds

packages/contracts/src/contract-deployment/config.ts
Adds an import that was removed when splitting apart 0.4.0 and 0.50.
=> fix(contracts): import predeploys

.changeset/fuzzy-dogs-share.md, integration-tests/test/erc20.spec.ts, integration-tests/test/fee-payment.spec.ts, integration-tests/test/native-eth.spec.ts, integration-tests/test/rpc.spec.ts, l2geth/core/rollup_fee.go, l2geth/core/rollup_fee_test.go, l2geth/eth/gasprice/rollup_gasprice.go, l2geth/internal/ethapi/api.go, l2geth/rollup/client.go, l2geth/rollup/fees/rollup_fee.go, l2geth/rollup/fees/rollup_fee_test.go, l2geth/rollup/sync_service.go, l2geth/rollup/sync_service_test.go, packages/core-utils/README.md, packages/core-utils/src/fees.ts, packages/core-utils/test/fees/fees.spec.ts
This PR implements the next iteration of the fee spec
```
fee = (floor((l1GasLimit*l1GasPrice + l2GasLimit*l2GasPrice) / max(tx.gasPrice, 1)) + l2GasLimit) * tx.gasPrice
```
Where `tx.gasPrice` is set to 1000
The diff to the actual fee logic can be found in https://github.com/ethereum-optimism/optimism/pull/976/commits/75ccc47b973ac9d1e0d6d8bb279d8f9ac5449389 - the functions themselves have been moved out of the `core` package and into the `rollup/fees` package for better modularity
=> feat: fees v2

l2geth/rollup/sync_service_test.go
Fixes an accidental merge conflict introduced in `regenesis/0.4.0`.
=> fix[l2geth]: fix accidental merge conflict

.changeset/cool-baboons-guess.md, packages/smock/src/smockit/smockit.ts, packages/smock/test/contracts/TestHelpers_MockCaller.sol, packages/smock/test/smockit/call-assertions.spec.ts
Fixes a bug that would cause smock call assertions to fail for overloaded functions. Also starts adding tests for call assertions so we avoid this sort of thing in the future. Necessary for Ben's native ETH work.
=> fix[smock]: fix broken call assertions for overloaded functions 

packages/message-relayer/test/unit-tests/relay-tx.spec.ts
Fixes a failing test that was referring to an outdated contract name.
=> fix[message-relayer]: fix failing test because of merge with develop

.changeset/smooth-ears-pay.md, examples/truffle/truffle-config-ovm.js, integration-tests/test/fee-payment.spec.ts, integration-tests/test/native-eth.spec.ts, integration-tests/test/rpc.spec.ts, l2geth/core/tx_pool.go, l2geth/core/types/transaction.go, l2geth/internal/ethapi/api.go, l2geth/rollup/fees/rollup_fee.go, l2geth/rollup/fees/rollup_fee_test.go, packages/core-utils/src/fees.ts, packages/core-utils/test/fees/fees.spec.ts
Updates the fee calculation to match https://github.com/ethereum-optimism/optimism/issues/823#issuecomment-851760512
This scales down the L2 Gas Limit such that it has the granularity of 10,000. The numbers should now show correctly in metamask
=> feat: fees v3

.changeset/great-shrimps-rule.md, packages/message-relayer/README.md, packages/message-relayer/src/relay-tx.ts
Adds a `README.md` and slightly improves on the interface for `getMessagesAndProofsForL2Transaction` for etherscan's sake.
=> docs[message-relayer]: add a README and improve the interface for generating proofs

.changeset/slimy-rivers-promise.md, packages/data-transport-layer/src/services/server/service.ts
This PR adds in logging of the error stack when there is a failed HTTP request to the DTL
This will be nice for debugging purposes
=> dtl: log error stack for failed http request

.changeset/wild-months-matter.md, integration-tests/test/native-eth.spec.ts, integration-tests/test/shared/utils.ts, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/Abs_L1TokenGateway.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/Abs_L2DepositedToken.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ERC20Gateway.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ETHGateway.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2DepositedERC20.sol, packages/contracts/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L1ETHGateway.sol, packages/contracts/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L1TokenGateway.sol, packages/contracts/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L2DepositedToken.sol, packages/contracts/contracts/optimistic-ethereum/libraries/bridge/OVM_CrossDomainEnabled.sol, packages/contracts/test/contracts/OVM/bridge/assets/OVM_L1ERC20Gateway.spec.ts, packages/contracts/test/contracts/OVM/bridge/assets/OVM_L1ETHGateway.spec.ts, packages/contracts/test/contracts/OVM/bridge/assets/OVM_L2DepositedERC20.spec.ts
Enables passing additional information across domains, by adding 3 new arguments to the initiating deposit/withdraw functions: 
- `address _from`: address of the sender on the originating domain
- `bytes _data`: arbitrary data to pass to the receiving domain
- `uint32 gas`: an optional argument allowing the sender to specify the gas amount required to relay the message on the receiving domain (necessary because the `_data` field makes the cost unbounded.
**NOTE:**
This PR replaces #733 which also include changing the function names to us the `inbound`/`outbound` terminology in the [draft EIP](https://ethereum-magicians.org/t/outlining-a-standard-interface-for-cross-domain-erc20-transfers/6151). I cut the scope of the PR down to make it easier to review. Whether or not the terminology …
=> Pass additional information across domains via token gateways

ops/envs/geth.env
Exposes the `debug` namespace for the integration tests so that these methods can have integration tests written for them. Right now there is a known issue with L1 to L2 transactions that cause methods in the `debug` namespace to fail. The error observed is "incorrect nonce" - the L1 to L2 messages technically don't have a "from" and the nonce is set to be the queue index as to prevent hash collisions between L1 to L2 messages. Since they do not have a "from", the nonce should be set to 0 when converting from a `types.Transaction` to a `types.Message` if the queue origin is L1 to L2
=> ops: expose debug namespace

.changeset/kind-houses-rush.md, l2geth/rollup/config.go, l2geth/rollup/sync_service.go
Prevents potential underflow when initializing the sync service with a latest index = 0.
Also removes dead code.
=> fix(sync-service): prevent underflows

.github/workflows/publish-canary.yml
This tags Canary build Docker images with the SHA of the commit hash it is being built for.
=> ci: tag docker image for canary with abbreviated GITHUB_SHA

packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
Helps us understand when transactions are being submitted with increasing gas price.
=> refactor: improve logging for transactions being submitted to chain with gasPrice

.changeset/cold-ways-grow.md, l2geth/rollup/client.go, packages/data-transport-layer/src/db/transport-db.ts, packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts, packages/data-transport-layer/src/services/l2-ingestion/handlers/transaction.ts, packages/data-transport-layer/src/types/database-types.ts
This removes the backwards compatible db fix that prevents overflows in `tx.gasLimit`
It also adds in more overflows checks by storing things as strings.
JSON is stored directly in the db, there is no longer a need to type cast it to a string to prevent overflows for JS numbers. The backwards compatibility allowed for a database with a combo of strings and numbers in it. Post regenesis, there will only be strings.
The DTL is very prone to overflows and we need to do a full pass over it to make sure that it is safe.
=> dtl: remove stringify from db logic + more overflow protection

.github/workflows/integration.yml
Adds logs to the `integration` job if a test case fails.
See [this job](https://github.com/ethereum-optimism/optimism/actions/runs/904282429) for an example.
Fixes OP-508
=> ci: upload logs for failed integration tests

.changeset/spotty-drinks-bathe.md, packages/data-transport-layer/src/services/l2-ingestion/service.ts
Parsing of the `eth_getBlockRange` result was incorrect. This was a bug due to a variable shadowing not realized until a lint error was fixed.
=> fix(dtl): incorrect parsing of eth_getBlockRange result

.changeset/sharp-dragons-check.md, l2geth/core/state_transition.go
We previously have observed account values being set when they shouldn't ever be and it is likely due to this line in the state transition. The unused gas was being refunded to the account. The optimism smart contracts should handle gas accounting instead of geth itself.
This PR simply ends the `refundGas` function early when running the OVM so that the account's balance is not modified
=> fix: no gas refund

.changeset/witty-horses-nail.md, packages/contracts/contracts/chugsplash/L1ChugSplashProxy.sol, packages/contracts/contracts/chugsplash/interfaces/iL1ChugSplashDeployer.sol, packages/contracts/test/contracts/chugsplash/L1ChugSplashProxy.spec.ts
Introduces the `L1ChugSplashProxy` contract. Uses some fancy footwork to avoid function signature collisions with the implementation contract, would appreciate a good amount of review on this.
**TODO**
**Metadata**
- Fixes #707 
- Fixes OP-625
=> feat[contracts]: introduce new L1ChugSplashProxy contract

.changeset/angry-numbers-swim.md, l2geth/rollup/sync_service.go
Replaces `time.Sleep` for loops with ranging over a `time.Ticker`. This pattern is easier for the scheduler to manage
Shoutout @fxfactorial
=> l2geth: optimize loops

.github/workflows/publish-canary.yml
Enables Github user to trigger a deployment with a custom Docker image name
=> Enable custom tagging of release docker image

.changeset/popular-feet-suffer.md, packages/batch-submitter/src/exec/run-batch-submitter.ts
Quickly fixing a typo in the `USE_HARDHAT` config
=> fix: typo in USE_HARDHAT config

.changeset/witty-chefs-learn.md, packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol, packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol, packages/contracts/contracts/optimistic-ethereum/iOVM/accounts/iOVM_ECDSAContractAccount.sol, packages/contracts/contracts/optimistic-ethereum/libraries/codec/Lib_EIP155Tx.sol, packages/contracts/package.json, packages/contracts/test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts, packages/contracts/test/contracts/OVM/accounts/OVM_ProxyEOA.spec.ts, packages/contracts/test/contracts/OVM/precompiles/OVM_SequencerEntrypoint.spec.ts, packages/contracts/test/helpers/types/ovm-types.ts, yarn.lock
This removes the RLP decoding logic from the `OVM_ECDSAContractAccount` because it is being decoded twice. This will lower gas usage for transactions with a lot of calldata.
Allows the `EXECUTE_INTRINSIC_GAS` to be much more predictable and smaller due to not needing to RLP decode the transaction inside of the `OVM_ECDSAContractAccount`. 
See https://github.com/ethereum-optimism/optimism/pull/1008
Fixes OP-859
=> fix: abi encoded tx

.changeset/grumpy-spiders-yell.md, l2geth/go.mod, ops/docker/Dockerfile.geth
Bumps the version of go used by l2geth to 1.15. This is the same version of go that upstream is using, see https://github.com/ethereum/go-ethereum/blob/master/go.mod
=> l2geth: bump to go 1.15

.changeset/shaggy-dogs-attend.md, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
=> Change monotonicity band-aid code to log warnings not errors

.changeset/blue-cooks-join.md, integration-tests/test/predeploys.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/shared/utils.ts, packages/contracts/contracts/optimistic-ethereum/OVM/accounts/OVM_ECDSAContractAccount.sol, packages/contracts/test/contracts/OVM/accounts/OVM_ECDSAContractAccount.spec.ts
Adds ERC1271 support to default contract account implementation. Needed for Uniswap `permit` functionality
Fixes OP-839
=> Add erc1271 support to contract account

.changeset/poor-owls-wash.md, packages/contracts/deploy/014-OVM_L1MultiMessageRelayer.deploy.ts, packages/contracts/deploy/018-fund-accounts.ts, packages/contracts/package.json
Slightly improves the funding mechanism by (1) making it parallel and (2) making it always fund the default hardhat accounts instead of funding whichever accounts are present in the config.
Cherry-picked @smartcontracts work from https://github.com/ethereum-optimism/optimism/pull/1056
=> feat[contracts]: slightly better account funding for hardhat accounts (rebased)

.changeset/modern-chicken-listen.md, packages/batch-submitter/package.json, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/common-ts/src/base-service.ts, packages/data-transport-layer/src/services/main/service.ts, packages/data-transport-layer/src/services/server/service.ts, packages/message-relayer/package.json, packages/message-relayer/src/exec/run.ts, packages/message-relayer/src/service.ts, yarn.lock
Three problems:
- The BaseService did not create `pino-sentry` friendly loggers by default
- The MessageRelayer was not configured to use Sentry at all
- The DTL was using STDOUT for logging errors, explaining their absence in Sentry
Three refactors:
- refactor: add logger and metrics to options for BaseService
- refactor: thread sentryOptions through from message-relayer into BaseService
- refactor: ensure DTL Logger is using Sentry for errors
Fixes OP-857
Fixes OP-856
=> Ensure Sentry is correctly set up for DTL and MR

.changeset/weak-terms-worry.md, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
Per @smartcontracts request
- refactor: log idx of monotonicity violation from batch
- build: add changeset
=> Add more logging information to monotonicity violation logs

.github/workflows/integration.yml
Temporarily disables the hardhat example tests so we can get a few other things merged. Will fix this test for real later.
=> fix: temporarily disable hardhat example tests

.changeset/slimy-snails-roll.md, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
Fix a bug in the fixMonotonicity auto healer. The bug was: when we increase a block's timestamp to fix a monotonicity violation, we did not update the `earliestTimestamp` to be AT MINIMUM the timestamp that we just used. This caused the SUBSEQUENT block to fail with a monotonicity violation.
To address this I simplified the logic we use to heal the timestamps & also updated the earliest timestamp to be AT LEAST the timestamp we just set the block to.
=> fix: monotonicity auto healer

.github/CODEOWNERS
Comments out CODEOWNERS so we don't get automatic review requests anymore but can still track who's responsible for what.
=> fix: comment out CODEOWNERS

.changeset/lazy-toes-teach.md, l2geth/miner/worker.go, l2geth/rollup/sync_service.go
Fixes an off-by-one (actually off-by-two but whatever) error that was breaking replica sync when geth was stopped and restarted. We've tested with hard and soft stops and seems to be working fine now.
=> fix[l2geth]: off-by-one sometimes breaking replica sync

.changeset/ten-pumas-perform.md, l2geth/core/vm/evm.go
Currently, Geth logs this statement "`Reached the end of an OVM execution`" a the end of every EVM `CALL`, which is far too noisy, and pretty meaningless for debugging.
This PR changes this log to occur only at the end of an OVM transaction, which I understand to be the original intent. H/T to @smartcontracts for showing me the fix, I'm just submitting. 
Here is an [image](https://user-images.githubusercontent.com/23033765/121917811-75ce9180-cd03-11eb-802d-2fb4f02636eb.png) of the logs after the change tested locally on my machine. Once the integration tests complete for this PR, you should also be able to see them in the `logs.tgz` file attached. 
Compare that to the logs [ops_l2geth_1.log](https://github.com/ethereum-optimism/optimism/files/6649521/ops_l2geth_1.log) …
=>  Log 'end of OVM execution' correctly

.changeset/selfish-dryers-teach.md, packages/batch-submitter/src/batch-submitter/batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts
Add the error status to our generic error from submissions to separate the different causes.
See ticket / sentry log for details!
**Metadata**
- Fixes OP-808
=> fix[bs]: disambiguate generic submission errors

.changeset/sour-adults-worry.md, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/common-ts/src/common/metrics.ts, packages/data-transport-layer/src/services/server/service.ts
Move the metric prefix string to a label
Changing metric names with a prefix or suffix affects the ability to reuse metric queries. It would be better to keep consistent metric names for the same metrics and use labels to identify specific services.
=> Move the metric prefix string to a label

.changeset/nice-terms-walk.md, packages/smock/package.json, packages/smock/src/smockit/binding.ts, yarn.lock
Fixes a conflict between smock and hardhat 2.4.0. An import that existed in previous versions of hardhat no longer exists as of 2.4.0 (`decodeRevertReason`). I recreated `decodeRevertReason` using the tools available in hardhat@2.4.0 so we can minimize the diff.
**Metadata**
- Fixes #1110
=> fix[smock]: add support for hardhat 2.4.0

.changeset/modern-pets-tie.md, packages/data-transport-layer/src/services/l1-ingestion/service.ts
Slight modification to the DTL so that we're using the same L2 chain ID everywhere. We already have it as an input argument so we can just use it there. Also removes another dependency on the `OVM_ExecutionManager`.
=> fix[dtl]: use the same L2 chain ID everywhere

.github/workflows/sync-tests.yml
Sync tests have been flaky, most likely due to running docker-compose multiple times. As of now, this sync test only runs a trivial test case and likely won't find any actual syncing issues, so I'm removing the workflow.
As follow ups, the best course of action would be to
1. Fix the root cause of verifier mismatches that's forcing us to do this test in a separate workflow
2. Bring the verifier up with the rest of the stack instead of individually during this test, to fix flakiness
**Metadata**
- replica tests would have the same issues, but because replicas don't have the same bugs, we should be able to do the approach in step 2 immediately https://github.com/ethereum-optimism/optimism/pull/981
=> temp: make sync tests workflow dispatch only

.changeset/gold-grapes-beg.md, packages/data-transport-layer/src/db/transport-db.ts
Removes a `stringify` function that was being used temporarily to guarantee backwards compatibility for older DTL instances. Function is no longer necessary after this regenesis because DTL databases will be wiped and will not have incompatible values anymore.
=> fix[dtl]: remove old stringification function

.changeset/lazy-foxes-jump.md, packages/data-transport-layer/src/services/server/service.ts
One-line fix to the DTL so that failed HTTP requests are marked as errors and not as info log lines.
Fixes OP-888
=> fix[dtl]: log server errors as ERROR instead of INFO

.changeset/happy-dancers-raise.md, l2geth/core/state_transition_ovm.go
It is possible to overflow the ABI encoding of the `Lib_OVMCodec.Transaction` from the geth `types.Transaction` on the way into the `OVM_SequencerEntrypoint` due to a type conversion from a `uin64` to an `int64`. This ensures that the types stay the same so that an overflow isn't possible
=> fix: prevent overflow in abi encoding

.changeset/lazy-ghosts-shop.md, packages/message-relayer/package.json
Updates `package.json` inside the message relayer to correctly export ALL files within `/dist` instead of just the index.
=> fix[relayer]: update exported files list in package.json

.changeset/tall-plums-behave.md, README.md, package.json, packages/core-utils/src/watcher.ts
As per #1018, when transaction volume is high, the watcher can sometimes fail to find a transaction receipt. A solution that iteratively queries the logs of the previous 10K blocks until a matching log is found has been implemented. 10K is an upper bound set by `NUM_BLOCKS_TO_FETCH`.
Additionally, a new script (`yarn ready`) has been added to `package.json` which bundles together linting and testing (`yarn lint && yarn test`). Personally I prefer running one command as a "pre-commit" script as opposed to typing out two but this is minor so can remove if preferred.
It may be worthwhile to add in a constant that controls the maximum number of iterations the loop that checks for a log with a matching txhash can run for.
It might also be worth optimizing …
=> Improve Watcher ability to find transactions

.vscode/extensions.json, .vscode/settings.json
Adds a basic VSCode configuration to simplify the setup and encourage contributors to use similar tooling, especially with regard to formatting.
=> Add minimal vscode settings and extensions

.changeset/red-hornets-design.md, packages/contracts/deploy/014-OVM_L1MultiMessageRelayer.deploy.ts
Portion of the deployment removed in this PR *only* impacts mainnet deployments because of the check that network == `mainnet`. If this part of the deployment were executed then only the `OVM_L1MultiMessageRelayer` would be allowed to relay L2 => L1 messages.
=> fix[contracts]: remove part of MultiMessageRelayer deployment

.changeset/big-brooms-melt.md, packages/core-utils/src/watcher.ts
Polling is happening in a while loop, which creates constant fetches. This adds a default 3 sec delay with the option for the user to change it.
=> Adds delay to watcher

.changeset/lovely-poems-cough.md, packages/data-transport-layer/src/services/l1-ingestion/service.ts, packages/data-transport-layer/src/services/main/service.ts
We observed an error of `this` not being bound correctly when going through the codepath that recovers from missing events. Still unsure of the root cause of the missing events, but this should help to recover from them.
=> fix: bind dtl functions for missing event codepath

.vscode/settings.json
#1109 added `"editor.formatOnSave": true` for all files. 
This PR turns that off, though now that it's on, you might also need to disable the setting yourself (`"solidity.formatter": "none"`)
This has caused the [solidity extension](https://github.com/juanfranblanco/vscode-solidity#formatting-using-prettier-and-the-prettier-solidity-plugin) to start formatting our `.sol` files using. We may want to activate this functionality in the near future, but it should be done in a PR which also handles the formatting.
=> fix: remove 'editor.formatOnSave' from global settings'

.eslintrc.js
When the `packages/contracts/hardhat` folder is present in the fs, the linter fails. Here we use the [eslint config option](https://eslint.org/docs/user-guide/configuring/ignoring-code#ignorepatterns-in-config-files) to exclude it from linting.
=> Ignore the hardhat folder from linting

.changeset/thick-birds-jog.md, l2geth/rollup/client.go, l2geth/rollup/client_test.go, l2geth/rollup/sync_service.go
The `RollupClient` was not explicitly checking for remote server errors when querying the DTL. This now will check for remote errors and pass through an error. It also causes the `SyncService` to retry its initial connection to the DTL on startup so that it doesn't shut down on boot up if it intends to connect to a DTL but receives a server error instead.
Fixes problems with a misconfigured DTL, specifically when a L1 Eth Provider is set up properly
=> fix: rollup client check err

.changeset/slimy-bugs-tan.md, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L1CrossDomainMessenger.sol, packages/contracts/src/contract-deployment/config.ts, packages/contracts/test/contracts/OVM/bridge/base/OVM_L1CrossDomainMessenger.spec.ts, packages/contracts/test/contracts/OVM/bridge/base/OVM_L1MultiMessageRelayer.spec.ts, packages/message-relayer/src/service.ts
Removes the `onlyRelayer` modifier which should no longer be used in the system since users will now be able to relay their own withdrawals. Also removes references to the modifier and to the `OVM_L2MessageRelayer` address elsewhere.
**Metadata**
- Closes OP-894
=> maintenance[contracts]: remove onlyRelayer modifier

.changeset/tall-oranges-doubt.md, packages/contracts/contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol, packages/contracts/test/contracts/OVM/chain/OVM_CanonicalTransactionChain.spec.ts, packages/contracts/test/contracts/OVM/execution/OVM_ExecutionManager.gas-spec.ts, packages/contracts/test/helpers/codec/index.ts, packages/contracts/test/helpers/codec/queueOrigin.ts
Fixes an issue which allowed an enqueued transaction to be falsely verified with the `l1QueueOrigin` field set to `SEQUENCER_QUEUE` (instead of `L1TOL2_QUEUE`). 
Although much larger changes are planned for the CTC, this test case should be included in the suite for use during refactoring.
If we object to modifying the code of the CTC as is, an alternative would be to simply add this test case with `.skip`.
=> Prevent modification of QueueOrigin during verification

README.md
Adds a brief section to the primary README that explains how to create a changeset.
=> upkeep[monorepo]: add changeset info to README

.changeset/clever-parents-clap.md, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2StandardTokenFactory.sol, packages/contracts/contracts/optimistic-ethereum/libraries/standards/L2StandardERC20.sol, packages/contracts/deploy-l2/000-OVM_L2StandardTokenFactory.deploy.ts, packages/contracts/test/contracts/OVM/bridge/assets/OVM_L2StandardTokenFactory.spec.ts
We add a factory contract we can whitelist for the community phase which will be used by the Gateway to create standard ERC20 tokens on L2. 
Closes OP-722
=> Factory for creating standard L2 ERC20 tokens

.changeset/weak-bugs-raise.md, packages/contracts/contracts/optimistic-ethereum/iOVM/bridge/messaging/iOVM_CrossDomainMessenger.sol, packages/core-utils/src/watcher.ts
This PR adds an index to the msgHash argument in the `RelayedMessage` and `FailedRelayedMessage` events. This index is needed since the watcher is filtering logs based on the `msgHash`.
See the discussion here for more context: https://github.com/ethereum-optimism/optimism/pull/1107#r654076328
This is my first Solidity PR. Let me know if I missed anything!
**Metadata**
- Fixes https://github.com/ethereum-optimism/optimism/issues/1116
- Fixes OP-915
=> Add index to msgHash

.github/workflows/geth.yml, .github/workflows/integration.yml, .github/workflows/publish-canary.yml
This updates the version of Go that is used in CI to match exactly what is used in production. This is important to keep in sync due to the possibility of the runtime introducing a bug.
Also lints files that had whitespace added to them. Please remember to remove extra whitespace before committing.
Some housecleaning
=> github actions: bump geth CI golang version

.github/workflows/ts-packages.yml
Fixes the statement meant to skip codechecks on PRs from external repositories based on this github thread: https://github.community/t/how-to-detect-a-pull-request-from-a-fork/18363/2. Original statement did not work correctly.
**Metadata**
- Fixes #1202
=> fix: update statement for skipping codechecks

ops/docker/Dockerfile.geth
A bug has appeared when older versions of Docker are used to build
alpine based images in alpine version 3.14. To prevent this problem
from happening to the users, this PR pins the version to 3.13.
The observed problem is that `make` cannot run any command and
the error message states `Operation not permitted.` Removing
`make` was one way to solve the problem but that would increase
the diff from upstream geth.
See these links for details:
https://github.com/alpinelinux/docker-alpine/issues/182
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0
=> docker: pin to alpine 3.13 for l2geth

.changeset/ninety-dryers-brush.md, packages/data-transport-layer/README.md, packages/data-transport-layer/src/services/main/service.ts, packages/data-transport-layer/src/services/run.ts, packages/data-transport-layer/src/services/server/service.ts
Adds a new config option `--l1-gas-price-backend` or
`DATA_TRANSPORT_LAYER_L1_GAS_PRICE_BACKEND` that can be set to `l1` or
`l2`. This impacts the behavior of the HTTP endpoint `GET /eth/gasprice`
by changing what is queried to return the L1 gas price. The L1 gas price
is required to compute the L2 fee since the L2 fee consists of
`L1 gas price * L1 gas used + L1 gas price * L2 gas limit`. If the L1
gas price differs too much between different L2 providers, then users
using `eth_estimateGas` may submit transactions with too low of a fee
and be unable to submit transactions to the sequencer.
By configuring the DTL to use L2 as the L1 gas price backend, it will
call the Sequencer's RPC endpoint `rollup_gasPrices` which returns the
L1 and L2 gas prices from the point of view …
=> dtl: configurable gas price backend

.github/workflows/integration.yml, ops/scripts/stats.sh
Resolves most common issues with CI running out of memory by waiting for the Sequencer before starting the integration tests. Also adds a `stats.sh` script that will log current memory usage of different parts of the system once per second while the integration tests are running.
**Metadata**
- Fixes #1057
=> fix: update CI to avoid running out of memory

.changeset/clean-crabs-wash.md, integration-tests/.env.example, integration-tests/README.md, integration-tests/hardhat.config.ts, integration-tests/package.json, integration-tests/test/basic-l1-l2-communication.spec.ts, integration-tests/test/fee-payment.spec.ts, integration-tests/test/native-eth.spec.ts, integration-tests/test/ovmcontext.spec.ts, integration-tests/test/queue-ingestion.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/shared/env.ts, integration-tests/test/shared/utils.ts, ops/docker/Dockerfile.integration-tests, yarn.lock
This PR contains the following set of tweaks to the integration tests so that the tests can be executed directly against a live network deployment:
- Default mocha timeout for the integration tests is increased from `20000ms` to `150000ms`.
- We no longer rely on the `message-relayer` during the integration tests. Instead, all tests that previously relied on the integration tests must now use a new utility `env.relayXDomainMessages(transaction)`.
- Introduces a new utility `useDynamicTimeoutForWithdrawals` that will dynamically increase the timeout of the current function based on the current challenge period timeout.
- Reduces ETH transfer amounts in tests to `0.0000001` to reduce the amount of ETH that the main wallet needs to have on hand.
- Less strict checks on …
=> feat[integration-tests]: make integration tests work against production networks

ops/docker/rpc-proxy/nginx.template.conf
Allow HTTP POSTs up to 128k.
The rpc-proxy was returning 400 - bad request for http POST's above ~ 16K due to the lua not having access to the nginx body (it was showing up as nil).
```
2021/07/05 20:46:25 [error] 15#15: *103 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/eth-jsonrpc-access.lua:54: bad argument #1 to 'decode' (string expected, got nil)
stack traceback:
coroutine 0:
[C]: in function 'decode'
```
This condition is occurring due to the client_body_buffer_size nginx setting which limits how large the body can be before writing it to a temporary file.
https://github.com/openresty/lua-nginx-module#ngxreqread_body
In my testing this resolved the error.
=> Increase client_body_buffer_size for rpc-proxy

.changeset/many-dots-know.md, l2geth/rollup/client.go, l2geth/rollup/client_test.go
The `RollupClient` decodes the JSON from the DTL as a uint64,
this updates it to be a `big.Int`
=> l2geth: use `hexutil.Big` to prevent overflows

.github/workflows/ts-packages.yml
In order to skip running the CodeCov job when it isn't relevant, a new job was added to the ts-packges workflow. For a PR, this job identifies all the files modified between the base branch and the tip of the PR branch, and writes to a variable which can be used to decide if subsequent jobs should run.
Github Actions provides an easy method for achieving this at the level of a workflow, but not for specific jobs within a workflow.
This work is based on GitHub community post [here](https://github.community/t/run-job-only-if-folder-changed/118292), and at the time of writing, I have no idea if it will work. 
I have not included a changeset, as no package files were changed.
=> ci(contracts): only run codecov if contracts package is modified

.github/workflows/ts-packages.yml
The recently added (#1209) GHA job which skips `test-coverage` when files are unchanged in `packages/contracts` causes a CI error when the event is a `push`. 
This causes issues for maintainers who want to fix conflicts locally and push to a release branch. 
This PR fixes that.
To be safe, I tested that it will still run the jobs when a push is made to an active PR.
* Fixes OP-679
=> chore(ci): Skip check files job on push events

.github/workflows/ext-test-snx.yml, integration-tests/ext-test/snx.sh
Adds a workflow file for running the snx test suite. There might be a cleaner way to do this than to use a separate sh script but whatever, hopefully reviewers will know. Currently workflow can only be triggered manually.
**Metadata**
- Fixes OP-837
=> feat: add workflow for running SNX test suite

.changeset/big-bags-grow.md, packages/contracts/hardhat.config.ts, packages/contracts/tasks/l2-gasprice.ts
Adds a simple task for updating the L2 Gas Price. This shouldn't be used in production but is useful for testnet/local deployments. It checks that the correct key was passed through and then will set the L2 gas price in the `OVM_GasPriceOracle`.
This contract is owned so only a single key can update the gas price currently
```
CONTRACTS_TARGET_NETWORK=... \
CONTRACTS_DEPLOYER_KEY=... \
CONTRACTS_RPC_URL=... \
npx hardhat set-l2-gasprice --network ... --l2-gas-price $(seth --to-wei 10 gwei)
```
Is automated in https://github.com/ethereum-optimism/optimism/pull/1103
=> contracts: add set-l2-gasprice task

.changeset/rich-jars-kick.md, integration-tests/contracts/SimpleStorage.sol, integration-tests/test/shared/env.ts, integration-tests/test/shared/stress-test-helpers.ts, integration-tests/test/stress-tests.spec.ts
Adds a series of new load tests. So far I've got:
- Perform X L1 => L2 transactions
- Perform X L2 => L1 transactions
- Perform X L2 transactions
I'll likely break this out into a series of helper functions so we can compose these different actions into more interesting test cases.
**Metadata**
- Fixes OP-772
=> feat[integration-tests]: add basic stress tests

.changeset/slimy-experts-travel.md, l2geth/cmd/geth/main.go, l2geth/cmd/geth/usage.go, l2geth/cmd/utils/flags.go, l2geth/rollup/config.go, l2geth/rollup/fees/rollup_fee.go, l2geth/rollup/fees/rollup_fee_test.go, l2geth/rollup/sync_service.go, l2geth/rollup/sync_service_test.go
The fees are currently calculated as a sum of the L1 fee and the L2 fee
where the L1 fee is the approximate cost of the batch submission of the
transaction (L1 gas price * L1 gas used) and the L2 fee is the
approximate cost of the execution on L2 taking into account congestion
(L2 gas price * L2 gas limit).
When either the L1 or L2 gas price is volatile, it can result in the
quote that the user receives from `eth_estimateGas` to be rejected
as the fee that the Sequencer is expecting has gone up.
This PR adds logic to set a buffer in either direction of the current
price that will allow the sequencer to still accept transactions within.
Two new config options are added:
- `--rollup.feethresholddown` or `ROLLUP_FEE_THRESHOLD_DOWN`
- `--rollup.feethresholdup` or …
=> l2geth: sequencer fee buffer

.changeset/forty-pigs-study.md, l2geth/rollup/sync_service.go, l2geth/rollup/sync_service_test.go
This PR allows the owner of the `OVM_GasPriceOracle` to send
transactions with 0 gas price when the enforce fees config option
is turned on.
The L2 gas price is currently updated by sending transactions to the
chain to a special contract. In the future it should be updated as a
side effect of transaction execution. Having the gas price on chain is
important so that it can be replicated accross the network to ensure
that users can send transactions with a high enough fee.
Having the `OVM_GasPriceOracle.owner` key not need to maintain
ETH on L2 is an operational simplification as well prevents a
terrible scenario where a bug causes the L2 gas price to go so high
that it is impossible for the owner to update it.
**Metadata**
=> l2geth: allow 0 gasprice txs for `OVM_GasPriceOracle.owner`

.github/workflows/release.yml, ops/scripts/ci-versions.js
This PR updates the `ops/scripts/ci-versions.js` file
to skip building the builder image for when there
are changes to the `gas-oracle`. The `builder` contains
all of the JS code required for the various typescript
based services.
This PR also publishes `ethereumoptimism/gas-oracle:latest`.
It is faster to `docker pull` than `docker build`.
This will speed up the workflow for developers building locally
against the `docker compose` setup as well as the CI if it
is refactored to pull the `latest` images for the unchanged images
instead of building them from scratch.
=> ci: handle gas-oracle latest image, skip builder

.changeset/plenty-walls-compare.md, packages/contracts/tasks/l2-gasprice.ts
This PR lints the tasks directory
It is also a round about way to force a publish of the go based software since the CI only does docker publishes if there are npm packages to publish as well
=> contracts: lint the tasks directory

.changeset/wise-mails-laugh.md, packages/smock/README.md, packages/smock/test/contracts/TestHelpers_BasicReturnContract.sol, packages/smock/test/smockit/function-manipulation.spec.ts
Minor PR, just adding a test and docs for returning more than one array in a smocked function.
**Metadata**
- Fixes #1228
=> maintance[smock]: add test and docs for returning multiple arrays

.changeset/tidy-swans-mate.md, l2geth/core/tx_pool.go
This PR makes it so that the sequencer will
only accept transactions if the nonce exactly
matches what is in the state. This is because the
mempool in upstream geth has different rules than
what l2geth needs.
This prevents issues with local nonce managers that
send transactions with a too large of nonce and
end up having all of the transactions revert since
the transaction is still accepted but reverts
in the OVM
=> l2geth: only accept txs with exact nonce

.changeset/six-cobras-fold.md, l2geth/cmd/utils/flags.go
The parsing of the `ROLLUP_FEE_THRESHOLD_UP` and
`ROLLUP_FEE_THRESHOLD_DOWN` config options were set to be boolean flags
instead of float64 flags. The config flags wouldn't parse if a float64
was used as a bool flag.
=> l2geth: fix bad flag parsing

.changeset/cool-birds-rescue.md, l2geth/rollup/sync_service.go
The sequencer will reject transactions when the fee
is too large to prevent users from accidentally sending
transactions with a huge fee.
This PR adds an actionable error message for when
the fee is too large.
=> l2geth: better error message for when fee is too large

.changeset/dry-chairs-watch.md, l2geth/rollup/fees/rollup_fee.go, l2geth/rollup/fees/rollup_fee_test.go, l2geth/rollup/sync_service.go
There was a bug in the floating point math that allowed
for transactions with extremely low fees to get through.
This PR fixes that bug as well as adds additional test
cases.
=> l2geth: prevent too low of fees from getting through

.changeset/nasty-tools-wink.md, l2geth/internal/ethapi/api.go
https://github.com/ethereum-optimism/optimism/pull/1279
=> fix(l2geth): revert rpcGasCap logic to upstream geth behavior

ops/README.md
/ops produces gigabytes per day in logs. Adds advice to /ops/README.md avoid disk exhaustion issues.
**Metadata**
- Fixes https://github.com/ethereum-optimism/optimism/issues/1281
=> Add logging advice to /ops/README.md to avoid disk exhaustion problems

.changeset/loud-rings-beg.md, packages/smock/src/smoddit/storage.ts, packages/smock/test/contracts/SimpleStorageGetter.sol, packages/smock/test/smoddit/smoddit.spec.ts
Fixes #1275 by adding basic support for packed storage slots. I'm calling this "naive" because I'm not sure if there are edge cases that are not covered by this very simple logic.
**Metadata**
- Fixes #1275
=> fix[smock]: add naive support for packed storage slots

.changeset/nervous-donuts-laugh.md, l2geth/rollup/sync_service.go
Update the error message returned when the fee is too
high to return the correct multiplication. It should be
the expected fee * the fee threshold up.
=> l2geth: fee too high error message

.changeset/wet-foxes-collect.md, l2geth/eth/backend.go
The blockhashes can be non deterministic because there is not a global
consensus in the existing deployment of the optimism network, instead
each node runs with `--dev 0` meaning that it auto mines transactions
itself. Previously, block hashes were non deterministic due to a
different clique signing key being used but that was fixed so that
a deterministic key is used for all nodes.
This fixes the possibility of the block extradata being different which
would result in different block hashes. The extradata is hard coded
to be the same value as the release @eth-optimism/l2geth@0.4.6. In
version 0.4.7, the underlying Dockerfile pulled in a patch release of
the Go runtime which caused the extradata field to become different.
The extradata field by default is the version of …
=> l2geth: make block hashes deterministic

.changeset/popular-carpets-applaud.md, packages/contracts/hardhat.config.ts, packages/contracts/tasks/whitelist.ts
This PR adds a hardhat task for whitelisting addresses. It can be used like so:
```
$ npx hardhat whitelist --address 0x.. --use-ledger true --contracts-rpc-url https://...
```
Fixes OP-1139
=> contracts: add hardhat task for whitelisting addresses

.changeset/silent-dolphins-hammer.md, packages/batch-submitter/src/batch-submitter/batch-submitter.ts, packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/batch-submitter/src/index.ts, packages/batch-submitter/src/transaction-chain-contract.ts, packages/batch-submitter/src/utils/index.ts, packages/batch-submitter/src/utils/tx-submission.ts, packages/batch-submitter/test/batch-submitter/batch-submitter.spec.ts, packages/batch-submitter/test/utils/tx-submission.spec.ts
We have observed that when a transaction is stuck in the mempool, the replacement transactions fail to be applied and would return `UNPREDICTABLE_GAS_LIMIT` with the error that the starting index in the batch is incorrect.
The reason the starting index was seemingly incorrect was because `eth_estimateGas` has `blockTag=pending` by default. 
That meant that when we attempted to resubmit our transaction, while estimating gas, it would attempt to reapply the same batch on top of the pending transaction. We explicitly **do not** want this behavior.
This PR changes the batch submitter submission logic in such a way that before submitting the transaction it populates the transaction fields **including** the `gasLimit`. This way we explicitly specify a `gasLimit`, we don't call …
=> fix: estimate gas when pending tx in mempool

.changeset/five-toys-impress.md, l2geth/core/vm/ovm_state_manager.go
This PR removes the assignment of a pointer to the
state manager abi and just directly uses it instead.
There is an assumption that the state manager abi exists,
but this check happens at startup time, when the abis are
pulled from the state dump.
=> l2geth: remove layer of indirection with state manager

.changeset/ten-bugs-cheat.md, l2geth/rollup/sync_service.go
Very minor syntax fix to the syncservice
=> l2geth: small syntax fix in the syncservice

.changeset/fifty-vans-camp.md, l2geth/core/vm/ovm_state_manager.go
There was a usage of `refect` that was not required. This PR removes its
usage so that the code is simplified.
=> l2geth: remove unnecessary reflect

.changeset/shy-ligers-smile.md, l2geth/miner/worker.go
This PR deletes pending tasks in the miner codepath that result in
a buildup of state objects. The pending tasks will grow over time
without deleting them, resulting in a memory leak.
**Metadata**
- Fixes OP-941
- Closes https://github.com/ethereum-optimism/optimism/issues/1333
=> l2geth: delete pending tasks in miner

.changeset/brave-bananas-bow.md, l2geth/core/vm/ovm_state_manager.go
Updates the style to encapsulate the `err` so that it
doesn't need to reassign `err` and can instead keep
the `err` in its own scope.
=> l2geth: small style fix to the state manager precompile

.changeset/new-elephants-rush.md, l2geth/core/state_transition.go, l2geth/core/vm/evm.go
The `id` field was added to the EVM to allow for the logs to make sense
during concurrent calls to EVM execution. It adds a diff and is not
required now that `eth_call` is no longer logged.
=> l2geth: removes the id from the evm

.changeset/gentle-geckos-approve.md, l2geth/eth/api_backend.go
When the custom batch serialization was being used instead of RLP, a
transaction being sent to `address(0)` was not allowed because that
meant that it was a contract creation because there is no abi encoding
for `nil`. To prevent collisions, transactions sent via RPC to
`address(0)` were banned. Now the RLP transactions are being used, this
check can be removed. It helps to reduce the diff from upstream geth.
=> l2geth: allow RPC transactions to go to `address(0)`

.changeset/small-swans-punch.md, l2geth/core/blockchain.go, l2geth/eth/api_backend.go, l2geth/internal/ethapi/backend.go, l2geth/miner/worker.go
This PR removes dead code that was responsible for timestamp management.
This codepath is no longer used so removing it will reduce the diff.
=> l2geth: remove dead code in `blockchain.go` and `miner/worker.go`

.changeset/red-peaches-kneel.md, .github/workflows/publish-canary.yml, .github/workflows/release.yml, ops/docker/Dockerfile.replica-healthcheck, packages/replica-healthcheck/src/healthcheck-server.ts
Adding replica-healthcheck to be published as a docker image since some providers are interested in using it!
I didn't add a script for this to be run along the other services and also didn't add it to docker-compose, happy to do so if we think this belongs in the dafault stack though!
**Metadata**
- Fixes OP-1207
=> ci: add replica-healthcheck to image publish workflow

packages/contracts/contracts/optimistic-ethereum/OVM/predeploys/OVM_L2ToL1MessagePasser.sol
`OVM_L2ToL1MessagePasser` contract's runtime target should be OVM, not EVM.
=> Fix runtime target comment

.changeset/empty-colts-attack.md, .changeset/healthy-dragons-worry.md, packages/batch-submitter/src/batch-submitter/batch-submitter.ts, packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/data-transport-layer/src/services/l1-ingestion/service.ts
This PR migrates the applications to use the Ethers.js
StaticJsonRpcProvider to reduce the number of requests
that are being sent.
Fixes  ENG-1161
=> batch-submitter,dtl: use ethers.StaticJsonRpcProvider

.changeset/many-pants-appear.md, packages/contracts/src/contract-defs.ts
Guess I missed this the first time around. Necessary to guarantee that the contracts package will be browser compatible.
=> fix: correctly use contract artifact import

.changeset/quiet-wasps-help.md, packages/core-utils/src/watcher.ts
Alchemy's limit of 2k blocks in the past still gets breached with 2k num blocks to fetch because in some cases a new block gets produced during the time between when the call to block number is made and the call to fetch logs.
Lowered to 1.5k to be safe in this PR. maybe even safer to go down to 1k?
=> Watcher: Even lower num blocks to fetch

.changeset/popular-tools-jog.md, l2geth/cmd/geth/main.go, l2geth/cmd/geth/usage.go, l2geth/cmd/utils/flags.go, l2geth/rollup/config.go, l2geth/rollup/fees/rollup_fee.go, l2geth/rollup/sync_service.go, l2geth/rollup/sync_service_test.go
This commit adds a new config flag `--rollup.minl2gaslimit` that
defaults to `0` and is used to prevent transactions from being ingested
that have a L2 gas limit smaller than the value configured. This
config flag can also be controlled with the env var
`ROLLUP_MIN_L2_GAS_LIMIT`.
This can be dropped on the experimental branch
**Metadata**
=> l2geth: configurable min L2 gas limit

.changeset/green-feet-begin.md, packages/contracts/hardhat.config.ts, packages/contracts/package.json, yarn.lock
Since https://github.com/nomiclabs/hardhat/releases/tag/hardhat-etherscan-v2.1.5 we can use hardhat verification for ovm compiled contracts to verify their source on etherscan. Here we add the required package and kovan and mainnet config to enable us to verify deployed contracts via the command line.
=> Add etherscan verification support

.changeset/nice-waves-jog.md, packages/core-utils/test/coders/batch-encoder.spec.ts, packages/core-utils/test/common/hex-utils.spec.ts, packages/core-utils/test/common/misc.spec.ts, packages/core-utils/test/fees/fees.spec.ts
- Increase coverage in `core-utils` package (71.3% up from 64%, 100% for all files excluding `l2context.ts` and `watcher.ts`)
- This doesn't currently handler increased coverage around `l2context` and `watcher` but that can be included if preferred.
This shouldn't be merged until #1412 is merged.
**Metadata**
- Directly a follow up to #1412
=> Extended test coverage of core-utils

.changeset/yellow-tomatoes-peel.md, packages/batch-submitter/src/batch-submitter/batch-submitter.ts
Log values related to eip1559 before sending a transaction.
- `maxFeePerGas`
- `maxPriorityFeePerGas`
Also log the `gasLimit` in case transactions revert.
Batches are being submitted to L1 with the same tip and max priority fee, the tip should be set lower. This will help to debug
=> batch-submitter: eip1559 logging

.changeset/sweet-actors-hope.md, go/utils/fees/rollup_fee.go, integration-tests/test/rpc.spec.ts, l2geth/rollup/fees/rollup_fee.go, packages/core-utils/src/fees.ts
Lowers per tx fee overhead to more accurately reflect L1 batch submission costs. This overhead value represents the sum of the non-calldata per tx overhead to submit a tx to the CTC (~ 1700 gas) and the per tx cost of submitting a state root to the SCC (~1060 gas)
Fixes ENG-1352
=> Lower per tx fee overhead

.changeset/many-masks-exercise.md, integration-tests/contracts/OVMContextStorage.sol, integration-tests/test/ovmcontext.spec.ts, l2geth/core/evm.go, l2geth/rollup/dump/constants.go
Some final opcode tweaks:
1. Difficulty always returns ZERO.
2. Coinbase always returns SequencerFeeVault.address.
**Metadata**
- Fixes ENG-1366
- Fixes ENG-1367
=> feat: final opcode tweaks

.changeset/rotten-kids-fly.md, packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts
Fixes the state batch submitter to use the same nonce when submitting transactions. Otherwise it tries to submit lots of transactions with increasing nonces.
=> fix: use the same nonce for each batch submission

.changeset/ninety-years-smell.md, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1StandardBridge.sol, packages/contracts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2StandardBridge.sol, packages/contracts/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L1ERC20Bridge.sol, packages/contracts/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L2ERC20Bridge.sol, packages/contracts/hardhat.config.ts
Some of the custom L1 bridges don't have an `l2TokenBridge()` address getter. 
This change would prevent that by adding the getter to the interface. The same is done on the L2 interface.
**Metadata**
Fixes ENG-1174
=> ERC20 Bridge interfaces: Add a getter to return the cross-domain bridge address

.changeset/unlucky-beds-train.md, packages/contracts/contracts/L1/messaging/OVM_L1CrossDomainMessenger.sol, packages/contracts/contracts/L1/rollup/iOVM_CanonicalTransactionChain.sol, packages/contracts/contracts/L2/messaging/OVM_L2CrossDomainMessenger.sol, packages/contracts/contracts/libraries/bridge/iOVM_CrossDomainMessenger.sol, packages/contracts/contracts/libraries/codec/Lib_OVMCodec.sol, packages/contracts/contracts/libraries/rlp/Lib_RLPWriter.sol, packages/contracts/contracts/libraries/utils/Lib_Bytes32Utils.sol, packages/contracts/contracts/libraries/utils/Lib_BytesUtils.sol, packages/core-utils/src/watcher.ts, packages/message-relayer/src/relay-tx.ts, packages/message-relayer/src/service.ts, packages/message-relayer/test/test-contracts/MockL2CrossDomainMessenger.sol
- `Account` struct in `Lib_OVMCodec`
- suggested dead code reported by `slither` 
```
Lib_Bytes32Utils.removeLeadingZeros(bytes32) (contracts/libraries/utils/Lib_Bytes32Utils.sol#86-116) is never used and should be removed
Lib_BytesUtils.toAddress(bytes,uint256) (contracts/libraries/utils/Lib_BytesUtils.sol#194-213) is never used and should be removed
Lib_BytesUtils.toBytes32PadLeft(bytes) (contracts/libraries/utils/Lib_BytesUtils.sol#103-118) is never used and should be removed
Lib_BytesUtils.toUint24(bytes,uint256) (contracts/libraries/utils/Lib_BytesUtils.sol#152-171) is never used and should be removed
Lib_BytesUtils.toUint8(bytes,uint256) (contracts/libraries/utils/Lib_BytesUtils.sol#173-192) is never used and should be removed
Lib_OVMCodec.encodeEVMAccount(Lib_OVMCodec.EVMAccount) …
```
=> Removes obsoleted and unused contract code

.github/workflows/integration.yml
The logs after failure are not being exported correctly as they are not
being written to the correct location. Previously `~` was not being
interpreted as `$HOME`. This assumes that the `cwd` is `$HOME`.
The CI doesn't export logs on failure, this PR fixes that.
Makes debugging easier
=> ci: fix workflow for exporting logs

.changeset/four-news-drive.md, packages/contracts/contracts/L1/messaging/OVM_L1CrossDomainMessenger.sol, packages/contracts/contracts/L2/messaging/OVM_L2CrossDomainMessenger.sol, packages/contracts/contracts/libraries/constants/Lib_DefaultValues.sol
Adds default values library for xdomain msg sender.
n/a
**Metadata**
- Fixes #803 
- Targets `experimental` based on https://github.com/ethereum-optimism/optimism/pull/1442#issuecomment-918520261
=> chore(contracts): defaults lib w/ xdomain msg sender

.changeset/happy-candles-burn.md, packages/data-transport-layer/src/services/l2-ingestion/service.ts
There is no need to query for the chain id over and over again
when syncing from L2 using the DTL. This also reduces the amount
of logs for the `docker-compose` setup and will save requests to
the sequencer in production.
=> dtl: use `ethers.StaticJsonRpcProvider` to reduce `eth_chainId` requests

.changeset/witty-feet-sniff.md, l2geth/core/vm/evm.go, l2geth/core/vm/ovm_state_dump.go, l2geth/rollup/sync_service.go
Add a new config option `ROLLUP_ENABLE_ARBITRARY_CONTRACT_DEPLOYMENT`.
This config option must be set with an env var, there is no flag to
set it with.
If it is not set, the functionality is unchanged. If it is set, then it
will override the function `isDeployerAllowed(address)` on the
`OVM_DeployerWhitelist`
=> l2geth: config enable arbitrary contract deployment

.github/labeler.yml
Pulling in the fix from `develop` so CI stops making the tags again.
=> fix: update labeler.yml

.changeset/khaki-pots-repeat.md, packages/contracts/contracts/L1/rollup/OVM_CanonicalTransactionChain.sol, packages/contracts/test/contracts/L1/rollup/OVM_CanonicalTransactionChain.gas.spec.ts, packages/contracts/test/contracts/L1/rollup/OVM_CanonicalTransactionChain.spec.ts
Determines a threshold amount `ENQUEUE_L2_GAS_PREPAID`. If a transaction is enqueued with a gas limit below this value, no gas is burned. 
In the case that gas is burned, the amount burned is reduced proportional to `ENQUEUE_L2_GAS_PREPAID`. 
The calculation of `ENQUEUE_L2_GAS_PREPAID` is calculated by multiplying the following values:
1. the baseline cost of calling `enqueue()` without the gas burn. ([per tenderly](https://dashboard.tenderly.co/tx/mainnet/0xdf2ca1773f9682df29748ad519cebba7aadde79cd7350741180f60816766ccd4/gas-usage)).
2. the `L2_GAS_DISCOUNT_DIVISOR`, which is an estimate of the ratio of the values of L2 gas to L1 gas ([Currently 32](https://github.com/ethereum-optimism/optimism/blob/8b477943f85443de62700b346d1c6ec0130a1e20/packages/c …
=> Only burn gas on deposits with a high L2 gas limit

.changeset/yellow-windows-scream.md, packages/core-utils/src/watcher.ts
The Watcher utility currently has a single `blocksToFetch` for both layers, which isn't ideal because L2 has much faster block times. This PR defines `l1BlocksToFetch` and `l2BlocksToFeth`
Note - I'm not sure why it added all the change set stuff. Feel free to remove if needed.
=> Watcher: l1 vs l2 blocksToFetch

specs/README.md
Tiny PR to add a notice to the `specs` folder that the content may be outdated and to look at the `optimistic-specs` repository for latest up-to-date content.
=> docs: point to new specs repository

.changeset/nice-flowers-lay.md, packages/contracts/contracts/L2/predeploys/WETH9.sol, packages/contracts/hardhat.config.ts, packages/contracts/src/predeploys.ts
Adds an instance of WETH9 at the old OVM_ETH address (0x42....06).
=> feat: add weth9 at old ovm eth address

.changeset/forty-cougars-teach.md, .changeset/four-chairs-press.md, .changeset/lazy-dingos-perform.md, integration-tests/test/rpc.spec.ts, l2geth/core/state_processor.go, l2geth/core/types/gen_receipt_json.go, l2geth/core/types/receipt.go, l2geth/internal/ethapi/api.go, l2geth/rollup/fees/rollup_fee.go, packages/core-utils/src/l2context.ts
Adds the L1 gas info to the transaction receipt. This makes it easy to know what sort of fee the transaction paid without needing to do historical calls to the `GasPriceOracle` predeploy
The response of the RPC endpoint `eth_getTransactionReceipt`
will now return 4 new fields.
- `l1GasPrice`
- `l1GasUsed`
- `l1Fee`
- `l1FeeScalar`
These fields are added to the database as part of the receipt
itself. This means that it is a consensus change as the
serialization of the receipt has been updated. This impacts
the blockhash because the block header commits to a merkle root
of all of the receipts in the block.
Each of the new fields on the receipt exist in the state but
would require an archive node to query for as the values can
change over time.
**Metadata**
- Fixes ENG-1322
=> feat: L1 gas info on receipt

.changeset/olive-coins-run.md, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/batch-submitter/test/batch-submitter/batch-submitter.spec.ts
The batch submitter is normally ran without running the call to
`appendQueueBatch`. The contracts have `appendQueueBatch` disabled
currently. This means that calling `appendQueueBatch` will result
in a revert. This PR removes the config option that is responsible
for turning of the call to `appendQueueBatch` so it is more likely
to "just work".
=> batch-submitter: remove call to `appendQueueBatch`

.changeset/dull-cheetahs-help.md, l2geth/rollup/sync_service.go
Previously the sequencer would call the `syncBatchesToTip` method
as part of its `sequence()` loop. This commit removes that as the
call to `syncBatchesToTip` does nothing for the sequencer currently.
Syncing the batches would be useful for triggering reorgs, but
that functionality does not currently exist. It would be better to
remove this functionality for now as it could potentially interfere
with the locking mechanism introduced in
dfaa8fc20f586265f0a5c07ca76c6c793ba49157.
This will also reduce the amount of time the `txLock` is held, meaning
that less transactions sent via RPC will be blocked and held in memory
while waiting to execute.
=> l2geth: no longer sync batches as sequencer

.changeset/tall-apples-refuse.md, packages/contracts/bin/deploy.ts, packages/contracts/contracts/L1/rollup/CanonicalTransactionChain.sol, packages/contracts/deploy/004-OVM_CanonicalTransactionChain.deploy.ts, packages/contracts/tasks/deploy.ts, packages/contracts/test/contracts/L1/messaging/L1CrossDomainMessenger.spec.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.gas.spec.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.spec.ts, packages/contracts/test/helpers/constants.ts
Allows us to modify the gas burn threshold (`ENQUEUE_L2_GAS_PREPAID`), by converting it to an `immutable` variable which can be set at create time. 
As before, it is calculated as the product of `L2_GAS_DISCOUNT_DIVISOR` and `ENQUEUE_GAS_COST`, so these variables are also now `immutable`s. 
Pretty sure this will pass the integration tests 👌
**Metadata**
- Fixes #ENG-1407
=> Make the gas burn amount configurable

.changeset/sharp-dancers-clap.md, packages/message-relayer/src/relay-tx.ts, packages/message-relayer/test/unit-tests/relay-tx.spec.ts
- added coverage for the `getMerkleTreeProof` function in `packages/message-relayer/relay-tx.ts`
Additional coverage increases total `message-relayer` package coverage from ~72% to 83%
**Metadata**
=> [added] coverage for getMerkleTreeProof

.changeset/rotten-bears-jump.md, packages/contracts/test/contracts/L1/messaging/deposit.gas.spec.ts
Add Gas Benchmarks for ETH and ERC20 deposits.
In order to get an accurate picture of costs, I've avoided using `smock` (except for using `smoddit` to set an ERC20 approval, which I don't _think_ would affect gas accounting).
=> test(contracts): Add full benchmarking of ETH and ERC20 deposits

.changeset/real-tips-own.md, packages/contracts/src/contract-deployment/config.ts
Removes the l1 only contracts from the deployment configuration since these are not actually deployed using this configuration. 
Doesn’t change too much. This is my first commit to this repo.
**Metadata**
- Fixes #1191
=> Remove L1 contracts from L2 state dump process

.changeset/little-donuts-wink.md, integration-tests/test/native-eth.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/shared/utils.ts, packages/contracts/hardhat.config.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.gas.spec.ts, packages/contracts/test/helpers/gas/gas.ts, packages/core-utils/src/common/index.ts, packages/core-utils/src/common/test-utils.ts, packages/core-utils/test/common/test-utils.spec.ts
Previously our gas specs have only printed the values they record,
without ensuring that the cost doesn't drift up over time. Adding expectApprox will allow these costs to decrease, but not increase.
I verbatim copy pasted the definition of `expectApprox` from the integration tests' shared utils.
I don't like this code duplication, but I also don't see a good reason to include it in the `@eth-optimism/contracts` package, so this seems like a good enough approach. But I'm open to alternative suggestions.
=> Assert upper bound on CTC gas costs

.changeset/sour-pandas-thank.md, packages/contracts/contracts/L1/verification/BondManager.sol, packages/contracts/contracts/L1/verification/IBondManager.sol
Removes some unused functions within the `BondManager`. I think it's better to get rid of the code and add it back in later if necessary than to have it just sitting there doing nothing.
=> refactor: remove unused bond manager functions 

.changeset/dirty-beans-fold.md, l2geth/core/state_transition_ovm.go
Fix `toExecutionManagerRun` in cases where `asOvmMessage` isn't applied.
Note that tracing currently does not work for optimistic ethereum.
=> l2geth: to execution manager run

.changeset/tender-bees-jump.md, packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol, packages/contracts/test/contracts/L1/messaging/L1CrossDomainMessenger.spec.ts, packages/message-relayer/src/service.ts
Removes the `onlyRelayer` modifier from the L1CrossDomainMessenger (which hasn't been used for a while now).
**Metadata**
- Fixes #623
=> feat: remove onlyRelayer modifier

.github/workflows/publish-canary.yml
Adds the ability to publish the builder as well as the
gas-oracle for the canary releases.
=> fix: canary publish

.github/workflows/publish-canary.yml
Fixes a typo in the canary build for gpo
=> ci: fix canary build for publishing gpo

.changeset/good-tigers-explain.md, packages/batch-submitter/test/batch-submitter/batch-submitter.spec.ts, packages/contracts/src/make-genesis.ts
Adds the git commit hash to the object returned by `make-genesis.ts`. Geth ignores this value but it's useful for keeping track of the exact code used to generate a given genesis.
=> feat: add git commit hash to genesis file 

.dockerignore, ops/docker/Dockerfile.deployer, ops/docker/Dockerfile.monorepo
This allows scripts that depend on the git hash
at build/runtime to access it.
=> ops: add .git folder to docker setup

.changeset/red-birds-kick.md, integration-tests/test/native-eth.spec.ts, integration-tests/test/rpc.spec.ts, packages/contracts/test/contracts/L1/messaging/deposit.gas.spec.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.gas.spec.ts, packages/core-utils/src/common/test-utils.ts, packages/core-utils/test/common/test-utils.spec.ts
I was finding that 1% was too much to allow a value to increase, but 0% was not enough. 
So I added some new parameters so that we can specify an absolute amount instead. 
1. The branching logic became fairly complex. I addressed this by trying to test every possible case. 
2. This depends on #1482, so I'll make this a draft until that is merged.
=> Improve expectApprox to allow setting bounds based on absolute values

ops/docker/Dockerfile.deployer
This was causing a build error in CI. We want to be able to run `git rev-parse HEAD` inside of the image.
=> ops: remove git dir from deployer docker image

.github/workflows/publish-canary.yml, .github/workflows/release.yml
The docs specify that `build-args` for the Github action
`docker/build-push-action@v2` should be a list, but
doing so results in an error:
`The workflow is not valid. .github/workflows/release.yml (Line: 362,
Col: 13): A sequence was not expected`
This updates the syntax to copy the example here:
https://github.com/docker/build-push-action/blob/3c507bedc4de3249e107413a7358ae1af558fd79/UPGRADE.md#L68
Uncertain if the env var parsing will work with this syntax
=> workflows: fix build-args syntax

.changeset/blue-games-remember.md, .github/workflows/release.yml, ops/scripts/ci-versions.js
The variables used in the canary release were used in the actual
release, causing it to not have the correct variables in place.
This caused the CI to skip the steps for publishing the `rpc-proxy`
and `proxyd`. This commit should fix the problem.
Add changesets for rpc-proxy and proxyd. Just a patch changeset to trigger
releases as a bug prevented releases previously.
=> fix: ci publish proxy

packages/regenesis-surgery/scripts/solc.ts
Import `setupMethods` from `solc/wrapper` to avoid indirectly `require`ing `soljson.js`, which throws this massive ridiculous error whenever an unhandled promise rejection is thrown because the file is minified and it's dumb.
=> fix: solc import to avoid annoying crashes

.eslintrc.js, packages/contracts/.prettierignore, packages/contracts/package.json
After running `yarn test:coverage` locally, `yarn lint` and `git commit` will fail due to errors raised by eslint.
This PR ensures that test coverage output is ignored during linting and formatting, and is removed by the `yarn clean` script.
=> fix(contracts): Add coverage to yarn clean and ignore when linting or formatting

package.json, packages/contracts/package.json, yarn.lock
Removes `prettier-plugin-solidity` and `solhint-plugin-prettier` deps from the root dir.
These deps were introduced on the `regenesis/0.5.0` branch, thus are being removed there rather than `develop`.
=> Remove unnecessary packages from the root dir

packages/regenesis-surgery/scripts/constants.ts
Add Rubicon contracts that require WETH
bathUSDC https://optimistic.etherscan.io/address/0xe0e112e8f33d3f437d1f895cbb1a456836125952
bathDAI https://optimistic.etherscan.io/address/0x60daec2fc9d2e0de0577a5c708bcadba1458a833
bathUSDT https://optimistic.etherscan.io/address/0xffbd695bf246c514110f5dae3fa88b8c2f42c411
**Metadata**
- Fixes ENG-1634
=> feat: add extra rubicon weth transfer addresses

.changeset/sixty-countries-know.md, .github/workflows/publish-canary.yml, go/proxyd/Dockerfile, go/proxyd/Makefile
- Update canary to build proxyd and rpc-proxy
- fixed "runs-on" value
- fixing env step
- Update docker build context
- Alpine 3.14 doesn't play nice with make
- populate version information with Docker
```
$ docker run --rm  ethereumoptimism/proxyd:0.0.0-2021104132020
INFO [11-04|13:29:38.383] starting proxyd                          version=1.0.2 commit=53bf93ef2d041c65ac5f5db9022fe411fcb80066 date=04-11-2021
CRIT [11-04|13:29:38.383] error reading config file                err="open /etc/proxyd/proxyd.toml: no such file or directory"
```
=> Update proxyd github actions

.changeset/five-penguins-protect.md, packages/batch-submitter/src/exec/run-batch-submitter.ts, packages/core-utils/package.json, packages/core-utils/src/provider.ts, packages/data-transport-layer/src/services/l1-ingestion/service.ts, packages/data-transport-layer/src/services/l2-ingestion/service.ts, packages/message-relayer/src/exec/run.ts, packages/replica-healthcheck/src/healthcheck-server.ts
Adds the http header 'User-Agent' to the creation
of ethers providers across the services to allow
for more visibility into what services are sending
requests.
Also delete dead imports since they were breaking
during linting.
=> pkgs: add http headers to ethers providers

integration-tests/contracts/ERC20.sol, integration-tests/hardhat.config.ts, integration-tests/package.json, integration-tests/sync-tests/1-sync-verifier.spec.ts, integration-tests/sync-tests/2-sync-replica.spec.ts, integration-tests/test/basic-l1-l2-communication.spec.ts, integration-tests/test/contracts.spec.ts, integration-tests/test/shared/utils.ts, yarn.lock
This PR adds integration tests for basic smart contract interactions and swaps on Uniswap. Tested against both my local Hardhat node and the Kovan staging environment.
Note that in order to deploy the Uniswap contracts I had to change the Solidity compiler version in the integration tests to `^0.7.6`.
=> integration-tests: Add contract tests

packages/regenesis-surgery/scripts/data.ts, packages/regenesis-surgery/scripts/solc.ts
Fixes some small bugs that were recently introduced.
1. `eth_chainId` seems to return a `response` object without a `result`.
2. Turn the chain ID mismatch between genesis file and L2 network into a warning.
3. Correctly import setupMethods
=> fix: various minor issues with surgery script

ops/Makefile, ops/README.md
This will ensure the `builder` is built first so that other
services that depend on the `builder` do not pull a remote
`builder` image.
=> ops: add `make build` command

.changeset/five-baboons-serve.md, go/proxyd/README.md, go/proxyd/backend.go, go/proxyd/config.go, go/proxyd/example.config.toml, go/proxyd/metrics.go, go/proxyd/proxyd.go, go/proxyd/server.go
We can now specify an auth string in WS/RPC paths. Metrics have been updated to record the authenticated user.
Fixes ENG-1596
=> go/proxyd: ENG-1596 support authenticated client requests

.changeset/chilled-pugs-rule.md, l2geth/rollup/sync_service.go
Repair the latest known queue index on startup to prevent
skipped deposits
=> l2geth: set latest queue index and index after tx applied

.changeset/many-hounds-smile.md, packages/contracts/deploy/011-set-addresses.ts, packages/contracts/deploy/014-OVM_L1StandardBridge.deploy.ts
This PR does two things: 
1. ccff1275a7204ea807b6879e117a4ec3a16f9626: Ensures that the address and chugsplash dictator instructions are always printed during deployment. This makes testing feel more realistic, even if the step is being skipped.
2. 3aa51fc656133d565f3999596ef1c383bdee1804: Uses the `chainId` to detect when the deployments are being run in CI. During a fresh system deployment the owner of the AddressManager is the deployer (just like in CI), so the previous method would have resulted in skipping the `waitUntilTrue` loop allowing for verification.
metadata:
fixes: eng-1613
=> Deployment script CI and testing fixes

.changeset/perfect-swans-rest.md, ops/docker/Dockerfile.deployer, ops/docker/Dockerfile.integration-tests, ops/scripts/deployer.sh
The dockerfile was failing on the step due to `python` no longer
existing in the alpinelinux archives. This commit updates the
version of `python` to `python3` so that the deployer image
can build properly.
```
> [ethereumoptimism/deployer:latest stage-1  2/13] RUN apk add --no-cache git curl python bash jq:
124 2.190 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
124 2.170 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
124 2.803 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
124 2.783 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
124 6.396 ERROR: unable to select packages:
124 6.416 ERROR: unable to select packages:
124 6.431   python (no …
```
=> ops: use alpine python3 in deployer

.changeset/three-gifts-fail.md, go/proxyd/.gitignore, go/proxyd/backend.go, go/proxyd/config.go, go/proxyd/example.config.toml, go/proxyd/proxyd.go, go/proxyd/server.go
This PR brings back the ability to selectively route RPCs to different backends.
=> go/proxyd: Bring back method mappings

.changeset/clean-buttons-think.md, packages/contracts/deploy/002-OVM_ChainStorageContainer_ctc_batches.deploy.ts, packages/contracts/deploy/003-OVM_ChainStorageContainer_scc_batches.deploy.ts, packages/contracts/deploy/004-OVM_CanonicalTransactionChain.deploy.ts, packages/contracts/deploy/005-OVM_StateCommitmentChain.deploy.ts, packages/contracts/deploy/006-OVM_BondManager.deploy.ts, packages/contracts/deploy/007-OVM_L1CrossDomainMessenger.deploy.ts, packages/contracts/deploy/008-Proxy__OVM_L1CrossDomainMessenger.deploy.ts, packages/contracts/deploy/009-Proxy__OVM_L1StandardBridge.deploy.ts, packages/contracts/deploy/010-AddressDictator.deploy.ts, packages/contracts/deploy/011-set-addresses.ts, packages/contracts/deploy/013-ChugSplashDictator.deploy.ts, packages/contracts/deploy/014-OVM_L1StandardBridge.deploy.ts, packages/contracts/deploy/016-fund-accounts.ts, packages/contracts/src/hardhat-deploy-ethers.ts
Adds a `try/catch` wrapped attempt to verify each contract on etherscan immediately after deployment.
**Testing instructions**
1. Download and apply the patch file attached: 
[0001-TEMP-commit-for-testing-eng-1632.patch.txt](https://github.com/ethereum-optimism/optimism/files/7505734/0001-TEMP-commit-for-testing-eng-1632.patch.txt)
2. Set and source the appropriate values in your `.env `file.
3. Open `./scripts/deploy-scripts/kovan.sh` and modify according to the instructions therein.
4. Run that script.
**Expected results**
I think that on Kovan, all verification attempts will just give an "error", since identical source code has already been verified on Kovan, but that's OK. 
```
Error when verifying bytecode on etherscan:
NomicLabsHardhatPluginError: The Etherscan API …
```
=> Run etherscan validation during the deployment process

.changeset/stupid-dogs-turn.md, packages/contracts/deploy/000-hardhat-setup.ts, packages/contracts/deploy/001-Lib_AddressManager.deploy.ts, packages/contracts/deploy/002-OVM_ChainStorageContainer_ctc_batches.deploy.ts, packages/contracts/deploy/003-OVM_ChainStorageContainer_scc_batches.deploy.ts, packages/contracts/deploy/004-OVM_CanonicalTransactionChain.deploy.ts, packages/contracts/deploy/005-OVM_StateCommitmentChain.deploy.ts, packages/contracts/deploy/006-OVM_BondManager.deploy.ts, packages/contracts/deploy/007-OVM_L1CrossDomainMessenger.deploy.ts, packages/contracts/deploy/008-Proxy__OVM_L1CrossDomainMessenger.deploy.ts, packages/contracts/deploy/009-Proxy__OVM_L1StandardBridge.deploy.ts, packages/contracts/deploy/010-AddressDictator.deploy.ts, packages/contracts/deploy/011-set-addresses.ts, packages/contracts/deploy/012-initialize-Proxy__L1CrossDomainMessenger.ts, packages/contracts/deploy/013-ChugSplashDictator.deploy.ts, packages/contracts/deploy/014-OVM_L1StandardBridge.deploy.ts, packages/contracts/deploy/016-fund-accounts.ts, packages/contracts/src/address-names.ts, packages/contracts/src/hardhat-deploy-ethers.ts, packages/contracts/src/index.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.spec.ts
The strings used to resolve system contracts in the Address Manager must be correct, but they are declared independently in many places. 
This PR defines an exported object to act as a dictionary of correct names.
=> Remove redundant declaration of address names

packages/regenesis-surgery/test/eoa.spec.ts
Enables + fixes the tests for the 1inch deployer in the regenesis surgery tests
=> regenesis-surgery: enable 1inch deployer tests

integration-tests/README.md, integration-tests/test/basic-l1-l2-communication.spec.ts, integration-tests/test/contracts.spec.ts, integration-tests/test/native-eth-ovm-calls.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/shared/env.ts, integration-tests/test/shared/stress-test-helpers.ts, integration-tests/test/shared/utils.ts, integration-tests/test/stress-tests.spec.ts
This PR gets integration tests into shape to work against mainnet. Specific changes include:
- Stress tests do not run against mainnet since they are very costly.
- You can now provide env vars that define addresses for the Uniswap position manager and router. This avoids the need to deploy them ourselves on mainnet.
- Withdrawal tests are disabled because the withdrawal window on mainnet is 1 week.
- Mainnet L2 gas prices are pulled from the sequencer rather than using a hardcoded value.
- The L2 wallet is funded with 1ETH rather than 20. Subsequent tests runs will "top up" the L2 wallet up to 1 ETH.
=> Itests mainnet prep

integration-tests/test/bridged-tokens.ts, integration-tests/test/native-eth.spec.ts
Skips all tests that use L2->L1 comms on mainnet since they are all subject to the withdrawal period.﻿
=> integration-tests: skip all tests on mainnet subject to wd period

integration-tests/test/rpc.spec.ts
Enable the RPC test for `rollup_gasPrices` that
was previously disabled due to how the gas pricing
scheme was changed in `v0.5.0`.
=> integration-tests: enable rollup_gasPrices test

.github/workflows/integration.yml, integration-tests/README.md, integration-tests/test/basic-l1-l2-communication.spec.ts, integration-tests/test/contracts.spec.ts, integration-tests/test/fee-payment.spec.ts, integration-tests/test/native-eth-ovm-calls.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/shared/env.ts, integration-tests/test/shared/stress-test-helpers.ts, integration-tests/test/shared/utils.ts, integration-tests/test/stress-tests.spec.ts, ops/Makefile, ops/docker-compose.yml, ops/docker/Dockerfile.integration-tests, ops/docker/Dockerfile.packages
This PR updates the integration tests to build JS services using a single Dockerfile rather than multiple Dockerfiles that inherit from a builder image. This fixes the issues we've been seeing where the builder image on Docker Hub gets pulled instead of the locally-build one. The individual service to build is selected via the `target` attribute in `docker-compose.yml`.
=> integration-tests: Build using single Dockerfile

.changeset/bright-bulldogs-sleep.md, packages/message-relayer/src/relay-tx.ts
Pre-regenesis withdrawals are persisted in the state, but proof data needs to be pulled from post-regenesis state.  Thus, the existing `getMessagesAndProofsForL2Transaction` in the message relayer package won't cut it.  This PR adds a `getLegacyProofsForL2Transaction` function which will grab the proofdata from the post-regenesis chain's first block.
Assumes we have cached the L2 transactions and their corresponding messages.
=> feat(message-relayer): add legacy relay function

.changeset/great-donkeys-buy.md, go/proxyd/backend.go, go/proxyd/config.go, go/proxyd/example.config.toml, go/proxyd/proxyd.go, go/proxyd/server.go
This PR makes the following changes:
**Makes the RPC/WS endpoints match Geth**
Rather than use custom paths for RPC/WS endpoints, Geth has the RPC and WS servers listen on different ports. This PR makes proxyd match that behavior. To configure Proxyd in this mode, use the following configuration:
```toml
[server]
rpc_host = "0.0.0.0"
rpc_port = 8080
ws_host = "0.0.0.0"
ws_port = 8085
max_body_size_bytes = 10485760
```
**Better logging**
This PR adds logging to all incoming requests, attempted WS connections, and exchanged WS messages. Additionally, it adds a randomly-generated `req_id` field to log output that will allow us to trace requests as they go from the web server, to the proxied backend, and back.
Example WS logs:
```
INFO [11-09|15:31:09.261] received WS connection …
```
=> go/proxyd: Make endpoints match Geth, better logging

packages/contracts/hardhat.config.ts
Minor fix to use a valid default private key in our `contracts` hardhat config. Stuff doesn't work properly without this fix.
=> fix: use valid default pk in hh config

packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol, packages/contracts/contracts/L1/messaging/L1StandardBridge.sol, packages/contracts/contracts/L1/rollup/CanonicalTransactionChain.sol, packages/contracts/contracts/L1/rollup/ChainStorageContainer.sol, packages/contracts/contracts/L1/rollup/StateCommitmentChain.sol, packages/contracts/contracts/L1/verification/BondManager.sol, packages/contracts/contracts/libraries/bridge/CrossDomainEnabled.sol
Remove runtime target from doc strings and identify contracts with missing descriptions
Contracts in the contracts package with missing descriptions are:
packages/contracts/L2/predeploys/WETH9.sol
packages/contracts/libraries/resolver/Lib_AddressManager.sol
packages/contracts/libraries/resolver/Lib_AddressResolver.
packages/contracts/libraries/resolver/Lib_ResolvedDelegateProxy.sol
packages/contracts/standards/L2StandardERC20.sol
packages/contracts/test-helpers/Helper_GasMeasurer.sol
packages/contracts/test-helpers/Helper_SimpleProxy.sol
packages/contracts/test-helpers/TestERC20.sol
packages/contracts/test-libraries/codec/TestLib_OVMCodec.sol
packages/contracts/contracts/test-libraries/rlp/TestLib_RLPReader.sol …
=> docs: Remove runtime target from docstrings

.changeset/lovely-pumas-sing.md, packages/contracts/deploy/000-hardhat-setup.ts, packages/contracts/deploy/002-OVM_ChainStorageContainer_ctc_batches.deploy.ts, packages/contracts/deploy/003-OVM_ChainStorageContainer_scc_batches.deploy.ts, packages/contracts/deploy/004-OVM_CanonicalTransactionChain.deploy.ts, packages/contracts/deploy/005-OVM_StateCommitmentChain.deploy.ts, packages/contracts/deploy/006-OVM_BondManager.deploy.ts, packages/contracts/deploy/007-OVM_L1CrossDomainMessenger.deploy.ts, packages/contracts/deploy/008-Proxy__OVM_L1CrossDomainMessenger.deploy.ts, packages/contracts/deploy/009-Proxy__OVM_L1StandardBridge.deploy.ts, packages/contracts/deploy/010-AddressDictator.deploy.ts, packages/contracts/deploy/011-set-addresses.ts, packages/contracts/deploy/012-initialize-Proxy__L1CrossDomainMessenger.ts, packages/contracts/deploy/013-ChugSplashDictator.deploy.ts, packages/contracts/deploy/014-OVM_L1StandardBridge.deploy.ts, packages/contracts/deploy/015-finalize.ts, packages/contracts/deploy/016-fund-accounts.ts, packages/contracts/src/deploy-utils.ts
Fixes the issue that we experienced yesterday where static calls would fail because we provide a gas price. Now, if the function is constant (static), we provide an explicit gas price of 0.
I also renamed `hardhat-deploy-ethers.ts` (a terrible file name) to `deploy-utils.ts`.
=> fix: no gas price for static fns in deploy

.changeset/sharp-ants-act.md, packages/contracts/deploy/007-OVM_L1CrossDomainMessenger.deploy.ts, packages/contracts/deploy/012-initialize-Proxy__L1CrossDomainMessenger.ts
Adds steps to the deployment to transfer away messenger ownership *during* the deployment so we don't have to do it manually afterwards.
=> feat: transfer messenger ownership during deploy

.changeset/spicy-spoons-jog.md, l2geth/core/events.go, l2geth/core/tx_pool.go, l2geth/miner/worker.go, l2geth/rollup/sync_service.go
- Fixes a bug that causes Geth to deadlock if transactions pass the policy checks but fail in the miner.
- Fixes a bug that causes Geth to mine empty blocks, and returns a proper error to users.
Replaces https://github.com/ethereum-optimism/optimism/pull/1783
=> l2geth: fix deadlock on invalid txs

.changeset/slow-dodos-argue.md, packages/batch-submitter/src/utils/tx-submission.ts, packages/batch-submitter/test/utils/tx-submission.spec.ts
YNATM was retrying transactions with bad nonces for up to an hour on Kovan. This PR causes YNATM to immediately reject when bad nonce errors are encountered.
=> batch-submitter: ENG-1688 fix bug causing Kovan to fall behind

.github/workflows/release.yml
Fix CI publishing of the builder image
=> ci: publish builder latest only

.changeset/proud-bears-do.md
Trigger a release of the batch submitter with the yatm fix.
The batch submitter would get stuck in a loop on kovan,
attempting to submit a transaction with a bad nonce over
and over again. The fix was to add a hook function
that can notice when there is a nonce error.
=> batch-submitter: trigger release

.github/workflows/batch-submitter.yml, .github/workflows/gas-oracle.yml, .github/workflows/geth.yml, .github/workflows/golangci-lint.yml
Removes branch restrictions for all testing/linting workflows that still had them so that we're running these when working on  *any* base branch.
**Metadata**
- Fixes ENG-1541
=> fix: remove branch restrictions for some workflows

.changeset/swift-ways-glow.md, go/proxyd/backend.go, go/proxyd/config.go, go/proxyd/metrics.go, go/proxyd/proxyd.go, go/proxyd/rate_limiter.go, go/proxyd/rpc.go, go/proxyd/server.go
This PR improves `proxyd` metrics, and removes the requirement to use Redis with the rate limiter.
**New metrics** 
`rpc_backend_http_response_codes_total{"auth", "backend_name", "method_name", "status_code"}` - This counter tracks HTTP error codes returned from each proxy backend. It's maintained as a separate metric from `rpc_errors_total` since `rpc_errors_total` keeps track of errors found _in the JSON-RPC response body_.
`http_response_codes_total` - This counter tracks HTTP response codes returned to the client. Usually, this will be 200 except in a couple of exceptional cases:
- 503 when there are no backends available.
- 400 when the request payload is inavlid.
- 401 when a bad auth token is provided.
- 404 when a path can't be found.
Other errors will return either a 500, or a …
=> ENG-1670 - improve proxyd metrics, support local rate limiter

.changeset/flat-bags-chew.md, go/gas-oracle/oracle/updater_interface.go
The `gas-price` metric was renamed to `gas_price`
as using a `-` is invalid syntax in a prometheus metric.
Fixes https://github.com/ethereum-optimism/optimism/issues/1819
=> gas-oracle: fix the gas price metric

go/batch-submitter/Makefile, go/batch-submitter/bindings/ctc/canonical_transaction_chain.go, go/batch-submitter/bindings/scc/state_commitment_chain.go, go/batch-submitter/go.sum
This PR adds the CTC and SCC contract bindings required by the batch submitter. The Makefile has been updated to include a new `make bindings` target that generates both, as well as `make bindings-ctc` and `bindings-scc` to compile each individually.
**Metadata**
- Fixes ENG-1482
=> feat: add CTC and SCC contract bindings

.changeset/friendly-queens-rule.md, go/proxyd/Dockerfile, go/proxyd/README.md, go/proxyd/backend.go, go/proxyd/config.go, go/proxyd/entrypoint.sh, go/proxyd/example.config.toml, go/proxyd/proxyd.go, go/proxyd/tls.go
=> go/proxyd: Add support for additional SSL certs

ops/docker-compose-metrics.yml, ops/docker-compose-nobuild.yml, ops/docker-compose-rpc-proxy.yml, ops/docker-compose.yml
The `docker-compose` setup uses features that
are not available in all versions. This pins
the `docker-compose` setup to version `3.4`
instead of just `3`.
It is known to work under the following versions:
```
$ uname -or
5.10.70-1-MANJARO GNU/Linux
$ docker-compose --version
Docker Compose version 2.0.1
$ docker --version
Docker version 20.10.9, build c2ea9bc90b
```
Closes https://github.com/ethereum-optimism/optimism/issues/1815
Note that when building on my machine with version `3.7`, there is not problem
or warnings thrown, so I cannot repro the problem locally
=> ops: pin docker-compose version to 3.4

.changeset/nice-steaks-hammer.md, .changeset/old-moons-invite.md, .github/workflows/integration.yml, integration-tests/package.json, integration-tests/test/replica.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/shared/env.ts, integration-tests/test/shared/utils.ts, l2geth/internal/ethapi/api.go, l2geth/rollup/client.go, ops/docker-compose.yml, packages/data-transport-layer/src/utils/eth-tx.ts
The old transaction batch serialization assumed that the
correct chain id was used as there was a custom transaction
serialization used. Now that the full RLP of the transactions
are submitted to L1 for availability, it is possible to enable
non EIP155 transactions. This allows for universal addresses
to be used, where the same address exists across many chains.
A test is updated to test specifically that transactions that
are not protected with a chain id can be submitted and accepted
by the sequencer.
Fixes  ENG-1680
=> l2geth: allow for unprotected txs

.changeset/itchy-worms-cheat.md, go/gas-oracle/oracle/updater_interface.go
Fixed gas-oacle tx/not_significant metric name
**Metadata**
- Fixes https://github.com/ethereum-optimism/optimism/issues/1827
=> Fixed gas-oacle tx/not_significant metric name

.changeset/plenty-gifts-tell.md, .github/workflows/release.yml
Fix proxyd release workflow
**Metadata**
- Fixes https://github.com/ethereum-optimism/optimism/issues/1825
=> Fix proxyd release workflow

ops/docker-compose.yml
Don't bring up the message relayer in the docker-compose setup.
This is a breaking change and will need to be communicated.
Ideally there is time to communicate this but `regenesis/0.5.0` is breaking compared to `develop`, we might as well get this in now. Should save on some CI time
=> ops: turn off message relayer

ops/docker/Dockerfile.packages
message-relayer container works badly as building docker-compose on local machine.
`WORKDIR` of relayer section should be changed in `Dockerfile.packages`
And it looks well using `CMD` instead of `ENTRYPOINT` for relayer
=> fix: change relayer workdir and use CMD instead of ENTRYPOINT for docker-compose

.changeset/soft-countries-heal.md, ops/README.md
The message relayer is turned off by default,
mention how to turn it on in the docs.
Also trigger a new release so it builds with the updated dockerfile introduced in https://github.com/ethereum-optimism/optimism/pull/1826
=> fix: relayer docs + release

.changeset/dull-nails-sin.md, go/gas-oracle/gasprices/gas_price_updater.go, go/gas-oracle/gasprices/gas_price_updater_test.go, go/gas-oracle/gasprices/l2_gas_pricer.go, go/gas-oracle/oracle/config.go, go/gas-oracle/oracle/gas_price_oracle.go, go/gas-oracle/oracle/updater_interface.go
Compute the gas used in an epoch based on the
actual amount of gas used instead of assuming
that the full block's worth of gas was used in
each block.
Convert the average block gas limit to a `uint64` in the
codebase instead of it being used as a `float64`.
Minimal changes were done in a way where the existing tests
could ensure there is no regression. The `gas-oracle` is not
part of the `integration-tests` so thorough review and observing
its behavior on kovan is necessary before rolling this out to mainnet.
https://github.com/ethereum-optimism/optimism/pull/1736 is a prerequisite
for getting the `gas-oracle` into the itests
**Metadata**
- Fixes ENG-1681
=> feat: more accurate gas-oracle gas metering

.github/workflows/release.yml
Updates the github action to properly reference
the `proxyd` dockerfile. The logic is copied from
the canary publish github action.
=> ci: fix proxyd publish

.changeset/new-nails-arrive.md, l2geth/miner/worker.go, l2geth/miner/worker_test.go
This PR makes some minor improvements to the sequencers empty block detection, specifically:
- fixes the empty block detection within `commitTransactions` to only count transactions if they are successfully executed
- handles an edge case in `commitTransactions` where an empty block can be produced when the execution is interrupted
- moves the low-level empty block check up in `commit`, to avoid sending empty blocks on `w.taskCh`
Note, the empty block production in this case was never accepted by the chain, but this improves our detection of these cases locally instead of relying on the catch-all check in `commit`.
**Metadata**
- Fixes ENG-1703
=> fix: minor improvements to empty sequencer block handling

.changeset/wicked-mugs-admire.md, ops/docker/Dockerfile.batch-submitter, ops/docker/Dockerfile.data-transport-layer, ops/docker/Dockerfile.deployer, ops/docker/Dockerfile.integration-tests, ops/docker/Dockerfile.message-relayer, ops/docker/Dockerfile.monorepo, ops/docker/Dockerfile.packages, ops/docker/Dockerfile.regenesis-surgery, ops/docker/Dockerfile.replica-healthcheck
node.js version 16 is currently the lts version
so this commit updates each of the dockerfiles to
use node version 16
=> docker: update node version to 16

package.json
Tracking the builder image causes problems
in the CI. It started to be tracked when
there was a desire for faster builds. Publishing
a versioned builder image has resulted in
many CI publishing related bugs. This commit
removes tracking of the builder image.
=> changesets: don't track builder image

.changeset/flat-mirrors-sort.md, ops/docker/hardhat/Dockerfile
A bug caused the previous releases to not build in CI, so re triggering. The root cause of the bug was fixed so this should not happen again.
=> fix: trigger node 16 releases

.changeset/silly-bugs-sit.md, go/gas-oracle/gasprices/gas_price_updater.go, go/gas-oracle/gasprices/gas_price_updater_test.go, go/gas-oracle/gasprices/l2_gas_pricer.go
Also corrects the targetGps constant in the test harness. The constant
was chosen to be the expected Gps of the initial burst, causing the Gps
to stablize in the second part of the test at the floor.
Adding a check that the average measured gas price matches our desired
constant prevents this from silently passing.
Logging the incremental gas prices in the `TestUsageOfGasPriceUpdater` yields the following
on `develop`: 
```
burst
prevGasPrice: 1000, curPrice: 1001
prevGasPrice: 1001, curPrice: 1002
prevGasPrice: 1002, curPrice: 1003
prevGasPrice: 1003, curPrice: 1004
stablize
prevGasPrice: 1004, curPrice: 302
prevGasPrice: 302, curPrice: 91
prevGasPrice: 91, curPrice: 28
prevGasPrice: 28, curPrice: 9
prevGasPrice: 9, curPrice: 3
prevGasPrice: 3, curPrice: 1
prevGasPrice: …
```
=> fix: don't round down average gas per epoch

.github/workflows/publish-canary.yml, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/ts-packages.yml
The Github actions often run node.js. This commit
standardizes the usage of node.js to version 16,
the current LTS.
=> ci: standardize ci node version to 16

packages/contracts/tasks/whitelist.ts
Modifies the whitelist script to add support for whitelisting multiple addresses. Also adds support for adding or removing addresses from the whitelist instead of just adding.
**Metadata**
- Fixes ENG-1647
=> feat: update whitelist task for multiple addresses

.changeset/eight-poems-add.md, go/gas-oracle/flags/flags.go
The average block gas limit was converted to a uint64
from a float64, this commit updates the flag parsing
to parse the correct type.
=> gas-oracle: fix average block gas limit flag

.changeset/new-squids-hunt.md, go/proxyd/config.go, go/proxyd/example.config.toml, go/proxyd/proxyd.go, go/proxyd/tls.go
Certain config parameters can now be read from the environment if environment variables as provided as config values. The following parameters can be read from the environment:
- `backends.*.rpc_url`
- `backends.*.ws_url`
- `backends.*.password`
- `authentication.*`
Example backend config:
```toml
[backends]
[backends.from_env]
rpc_url = "$SECRET_RPC_URL"
ws_url = "$SECRET_WS_URL"
```
Example authentication config. Note the additional double quotes around the secret key:
```toml
[authentication]
"$SECRET_AUTH_KEY" = "auth_key_alias"
```
Env vars can be escaped with two backslashes (`\\`). We have to use two backslashes because it's also the escape character in TOML.
Env vars defined in the config but not defined in the actual environment will result in an error that prevents `proxyd` from …
=> go/proxyd: Add support for env vars in the config

.changeset/five-pandas-reflect.md, ops/docker/Dockerfile.deployer
Adds a changeset on top of https://github.com/ethereum-optimism/optimism/pull/1843
--------------------------
When `yarn run autogen:markdown` is running on `deployer`, `deployments` directory should be needed.
`deployer` container shows a error and be exited without `deployments` directory.
**errors**
```
$ docker-compose -f docker-compose-nobuild.yml up
...
deployer_1         | $ ts-node scripts/generate-markdown.ts
deployer_1         | Error: Cannot find module '../deployments/goerli/BondManager.json'
deployer_1         | Require stack:
deployer_1         | - /opt/optimism/packages/contracts/src/contract-deployed-artifacts.ts
deployer_1         | - /opt/optimism/packages/contracts/src/connect-contracts.ts
deployer_1         | - …
```
=> fix: deployer dockerfile

packages/sdk/src/index.ts, packages/sdk/src/interfaces/cross-chain-messenger.ts, packages/sdk/src/interfaces/cross-chain-provider.ts, packages/sdk/src/interfaces/index.ts, packages/sdk/src/interfaces/l2-provider.ts, packages/sdk/src/interfaces/types.ts
This PR translates the [API specification](https://optimismpbc.notion.site/Optimism-JS-SDK-3373779bf65e42cfae98858aad6b4946) from the SDK project charter into complete TypeScript types. I've added extra comments and made some minor modifications where I felt necessary, but this is mostly a copy/paste of the specified API.
**Metadata**
- Fixes ENG-1745
=> feat: translate SDK API spec to TS types

.changeset/famous-sheep-bathe.md, packages/contracts/src/validation-utils.ts, packages/contracts/tasks/validate-address-dictator.ts, packages/contracts/tasks/validate-chugsplash-dictator.ts
This PR contains the most complete version of the deployment validation scripts which were run during the 0.5.0 regenesis.
Since the regenesis I've made quite a few small adjustments to improve the UX, but all the checks present here were also done prior to finalizing the upgrades.
=> Add checks for proper config values in deployment validation

packages/sdk/src/interfaces/cross-chain-erc20-pair.ts, packages/sdk/src/interfaces/cross-chain-messenger.ts, packages/sdk/src/interfaces/index.ts, packages/sdk/test/cross-chain-messenger.spec.ts
Adds the test scaffold for the `CrossChainMessenger` class and breaks out the proposed `CrossChainERC20Pair` API.
**Metadata**
- Fixes ENG-1753
=> feat: add CrossChainMessenger test scaffold and CrossChainERC20Pair API

.changeset/angry-ducks-arrive.md, l2geth/miner/worker.go, l2geth/miner/worker_test.go
After surfacing the errors as part of the deadlock fix, the itests now exhibit a flake caused by these unexpected errors being returned. Internally, the harness detects and reattempts expected errors (currently rejected at the txpool level), however, the specific lower-level execution errors are still not surfaced. To fix the itests, we need to bubble up the specific execution errors (rather than the generic "Cannot commit transaction in miner") to the rpc caller, which will allow the test harness to proceed as usual.
Builds on:
**Metadata**
- Fixes ENG-1705
- Fixes ENG-1531
- Fixes #1891
=> feat: surface low-level sequencer execution errors, fix itest flakes

.editorconfig
Github will also pick this up and use this formatting on web.
Old: https://github.com/ethereum-optimism/optimism/blob/c62c48651dbcad6a0e4b21bdd87113d60a57b190/l2geth/miner/worker.go
New: https://github.com/cfromknecht/optimism/blob/b10a1e85387d2b7e1e26e8b25e2b04a6b17c2af9/l2geth/miner/worker.go
=> editorconfig: display Go code with 4 space tabs

.changeset/clever-ducks-rescue.md, go/proxyd/backend.go, go/proxyd/config.go, go/proxyd/metrics.go, go/proxyd/server.go
- Updates the HTTP response code metric to includes 200s
- Removes the total HTTP requests metric since it's redundant
- Fixes `MaxRetries` to read from the correct config variable
- Reduces max retry backoff to 3 seconds
=> go/proxyd: Various fixes

.changeset/olive-pots-camp.md, l2geth/miner/worker.go
This commit exposes the ErrNonceTooHigh at the execution level to
external users. Previously the error was mapped to ErrNonceTooLow to
match the mempool behavior. As this is a new error, and one not
currently exposed in L1, this could be a breaking change for some
applications depending on how the error messages are parsed.
This PR should be merged in conjunction with #1882, so that the errors
are returned at the mempool and miner level simultaneously.
**Metadata**
- Fixes ENG-1775
=> feat: surface miner nonce too high errors

.circleci/config.yml
Uses CircleCI to push our main services to the Stackman Docker registry on a nightly basis.
Metadata:
- Fixes ENG-1660
=> Add nightly builds via CircleCI

go/batch-submitter/batch_submitter.go, go/batch-submitter/drivers/proposer/driver.go, go/batch-submitter/drivers/sequencer/driver.go, go/batch-submitter/metrics/metrics.go, go/batch-submitter/service.go
Adds prometheus metrics to the Go batch-submitter. [All of the existing metrics](https://github.com/ethereum-optimism/optimism/blob/develop/packages/batch-submitter/src/batch-submitter/batch-submitter.ts#L256L302) are included here with the exception of `malformed_batches`, which is no longer used after the monotonicity checks were disabled. `submission_timestamp` is also removed since we currently don't use it in any of our dashboards.
Additionally, a new `batch_submitter_confirmation_time` gauge is added to be able to directly measure the confirmation latency experienced by the batch submitter.
**Metadata**
- Fixes ENG-1671
=> feat: add telemetry to go batch-submitter

ops/docker/Dockerfile.packages
`Dockerfile.packages` placed build artifacts in `/optimism`, whereas all of our other Dockerfiles place build artifactrs in `/opt/optimism`. As a result, downstream consumers of the packages Dockerfile cannot use images created by our other Dockerfiles. This is a problem for the nightly environment, since it relies upon the `/opt/optimism` structure to customize container entrypoints.
This PR fixes the problem by having `Dockerfile.packages` put build artifacts in `/opt/optimism` like everything else.
=> ops/docker: Use old directory in packages dockerfile

.changeset/purple-squids-taste.md, go/batch-submitter/batch_submitter.go
The metrics server wasn't running because of a space between the host and port.
=> go/batch-submitter: Fix metrics server

.circleci/config.yml
Deploys the nightly image after the build. We can use a `kubectl rollout restart` here because the nightly uses images of the form `image-name:nightly` and have `imagePullPolicy` set to `Always`. This forces Kubernetes to always re-pull images upon pod restart.
Metadata:
- Fixes ENG-1661
=> Add nightly deploys

.changeset/cyan-owls-grow.md, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
Changes the `numTxPerBatch` metric to observe the actual number of elements inside `batchParams` rather than `endBlock - startBlock`.
Metadata:
- Fixes ENG-1807
=> batch-submitter: Fix the numTxPerBatch metric

packages/sdk/README.md
Updates the SDK README to include a warning that the package is not ready to be used.
=> fix: update SDK readme to include warning

.github/workflows/ts-packages.yml
Modifies CI so that the SDK package correctly generates coverage reports.
=> fix: have SDK generate coverage reports

integration-tests/actor-tests/lib/runner.ts, integration-tests/actor-tests/uniswap.test.ts, integration-tests/package.json, packages/batch-submitter/package.json, packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/common-ts/package.json, packages/contracts/package.json, packages/core-utils/package.json, packages/data-transport-layer/package.json, packages/message-relayer/package.json, packages/regenesis-surgery/package.json, packages/replica-healthcheck/package.json, packages/sdk/package.json
CI hasn't been reporting linting errors for a while. Seems eslint requires that you provide `--max-warnings=0` or it'll just warn instead of throw. Our tooling will automatically lint files when you commit something but stuff slips through if people commit with --no-verify. This PR fixes the issue by adding the `--max-warnings=0` flag to all invokations of eslint and also fixes the few linting issues that slipped through.
=> fix: make CI correctly report linting errors

.changeset/fair-starfishes-admire.md, CONTRIBUTING.md, README.md, go/gas-oracle/README.md, go/gas-oracle/main.go, go/op-exporter/README.md, integration-tests/test/rpc.spec.ts, packages/contracts/README.md, packages/contracts/deployments/README.md, packages/contracts/deployments/goerli/README.md, packages/contracts/deployments/kovan/README.md, packages/contracts/deployments/mainnet/README.md, packages/contracts/package.json, packages/contracts/scripts/generate-markdown.ts, packages/data-transport-layer/README.md, packages/data-transport-layer/src/services/l2-ingestion/service.ts, packages/regenesis-surgery/test/eoa.spec.ts, packages/sdk/README.md, packages/sdk/package.json, packages/sdk/src/interfaces/types.ts, packages/sdk/src/utils/message-encoding.ts
As per our recent decision to start calling the network "Optimism", this PR modifies all references of Optimistic Ethereum to just "Optimism".
=> fix: replace OE with Optimism

.changeset/clean-jars-check.md, packages/data-transport-layer/src/services/l1-ingestion/service.ts
On fresh startup, the DTL attempts to make a range
query that is very large when the starting L1 block
height is not configured. It looks for ownership
transferred events on the address manager, the first
one to happen indicates that the address manager was
deployed at that height.
Now that we use the same address manager over time instead
of the old way of upgrading the system where we would
redeploy the address manager each time, we must pass
the L1 start height as a config option to the DTL,
otherwise it will attempt to sync old transactions
(from a previous regenesis).
This commit will reduce the range at which the DTL
will query for the events, as alchemy only supports
a range of 2000. This will make the search prohibitively
slow, but that is ok as the value ought to …
=> dtl: smaller range for filter query

.changeset/mean-llamas-speak.md, ops/docker/Dockerfile.message-relayer
After https://github.com/ethereum-optimism/optimism/commit/3a673322e4ac22d565a902d82f3c0d5fd567584d
was merged, it broke the docker build of the `message-relayer`. See:
https://github.com/ethereum-optimism/optimism/runs/4600810001?check_suite_focus=true
```
#25 [stage-1 18/20] COPY --from=builder /optimism/packages/message-relayer/exec ./exec
#25 ERROR: "/optimism/packages/message-relayer/exec": not found
------
> [stage-1 18/20] COPY --from=builder /optimism/packages/message-relayer/exec ./exec:
------
Dockerfile.message-relayer:31
--------------------
29 |     COPY --from=builder /optimism/packages/message-relayer/dist ./dist
30 |     COPY --from=builder /optimism/packages/message-relayer/package.json .
31 | >>> COPY --from=builder /optimism/packages/message-relayer/exec …
```
=> fix: message relayer docker build

.circleci/config.yml
I encountered merge conflicts in the CircleCI YAML, and missed a stanza that builds proxyd.
=> ci: Fix merge bug in CircleCI YAML

packages/contracts/codechecks.yml
Codechecks reports for gas cost differences currently don't show the correct gas cost diff because the base branch where gas numbers are compared against is `master` (default) rather than `develop`. Here we add base branch settings to codechecks that defines `develop` as the first branch to compare to. Additionally we turn off [speculative branch execution](https://github.com/codechecks/docs/blob/master/configuration.md#speculative-branch-execution) which is not recommended outside of Circle CI. 
Additionally the Github action for running codechecks on merge to develop and master works correctly which re-baselines the gas costs that new PRs are compared against. 
**Metadata**
- Fixes #ENG-1328
=> Fixes codechecks reports

.changeset/beige-zoos-roll.md, integration-tests/actor-tests/lib/metrics.ts, integration-tests/actor-tests/lib/runner.ts, integration-tests/actor-tests/nft.test.ts, integration-tests/actor-tests/uniswap.test.ts, integration-tests/tsconfig.json
- Modifies the existing actor tests to use predeployed contract addresses
- Exposes metrics about the actor via Prometheus
- Adds various Hardhat tasks that make is easier to set up new environments with predeployed contracts and funded accounts
To see how the actors are set up using Stackman, see https://github.com/ethereum-optimism/stacks/blob/master/nightly/actors.yml.
Fixes ENG-1667
=> integration-tests: Actor updates to run against nightly

.changeset/empty-deers-buy.md, go/op-exporter/main.go
The op-exporter detected `version` was being referenced being set, resulting in the nil deference panics.
Fixes https://github.com/ethereum-optimism/optimism/issues/1978
=> op-exporter version nil deference

packages/sdk/src/cross-chain-provider.ts, packages/sdk/src/interfaces/cross-chain-provider.ts, packages/sdk/test/cross-chain-erc20-pair.spec.ts, packages/sdk/test/cross-chain-messenger.spec.ts, packages/sdk/test/cross-chain-provider.spec.ts
Implements the `waitForMessageReceipt` function. Will allow us to replace the `Watcher` globally.
**Metadata**
- Fixes ENG-1801
=> feat(sdk): implement waitForMessageReceipt

.changeset/fair-eyes-build.md, go/proxyd/backend.go, go/proxyd/config.go, go/proxyd/proxyd.go, go/proxyd/server.go
Provide the client origin to node providers via the X-Forwarded-For header in order to facilitate IP-based rate limiting on node providers.
This patch also adds a new proxyd backend setting, `strip_trailing_xff`, to remove trailing IP addresses in the X-Forwarded-For header. This is needed for node providers that can't handle multiple entries in the header.
A new env, `PROXYD_IP`, is introduced to indicate the proxy IP address to be added to the XFF.
**Metadata**
- Fixes ENG-1710
=> feat(proxyd): Add X-Forwarded-For header when proxying RPCs

go/batch-submitter/metrics/metrics.go, go/batch-submitter/service.go
- Renames a couple of metrics to include their units.
- Adds histogram buckets to `num_elements_per_batch`.
- Changes `batch_size_bytes` to a summary.
- Changes a couple of metrics to be gauges rather than counters.
=> go/batch-submitter: Metrics updates

.changeset/happy-ears-rhyme.md, .changeset/tame-trains-relax.md, integration-tests/test/ovmcontext.spec.ts, integration-tests/test/shared/env.ts, integration-tests/test/stress-tests.spec.ts, l2geth/rollup/sync_service.go, l2geth/rollup/sync_service_test.go
This commit updates the timestamp updating logic
such that `time.Now` is used instead of relying on
L1 timestamps. This gives a higher fidelity for the
`TIMESTAMP` opcode as well as makes the time on L2
be closer to the time on L1.
L1 to L2 transactions no longer have the property of
having the same timestamp on L2 as the timestamp
of the L1 block they were included in.
This should be able to be turned on without needing
hardfork logic as replicas should always accept the
timestamp that the sequencer sets. The sequencer is
a trusted entity in the existing implementation and
it is expected that the sequencer will become more
trustless in future iterations of the protocol.
This change is added to improve both UX and devex.
Users are confused by the timestamps on Etherscan …
=> l2geth: update timestamp logic

.changeset/chilled-mayflies-push.md, go/proxyd/metrics.go, go/proxyd/server.go
Request and response payload lengths are recorded as histograms.
**Metadata**
- Fixes ENG-1687
=> go/proxyd: Add request/response payload size metrics

go/batch-submitter/drivers/sequencer/driver.go, go/batch-submitter/metrics/metrics.go
This metric gives insight into how many times a batch is pruned to meet
the required MaxL1TxSize.
Follow up from #1993 
**Metadata**
- Fixes ENG-1868
=> feat: add BatchPruneCount metric

go/batch-submitter/batch_submitter.go, go/batch-submitter/drivers/clear_pending_tx.go, go/batch-submitter/drivers/clear_pending_tx_test.go, go/batch-submitter/drivers/interface.go, go/batch-submitter/drivers/proposer/driver.go, go/batch-submitter/drivers/sequencer/driver.go, go/batch-submitter/mock/l1client.go, go/batch-submitter/service.go, go/batch-submitter/utils/gas_price.go, go/batch-submitter/utils/gas_price_test.go
This PR adds logic to the Go Batch Submitter, allowing it to clear any pending transactions from the mempool that may have been left from a prior running instance. It does so by sending a 0-value tx to itself, and waiting until either the transaction confirms or a different transaction at the same nonce has confirmed. After ensuring that the mempool state is in a safe state to proceed, the batch submitter begins operation as before.
In addition, this PR begins the process of mocking out the L1 backend, in a way that can be reused across the project/packages. Continuing this approach will allow us to extensively test for behavior under network-level failures.
**Metadata**
- Fixes ENG-1887
=> feat: implement clear pending txs for go batch submitter

.changeset/pink-frogs-report.md, packages/batch-submitter/src/exec/run-batch-submitter.ts
Fixes a bug where both the sequencer and proposer main loops were
attempting to clear the pending transactions from the batch-tx
submitter's wallet. The impact is that we may have been overspending on
fees due to conflicting/reverting state batches. However the impact
overall should be minor given the relative size of state batches in
comparison to tx-batches.
**Metadata**
- Fixes ENG-1890
=> fix(batch-submitter): clear state root batches

go/batch-submitter/drivers/proposer/driver.go, go/batch-submitter/drivers/sequencer/driver.go, go/batch-submitter/service.go
The current `Driver` interface supports only one method for both crafting and
publishing a batch transaction, `SubmitBatchTx`. Currently this is being
executed on each new gas price that the `txmgr` commands, implying we are
doing a lot of extra work to rederive batches. In addition, much our
instrumentation lives inside this method, meaning that the they are also
being recorded multiple times per transaction. When we get to
processing larger batches on Kovan and Mainnet, this could also become a
resource bottleneck.
This PR remedies all of the above issues by splitting out the
transaction crafting process from the publication. A new method,
`CraftBatchTx`, is added to the `Driver` interface. This method is
responsible for creating a fully formed transaction, but does not …
=> bss: split up SubmitBatchTx method in Driver iface

go/proxyd/Dockerfile
Adds musl headers and GCC to the proxyd build.
=> Fix proxyd build

.github/workflows/ts-packages.yml, integration-tests/.depcheckrc, packages/contracts/.depcheckrc, packages/sdk/.depcheckrc
This PR adds depcheck to the `.github/workflows/ts-packages.yml` CI workflow to detect unused packages in the codebase.
The issue raised by @smartcontracts suggests relying on the `--ignore-path` option to avoid errors being thrown from false positives (such as packages being relied on by Solidity smart contracts, undetected by depcheck). The ignore-path option specifies files to ignore, rather than packages. This won't help with censoring false positives for unused packages. (i.e. depcheck will see packages in `package.json` and not be able to recognize their use in Solidity files; ignoring the Solidity files won't change this.) Instead, I've used the `ignores` option specified in `.depcheckrc` files. 
**Metadata**
- Fixes #1706
=> Adds depcheck to CI

integration-tests/test/replica.spec.ts, l2geth/cmd/geth/main.go, l2geth/cmd/geth/usage.go, l2geth/cmd/utils/flags.go, l2geth/eth/api_backend.go, l2geth/internal/ethapi/api.go, l2geth/internal/ethapi/backend.go, l2geth/les/api_backend.go, l2geth/rollup/config.go, ops/docker-compose.yml
This PR makes it easier for replica nodes to handle a transaction submitted via RPC and to transparently forward it to the sequencer, based on the configured endpoint.
This allows the consumer of the replica node's RPC to directly submit transactions instead of having to rely on third-party applications.
**Metadata**
- Fixes #1781
=> l2geth: forward tx to sequencer

.changeset/big-pants-remain.md, l2geth/core/types/gen_receipt_json.go, l2geth/core/types/receipt.go
Adds support for fully unmarshaling a receipt response into the Receipt type, which currently errors on hex values in OVM fields.
**Metadata**
- Unblocks ECO-79
=> feat: regenerate receipt json for optimism fields

.changeset/dull-ladybugs-learn.md
Add missing changeset for https://github.com/ethereum-optimism/optimism/pull/2011
A replica can be configured with the flag
`--sequencer.clienthttp` or the env var
`SEQUENCER_CLIENT_HTTP` which points to the
sequencer and when users hit the RPC endpoint
`eth_sendRawTransaction` it will forward the
value to the sequencer.
If running a mainnet node, this value should be
set to `https://mainnet.optimism.io` or an
infrastructure provider such as Quiknode, Infura
or Alchemy.
=> chore: add changeset for l2geth

.changeset/tidy-items-confess.md, integration-tests/contracts/Multicall.sol, integration-tests/contracts/OVMContext.sol, integration-tests/contracts/OVMContextStorage.sol, integration-tests/test/ovmcontext.spec.ts
**Changes in Contracts**
Deleted OVMMulticall.sol. 
(new) Multicall.sol --> copied from the [makerdao implementation](https://github.com/makerdao/multicall/blob/master/src/Multicall.sol)
(new) OVMContext.sol --> contains the helper functions.
OVMContextState.sol --> extends from OVMContext.sol.
1. All `aggregate()` invocations now call Multicall.sol
2. OVMContextState.sol is now used for calling the helper functions. 
**Metadata**
- Fixes [#2014](https://github.com/ethereum-optimism/optimism/issues/2014)
=> Split OVMMulticall.sol into Multicall.sol & OVMContext.sol in integration tests

.changeset/spicy-kiwis-double.md, integration-tests/actor-tests/state-dos.test.ts, integration-tests/test/basic-l1-l2-communication.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/stress-tests.spec.ts
Use hardhat-ethers for importing factories in integration tests.
Using hardhat-ethers is cleaner and more future-proof than importing the json files directly.
**Metadata**
- Fixes #2016
=> test: use hardhat-ethers for importing factories in integration tests

.changeset/fuzzy-rivers-double.md, go/batch-submitter/batch_submitter.go, go/batch-submitter/drivers/clear_pending_tx_test.go, go/batch-submitter/mock/l1client.go, go/batch-submitter/txmgr/txmgr.go, go/batch-submitter/txmgr/txmgr_test.go
This PR adds functionality to the `txmgr`, allowing it to be configured with a desired confirmation depth. As a result the `Send` function will block until `NumConfirmations` has been reached.
**Metadata**
- Fixes ENG-1884
=> feat: add confirmation depth awareness to txmgr

.changeset/warm-ears-float.md, l2geth/rollup/sync_service.go
The logline `Blocknumber monotonicity violation`
was being logged erroneously. This commit ensures
that it is not logged when it doesn't need to be
logged.
It would previously log if the L1 blocknumber
was equal to or less than and now it only logs
if the L1 blocknumber is less than.
**Metadata**
- Fixes https://github.com/ethereum-optimism/optimism/issues/2033
=> l2geth: fix monotonicity logging bug

go/proxyd/rpc.go, go/proxyd/rpc_test.go
Both the `Error` and `Result` fields on `RPCRes` had `omitempty` tags, so null results were being swallowed. We didn't catch this in integration tests because JavaScript tolerates missing keys. This is now fixed by using a custom JSON marshaler.
Fixes #2049
=> go/proxyd: Properly handle null results

.changeset/happy-lions-divide.md, l2geth/internal/ethapi/api.go
This commit adds a better error message when there
is an error for proxying user requests to the sequencer.
This allows the change to be relatively backwards compatible
as a good error message is returned when the sequencer url
is not configured.
=> l2geth: better error message for proxying user txs

packages/sdk/src/cross-chain-provider.ts, packages/sdk/src/interfaces/cross-chain-provider.ts, packages/sdk/test/cross-chain-provider.spec.ts
Implements the `estimateL2MessageGas` function in the `CrossChainProvider`. This function will be used when attempting to send a message from L1 to L2.
**Metadata**
- Fixes ENG-1802
=> feat(sdk): implement L2 message gas estimation

.changeset/curly-candles-pretend.md, go/proxyd/cache.go
Set TTL for RPC keys in redis. Otherwise they won't get evicted once we've hit max memory.
=> proxyd: Allow cached RPC keys to be evicted

packages/sdk/src/cross-chain-messenger.ts, packages/sdk/src/cross-chain-provider.ts, packages/sdk/src/index.ts, packages/sdk/src/interfaces/cross-chain-messenger.ts, packages/sdk/src/interfaces/cross-chain-provider.ts, packages/sdk/src/interfaces/types.ts, packages/sdk/test/contracts/MockMessenger.sol, packages/sdk/test/cross-chain-messenger.spec.ts, packages/sdk/test/cross-chain-provider.spec.ts
Implements the SDK's `sendMessage` functionality + tests. Includes some minor bug fixes. Also removes block time logic in favor of using seconds everywhere, since block time is variable.
**Metadata**
- Fixes ENG-1825
=> feat(sdk): implement sendMessage

packages/contracts/README.md
Removes a broken link in the contracts README. The referenced page no longer exists.
**Metadata**
- Fixes #2082
=> fix(contracts): remove broken link in README

.changeset/spicy-squids-serve.md, packages/batch-submitter/src/batch-submitter/state-batch-submitter.ts, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
Don't rely on `performance` as a builtin to prevent
coupling the batch submitter to a version of nodejs
that has it as a builtin.
=> batch-submitter: import performance

.github/workflows/publish-canary.yml, .github/workflows/release.yml
Using the `@master` version has been deprecated
so this updates to `@v1`
=> ci: update version of changesets

.github/workflows/release.yml
There is a changeset managed `rpc-proxy` publishing step
so we no longer need to publish `rpc-proxy` with `l2geth`.
This was originally added to quickly be able to publish
`rpc-proxy`
=> ci: decouple rpc-proxy publishing from l2geth

.changeset/gentle-beds-give.md, packages/core-utils/src/common/hex-strings.ts, packages/core-utils/test/hex-utils.spec.ts
Description
Improve docstrings and tests for utils inside of hex-strings.ts #2053
Additional context
I wrote docstrings & tests to confirm the current functionality of hex-strings.ts. I do not have a good understanding of what could be wrong in the functions of hex-strings.ts or how they're used.
Notes:
I see duplicate code in packages/data-transport-layer/src/utils/common.ts
padHexString is confusing & should maybe add a if (!ethers.utils.isHexString(inputString)) check
**Metadata**
- Fixes #2053
=> test/docs: Improve docstrings and tests for utils in hex-strings.ts

packages/sdk/src/cross-chain-messenger.ts, packages/sdk/src/interfaces/cross-chain-erc20-pair.ts, packages/sdk/src/interfaces/cross-chain-messenger.ts, packages/sdk/src/interfaces/types.ts
Slightly cleans up the API for overriding transaction options. Previous
API was a bit confusing and didn't leave room for additional optional
parameters. By separating options and overrides, we can add new options
that are unrelated to transaction overrides.
=> fix(sdk): clean up tx override api

.changeset/shaggy-stingrays-compare.md, packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts
Fixes a bug in the batch submitter where new contexts were not being
correctly created for L1 to L2 transactions with a different timestamp.
This bug exists because of recent changes to L2Geth where timestamps are
now being updated more frequently.
=> fix(bss): have BSS correctly create new contexts

packages/core-utils/test/alias.spec.ts
This commit improves the test coverage for address aliasing to 100% in packages/core-utils/alias.spec.ts
- added two additional error messages to check against
**Metadata**
- Fixes #2054
=> test: improve test coverage for aliasing

ops/docker/Dockerfile.batch-submitter-service
Alpine 3.14 has an issue (https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2) that prevents it from working on CircleCI at this time.
=> go/batch-submitter: Downgrade Alpine version

.changeset/famous-wombats-exercise.md, integration-tests/contracts/FakeL2StandardERC20.sol, integration-tests/test/bridged-tokens.spec.ts
Adds an integration test demonstrating that a commonly perceived vulnerability does not in fact exist.
Specifically, there appears to an obvious bug which would allow an attacker to withdraw a fake ERC20 token from L2 in exchange for a real ERC20 (such as WBTC) token on L1. There is no check in the L2StandardBridge, however the withdrawal is prevented from finalizing by a check in the L1StandardBridge.
=> test(integration): withdrawing a fake L2 token

integration-tests/test/native-eth.spec.ts, integration-tests/test/shared/utils.ts
remove the unused variable from the integration tests
**Metadata**
- Fixes #2110
=> Depreciated unused variable from Integration tests

.changeset/many-seals-argue.md, go/batch-submitter/drivers/sequencer/batch.go
See https://github.com/ethereum-optimism/optimism/pull/2093 for more
details.
**Metadata**
- Fixes ENG-1937
=> fix: mimic BSS timestamp bug fix from #2093

.changeset/happy-poems-impress.md, go/batch-submitter/config.go
This was a known bug, but recently caught the reason in combing through
the new copy in the specs repo. The old hack that auto defaulted to
debug has been removed.
**Metadata**
- Fixes ENG-1935
=> fix: actually allow BSS log level to be set via flags

.changeset/tricky-bees-sneeze.md, integration-tests/package.json, integration-tests/test/basic-l1-l2-communication.spec.ts, integration-tests/test/shared/env.ts, ops/docker/Dockerfile.integration-tests, ops/docker/Dockerfile.packages, packages/sdk/src/utils/contracts.ts, packages/sdk/src/utils/merkle-utils.ts
First PR in a series of PRs to start integrating the SDK into the integration tests. It's too much work to do this all in one PR. Includes a few minor bugfixes to the SDK.
=> feat(sdk): start using sdk in integration tests

l2geth/README.md
Simply update the readme to make local development with l2geth easier
=> l2geth: update readme

.changeset/yellow-steaks-trade.md, packages/sdk/package.json
Minor bugfix, has SDK use ethers as a peer dependency instead of including as a direct dependency. This helps with certain ethers-specific typing issues.
=> fix: have sdk use ethers peer dep

.changeset/warm-news-punch.md, packages/data-transport-layer/src/services/server/service.ts
Both `GET /eth/context/latest` and `GET /eth/context/blocknumber/:number`
rely on fetching a remote block to pull the timestamp, blocknumber and
blockhash from. If the fetched block is not found, then properties on
`null` will be attempted to be accessed which will result in a runtime
error. This commit adds handling for this case to prevent that kind of
bug.
=> dtl: handle errors in context api

integration-tests/test/native-eth-ovm-calls.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/shared/env.ts, integration-tests/test/shared/utils.ts, integration-tests/test/stress-tests.spec.ts
This commit removes the deprecated Watcher class from the fundUser
function in favor of using the CrossChainMessenger class from the new
Optimism SDK. This is part of a series of commits that are designed to
eventually remove the Watcher entirely from the integration tests (and
then from the entire repository).
=> feat(itests): remove Watcher from fundUser

.changeset/big-windows-shout.md, packages/sdk/src/adapters/eth-bridge.ts, packages/sdk/src/adapters/standard-bridge.ts, packages/sdk/src/cross-chain-messenger.ts, packages/sdk/src/interfaces/bridge-adapter.ts, packages/sdk/src/interfaces/cross-chain-messenger.ts
This commit updates the SDK to add support for withdrawing or depositing
to a target address (as opposed to simply depositing or withdrawing to
yourself).
=> feat(sdk): allow withdrawals or deposits to target

.changeset/short-news-cover.md, integration-tests/actor-tests/sends.test.ts, integration-tests/test/shared/env.ts
The SDK expects all L1 contracts to be specified if the L1 chain ID isn't well-known. This PR makes the integration test setup always specify the L1 contracts, since networks like the nightly don't use a well-known chain ID.
=> integration-tests: Support networks that aren't specified in the SDK

integration-tests/actor-tests/lib/actor.ts, integration-tests/test/replica.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/shared/env.ts, integration-tests/test/shared/stress-test-helpers.ts, integration-tests/test/shared/utils.ts, integration-tests/test/verifier.spec.ts
Replaced sleep function in integration-tests and added external/internal import comments.
**Metadata**
- Fixes #2155
=> Replaced sleep function in integration-tests

.changeset/eighty-comics-push.md, packages/core-utils/src/common/misc.ts, packages/core-utils/test/misc.spec.ts
- Adds docstrings for functions
- Adds tests for said functions
The [clone](https://github.com/ethereum-optimism/optimism/blob/eb926e2f90b5eec4558f3c82746b639b19ddf9d5/packages/core-utils/src/common/misc.ts#L15) function currently does a shallow copy, deepClone from lodash in being used in other places in the repo, though I've only seen this function being used in places where it's not needed. Let me know if it makes sense to change it.
**Metadata**
- Fixes #2052
=> test: misc.ts in core-utils

.changeset/selfish-numbers-tan.md, packages/sdk/src/adapters/eth-bridge.ts, packages/sdk/src/adapters/standard-bridge.ts, packages/sdk/src/cross-chain-messenger.ts
Has the SDK sort messages (deposits/withdrawals) descending by block
number. Makes for a better experience when presenting this data to
users.
**Metadata**
- Fixes ENG-1949
=> feat(sdk): have SDK sort messages descending by bn

.changeset/fresh-planes-report.md, integration-tests/actor-tests/deposits.test.ts, integration-tests/test/fee-payment.spec.ts, integration-tests/test/native-eth.spec.ts, integration-tests/test/ovmcontext.spec.ts, integration-tests/test/queue-ingestion.spec.ts, integration-tests/test/shared/env.ts, integration-tests/test/shared/stress-test-helpers.ts, integration-tests/test/shared/watcher-utils.ts
Removes all remaining usage of the Watcher from the integration tests.
Makes it possible to entirely remove the Watcher in a following commit.
**Metadata**
- Fixes #2055
=> test(integration): replace watcher with sdk CrossChainMessenger

.changeset/eleven-lobsters-add.md, go/bss-core/metrics/metrics.go
Removes an extra space in the BSS metrics names that causes the service to die on startup.
**Metadata**
- Fixes ENG-1954
=> fix: remove extra space in BSS metric names

.github/workflows/label-requires-reviews.yml
PERSONAL_ACCESS_TOKEN doesn't seem to exist or is expired (also no other check uses this token). Works now with GITHUB_TOKEN.
=> fix: use correct token for label-requires-review

.changeset/wise-weeks-explode.md, integration-tests/test/ovmcontext.spec.ts
Skips the unreliable timestamp/blocknumber test which would often be off
by one or two. Creates an annoying habit of having to rerun the
integration tests until the test passes, which isn't how integration
tests should work.
=> fix: skip an unreliable integration test

ops/README.md
An issue was recently reported (#2191) that showed that 4gb was not
sufficient to run the docker setup. This commit updates the recommended
amount of memory to 8gb.
=> fix: update recommended memory for ops setup

.github/labeler.yml
Updates the PR labeler to correctly label the SDK. I noticed that the
SDK was not being correctly labeled and realized that I had to add it to
this file.
=> fix: update PR labeler to include SDK

.changeset/grumpy-ads-smile.md, packages/sdk/src/cross-chain-messenger.ts
Fixes the SDK so that it correctly handles the case where no batches
have been submitted to the StateCommitmentChain yet. Only happens in
development or immediately after a new chain is started.
**Metadata**
- Fixes #2211
=> fix(sdk): correctly handle no batch case

.changeset/lemon-chefs-walk.md, packages/sdk/src/cross-chain-messenger.ts
Minor fix to the SDK to guarantee that transactions are `wait`ed to avoid situations in which the receipt does not yet exist because the transaction has not been processed yet.
=> fix(sdk): have sdk properly wait for transactions

.changeset/thin-seahorses-fry.md, packages/sdk/src/adapters/eth-bridge.ts, packages/sdk/src/adapters/standard-bridge.ts, packages/sdk/src/cross-chain-messenger.ts, packages/sdk/src/interfaces/bridge-adapter.ts, packages/sdk/src/interfaces/cross-chain-messenger.ts
Adds functions to the SDK for handling token approvals to bridges.
=> feat(sdk): add approval fns to the SDK

.changeset/fifty-ears-fly.md, packages/data-transport-layer/src/services/main/service.ts
Adds a basic log line to the DTL when BSS HF1 is active. Will also log
when BSS HF1 is not active.
=> fix: add logging to the DTL when BSS HF1 is live

.changeset/young-gorillas-raise.md, packages/data-transport-layer/src/services/l2-ingestion/service.ts
Log the current synchronized tx number and block tip reported by the rpc provider at l2-ingestion.
We observed an issue where the dtl thinks it has reached the tip and thus stopped syncing transactions on l2. There isn't enough visibility to determine if this was because the l2 rpc provider returned an incorrect block tip or not.
=> dtl: Periodically log current l2 sync

.changeset/spotty-trains-sneeze.md, packages/sdk/src/l2-provider.ts
1. Fix a bug in `L2Provider.getL1GasPrice()`
2. Make it easier to get correct estimates from `L2Provider.estimateL1Gas()` and `L2.estimateL2GasCost`.
=> Fix and usability improvements for L1 gas and cost estimates in L2Provider

.changeset/brown-foxes-hang.md, integration-tests/test/ovmcontext.spec.ts, integration-tests/test/rpc.spec.ts, integration-tests/test/whitelist.spec.ts
Replaced l2Provider with env.l2Provider in [whitelist.spec.ts](https://github.com/ethereum-optimism/optimism/blob/develop/integration-tests/test/whitelist.spec.ts), [rpc.spec.ts](https://github.com/ethereum-optimism/optimism/blob/develop/integration-tests/test/rpc.spec.ts) & [ovmcontext.spec.ts](https://github.com/ethereum-optimism/optimism/blob/develop/integration-tests/test/ovmcontext.spec.ts)
**Metadata**
- Fixes #2154
=> maintance: replaced l2Provider with env.l2Provider

.changeset/khaki-boxes-learn.md, go/batch-submitter/go.mod, go/batch-submitter/go.sum
Update to go-ethereum v1.10.16.
Release notes:
https://github.com/ethereum/go-ethereum/releases/tag/v1.10.16
This notably fixes the http2 bug in the rpc client.
https://github.com/ethereum-optimism/optimism/pull/2078 will be able to be reverted after this is merged in
=> batch-submitter: update to go-ethereum v1.10.16

.changeset/lovely-shrimps-explain.md, go/batch-submitter/drivers/proposer/driver.go, go/batch-submitter/drivers/sequencer/driver.go, go/batch-submitter/drivers/sequencer/metrics.go, go/batch-submitter/go.mod, go/bss-core/metrics/interface.go, go/bss-core/metrics/metrics.go, go/bss-core/service.go
Modifies the bss-core `Service` to operate on a `metrics.Metrics` interface rather than a concrete struct.
The interface is now implemented by `metrics.Base` which can embedded in driver-specific metrics extensions.
Some extra functionality is added to make this process simpler, e.g  exposing the `SubsystemName()` to ensure the extensions all have the same metrics prefix. To demonstrate the behavior, the `BatchPruneCount` metrics is moved into an extended metrics object specific to the sequencer, since the proposer does not have this concept.
**Metadata**
- Fixes ENG-1969
=> interface bss-core metrics to allow for driver-specific metrics extensions

.changeset/big-cycles-listen.md, ops/docker/Dockerfile.replica-healthcheck
Fixes an issue in the replica-healthcheck dockerfile where the file was
not properly including the SDK. As a result, the replica-healthcheck
service was not able to import the SDK and the service would break on
start.
**Metadata**
- Fixes #2236
=> fix(rhc): dockerfile not properly including sdk

.changeset/quick-tables-double.md, l2geth/rollup/sync_service.go
=> l2geth: fix startup logic for repairing queue index

.changeset/nasty-boats-type.md, l2geth/internal/ethapi/api.go, l2geth/rollup/sync_service.go
Allow for read requests during initial sync but
don't allow for write requests during initial sync.
This is done by spawning a goroutine so that the
initial sync logic is non-blocking.
cc @smartcontracts
=> l2geth: don't block read rpc when doing initial sync

.changeset/cool-cougars-lick.md, l2geth/core/state_transition.go
Some left over dead code is removed.
It has never been triggered and cannot
be triggered due to the locks in the syncservice.
=> l2geth: remove dead code

.changeset/big-cycles-listen.md, .changeset/brown-foxes-hang.md, .changeset/cool-cougars-lick.md, .changeset/grumpy-lemons-laugh.md, .changeset/happy-yaks-clap.md, .changeset/healthy-cycles-jam.md, .changeset/hungry-apples-exist.md, .changeset/khaki-boxes-learn.md, .changeset/lovely-shrimps-explain.md, .changeset/nasty-boats-type.md, .changeset/quick-tables-double.md, .changeset/spotty-trains-sneeze.md, go/batch-submitter/CHANGELOG.md, go/batch-submitter/package.json, go/gas-oracle/CHANGELOG.md, go/gas-oracle/package.json, go/proxyd/CHANGELOG.md, go/proxyd/package.json, integration-tests/CHANGELOG.md, integration-tests/package.json, l2geth/CHANGELOG.md, l2geth/core/state_transition.go, l2geth/package.json, packages/data-transport-layer/CHANGELOG.md, packages/data-transport-layer/package.json, packages/replica-healthcheck/CHANGELOG.md, packages/replica-healthcheck/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json
- l2geth: don't block read rpc when doing initial sync
- l2geth: fix startup logic for repairing queue index
- maintenance: minor README updates
- Deleted common.ts in data-transport-layer and replaced them from core-utils
- feat: split up SubmitBatchTx driver method
- feat: add failing Test for txmgr edge case
- fix: add SendState to determine when to abort Send
- feat: add SAFE_ABORT_NONCE_TOO_LOW_COUNT flag
- feat: stop publishing txs after receiving confirmation
- feat: update message-relayer to use the SDK
- feat: add teleport Postgres APIs
- fix: add missing "*" to pull_request path for bathc-submitter and bss-core
- feat: add teleportr unit tests to GH Actions with Postgres service
- maintenance: use new asL2Provider function
- feat(core-utils): remove Watcher and injectL2Context
- …
=> Develop -> Master

.github/workflows/golangci-lint.yml, .github/workflows/teleportr.yml, go/teleportr/db/db.go
Also fixes a linter error that wasn't caught while the CI was broken.
The yaml failed to parse because the postgres env vars didn't have dashes before them:
```
The workflow is not valid. .github/workflows/teleportr.yml (Line: 28, Col: 11): A sequence was not expected
```
Example of failed run: https://github.com/ethereum-optimism/optimism/actions/runs/1924304434
=> feat: fix teleportr ci, and lint target

.github/workflows/batch-submitter.yml, .github/workflows/bss-core.yml, .github/workflows/gas-oracle.yml, .github/workflows/golangci-lint.yml, .github/workflows/proxyd.yml
The current methodology only attempts to run unit tests when changes to
the package paths are detected. However, this is brittle and most
notably doesn't capture when changes are made to the workflow itself. As
a result, a green build in a PR doesn't neccessarily correlate to a
green build after merge. Unit tests are cheap, so this should prevent
needless false positives.
I've intentionally left the l2geth tests with path selection on since that isn't likely
to receive many changes, and they are considerably more expensive than the unit
tests in our services.
=> feat: always run go unit tests/golangci-lint on every PR

integration-tests/test/z-batch-serialization.spec.ts
PR #2199 introduced removed ctc from `env`, so the itests for batch serialization need to be updated.﻿
=> integration-tests: Fix merge issue

.changeset/early-pans-provide.md, .github/workflows/publish-canary.yml, ops/docker/Dockerfile.replica-healthcheck
Fixes another bug in the Replica Healthcheck docker file.
**Metadata**
- Fixes #2243
=> fix(rhc): fix dockerfile bug

.changeset/moody-lobsters-lay.md, integration-tests/test/basic-l1-l2-communication.spec.ts, integration-tests/test/bridged-tokens.spec.ts, integration-tests/test/shared/env.ts, packages/sdk/src/cross-chain-messenger.ts, packages/sdk/src/interfaces/cross-chain-messenger.ts
Adds a function to the SDK (waitForMessageStatus) which will wait until
the status of a particular message matches the target status.
waitForMessageStatus also handles certain special cases where different
status messages are incompatible (e.g., the RELAYED and
FAILED_L1_TO_L2_MESSAGE status for L1 to L2 messages). Useful to avoid
including looping logic in your own application.
=> feat(sdk): add fn to wait for message status

.changeset/khaki-chefs-call.md, packages/contracts/.depcheckrc, packages/contracts/package.json
Removes yargs as a dependency from the contracts package since it wasn't
being used. Always good to cut unused dependencies.
=> fix(ct): remove yargs as unused dep

.changeset/healthy-otters-yawn.md, packages/contracts/src/contract-defs.ts, packages/contracts/test/helpers/constants.ts, packages/contracts/test/helpers/trie/trie-test-generator.ts, packages/contracts/test/helpers/utils/eth-time.ts
Removes functions and constants that are not used in the contracts
package. Also removes export from interfaces that are not being imported.
**Metadata**
- Fixes #2261
=> cleanup(contracts): remove unused code

.eslintrc.js
https://github.com/typescript-eslint/typescript-eslint/issues/3528
Cuts the run of linting from 68s to 44s on my local machine
with `yarn lint` at the root of the repo
Attempting to debug https://github.com/ethereum-optimism/optimism/pull/2249, will rebase on top
of this commit to see if it fixes the oom error in that PR.
=> linting: speed up with new config

go/indexer/package.json, package.json
This commit adds all packages in the `go` directory
to the changesets packages so that they don't need
to be added individually. It also removes `specs` since
that directory no longer exists.
=> changeset: cleanup packages

packages/contracts/package.json, packages/contracts/test/contracts/L1/messaging/L1CrossDomainMessenger.spec.ts, packages/contracts/test/contracts/L1/messaging/L1StandardBridge.spec.ts, packages/contracts/test/contracts/L1/messaging/deposit.gas.spec.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.gas.spec.ts, packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.spec.ts, packages/contracts/test/contracts/L1/rollup/StateCommitmentChain.spec.ts, packages/contracts/test/contracts/L2/messaging/L2CrossDomainMessenger.spec.ts, packages/contracts/test/contracts/L2/messaging/L2StandardBridge.spec.ts, packages/contracts/test/contracts/L2/messaging/L2StandardTokenFactory.spec.ts, packages/contracts/test/contracts/L2/predeploys/OVM_L2ToL1MessagePasser.spec.ts, packages/contracts/test/contracts/L2/predeploys/OVM_SequencerFeeVault.spec.ts, packages/contracts/test/contracts/chugsplash/L1ChugSplashProxy.spec.ts, packages/contracts/test/helpers/resolver/address-manager.ts, yarn.lock
This PR is focused on migration from Smock v1 to Smock v2 since v1 is deprecated
**Metadata**
- Fixes #2258
=> refactor(tests): migrate from smock v1 to smock v2

.github/workflows/batch-submitter.yml, .github/workflows/bss-core.yml, .github/workflows/gas-oracle.yml, .github/workflows/geth.yml, .github/workflows/golangci-lint.yml, .github/workflows/integration.yml, .github/workflows/teleportr.yml, .github/workflows/ts-packages.yml, CONTRIBUTING.md, README.md
Changes our branching model to use release/ branches instead of
regenesis/ branches now that we no longer plan to perform any
regenesis-style upgrades. Using release/ branches will reduce confusion
from people who see a regenesis/ branch and assume (logically) that this
branch will result in a regenesis.
=> maint: use release instead of regenesis branches

.changeset/tiny-chicken-occur.md, packages/contracts/README.md
Going to update the contracts README in a series of PRs. I don't feel like doing this all in a single PR because there's a lot of content and I'm tired.
=> maintenance: contracts README update 1

.gitignore, packages/message-relayer/.env.example, packages/message-relayer/README.md
Updates `message-relayer` README to remove outdated content and reflect the features of the latest version.
=> fix(mr): update README to reflect latest version

.changeset/purple-peaches-serve.md, packages/common-ts/src/base-service/base-service-v2.ts
Gracefully handles BaseServiceV2 exits by default. Adds a new function
for stopping the service and catches SIGTERM and SIGINT correctly.
=> feat(cmn): gracefully handle BaseServiceV2 exits

.changeset/fair-bees-promise.md, go/batch-submitter/drivers/sequencer/driver.go
On mainnet we are seeing out of gas  exceptions with some frequency. In all
of these cases it appears we are very, very close to being successful.
This commit extracts the internal calls performed by RawTransact into
the driver and then adds a buffer to limit the possibility of losing
money on the reverting transactions, since these very large transactions
are costly especially in the current fee market.
**Metadata**
- Fixes ENG-2046
=> feat: extract gas limit estimation to driver, add 20% buffer

.changeset/perfect-ties-decide.md, go/proxyd/rate_limiter.go
When the out of service interval is zero, `proxyd` will send a `SETEX` command to Redis with a zero expiry. This is technically an error, and causes messages like `error setting backend unavailable ERR invalid expire time in setex` to appear in the logs. Users won't notice the issue since `proxyd` can continue working when Redis returns an error, but we should clean this up nonetheless since these problems appear in our alerting.
=> proxyd: Don't hit Redis when the out of service interval is zero

go/indexer/Makefile, go/indexer/config.go, go/indexer/crypto_test.go, go/indexer/db/db.go, go/indexer/db/deposit.go, go/indexer/db/eth.go, go/indexer/db/guid.go, go/indexer/db/l1block.go, go/indexer/db/locator.go, go/indexer/db/pagination.go, go/indexer/db/sql.go, go/indexer/db/state_batch.go, go/indexer/db/token.go, go/indexer/db/txn.go, go/indexer/db/withdrawal.go, go/indexer/flags/flags.go, go/indexer/go.mod, go/indexer/go.sum, go/indexer/indexer.go, go/indexer/server/server.go, go/indexer/services/l1/bridge/filter.go, go/indexer/services/l1/confirmed_headers.go, go/indexer/services/l1/service.go, go/indexer/services/l2/bridge/filter.go, go/indexer/services/l2/service.go
This PR adds pagination metadata to the `/deposits` and `/withdrawals` endpoints.
The indexer REST server host/port is now configurable via the vars `REST_HOSTNAME`, `REST_PORT` but defaults to `127.0.0.1:8080` like before.
Also a general cleanup, test fixes and docs. Most notably the file `db.go` is split by topic into different files.
=> indexer: add pagination metadata for deposit, withdrawal endpoints

technical-documents/postmortems/2022-02-02-inflation-vuln.md
This edit is meant to remove any ambiguity about which instance is being referred to, and also standardizes on the 
spacing and capitalization used for Geth and L2Geth
=> fix: Use consistent style/naming for Geth, L2Geth

packages/message-relayer/package.json
Tiny pr, marking the `message-relayer` package as private.
- Fixes #2312
=> Set the message-relayer package to private

go/teleportr/api/server.go, go/teleportr/db/db.go, go/teleportr/db/db_test.go
Addresses some minor fixes for issues discovered in Kovan deployment.
=> minor teleportr API fixes

.changeset/lucky-cameras-grin.md, go/bss-core/drivers/clear_pending_tx_test.go, go/bss-core/service.go, go/bss-core/txmgr/txmgr.go, go/bss-core/txmgr/txmgr_test.go
Currently the txmgr treats confirmation of a transaction as successful
if it achieves the proper confirmation depth, however it fails to
acknowledge the possibility that the transaction reverts. Thus to an
external caller the transaction silently succeeds.
This commit now inspects the receipt and returns an ErrReverted failure
in the event that receipt.Status is not 1. This allows higher level
applications to add logging/telemetry or take action on these events.
**Metadata**
- Fixes ENG-2069
=> feat: txmgr return ErrReverted if confirmed tx reverts

README.md, l2geth/README.md, packages/contracts/README.md, packages/data-transport-layer/README.md, packages/smock/README.md
I noticed a couple of outdated links in the READMEs throughout the repo and updated them. Also deleted smockv1 folden since we use `@defi-wonderland/smock`.
=> maint: update readme links and remove smockv1 package

.changeset/blue-carrots-vanish.md, go/teleportr/api/server.go
Adds the same fallback mechanism for `SuggestGasTipCap` used the batch submitter for
estimating gas prices in the teleportr API server.
**Metadata**
- Fixes ENG-2067
=> feat: add SuggestGasTipCap fallback in teleportr api server

.changeset/stale-ladybugs-smell.md, go/batch-submitter/drivers/sequencer/batch.go, go/batch-submitter/drivers/sequencer/driver.go, go/batch-submitter/drivers/sequencer/encoding.go, go/batch-submitter/drivers/sequencer/encoding_test.go
This PR modifies the BSS to enforce the configured `MinTxSize` and `MaxTxSize` on the plaintext encoding of calldata, regardless of which encoding scheme is used. Previously the only initial, conservative pass was performed against the plaintext size, after which (when using zlib) the min and max would be applied to the compressed calldata size. To ensure these are applied consistently, we now abort/prune based on the plaintext size before performing the final encoding. This protects against the edge case where the initial pass includes a maximum plaintext-sized batch, but the compressed size ends up being under the minimum.
**Metadata**
- Fixes ENG-2065
=> feat: bss plaintext tx size enforcement

packages/contracts/tasks/fetch-batches.ts
Makes it very easy to observe the compression ratio when using the hardhat task `fetch-batches`
=> contracts: batch compression ratios in fetch-batches task

.changeset/ninety-kids-deny.md, go/teleportr/go.mod, go/teleportr/go.sum
https://github.com/ethereum/go-ethereum/releases/tag/v1.10.16
This is a useful version to upgrade to due to the HTTP2 fix
in the RPC client.
=> teleportr: bump go-ethereum to v1.10.16

.changeset/lazy-years-call.md, go/indexer/go.mod, go/indexer/go.sum
https://github.com/ethereum/go-ethereum/releases/tag/v1.10.16
This is a useful version to upgrade to due to the HTTP2 fix
in the RPC client.
=> indexer: bump go-ethereum dep to v1.10.16

.changeset/healthy-rings-fix.md, ops/docker/Dockerfile.packages
Fixes a bug in the dockerfile for the replica-healthcheck. Healthcheck
does not run properly as a result of this bug.
=> fix(rhc): bug in replica-healthcheck dockerfile

go/bss-core/go.mod, go/bss-core/go.sum
Updates to use go-ethereum v1.10.16
=> deps: update bss-core to go-ethereum v1.10.16

.changeset/thirty-stingrays-reply.md, go/gas-oracle/flags/flags.go, go/gas-oracle/oracle/config.go, go/gas-oracle/oracle/gas_price_oracle.go
This commit adds a new config option that can be
configured via argv with `--l1-base-fee-epoch-length-seconds`
or an env var `GAS_PRICE_ORACLE_L1_BASE_FEE_EPOCH_LENGTH_SECONDS`.
It defaults to 15 seconds. Ideally the implementation uses a
duration flag instead of a uint64 flag, but that would be a
breaking change for the config and this service will be
deprecated in the future with the release of bedrock.
By setting this value to a larger number, we are able to update
the L1 base fee that is held in the L2 state less often.
This will save the sequencer money, because it needs to
front the costs of submitting these transactions.
=> gas-oracle: allow configurable base fee poll interval

.circleci/config.yml, .github/workflows/integration.yml, ops/docker-compose.yml
Fixes a typo in the primary docker-compose file. replica-healthcheck
should be replica_healthcheck to conform with the style used everywhere
else.
=> fix(rhc): typo in healthcheck docker-compose

.changeset/twelve-shrimps-add.md, .changeset/weak-walls-cross.md, integration-tests/package.json, ops/docker/hardhat/hardhat.config.js, ops/docker/hardhat/package.json, packages/contracts/package.json, packages/contracts/test/contracts/L2/predeploys/OVM_GasPriceOracle.spec.ts, packages/data-transport-layer/package.json, packages/message-relayer/package.json, packages/sdk/package.json, yarn.lock
See release notes here:
https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.9.0
This is a performance release, so it is good to upgrade here
to improve the time of CI. The compilation happens in parallel
with this release, as well as tests being able to be ran in parallel.
We do not make use of any forked network tests currently, but
this PR does help to speed up that usecase as well.
=> deps: bump hardhat

infra/op-replica/docker-compose/replica.yml
Updates replica.yml in our infra folder to use an older version of the
healthcheck service by default. We'll use latest when we update our
environment variables everywhere later.
=> fix(infra): use older version of hc by default

.changeset/sharp-terms-pay.md, packages/common-ts/src/base-service/base-service-v2.ts
Fixes a bug where BaseServiceV2 was not properly throwing when options
were missing.
=> fix(cmn): have BaseService throw on missing options

.changeset/tiny-melons-float.md, l2geth/cmd/geth/chaincmd.go, l2geth/cmd/geth/main.go, l2geth/cmd/geth/usage.go, l2geth/cmd/utils/flags.go, packages/contracts/package.json
Adds a configurable timeout for fetching the genesis file when running
l2Geth. Useful for people who want to run a node on slower internet and
need more than 60 seconds to fetch the genesis file.
=> feat(l2geth): add configurable genesis timeout

.changeset/popular-plants-change.md, .circleci/config.yml, ops/docker/Dockerfile.packages, ops/scripts/wait-for-sequencer.sh
Image sizes were increased because the packages Dockerfile used `buster-slim` rather than Alpine. Unfortunately, the images will still be large because the `node_modules` directory contains dev dependencies. This is how it was before the CircleCI migration/larger build cleanup, and will need a larger rethink of how we build TypeScript projects in the monorepo before it can be solved.
=> ci: Use Alpine to reduce image size

.circleci/config.yml
Updates cache keys to fix the CircleCI permissions errors we've seen. Builds will be a bit slow while the cache rebuilds.
=> ci: Change cache keys

.changeset/tender-scissors-report.md, packages/common-ts/src/base-service/validators.ts
Adds a new JsonRpcProvider validator which specifically parses the input
type into a JsonRpcProvider instead of a generic provider.
=> feat(cmn): add JsonRpcProvider validator

.circleci/config.yml, packages/contracts/deployments/kovan/README.md
Adds a step to the contract tests to confirm that the contract
deployment docs are up to date. Will only fail if a deployment has been
modified but yarn autogen:markdown was not run properly.
=> feat(ci): check deploy markdown correctness

.changeset/new-jokes-walk.md, packages/data-transport-layer/src/services/l2-ingestion/service.ts, packages/data-transport-layer/src/services/main/service.ts
=> data-transport-layer: add new metrics

.changeset/light-bugs-teach.md, l2geth/cmd/geth/accountcmd_test.go
Skip some tests that flake in CI.
It is safe to skip these because
this code will not be changed and we
will be deprecating this codebase soon.
=> l2geth: skip flaky accountcmd tests

.github/workflows/publish-canary.yml, .github/workflows/release.yml
Teleportr was getting released on GitHub, but not pushed to Docker Hub. The indexer's canary builds were pushing `batch-submitter-service` images, which was incorrect.
=> ci: Add teleportr release, fix indexer canary

.changeset/lovely-pigs-return.md, l2geth/eth/downloader/downloader_test.go
The tests include:
- `TestBoundedForkedSync62`
- `TestBoundedForkedSync63Full`
- `TestBoundedForkedSync63Fast`
- `TestBoundedForkedSync64Full`
- `TestBoundedForkedSync64Fast`
- `TestBoundedForkedSync64Light`
None of these tests cover code that we use in production.
These tests were flaky upstream and eventually fixed.
No major changes to this codebase are planned before
deprecating it.
=> l2geth: skip unused tests

.changeset/shy-panthers-cough.md, .github/workflows/release.yml, ops/docker/go-builder/Dockerfile, ops/docker/go-builder/package.json, ops/docker/js-builder/package.json, package.json
Use `golang:1.18.0-alpine3.15`
and `golangci-lint@1.45.2`. This
will allow linting of code that
uses generics
=> {go,js}-builder: bump versions, add to ci

.github/workflows/changesets.yml, .github/workflows/release.yml
The `go-builder` and `js-builder` failed to publish again, this time it says that the dockerfile doesn't exist. I updated the config to work differently to see if this works
https://github.com/ethereum-optimism/optimism/runs/5853892666?check_suite_focus=true
```
/usr/bin/docker buildx build --file ./Dockerfile --iidfile /tmp/docker-build-push-S58KMP/iidfile --tag ethereumoptimism/go-builder:0.0.2 --tag ethereumoptimism/go-builder:latest --metadata-file /tmp/docker-build-push-S58KMP/metadata-file --push ./ops/docker/go-builder
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 2B done
#1 DONE 0.0s
#2 [internal] load .dockerignore
#2 transferring context:
error: failed to solve: failed to read dockerfile: open …
```
=> ci: fix broken publish + changeset integrity

.changeset/popular-birds-whisper.md, packages/data-transport-layer/src/services/server/service.ts
Basic auth support was previously added by 29f13641dd434f0ef0ce7750ec830e826566c0e3 but I neglected to update the L1TransportServer to use it when available.
=> dtl: Use Basic Auth in L1TransportServer

.github/mergify.yml
Mergify will now add a comment asking if you forgot a changeset if you change TS, Go, or JS code without adding one.
=> ci: Add a job to nag when changesets are missing

.changeset/swift-impalas-sip.md, go/indexer/services/l2/bridge/bridge.go
Fixes the L2 withdrawal bridge addresses which were pointing to L1 contracts. This fixes an issue with BitBTC bridge withdrawals missing from the indexer results.
For reference, the corresponding bridge addresses in the SDK can be found at:
https://github.com/ethereum-optimism/optimism/blob/a9f8e577f96158e22a0bad83eb8d878d3be60247/packages/sdk/src/utils/contracts.ts#L118-L170
=> fix (indexer): update l2 bridge addresses

packages/contracts/contracts/L2/messaging/L2CrossDomainMessenger.sol
Adds a comment clarifying how reentrancy protection is provided in `L2CrossDomainMessenger.relaymessage()`.
=> docs: reentrancy protection comment on L2 messenger

.changeset/tidy-swans-yell.md, packages/replica-healthcheck/src/service.ts
Fixes a bug that would cause the healthcheck service not to properly
check blocks when the target is advancing faster than the reference
client. RHC will now check the block correpsonding to the lesser of the
two block heights. Also adds a new metric to track the height difference
in the two providers which could be used to alert if the target leads
the reference by too much or vice versa.
**Metadata**
- Fixes #2455
=> fix(rhc): bug when target leads reference

.github/mergify.yml
Modifies mergify.yml to no longer yell at me to add a changeset
when a PR only modifies .spec.ts files.
=> fix(ci): no changeset nag for ts tests

packages/contracts/test/contracts/L1/rollup/ChainStorageContainer.spec.ts
Yet another test cleanup commit. Cleans up the ChainStorageContainer
tests with the same techniques as the previous commits along the same
lines.
Last one for the night!
=> maint(ct): clean up CSC tests

packages/contracts/test/contracts/L1/messaging/deposit.gas.spec.ts
Cleans up the deposit gas spec tests using the same techniques as found
in #2458 and #2459.
=> maint(ct): clean up deposit gas spec tests

packages/contracts/test/contracts/L1/messaging/L1CrossDomainMessenger.spec.ts
Cleans up the L1CrossDomainMessenger tests using the new deploy
function. Removes some unnecessary code.
=> maint(ct): clean up L1XDM tests

packages/contracts/test/contracts/L1/messaging/L1StandardBridge.spec.ts
Cleans up tests for the L1StandardBridge. Removes a lot of unnecessary
code and simplifies certain tests by bundling things into a single
assertion.
=> maint(ct): clean up L1StandardBridge tests

.changeset/yellow-pandas-help.md, packages/sdk/src/adapters/standard-bridge.ts, packages/sdk/src/cross-chain-messenger.ts, packages/sdk/src/interfaces/bridge-adapter.ts, packages/sdk/src/interfaces/cross-chain-messenger.ts
Replaces Overrides with CallOverrides for estimateGas functions so you
can specify the "from" address.
=> fix(sdk): use correct overrides type

packages/contracts/test/contracts/L1/teleportr/TeleportrDeposit.spec.ts
Cleans up the TeleportrDeposit tests using the same techniques as
previous cleanup PRs.
=> maint(ct): clean up Teleportr tests

.changeset/rude-mayflies-shout.md, go/proxyd/backend.go, go/proxyd/config.go, go/proxyd/example.config.toml, go/proxyd/go.mod, go/proxyd/integration_tests/max_rpc_conns_test.go, go/proxyd/integration_tests/testdata/max_rpc_conns.toml, go/proxyd/metrics.go, go/proxyd/proxyd.go
We add a new config `max_concurrent_rpcs` under the server section to
prevent too many RPC requests. This also sets a limit on the number of open connections to upstream.
However, due to connection reuse, there can be less connections in-use than concurrent RPCs.
Requests are blocked, in a FIFO fashion, until the number of in-flight RPCs is under the limit.
=> proxyd: Limit the number of concurrent RPCs to backends

packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.spec.ts
Cleans up the CTC tests using the same techniques as used in other
previous test cleanups.
=> maint(ct): clean up CTC tests

packages/contracts/test/contracts/L2/messaging/L2CrossDomainMessenger.spec.ts, packages/contracts/test/helpers/utils/impersonation.ts, packages/contracts/test/helpers/utils/index.ts
Cleans up the L2CrossDomainMessenger tests in the same manner as
previous cleanup PRs.
=> maint(ct): clean up L2xDM tests

.circleci/config.yml
The nightly CI fails because default remote docker (17.09.0-ce) does
not support DOCKER_BUILDKIT. Updating the remote docker version to be at
least 18.09 fixes this.
=> ci: Update remote docker version

packages/data-transport-layer/openapi.yml
This pull request fix opnenapi typo to enable postman import.
I try importing openapi through postman. But It doesn't work. So I find typo in openapi
**Metadata**
=> dtl: fix openapi

.changeset/stupid-apples-glow.md, go/indexer/services/l1/bridge/eth_bridge.go, go/indexer/services/l1/bridge/filter.go, go/indexer/services/l1/bridge/standard_bridge.go, go/indexer/services/l1/query.go, go/indexer/services/l2/bridge/filter.go, go/indexer/services/l2/bridge/standard_bridge.go
This PR addresses an issue with the indexer where a long running service stalls with the error: `context deadline exceeded`.
This was happening because the context for the first `FilterWithdrawalInitiatedWithRetry` call was being re-used in _all subsequent_ calls. This means that if for whatever reason, _one_ request to the API fails to complete within the deadline, _all_ subsequent calls will fail with the same error.
I have reproduced the underlying cause of the error in this minimal gist: [https://gist.github.com/tuxcanfly/28bee3ef233764d9d7ea6d63cbae48f6
](https://gist.github.com/tuxcanfly/28bee3ef233764d9d7ea6d63cbae48f6)
With this fix the parent context remains separate from all the retry context which are all the direct children of the parent context.
The parent …
=> indexer: fix context reuse in bridge filter query

.changeset/new-hairs-scream.md, .changeset/three-eggs-approve.md, l2geth/rollup/sync_service.go
fix log.Crit usage
```
log.Crit("Sequencer cannot sync transactions to tip: %w", err)
log.Crit("Sequencer cannot sync queue to tip: %w", err)
```
->
```
log.Crit("Sequencer cannot sync transactions to tip", "err", err)
log.Crit("Sequencer cannot sync queue to tip", "err", err)
```
=> l2geth: fix log.Crit usage

.changeset/tidy-oranges-float.md, l2geth/miner/worker.go
Adds metrics for transaction execution. These metrics were only collected when `USING_OVM=false` as a rollup node uses a different codepath during metrics collection.
The immediate usecase for this is to be able to estimate when indexers and vm tracers will no longer keep up with the increasing rate of transactions executed by replicas.
=> l2geth: Record rollup transaction metrics

packages/contracts/test/contracts/L1/rollup/StateCommitmentChain.spec.ts
Cleans up the StateCommitmentChain tests using the same techniques as
used in previous test cleanups.
No changeset added since it's just test cleanup.
=> maint(ct): clean up SCC tests

.changeset/flat-goats-itch.md, go/proxyd/server.go
Logging the entire RPC request can be too "expensive" when logging request
objects in a large JSON-RPC batch request. We log the raw HTTP request
body instead so we can truncate effectively when the entire body
exceeds the maxLogLength.
=> proxyd: Reduce RPC request logging

.changeset/tasty-adults-explode.md, packages/contracts/tasks/fetch-batches.ts, packages/core-utils/src/optimism/fees.ts, packages/core-utils/test/fees.spec.ts
Compute the calldata cost diff in the contracts packages
`fetch-batches` hardhat task.
=> tasks: compute calldata cost diff in `fetch-batches`

packages/contracts/test/contracts/L1/deployment/AddressDictator.spec.ts, packages/contracts/test/contracts/L1/deployment/ChugSplashDictator.spec.ts, packages/contracts/test/contracts/L2/predeploys/WETH9.spec.ts
Another test cleanup, this time for AddressDictator, ChugSplashDictator
and WETH9. Putting them in the same PR since 2 of the files have very
few changes.
=> maint(ct): cleanup AddressDictator, ChugSplashDicator and WETH9 tests

.changeset/hungry-turkeys-repeat.md, package.json, teleportr/api/server.go
Subtaction was being performed in the wrong order, causing underflow.
**Metadata**
- Fixes ENG-2191
=> feat: correct conf_remaining calculation

.changeset/lucky-buckets-crash.md, .changeset/shiny-bugs-scream.md, teleportr/api/server.go, teleportr/drivers/disburser/driver.go, teleportr/flags/api_flags.go
Previously we would always increment the counter instead of adding the
number of failed upserts observed.
**Metadata**
- Fixes ENG-2198
=> fix: correct FailedDatabase counter for upsert_disbursement, expose api-server metrics

.changeset/smart-readers-remember.md, packages/sdk/src/l2-provider.ts
Fixes a bug in the SDK that would throw an error when the user did not
provide a nonce along with the transaction (when estimating gas). If no
nonce is provided, will try to find a reasonable nonce or use a default
(large) nonce that will give a good upper bound for the L1 gas cost.
**Metadata**
- Fixes #2555
=> fix(sdk): bug causing error when no tx nonce given

packages/contracts/contracts/test-helpers/FailingReceiver.sol, packages/contracts/contracts/test-helpers/TestERC20.sol
Simplifies test helpers slightly by cutting out unnecessary code.
=> maint(ct): simplify test helpers

op-bindings/gen_bindings.sh, op-bindings/gen_deployed_bytecode.sh
This specifically notifies users if abigen, forge, and gofmt are
not found in the path. This is to provide an early warning that
the commands are required instead of failing when attempting to
invoke the commands.
=> bindings: Notify users if builds deps are not found

.changeset/cyan-ravens-swim.md, packages/common-ts/src/common/metrics.ts
Updates legacy MetricsServer to bind to 0.0.0.0 instead of 127.0.0.1 by
default which makes it possible to expose the metrics server from inside
docker. Only the DTL is still using legacy metrics, so should be fine.
=> fix(cmn): legacy metrics binds to 0.0.0.0

op-e2e/geth.go, op-proposer/service.go, op-proposer/txmgr/txmgr.go
Repeatedly using time.After in a select loop leaks resources as
resources are allocated for each timer, but not released until the
timer fires. The timer may not fire due to other return paths. By
using tickers, this resource leak is no longer able to happen.
I verified that this problem no longer exists with the following
semgrep command.
semgrep --config="r/dgryski.semgrep-go.timeafter.leaky-time-after"
**Metadata**
- Fixes ENG-2155
=> Use ticker instead of time.After in select loop

.changeset/stupid-pears-cough.md, l2geth/rollup/client.go, l2geth/rollup/sync_service.go, l2geth/rollup/sync_service_test.go
Adds logic to startup that will attempt to recover from situations in
which a DTL batch was skipped. Specifically meant to allow existing L1
syncing nodes to continue to sync after the recent DTL bug.
=> fix(l2geth): L1 sync error recovery logic

.changeset/green-phones-shop.md, .github/workflows/release.yml
The previous build didn't work due to a bug
in the CI, this fixes the release
The build previously failed in the release, this fixes the build in the release for `l2geth`
=> l2geth: fix docker release build

.changeset/tricky-hotels-crash.md, packages/contracts-bedrock/package.json
It was previously in dev dependencies which could
cause problems for production builds
Moves core-utils to deps from devdeps, should resolve build issues
=> contracts-bedrock: move core-utils to deps

packages/contracts-bedrock/package.json
Fixes the linter to ensure that the prettier
that was installed is used instead of a global
prettier executable
Fixes linting in the `contracts-bedrock` package, the old linting command wasn't using the same version as used in the repo
=> contracts-bedrock: fix linter

.changeset/curly-swans-crash.md, teleportr/drivers/disburser/driver.go, teleportr/drivers/disburser/metrics.go, teleportr/teleportr.go
- Update metrics collection to happen on an interval in addition to on each tick of the driver loop. This lets us continue collecting on-chain metrics if the driver loop halts for some reason.
- Adds an additional metric to track the last on-chian deposit ID. This will let add Teleportr halting alerts more easily.
=> teleportr: Improve metrics

.changeset/rude-foxes-think.md, proxyd/backend.go, proxyd/integration_tests/mock_backend_test.go, proxyd/integration_tests/testdata/ws.toml, proxyd/integration_tests/util_test.go, proxyd/integration_tests/ws_test.go, proxyd/server.go
Fixes a panic in the websocket proxyd logic. Normally, the `clientPump` and `backendPump` methods in `WSProxier` send data in one direction. However, when the client sends an invalid RPC, the `clientPump` will send a response _directly to the client_ in order to avoid unnecessary roundtrips to the backend. This could be interleaved with concurrent writes to the client's WS in `backendPump`, and would cause a panic in the WS library.
To test this, this PR includes a dedicated integration test that reliably triggers the issue. In addition, this PR adds additional testing for WS functionality.
=> proxyd: Fix concurrent WS write panic

.changeset/ten-owls-return.md, packages/common-ts/src/base-service/base-service-v2.ts
BaseServiceV2 will expose internal options (loop interval, metrics port,
etc) as environment variables or command line options.
=> feat(cmn): BaseServiceV2 exposes internal options

specs/deposits.md, specs/exec-engine.md, specs/overview.md, specs/rollup-node.md, specs/withdrawals.md
Three small commits + one wontfix to fix the four inconsistencies that ToB found in our documentation.
**Metadata**
- Fixes ENG-2152
=> specs: Fix inconsistencies within documentation

l2geth/eth/downloader/downloader_test.go
Skip flakey tests in `l2geth`, these tests are not useful to the way we use `l2geth`
=> l2geth: skip flaky tests

.changeset/wicked-knives-jog.md, packages/fault-detector/src/service.ts
Fixes a simple off-by-one error in the highestCheckedBatchIndex metric.
=> fix(fd): off by one in metric

packages/contracts/test/helpers/test-runner/json-test-runner.ts
The `contracts` tests included a test that did a deep equality check
against two bignumbers. This check stopped working due to changes
in the bignumber implementations used, two bignumbers of the same number
no longer were considered equal. This commit fixes that problem by
using the same version of ethers as `hardhat` and also stringifying
the results so that strings are compared instead of objects. This
fixes the broken tests.
=> contracts: fix broken contracts tests

.changeset/brown-parrots-type.md, teleportr/drivers/disburser/driver.go
When `err` is nil, `IsRetryableError` panics.
=> teleportr: Fix panic

.changeset/eighty-countries-develop.md, packages/common-ts/src/base-service/base-service-v2.ts
Sends BSV2 server logs to this.logger instead of stdout.
=> feat(cmn): BSV2 server logs to logger

.changeset/weak-needles-jam.md, packages/common-ts/src/base-service/base-service-v2.ts
Fix for BSV2 to expose default options in the metadata metric.
=> fix(cmn): BSV2 exposes default options in metadata

op-node/rollup/derive/batch_queue.go
This implements a simple algorithm for the batch queue. It waits
until it has a full sequence window and then runs the historical
batch derivation process over that data.
The WIP part is that it needs more data that it does not yet have.
**Metadata**
=> (WIP) derive: Implement BatchQueue with full window

.changeset/tasty-drinks-rhyme.md, packages/common-ts/src/base-service/base-service-v2.ts
The server does not end when we call stop because async loops do not end.  This makes it so the async loop stops right away.
=> feat(BaseServiceV2):End immediately when looping

.changeset/slow-scissors-battle.md, ops/docker/js-builder/Dockerfile
The curl commands weren't outputting files and the checksum verification was breaking other commands.
=> ci: Fix broken js-builder build

op-e2e/setup.go, op-node/rollup/derive/l1_block_info.go, op-node/withdrawals/utils.go
Use common.Address predeploy types. These are a couple fixes that I forgot to commit.
=> op-bindings: Use common.Address predeploy types

.changeset/dry-drinks-sneeze.md, .github/workflows/publish-canary.yml, ops/docker/Dockerfile.packages
There was no `drippie-mon` target in `Dockerfile.packages`, and the canary build was using the `relayer` target.
=> drippie-mon: Fix build

.changeset/heavy-buttons-impress.md, packages/common-ts/src/base-service/base-service-v2.ts
Fixes BSV2 to correctly ignore invalid routes in metrics by normalizing
them to /invalid_path_not_a_real_route.
=> fix(cmn): correctly ignore invalid routes

packages/contracts-bedrock/.eslintignore, packages/contracts-bedrock/.prettierignore, packages/contracts-bedrock/hardhat.config.ts, packages/contracts-bedrock/package.json
This PR: 
1. Adds the deployments folder to `.eslintignore` and `.prettierignore`. 
2. Changes the `yarn lint:ts:check` command so that it throws an error on warnings.  This prevents the issue where warnings don't cause an error in CI, but `yarn lint:ts:fix` will modify the code anyways. The approach used is consistent with other packages.
3. Formats the hardhat config file.
=> Fix linting issues in bedrock package

l2geth/eth/downloader/downloader_test.go
Skips some flakey tests that don't pertain to our codebase, we don't sync p2p
=> l2geth: skip unused flakey tests

.changeset/funny-goats-appear.md, packages/contracts-bedrock/deploy/000-L2OutputOracle.deploy.ts
Fixed the order of the args to L2OO deploy script recently updated in #2830 which was causing L1 deploy scripts to fail with:
```
2028 [48b901ec] Error: ERROR processing /hive/contracts/deploy/000-L2OutputOracle.deploy.ts:
2029 [48b901ec] Error: incorrect data length (argument="_genesisL2Output", value=2, code=INVALID_ARGUMENT, version=abi/5.6.4)
2030 [48b901ec]     at Logger.makeError (/hive/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
2031 [48b901ec]     at Logger.throwError (/hive/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
2032 [48b901ec]     at Logger.throwArgumentError (/hive/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:277:21)
2033 [48b901ec]     at FixedBytesCoder.Coder._throwError …
```
=> fix (bedrock): deploy L2OO - fix args

op-e2e/system_test.go
Increase SubmissionFrequency and L2BlockTime in system_test.go which appears to greatly reduce the failures in TestL2OutputSubmitter.
=> fix(op-e2e): less flakey TestL2OutputSubmitter

.changeset/thin-carpets-perform.md, ops/docker/go-builder/Dockerfile, proxyd/integration_tests/mock_backend_test.go
This has been pushed as `latest` and `0.0.5` to Docker Hub via a manual push in order to unblock other PRs.
=> ci: Upgrade golangci-lint version to one that handles Go 1.18

.changeset/mighty-rockets-provide.md, packages/contracts-bedrock/tasks/genesis-l2.ts
A small change to ensure the code address prefix is repeated correctly. Not a big deal, but could prevent errors of manually rewriting an address.
=> Correct l33t sp34k in toCodeAddr

.changeset/curly-spoons-invent.md, packages/contracts-bedrock/foundry.toml, packages/contracts-bedrock/package.json, yarn.lock
Enable hardhat style `BuildInfo` generation that integrates
with the hardhat plugin. The debug files (`*.dbg.json`) are
generated by default and are able to be pulled into hardhat
tasks with `Artifacts.getBuildInfo`.
=> feat: contracts-bedrock `BuildInfo`

op-node/testlog/README.md, op-node/testlog/testlog.go
Logs in go tests (including e2e) in bedrock now have aligned lines and color.
New:
Old:
The improved readability is especially nice when testing things with a mix of long and short file names, and important log kev-value pairs to compare.
Maybe it's worth upstreaming into Geth for their testing too?
=> feat(op-node): testlog alignment and color by default

.circleci/config.yml, batch-submitter/drivers/sequencer/batch.go, batch-submitter/drivers/sequencer/encoding.go, bss-core/crypto.go, bss-core/crypto_test.go, bss-core/metrics/metrics.go, bss-core/txmgr/send_state.go, bss-core/txmgr/send_state_test.go, bss-core/txmgr/txmgr.go, bss-core/txmgr/txmgr_test.go, gas-oracle/gasprices/gas_price_updater_test.go, indexer/crypto.go, indexer/crypto_test.go, ops/docker/ci-builder/Dockerfile, ops/docker/ci-builder/check-changed.sh, ops/docker/ci-builder/package.json, teleportr/db/db.go, teleportr/drivers/disburser/driver.go
- Updates CircleCI jobs to exit early if the git diff doesn't require them to run. This will dramatically reduce our CircleCI usage and speed up the pipeline for projects like Bedrock that don't touch legacy code. The entire pipeline will still run on `develop` and `master`. The conditional logic is aware of package dependencies, so changing an upstream package will correctly trigger a build on downstream dependencies.
- Creates a new `ci-builder` image to replace `js-builder` and `go-builder`. The `ci-builder` image contains everything we need to run builds on CircleCI.
- Fixes a bunch of misspellings that should have failed the linter, but didn't.
You can see the conditional builds in action on this PR. The JS tests in the monorepo exit early but the integration tests still run since …
=> ci: Use conditional builds

.circleci/config.yml, ops/docker/ci-builder/Dockerfile, ops/docker/ci-builder/check-changed.sh
- Outputs the raw GitHub response in check-changed
- Updates the golangci-lint version to the one in `go-builder` that supports 1.18
=> ci: Conditional check fixes
